### ISSUE TITLE
Jetty 12 flaky test: org.eclipse.jetty.test.client.transport.TrailersTest.testTrailers(Transport)[4] 

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#9662] opened 2023-04-19 05:38 UTC
org.eclipse.jetty.test.client.transport.TrailersTest.testTrailers(Transport)[4]  is flaky

```
org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:301)
	at org.eclipse.jetty.test.client.transport.TrailersTest.testTrailers(TrailersTest.java:109)
```

**Comment by sbordet** [comment] 2023-07-10 17:09
Possibly a duplicate of #10087.

**Closed as completed by sbordet** 2023-07-10 17:09 UTC
Labels: flaky-test
