### ISSUE TITLE
Flakey test org.eclipse.jetty.websocket.jakarta.tests.server.SessionTest.testRequestUriEndpointBasic

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6437] opened 2021-06-18 04:33 UTC
**jetty-11.0.x*

Failed in jenkins 
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-11.0.x-6394-port/1/pipeline

**Comment by lachlan-roberts** [comment] 2021-06-22 02:45
@janbartel do you have the log for this failure, or just the stacktrace? I can't load that page in jenkins and I cannot reproduce locally after running the test on repeat.

**Comment by janbartel** [comment] 2021-06-22 06:40
No sorry, I don't have any other info - looks like when the PR got merged and the branch was deleted the CI runs were too.

**Comment by lachlan-roberts** [comment] 2021-09-02 02:55
Closing as no info available on the failure and cannot reproduce.
Will re-open issue if the failure occurs again.

**Closed as completed by lachlan-roberts** 2021-09-02 02:55 UTC
Labels: Test
