### ISSUE TITLE
UnsupportedOperationException when adding servlet to ServletContext from @WebListener-annotated ServletContextListener

### ISSUE THREAD

**Issue by swingfield** [eclipse/jetty.project#4103] opened 2019-09-19 02:39 UTC
I have a `ServletContextListener` that is annotated with `@WebListener`.

In its `contextInitialized()` method, I try to add a servlet to the `ServletContext` via a call to

`servletContext.addServlet("myServlet", new MyServlet())`

but this throws an `UnsupportedOperationException`.

Reading the documentation of [ServletContext.addServlet()](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContext.html#addServlet-java.lang.String-javax.servlet.Servlet-), it seems to me like the operation should succeed, since I have annotated my `ServletContextListener `with the `WebListener `annotation:

>  **addServlet**
> 
> Registers the given servlet instance with this ServletContext under the given servletName. 
> ...
> throws UnsupportedOperationException - if this ServletContext was passed to the 
> ServletContextListener.contextInitialized(javax.servlet.ServletContextEvent) method 
> of a ServletContextListener that was neither declared in web.xml or web-fragment.xml, 
> _**nor annotated with WebListener**_

Here is an example class that can demonstrate the problem: 

```java
package com.example;

import javax.servlet.*;
import javax.servlet.annotation.WebListener;
import java.io.IOException;

@WebListener
public class MyServletContextListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent servletContextEvent) {
        ServletContext servletContext = servletContextEvent.getServletContext();
        // uncomment this line to get method to succeed...
        //((WebAppContext.Context) servletContext).setEnabled(true);
        ServletRegistration.Dynamic serviceServlet = servletContext.addServlet(
                "MyServlet", new Servlet() {
                    @Override
                    public void init(ServletConfig config) throws ServletException { }

                    @Override
                    public ServletConfig getServletConfig() { return null; }

                    @Override
                    public void service(ServletRequest req, ServletResponse res) throws ServletException, IOException { }

                    @Override
                    public String getServletInfo() { return null; }

                    @Override
                    public void destroy() { }
                });
        serviceServlet.addMapping("/myservlet/*");
        serviceServlet.setLoadOnStartup(1);
    }
}
```

Please let me know if I have misunderstood anything.

Thanks,
Steve

**Comment by janbartel** [comment] 2019-09-19 05:12
@swingfield you don't say which version  of jetty? I have just tested this with the head of jetty-9.4.x branch, and it works fine. We are making a new release of jetty-9.4.x in the next couple of days, so what is in head will be released - perhaps you can build and test against that?

**Comment by swingfield** [comment] 2019-09-19 13:37
Sorry it was Jetty 9.4.19.v20199010.  I will retest with the next release and let you know the results.

Thanks,
Steve

**Comment by janbartel** [comment] 2019-09-23 05:48
@swingfield I've opened an issue at SpringBoot, as the problem lies with the way they are processing `@WebListener` annotations - this is why the problem exists also for Tomcat.

See https://github.com/spring-projects/spring-boot/issues/18303

**Comment by janbartel** [comment] 2019-09-25 22:01
I'm closing this on the jetty bug tracker as it is not a bug in jetty, but rather a bug in springboot.

**Closed by janbartel** 2019-09-25 22:01 UTC
Labels: Not a bug

**Comment by joakime** [comment] 2019-09-25 22:29
@janbartel we have a "Third Party" label btw.

**Comment by swingfield** [comment] 2019-09-26 00:04
Thanks @janbartel for looking into this and for creating the spring boot ticket.
