### ISSUE TITLE
Closing SSL after error response

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2244] opened 2018-02-26 06:42 UTC
Test `SelectChannelServerSslTest.testFullMethod` frequently fails (often on CI: https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/1261/)

However, suspect that this might not be a flaky test, rather a problem in how we are closing SSL connections.  Note that we are already catching and ignoring SocketExceptions with the message "Close overtook 400 response", which appears contrary to the whole reason for a gracefull SSL close handshake.

This test is failing because the SocketException is being wrapped by a SSLException. We could also ignore SSLException, but I think we need to investigate why we are getting the exception in the first place!

**Comment by joakime** [comment] 2018-02-26 12:03
The build that was linked:
`jetty-9.4.x` branch.
Linux build.
JDK9 build.
Bare metal build. (not docker / container)

**Comment by joakime** [comment] 2018-02-26 12:04
This is a duplicate of #2237

**Closed** 2018-03-20 18:19 UTC
Labels: Bug, Java 9
