### ISSUE TITLE
Request cookie properties are missing

### ISSUE THREAD

**Issue by johnshajiang** [eclipse/jetty.project#4102] opened 2019-09-19 01:44 UTC
Please consider the below simple Servlet,
```
public class TestServlet extends HttpServlet {

    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {
        Cookie[] cookies = request.getCookies();
        if (cookies != null) {
            for (Cookie cookie : cookies) {
                System.out.printf(
                        "%s=%s; $Path=%s; $Domain=%s%n",
                        cookie.getName(),
                        cookie.getValue(),
                        cookie.getPath(),
                        cookie.getDomain());
            }
        }
    }
}
```
The path and domain are always `null` even though some client cookies set these properties.
For example, using the below curl command,
```
$ curl -v --cookie "n=v; \$Path=/cookie; \$Domain=localhost.local" http://localhost:port/cookie
```
the server side output just be the followings,
```
n=v; $Path=null; $Domain=null
```

**Comment by johnshajiang** [comment] 2019-09-19 01:47
In my testings, this problem raised on Jetty 9.4.20 and 10.0.0-alpha0, but NOT on Jetty 9.3.21.

**Comment by sbordet** [comment] 2019-09-19 13:43
@johnshajiang Cookies have evolved over time.

Before, they were regulated by RFC 2965, but later superseded by RFC 6265.
The latter does not support `$Path` etc. attributes in the `Cookie` header.

You can change the cookie compliance in Jetty via `HttpConfiguration.[request|response]CookieCompliance` which by default is RFC 6265 is the latest Jetty versions.

**Comment by joakime** [comment] 2019-09-19 13:53
in both [RFC2965](https://tools.ietf.org/html/rfc2965) and [RFC6265](https://tools.ietf.org/html/rfc6265) the User-Agent (aka HTTP Client or Web Browser) should never send the `$Path` and `$Domain` portions to the Server.

In [RFC6265](https://tools.ietf.org/html/rfc6265), the use of `$` prefixed identifiers was dropped.
The Server to Client `Set-Cookie` header also does not have the `$` prefixed identifiers.

**Example (Server to User-Agent)**

```
Set-Cookie: SID=31d4d96e407aad42; Path=/; Domain=example.com
```

**Example (User-Agent to Server)**

```
Cookie: SID=31d4d96e407aad42
```

We strongly recommend using RFC6265, as all modern web browsers now enforce it, and will (quietly) reject cookies that do not follow the rules outlined in RFC6265.

**Comment by johnshajiang** [comment] 2019-09-19 22:20
> You can change the cookie compliance in Jetty via `HttpConfiguration.[request|response]CookieCompliance` which by default is RFC 6265 is the latest Jetty versions.
I just set the below lines in server module section in JETTY_HOME/start.ini,
jetty.httpConfig.requestCookieCompliance=RFC2965
jetty.httpConfig.responseCookieCompliance=RFC2965

It didn't work for me.

**Comment by johnshajiang** [comment] 2019-09-19 22:28
> in both [RFC2965](https://tools.ietf.org/html/rfc2965) and [RFC6265](https://tools.ietf.org/html/rfc6265) the User-Agent (aka HTTP Client or Web Browser) should never send the `$Path` and `$Domain` portions to the Server.

Could you please explain more about why RFC 2965 disallow these attributes?
I find an example about this usage in section 3.3.4 in this RFC.

**Comment by sbordet** [comment] 2019-09-20 08:21
@johnshajiang only RFC 6265 does not have `Cookie` attributes.
I just tried and works for me (embedded Jetty).
Can you put up a reproducible test case?

**Comment by johnshajiang** [comment] 2019-09-20 12:22
My test uses standalone Jetty server, but it is still straightforward.
1. Deploy a simply web application with the `TestServlet` in my first post.
2. Edit `JETTY_HOME/start.ini` and modify the below properties,
`jetty.httpConfig.requestCookieCompliance=RFC2965`
`jetty.httpConfig.responseCookieCompliance=RFC2965`
3. Launch Jetty server from the `JETTY_BASE`
`java -jar ../start.jar jetty.http.port=port`
4. Use the curl command as the client and connect to the Jetty server
`curl -v --cookie "n=v; \$Path=/cookie; \$Domain=localhost.local" http://localhost:port/cookie`

**Comment by johnshajiang** [comment] 2019-09-20 12:27
Please find my Jetty base at [test-base.zip](https://github.com/eclipse/jetty.project/files/3635867/test-base.zip)

**Comment by gregw** [comment] 2019-09-23 06:35
I just added your servlet to our [OneServletContext embedded example](https://gist.github.com/gregw/8419c2fa8b9b1f1bb24dcf54d43e78c2) and it worked fine:
```
curl -v --cookie "n=v; \$Path=/cookie; \$Domain=localhost.local" http://localhost:8080/test
```
produced:
```
n=v; $Path=/cookie; $Domain=localhost.local
```

So the server is working... I'm suspecting a configuration problem. Let me look more at your base...

**Comment by gregw** [comment] 2019-09-23 06:42
and your base works as well:
```
n=v; $Path=/cookie; $Domain=localhost.local
```

Closing as cannot reproduce.  Please reopen if you can

**Closed by gregw** 2019-09-23 06:42 UTC
