### ISSUE TITLE
UnsatisfiedResolutionException using Jetty 9.4 with CDI

### ISSUE THREAD

**Issue by Restage** [eclipse/jetty.project#1659] opened 2017-07-04 13:45 UTC
Hi,
I've got another problem running Jetty 9.4.6 together with cdi. Sendung a request to my webservice the container returns http error code 500 and throws the following exception in the background:

    org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001308: Unable to resolve any beans for Type: interface org.jboss.weld.context.http.HttpRequestContext; Qualifiers: []
        at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:100)
        at org.jboss.weld.servlet.HttpContextLifecycle.getRequestContext(HttpContextLifecycle.java:126)
        at org.jboss.weld.servlet.HttpContextLifecycle.requestDestroyed(HttpContextLifecycle.java:295)
        at org.jboss.weld.servlet.WeldInitialListener.requestDestroyed(WeldInitialListener.java:143)
        at org.jboss.weld.servlet.api.helpers.ForwardingServletListener.requestDestroyed(ForwardingServletListener.java:38)
        at org.eclipse.jetty.server.handler.ContextHandler.requestDestroyed(ContextHandler.java:1203)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1258)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:745)

Is this a Jetty or Weld problem? The stacktrace does not indicate that there is something wrong with my application.

**Comment by joakime** [comment] 2017-07-05 20:36
Closing as likely duplicate of #1658

**Closed by joakime** 2017-07-05 20:36 UTC
Labels: Duplicate
