### ISSUE TITLE
jetty-maven-plugin doStop fails if target/classes does not exist

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#853] opened 2016-08-17 16:45 UTC
See discussion at http://stackoverflow.com/questions/28170244/jetty-throws-noclassdeffounderror-org-eclipse-jetty-util-futurecallback-on-shut

It appears that if you have a maven project with `<packaging>war</packaging>`, and it has no java classes (no `src/main/java` directory), no `target/classes` directory exist (which is correct).

However, this lack of `target/classes` can result in `doStop()` failure (according to the comments on that stackoverflow)

**Comment by janbartel** [comment] 2016-08-18 00:34
I can't reproduce any issues with a recent jetty-9.2, 9.3 or higher.

There were 2 bugs, both since fixed, that may be relevant:

1. https://bugs.eclipse.org/bugs/show_bug.cgi?id=438500 That was fixed in jetty-9.2.3 and beyond.
2. https://github.com/eclipse/jetty.project/issues/785 That only affected jetty-9.3.x and higher and is fixed in HEAD of jetty-9.3.x (9.3.12-SNAPSHOT) and beyond.

Pretty much any time something goes catastrophically wrong with a maven execution its possible that you might see some kind of failure to load classes, because maven/the jvm takes the classloader away from the plugin. These are some scenarios:

- because of a bug in the plugin (like issue #785)

- because you've configured jetty to run before some unit tests which fail causing the jvm to exit suddenly, although most of these should be avoided by the fix [438500](https://bugs.eclipse.org/bugs/show_bug.cgi?id=438500)

- you've executed on the command line a build phase that does not include the build phase that is bound to a graceful termination of jetty

If someone can provide a simple reproduction project I will take another look.

**Closed by janbartel** 2016-08-18 00:34 UTC
Labels: Bug
