### ISSUE TITLE
Accept ISO-8859-1 characters in response reason

### ISSUE THREAD

**Issue by toref** [eclipse/jetty.project#1792] opened 2017-09-05 05:40 UTC
Hi

I am using Jetty Proxy (9.4.6.v20170531) to forward requests into a Tomcat 7 Server. The response from the Tomcat Server returns a 302 déplacé temporairement because the user in this case is french (apparently Tomcat decides to localize the response).

The HttpParser class fails to parse the special french characters and throws a 400 error.  The actual code that is failling seems to be around like 862 where we parse the status reason code. The french character gets interpreted as a negative character and since its' not >= HttpTokens.SPACE the badMessageException is thrown. 

                case REASON:
                    if (ch == HttpTokens.LINE_FEED)
                    {
                        String reason=takeString();
                        setState(State.HEADER);
                        handle=_responseHandler.startResponse(_version, _responseStatus, reason)||handle;
                        continue;
                    }
                    else if (ch>=HttpTokens.SPACE)
                    {
                        _string.append((char)ch);
                        if (ch!=' '&&ch!='\t')
                            _length=_string.length();
                    }
                    else
                        throw new BadMessageException();
                    break;

Can this be updated to allow special characters from the iso-8859-1 character set?

If you change this line:
<code>else if (ch>=HttpTokens.SPACE)</code>
to:
<code>else if (((char) ch)>=HttpTokens.SPACE)</code>

It seems to work.

**Comment by gregw** [comment] 2017-09-05 06:08
With the update to [RFC7230](https://tools.ietf.org/html/rfc7230), there has been a move to distinguish between legal `VCHAR` characters (visible US-ASCII) and `obs-text` (obsolete text ie is-8859-1).

I think that we have perhaps gone a little too far with disallowing obs-text, specially in fields like the reason field.  We should be strict in what we generate and flexible in what we parse.

So I think we should definitely accept iso-8859-1 in a reason field, but I do not think we will allow it to be sent by the proxy, so it might arrive finally at your client as `302 d?plac? temporairement`, although we might support a legacy field.

Note that a future RFC may disallow obs-text, so you should definitely ask that server to send only US-ASCII

**Comment by gregw** [comment] 2017-09-05 07:31
Actually, as we already accept `obs-text` ( iso-8859-1 ) characters in headers, and we allow the generator to generate them, I just added support for `obs-text` characters in the response reason. 
Will be in the next release.

**Closed by gregw** 2017-09-05 07:31 UTC

**Comment by toref** [comment] 2017-09-05 08:55
Thank you. Do you know when the next release is planned for? Perhaps there is a page where this is mentioned but I didn't find it.

**Comment by gregw** [comment] 2017-09-06 00:34
release 9.4.7 is due out in the next few weeks.

**Comment by joakime** [comment] 2017-09-06 18:15
@gregw isn't this a duplicate of #1333 ?

**Comment by gregw** [comment] 2017-09-06 21:08
It is definitely a subset of #1333
