### ISSUE TITLE
NPE in FileServer Example

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#1904] opened 2017-10-17 17:01 UTC
Getting an NPE out of the file server example, something odd going on with serving default index.html file.

2017-10-17 11:57:06.964:WARN:oejs.HttpChannel:qtp1880587981-14: /
java.lang.NullPointerException
	at org.eclipse.jetty.server.ResourceService.sendWelcome(ResourceService.java:419)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:251)
	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:281)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)

https://www.eclipse.org/jetty/documentation/current/embedded-examples.html#embedded-file-server

Seem to be assuming servlet context out of the resource handler now?

**Comment by joakime** [comment] 2017-10-17 18:10
Duplicate of #1856

**Closed by joakime** 2017-10-17 18:10 UTC
