### ISSUE TITLE
Flaky test `CloseableDoSFilterTest.testEvenLowRateIP`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#9864] opened 2023-06-01 08:25 UTC
**Jetty version(s)**
12

**Description**
It failed with:
```
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at org.eclipse.jetty.ee10.servlets@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlets.AbstractDoSFilterTest.testEvenLowRateIP(AbstractDoSFilterTest.java:159)
```

See https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1248/testReport/junit/org.eclipse.jetty.ee10.servlets/CloseableDoSFilterTest/Parallel_Stage___Build___Test___JDK17___testEvenLowRateIP/

**Comment by olamy** [comment] 2023-06-02 08:34
duplicate of https://github.com/eclipse/jetty.project/issues/9654

**Closed as not planned** 2023-06-02 10:05 UTC
Labels: flaky-test
