### ISSUE TITLE
java.lang.ClassNotFoundException: org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory

### ISSUE THREAD

**Issue by BodoWissemann** [eclipse/jetty.project#1674] opened 2017-07-17 11:32 UTC
Hey,

i'm new to jetty at all and i'm trying to enable http2 in a jetty9-app (java version "1.8.0_131"). 
I have to configure it all by using xml-files.. and right now i use the jetty-xml-files provided in the documentation: http://www.eclipse.org/jetty/documentation/9.3.x/configuring-connectors.html

I try to load the alpn-boot-jar by adding it to `<jvmArgs/>` in `pom.xml`. It matches my OpenJDK-version and it works in another project. (right now it's maybe not the best location to store it, but i think it should work like this..)

this is the relevant part of my `pom.xml`:

```xml
<jvmArgs>-Xbootclasspath/p:${basedir}/alpn-boot-8.1.11.v20170118.jar</jvmArgs>          
<jettyXml>${basedir}/src/main/webapp/WEB-INF/jetty.xml,
        ${basedir}/src/main/webapp/WEB-INF/jetty-http.xml,
	${basedir}/src/main/webapp/WEB-INF/jetty-ssl-context.xml,
        ${basedir}/src/main/webapp/WEB-INF/jetty-ssl.xml,
        ${basedir}/src/main/webapp/WEB-INF/jetty-https.xml,
	**${basedir}/src/main/webapp/WEB-INF/jetty-http2.xml**
</jettyXml>
```

it works well when i load `jetty-https.xml` instead of `jetty-http2.xml`, but when i try loading `jetty-http2.xml`, i get this:

```
java.lang.ClassNotFoundException: org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory
```

The desired class exists, the relevant jars are correctly loaded as dependencies.

I think it has to do sth. with the alpn-boot-jar, but somehow i'm unable to figure it out.

Thx a lot!!

B

**Comment by sbordet** [comment] 2017-07-25 09:13
It's a weird configuration.

HTTP/2 is a feature of the Servlet Container (the server), not of a web application.

As such, it is weird that you are trying to load Jetty (the server) configuration classes from a web application path (`${basedir}/src/main/webapp/WEB-INF/`).
If that is what you're trying to do (load server classes from a web application) then it's not going to work, and it's probably the reason you get the `ClassNotFoundException`.

I recommend that you configure a standalone Jetty server with HTTP/2 and then just deploy your web application into it.

**Comment by BodoWissemann** [comment] 2017-08-17 16:14
Thx for the reply!

I'm trying to use BaseX with jetty 9 (https://github.com/BaseXdb/basex)

I configured the jetty-maven-plugin like it was done before (https://github.com/BaseXdb/basex/blob/master/basex-api/pom.xml).

I think the jetty-documentations also shows this way to configure the plugin inside the pom.xml:

"<plugin>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-maven-plugin</artifactId>
    <version>9.4.7-SNAPSHOT</version>
    <configuration>
        <jettyXml>jetty.xml,jetty-ssl.xml,jetty-https.xml</jettyXml>
    </configuration>
</plugin>"

Loading the jetty.xml from different locations does not solve the problem.. 

Is there maybe anything else needed especially for configuring the server for alpn / http2?


The jetty.xml i'm using works fine when starting jetty embedded...

**Comment by sbordet** [comment] 2017-08-18 20:47
If you want to be able to use the Jetty Maven Plugin for HTTP/2, please have a look at the POM configuration at https://github.com/jetty-project/http2-demo and instructions in the README.

In particular, you need to run the plugin in forked mode via `mvn jetty:run-forked`.

**Comment by BodoWissemann** [comment] 2017-08-19 10:24
thx for the tipp with run-forked, but unfortunately, this doesn't change anything.

here's the output and the stacktrace:

Configuring Jetty for project: BaseX API
[INFO] webAppSourceDirectory not set. Trying src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /Users/wissemann/Documents/Code/basex/basex-api/target/classes
[INFO] Logging initialized @7430ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] Context path = /
[INFO] Tmp directory = /Users/wissemann/Documents/Code/basex/basex-api/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:///Users/wissemann/Documents/Code/basex/basex-api/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Users/wissemann/Documents/Code/basex/basex-api/src/main/webapp
[INFO] Scanning elapsed time=355ms
[INFO] Quickstart generating
[INFO] Started o.e.j.m.p.JettyWebAppContext@1b1f5012{/,file:///Users/wissemann/Documents/Code/basex/basex-api/src/main/webapp/,AVAILABLE}{file:///Users/wissemann/Documents/Code/basex/basex-api/src/main/webapp/}
[INFO] Stopped o.e.j.m.p.JettyWebAppContext@1b1f5012{/,file:///Users/wissemann/Documents/Code/basex/basex-api/src/main/webapp/,UNAVAILABLE}{file:///Users/wissemann/Documents/Code/basex/basex-api/src/main/webapp/}
[INFO] Forked process starting
[STDERR] 2017-08-19 11:37:14.600:INFO::main: Logging initialized @146ms to org.eclipse.jetty.util.log.StdErrLog
[STDERR] 2017-08-19 11:37:14.741:WARN:oejx.XmlConfiguration:main: Config error at
`Call name="addConnectionFactory"><Arg>|                        <New id="alpn" class="org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory"><Arg type="String">|                                <Property name="jetty.alpn.protocols" deprecated="alpn.protocols" default=""/>|                            </Arg><Set name="defaultProtocol">|                                <Property name="h2" deprecated="alpn.defaultProtocol"/>|                            </Set></New>|                    </Arg></Call>`
java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory in file:/Users/wissemann/Documents/Code/basex/basex-api/src/main/webapp/WEB-INF/jetty.xml
2017-08-19 11:37:14.742:WARN:oejx.XmlConfiguration:main: Config error at `<Call name="addConnector"><Arg>|            <New id="sslConnector" class="org.eclipse.jetty.server.ServerConnector"><Arg name="server">|                    <Ref refid="Server"/>|                </Arg><Arg name="acceptors" type="int">|                    <Property name="jetty.ssl.acceptors" deprecated="ssl.acceptors" default="-1"/>|                </Arg><Arg name="selectors" type="int">|                    <Property name="jetty.ssl.selectors" deprecated="ssl.selectors" default="-1"/>|                </Arg><Arg name="factories">|                    <Array type="org.eclipse.jetty.server.ConnectionFactory"/>|                </Arg><Set name="host">|                    <Property name="jetty.ssl.host" deprecated="jetty.host"/>|                </Set><Set name="port">|                    <Property name="jetty.ssl.port" deprecated="ssl.port" default="8443"/>|                </Set><Set name="idleTimeout">|                    <Property name="jetty.ssl.idleTimeout" deprecated="ssl.timeout" default="30000"/>|                </Set><Set name="soLingerTime">|                    <Property name="jetty.ssl.soLin¡#¢¢gerTime" deprecated="ssl.soLingerTime" default="-1"/>|                </Set><Set name="acceptorPriorityDelta">|                    <Property name="jetty.ssl.acceptorPriorityDelta" deprecated="ssl.acceptorPriorityDelta" default="0"/>|                </Set><Set name="acceptQueueSize">|                    <Property name="jetty.ssl.acceptQueueSize" deprecated="ssl.acceptQueueSize" default="0"/>|                </Set><Call name="addConnectionFactory"><Arg>|                        <New class="org.eclipse.jetty.server.SslConnectionFactory"><Arg name="next">alpn</Arg><Arg name="sslContextFactory">|                                <Ref refid="sslContextFactory"/>|                            </Arg></New>|                    </Arg></Call><Call name="addConnectionFactory"><Arg>|                        <New id="alpn" class="org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory"><Arg type="String">|                                <Property name="jetty.alpn.protocols" deprecated="alpn.protocols" default=""/>|                            </Arg><Set name="defaultProtocol">|                                <Property name="h2" deprecated="alpn.defaultProtocol"/>|                            </Set></New>|                    </Arg></Call><Call name="addConnectionFactory"><Arg>|                        <New class="org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory"><Arg name="config">|                                <Ref refid="sslHttpConfig"/>|                            </Arg><Set name="maxConcurrentStreams">|                                <Property name="jetty.http2.maxConcurrentStreams" deprecated="http2.maxConcurrentStreams" default="1024"/>|                            </Set><Set name="initialStreamRecvWindow">|                                <Property name="jetty.http2.initialStreamRecvWindow" deprecated="jetty.http2.initialStreamSendWindow" default="65535"/>|                            </Set></New>|                    </Arg></Call><Ref refid="sslContextFactory"><Set name="CipherComparator">|                        <Get class="org.eclipse.jetty.http2.HTTP2Cipher" name="COMPARATOR"/>|                    </Set><Set name="useCipherSuitesOrder">true</Set></Ref><Call name="addIfAbsentConnectionFactory"><Arg>|                        <New class="org.eclipse.jetty.server.SslConnectionFactory"><Arg name="next">http1.1</Arg><Arg name="sslContextFactory">|                                <Ref refid="sslContextFactory"/>|                            </Arg></New>|                    </Arg></Call><Call name="addConnectionFactory"><Arg>|                        <New class="org.eclipse.jetty.server.HttpConnectionFactory"><Arg name="config">|                                <Ref refid="sslHttpConfig"/>|                            </Arg><Arg name="compliance">|                                <Call class="org.eclipse.jetty.http.HttpCompliance" name="valueOf"><Arg>|                                        <Property name="jetty.http.compliance" default="RFC7230"/>|                                    </Arg></Call>|                            </Arg></New>|                    </Arg></Call></New>|        </Arg></Call>`
java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory in file:/Users/wissemann/Documents/Code/basex/basex-api/src/main/config/jetty.xml


I'm loading ALPNServerConnectionFactory before HTTP2ServerConnectionFactory. If i remove alpn from the jetty.xml, http2-classes are next to be not found.


Thx again!!

**Comment by sbordet** [comment] 2017-08-19 12:52
@BodoWissemann please also make sure you have all the required dependencies in your main POM, like the `http2-demo` has.

**Comment by sbordet** [comment] 2017-09-26 08:50
Closing assuming the issue is resolved for the OP. Please comment if it's not.

**Closed by sbordet** 2017-09-26 08:50 UTC
