### ISSUE TITLE
Web Socket Session.close(CloseStatus) does not close web socket cleanly

### ISSUE THREAD

**Issue by eoghanoh1** [eclipse/jetty.project#865] opened 2016-08-24 16:58 UTC
Version: Jetty 9.3.6.
Jetty web socket native web socket implementation (not JSR-356).

Invoking Session.close() the web socket closes successfully and the on close handler is executed. 

However if I attempt to close the web socket using either;
Session.close(int statusCode, String reason) or
Session.close(CloseStatus closeStatus)

The web socket does not seem to close immediately  and the @OnWebSocketClose annotated handler is no invoked.

Looking at wireshark traces for both, I noticed a difference in the messaging.

For the successful close;
WebSocket Connection Close [FIN] packet is sent 
[FIN, ACK] is sent 
[ACK] is received

For the unsuccessful close;
WebSocket Connection Close [FIN] packet is sent
[ACK] is received

No [FIN, ACK] is sent. The socket only closes when the max idle timeout is exceeded.

**Comment by joakime** [comment] 2016-08-24 20:47
For websocket, the close is only successful when both sides send a close frame.

Known as [The Closing Handshake](https://tools.ietf.org/html/rfc6455#section-7.1.2). 

The close frame can be:

 - received from the remote (which is automatically responded to by Jetty, by appending the close frame after the current message, and then once that close frame is sent, it disconnects)
 - or initiated by the local (which half-closes, and would wait for a remote close frame response before performing a full disconnect)
 - or simultaneously sent by both sides (which satisfies the close handshake and disconnects the connection)

If the close handshake is not satisfied, then idle timeout will disconnect the active connection.

We would need to see if your wireshark actually shows close frames from both sides.

Incidentally, these close tests are part of the [autobahn websocket testsuite](http://autobahn.ws/testsuite/), that jetty uses for validating that it conforms to the same websocket behavior that the rest of the industry does (the autobahn testsuite is used by nearly the entire industry of websocket implementors)

**Comment by joakime** [comment] 2016-08-24 20:49
With JSR356, there is no provision for performing a connection disconnect, it must go through the proper WebSocket Closing Handshake process for it to be closed.

If you were using the Jetty Native WebSocket implementation, then you could use [`Session.disconnect()`](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/websocket/api/Session.html#disconnect--) to skip the close handshake requirement of WebSocket.

**Comment by eoghanoh1** [comment] 2016-08-25 08:36
Thanks for your response and information. This is using the native web socket implementation. If I use disconnect would the remote side of the web socket remain up until they determine the socket needs to be cleaned up (i.e. unable to send ping, missed pong response etc)?

I have attached the WireShark trace. I have removed certain packets containing transmitted data between open and close of the web socket. 

[websocket_close.zip](https://github.com/eclipse/jetty.project/files/436454/websocket_close.zip)

**Comment by eoghanoh1** [comment] 2016-08-25 08:38
10.134.37.123 is the machine that is running the application that is using the jetty web socket implementation.

**Comment by eoghanoh1** [comment] 2016-09-05 10:49
I have now upgraded to Jetty v9.3.11 and I am facing a problem with the  org.eclipse.jetty.websocket.api.Session.close() API.

On version 9.3.6 (as stated above), this API closes the web socket and invokes the @OnClose annotated method. On version 9.3.11, @OnClose is not invoked. The socket times out after the max idle timeout is exceeded.

I have not tried any versions in between 9.3.6 and 9.3.11 and therefore I do not know exactly where this behavior change was introduced. Can you review? Thanks.

**Comment by eoghanoh1** [comment] 2016-09-20 13:18
Hi,
Can you review the added comments?
Thanks,
Eoghan

**Comment by joakime** [comment] 2016-09-20 14:34
Do you have a reproduction case?

The close logic in Jetty is currently passing the industry testcases (autobahn testsuite and pywebsocket testsuite).

If we can reproduce it, we can fix it.

**Comment by eoghanoh1** [comment] 2016-10-03 15:30
Sorry for the delay. 
By a reproduction case what exactly do you mean? 
Is it test code from client side and server side that reproduces the problem?

**Comment by eoghanoh1** [comment] 2016-10-21 11:01
Can you provide some guidance as to what you would need to debug this.

Thanks,
Eoghan

**Comment by sbordet** [comment] 2016-10-21 11:18
Can you code a reproducible test case and attach it here ?

**Comment by nhooyr** [comment] 2018-09-14 03:07
Slightly off topic but does anyone know what the purpose of the websocket handshake is? Why not just send a close frame and then close the TCP connection? Why wait for a close frame from the peer?

**Comment by joakime** [comment] 2018-09-14 03:27
@nhooyr documented in the spec - https://tools.ietf.org/html/rfc6455#section-7

If you have ever spent time writing code for networking, you'll learn soon enough that the most difficult thing in all protocols is properly closing the connection.

Even your "then close the TCP connection" has a handshake, and it's got many different states it goes through. :-)

One real (and common) TCP thing is a half-closed connection, where side A says it's done writing and tells the side B it's closed, but then continues to read from side B until the side B also says it's closed.

**Comment by nhooyr** [comment] 2018-09-14 03:31
> If you have ever spent time writing code for networking, you'll learn soon enough that the most difficult thing in all protocols is properly closing the connection.

😂

> Even your "then close the TCP connection" has a handshake, and it's got many different states it goes through. :-)

Yup, but I'm wondering why reimplement that at the WebSocket level.

So just want to confirm I got this right, the only reason is so the client does not do the TCP close first to allow it to reuse the port? Seems like a weak reason imo. I'm writing a ws lib in go, was wondering whether to do the full websocket close handshake but now looks like I'm probably going to just send the close frame and then close the TCP connection.

**Comment by joakime** [comment] 2018-09-14 10:48
> So just want to confirm I got this right, the only reason is so the client does not do the TCP close first to allow it to reuse the port? Seems like a weak reason imo. I'm writing a ws lib in go, was wondering whether to do the full websocket close handshake but now looks like I'm probably going to just send the close frame and then close the TCP connection.

If you do that you'll wind up fighting CLOSE_WAIT issues at the TCP side, and protocols built on top of your websocket implementation that want "message trailers" (messages that signal the end of the conversation) will not work.

Also, make sure you verify your websocket implementation against the Autobahn|Testsuite. (pretty much the whole industry tests their websocket implementation against it)
https://github.com/crossbario/autobahn-testsuite

**Comment by nhooyr** [comment] 2018-09-14 16:26
> If you do that you'll wind up fighting CLOSE_WAIT issues at the TCP side

Could you elaborate on what issues or link me somewhere? I'm not intimately familiar with TCP.

> protocols built on top of your websocket implementation that want "message trailers" (messages that signal the end of the conversation) will not work.

Why wouldn't they work? They can send their own application level close frames before closing the websocket connection via my library.

> Also, make sure you verify your websocket implementation against the Autobahn|Testsuite. (pretty much the whole industry tests their websocket implementation against it)
https://github.com/crossbario/autobahn-testsuite

That suite is super useful thanks.

**Comment by ykonrad** [comment] 2019-03-07 14:56
I've discovered that jetty rejects (with exception) attempts to close with 'out of scope' codes. 
The only valid close status are 1000-1015 (taken from org.eclipse.jetty.websocket.api.StatusCode ). Calling the close (code, reason) with invalid code (For example 5xx), the method will throw exception that is subject to be ignored in case you are calling it in a scope of websocket hooks, for example onWebSocketConnect. In this case close frame will not be sent and socket will stay open.

**Comment by joakime** [comment] 2019-03-07 15:23
Per RFC6455, you can only use those status codes that are allowed to be used over the protocol.

https://tools.ietf.org/html/rfc6455#section-7.4.2

If you want to use custom close codes (not the standard ones), you are restricted to the 4000-4999 range.

**Comment by joakime** [comment] 2019-03-07 15:25
Also, see isTransmittable in this class.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/StatusCode.java

**Comment by lachlan-roberts** [comment] 2020-01-31 05:05
Doesn't look like there is anything to be done here.

**Closed by lachlan-roberts** 2020-01-31 05:05 UTC
