### ISSUE TITLE
Validation warnings in 12 beta3 maven plugin

### ISSUE THREAD

**Issue by Artur-** [eclipse/jetty.project#10076] opened 2023-07-06 12:27 UTC
**Jetty version(s)**
12 beta 3

**Java version/vendor** `(use: java -version)`
openjdk version "19.0.1" 2022-10-18

**OS type/version**
mac

**Description**
Using `jetty-ee10-maven-plugin` with Maven 3.9.2 results in 
```
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING] 
[WARNING]  * org.eclipse.jetty.ee10:jetty-ee10-maven-plugin:12.0.0.beta3
```

Adding `-Dmaven.plugin.validation=VERBOSE` shows
```
[WARNING]  * org.eclipse.jetty.ee10:jetty-ee10-maven-plugin:12.0.0.beta3
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin mixes multiple Maven versions: [3.8.7, 4.0.0-alpha-5]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-resolver-provider:3.8.7, org.apache.maven:maven-repository-metadata:3.8.7, org.apache.maven:maven-settings-builder:3.8.7, org.apache.maven:maven-artifact:3.8.7, org.apache.maven:maven-plugin-api:3.8.7, org.apache.maven:maven-model:3.8.7, org.apache.maven:maven-core:3.8.7, org.apache.maven:maven-settings:3.8.7, org.apache.maven:maven-model-builder:3.8.7, org.apache.maven:maven-builder-support:3.8.7]
```

**Comment by janbartel** [comment] 2023-07-07 08:57
@Artur- I can't seem to reproduce this. Can you post more information on how you are configuring and running the plugin?

**Comment by Artur-** [comment] 2023-07-07 09:12
You need to have a new enough Maven to see the warnings. You can see the same when building the `jetty-ee10-maven-plugin` module in this repository but in a different form:
```
[INFO] --- plugin:3.9.0:descriptor (default-descriptor) @ jetty-ee10-maven-plugin ---
[WARNING] 

Goal prefix is specified as: 'jetty'. Maven currently expects it to be 'jetty-ee10'.

[WARNING] 

Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.

The following dependencies are in wrong scope:
 * org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:compile
 * org.apache.maven:maven-api-xml:jar:4.0.0-alpha-5:compile
 * org.apache.maven:maven-api-meta:jar:4.0.0-alpha-5:compile
 * org.apache.maven:maven-plugin-api:jar:3.8.7:compile
 * org.apache.maven:maven-model:jar:3.8.7:compile
 * org.apache.maven:maven-artifact:jar:3.8.7:compile
 * org.apache.maven:maven-core:jar:3.8.7:compile
 * org.apache.maven:maven-settings:jar:3.8.7:compile
 * org.apache.maven:maven-settings-builder:jar:3.8.7:compile
 * org.apache.maven:maven-builder-support:jar:3.8.7:compile
 * org.apache.maven:maven-repository-metadata:jar:3.8.7:compile
 * org.apache.maven:maven-model-builder:jar:3.8.7:compile
 * org.apache.maven:maven-resolver-provider:jar:3.8.7:compile
```

**Comment by janbartel** [comment] 2023-07-07 10:30
@Artur- right, I can see those warnings when I build the plugin, but I don't see the warnings that _you_ got when I _run_ the plugin and they seem to be different warnings. I'm using maven 3.9.3, jdk 19.0.2 on linux.

**Comment by Artur-** [comment] 2023-07-07 17:04
I updated https://github.com/vaadin/skeleton-starter-flow/tree/jetty12-beta to use Jetty 12 beta. It uses nothing special for the maven plugin: https://github.com/vaadin/skeleton-starter-flow/blob/392baffcc24bea496b94af1a8f6215af721a200e/pom.xml#L72-L76

Now when running e.g. `mvn jetty:run` and then pressing ctrl-c, I see
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.507 s
[INFO] Finished at: 2023-07-07T20:04:07+03:00
[INFO] ------------------------------------------------------------------------
[WARNING] 
[WARNING] Plugin validation issues were detected in 3 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.8.1
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING]  * org.eclipse.jetty.ee10:jetty-ee10-maven-plugin:12.0.0.beta3
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
```

**Comment by janbartel** [comment] 2023-07-08 07:47
@Artur- that is very weird, I never get that with my own, very simple, webapp project. I'll try running your project and see what happens.

**Comment by olamy** [comment] 2023-07-08 19:58
The issue regarding scope already exists with 10/11 branches. 
Prior Maven 3.9.x those warnings were only at build time and not at runtime (e.g not displayed to end users)
Something to fix but not really blocker and not really urgent (not even sure those problems are blocker for Maven 4)

**Comment by olamy** [comment] 2023-10-04 02:27
duplicate of #7408

**Closed as completed by olamy** 2023-10-04 02:27 UTC
Labels: Bug
