### ISSUE TITLE
java.nio.file.ClosedFileSystemException on hot redeploy

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#11548] opened 2024-03-21 16:22 UTC
**12.0.x**

**ee-10**

**openjdk version "19.0.2"** 

**ubuntu**

**Description**

If an explicit webapp temporary directory is configured for a webapp  that is unpacked, then a hot redeploy of the webapp fails with the following exception:

```
2024-03-21 16:55:31.226:WARN :oejew.WebAppContext:Scanner-0-1: Failed startup of context oeje10w.WebAppContext@7c2cd67a{hotreload,/demo,b=file:///home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/foowork/webapp/,a=STOPPED,h=oeje10s.SessionHandler@17b8b0f9{STOPPED}}{/home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/wars/hotreload.war}
java.nio.file.ClosedFileSystemException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1635)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:536)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.readAttributes(ZipPath.java:773)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.readAttributes(ZipPath.java:783)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:276)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1849)
	at java.base/java.nio.file.Files.isDirectory(Files.java:2320)
	at org.eclipse.jetty.util.resource.PathResource.<init>(PathResource.java:170)
	at org.eclipse.jetty.util.resource.PathResource.<init>(PathResource.java:148)
	at org.eclipse.jetty.util.resource.MountedPathResource.<init>(MountedPathResource.java:33)
	at org.eclipse.jetty.util.resource.FileSystemPool.mount(FileSystemPool.java:132)
	at org.eclipse.jetty.util.resource.ResourceFactoryInternals$CompositeResourceFactory.mountIfNeeded(ResourceFactoryInternals.java:268)
	at org.eclipse.jetty.util.resource.ResourceFactoryInternals$CompositeResourceFactory.newResource(ResourceFactoryInternals.java:225)
	at org.eclipse.jetty.util.resource.ResourceFactoryInternals$Closeable.newResource(ResourceFactoryInternals.java:145)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.jetty.ee10.webapp.WebAppClassLoader.addJars(WebAppClassLoader.java:301)
	at org.eclipse.jetty.ee10.webapp.WebInfConfiguration.configure(WebInfConfiguration.java:85)
	at org.eclipse.jetty.ee10.webapp.Configurations.configure(Configurations.java:505)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.configure(WebAppContext.java:477)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1219)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1043)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1149)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1040)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:496)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:522)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:162)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.pathChanged(ScanningAppProvider.java:308)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.pathChanged(ScanningAppProvider.java:75)
	at org.eclipse.jetty.util.Scanner.reportChange(Scanner.java:947)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:871)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:775)
	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:147)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

At this stage, I think the problem is something to do with the jar having exactly the same name as the jar that was previously closed when the context was stopped as part of the redeploy. I'm assuming this because this problem never occurs if we let jetty unpack the war to a temporary location (because the temporary location will always be a different directory).

**Comment by lorban** [comment] 2024-03-21 18:46
The root of the problem lies in the `ZipFileSystem` embedded in the JVM's runtime.

`ResourceFactory` implementations just call `FileSystemPool.mount()` on creation, and `FileSystemPool.unmount()` on close. 

`FileSystemPool` keeps a map of [mounted JAR file] -> [mount counter]. Upon mount, when the map does not contain the mounted JAR file, the latter is mounted with `FileSystems.newFileSystem()`. When the map does contain it, the mount counter is incremented. Upon unmount, the counter is decremented, and if it reaches zero, `FileSystems.close()` is called.

The problem is that if `FileSystems.close()` is called on a mounted JAR file that does not exist on disk anymore, that method throws `IOException` and that jar file sticks around in the JVM's internal mount list... in an unusable state.

I've written a simple reproducer that only relies on `jetty-util`, plus a horribly ugly fix that seems to solve the problem in 
https://github.com/jetty/jetty.project/pull/11549.

But we should probably figure out why we delete a JAR file before we close the `ResourceFactory` that mounted it.

**Comment by lorban** [comment] 2024-03-21 18:50
More specifically: `ZipFileSystemProvider.removeFileSystem()` calls `Path.toRealPath()` _before_ cleaning up its filesystem map. And `Path.toRealPath()` throws `IOException` when the file pointed by the `Path` instance does not exist.

This looks like a JDK bug to me: `ZipFileSystemProvider` should clean its filesystem map even if `Path.toRealPath()` throws.

**Comment by joakime** [comment] 2024-03-21 19:18
@janbartel as I was chasing a duplicate WebAppClassloader entry thing that @lorban discovered, I was also able to replicate the ClosedFileSystemException from this issue in a smaller way.

See draft PR #11550

**Comment by joakime** [comment] 2024-03-21 19:20
> More specifically: `ZipFileSystemProvider.removeFileSystem()` calls `Path.toRealPath()` _before_ cleaning up its filesystem map. And `Path.toRealPath()` throws `IOException` when the file pointed by the `Path` instance does not exist.
> 
> This looks like a JDK bug to me: `ZipFileSystemProvider` should clean its filesystem map even if `Path.toRealPath()` throws.

We also still need to figure out why the hotreload seems to delete the `WEB-INF/lib/*.jar` from the disk before the `WebAppContext.stop()` has completed (and the associated `ResourceFactory` releases its entries)

**Comment by janbartel** [comment] 2024-03-22 08:45
@joakime and @lorban during the context stop, the sequence is:

`ServletContextHandler.doStop() -> WebAppContext.stopContext() -> ServletContextHandler.stopContext() -> ContextHandler.doStop() -> IO.deleteTempDirectory()`

then 

`WebAppContext.stopContext() -> WebAppClassLoader.close() -> IO.close(resourceFactory)`

So the `ContextHandler` is deleting the temp directory before the `WebAppClassLoader` closes its `ResourceFactory`.

I think @lorban is right, and that `ZipFileSystemProvider` should clean up correctly despite exceptions.

The only other alternative is to move the point at which the call to remove the temp directory is done.

**Comment by janbartel** [comment] 2024-03-22 09:39
@lorban actually, even if we called `ResourceFactory.Closeable.close()` _before_ we deleted the tmp directory, would those resources get unmounted properly? Is there a "sure kill" of unmounting, even if the resource count doesn't drop to 0?

**Comment by lorban** [comment] 2024-03-22 09:46
Unfortunately, I don't think there is a 100% guarantee with such behavior of the `ZipFileSystemProvider`. AFAICT the best we can do is to find workarounds, and file a bug against OpenJDK.

**Comment by lorban** [comment] 2024-03-22 09:47
It's actually already been reported: https://bugs.openjdk.org/browse/JDK-8291712

**Comment by janbartel** [comment] 2024-03-22 10:33
> Unfortunately, I don't think there is a 100% guarantee with such behavior of the `ZipFileSystemProvider`. AFAICT the best we can do is to find workarounds, and file a bug against OpenJDK.

I just quickly tried commenting out the deletion of the tmp dir by `ContextHandler` and the redploy worked fine - on ubuntu at least. This may be a path for us until the jvm gets fixed.

**Comment by sbordet** [comment] 2024-03-22 16:48
I agree with @janbartel that if this is an ordering problem, we should fix the order.
The workaround may remain, but ultimately it's a non-optimal ordering that causes the problem.

**Comment by lorban** [comment] 2024-03-22 16:52
@sbordet I agree with you: ordering needs to be fixed, and this is what @joakime has been working on in https://github.com/jetty/jetty.project/pull/11550.
But I also think this workaround is worth being merged too.

**Comment by lorban** [comment] 2024-03-25 10:14
The workaround (https://github.com/jetty/jetty.project/pull/11549) has been merged, but we still need to fix the delete/unmount ordering.

**Comment by joakime** [comment] 2024-03-27 21:05
Closing, as this has been addressed across a number of PRs.

**Closed as completed by joakime** 2024-03-27 21:05 UTC
Labels: High Priority, Bug
