### ISSUE TITLE
ArrayTernaryTrie max capacity

### ISSUE THREAD

**Issue by janci007** [eclipse/jetty.project#5323] opened 2020-09-24 12:49 UTC
**Jetty version** 9.4.30

**Java version** 8 (not relevant)

**OS type/version** Linux (not relevant)

**Description**

For org.eclipse.jetty.util.ArrayTernaryTrie

Expected:
- the maximum capacity will be stated in documentation

Actual:
- the maximum capacity is not stated in documentation

Expected:
- Trie created with large capacity by new ArrayTernaryTrie(65536)  would work correctly OR the constructor will throw IllegalArgumentException or OutOfBoundsException

Actual:
- new ArrayTernaryTrie(65536) works without exception but the Trie does not work correctly

Expected:
- put() will return false if element is not stored in trie

Actual:
- put() method on a trie with capacity > 65535 does not return false even if the element does not fit in the trie

This manifests in ContextHandlerCollection with large number of handlers by not being able to handle requests even when the handler is registered (Handler is not found in the Mapping)

Following code should either show "No capacity for xxxxxx..." or should find non-null result for the getBest() call.
It returns null result from getBest() instead.
```
public static void main(String args[]){
        Trie<String> t = new ArrayTernaryTrie<>(65536);    
        
        String search = "";
        int max = 2000;
        for(int i = 0; i < max; i++){
            String uid = UUID.randomUUID().toString();
            boolean ok = t.put(uid, Integer.toString(i));
            if(i == max/2) search = uid;
            if(!ok) System.out.println("No capacity for "+uid);
        }
        System.out.println(search+" = " + t.getBest(search));
    }
```

I believe it is caused by ArrayTernaryTrie being implemented by char[] array for tree nodes.

**Comment by joakime** [comment] 2020-09-24 14:37
This is a duplicate of #5291
And is being worked on in PR #5293

**Closed as completed by joakime** 2020-09-24 14:37 UTC
Labels: Duplicate
