### ISSUE TITLE
Jetty allows requests to hang under PUT load

### ISSUE THREAD

**Issue by sklock** [eclipse/jetty.project#1062] opened 2016-11-02 21:19 UTC
Using the `ServerConnector` backed by an `SslConnectionFactory` and an `HttpConnectionFactory`, we've observed Jetty go into a state where requests hang when subjected to `PUT` load.  In particular, the requests hang until the socket idle timeout is reached, whereupon Jetty terminates them.

I'm attaching [an archive](https://github.com/eclipse/jetty.project/files/567708/test-project.zip) containing a Maven project with a server and a JMeter test plan that seem to reproduce the issue.  We've been able to reproduce the issue with the server and test plan executed on different hosts (both running some flavor of Linux); we have not been able to reproduce it if the server and plan are executed on the same host.

Some additional details:

* We ran into this issue in the context of trying to upgrade from Jetty 8 to 9.  Through some experimentation, we've determined that the behavior was introduced in 9.3.0.M2.  We haven't tested every release since, but we have observed it in the most recent release.
** In previous versions of Jetty, with the same client, the test server would fully read each request and send a canned response.  No requests would hang.
* We know that Jetty is closing the connection due to the idle timeout because of the following logging output:
```
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms
	at org.eclipse.jetty.server.HttpInput$ErrorState.noContent(HttpInput.java:831)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:189)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at SimpleHandler$HelloHandler.read_data(SimpleHandler.java:97)
	at SimpleHandler$HelloHandler.handle(SimpleHandler.java:84)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:523)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
```
* We've also observed log records like these in some tests, but we don't know what they mean:
```
2016-11-02 11:43:42.979:WARN:oejut.QueuedThreadPool:qtp1324119927-136: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1daee9ab in qtp1324119927{STARTED,8<=200<=200,i=0,q=128}
2016-11-02 11:43:43.011:WARN:oejut.QueuedThreadPool:qtp1324119927-52: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1daee9ab in qtp1324119927{STARTED,8<=200<=200,i=177,q=0}
2016-11-02 11:43:43.009:WARN:oejut.QueuedThreadPool:qtp1324119927-62: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1daee9ab in qtp1324119927{STARTED,8<=200<=200,i=174,q=0}
2016-11-02 11:43:43.007:WARN:oejut.QueuedThreadPool:qtp1324119927-119: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1daee9ab in qtp1324119927{STARTED,8<=200<=200,i=167,q=0}
2016-11-02 11:43:43.004:WARN:oejut.QueuedThreadPool:qtp1324119927-211: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1daee9ab in qtp1324119927{STARTED,8<=200<=200,i=116,q=0}
2016-11-02 11:43:43.011:WARN:oejut.QueuedThreadPool:qtp1324119927-133: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1daee9ab in qtp1324119927{STARTED,8<=200<=200,i=177,q=0}
```
* To reproduce the issue, we sometimes have to run the test plan a couple times in succession (is this a race condition?).

**Comment by joakime** [comment] 2016-11-02 21:46
This appears to perform a multi-part POST but using PUT instead? (is that right?)

And not using the Servlet spec MultipartConfig behavior. (is that right?)

**Comment by joakime** [comment] 2016-11-02 21:54
Looks like jmeter is creating bad HTTP content to Jetty.

```
2016-11-02 14:52:29.900:WARN:oejh.HttpParser:qtp359037866-40: bad HTTP parsed: 400 Bad HostPort for HttpChannelOverHttp@f64c140{r=0,c=false,a=IDLE,uri=null}
org.eclipse.jetty.http.BadMessageException: 400: Bad HostPort
	at org.eclipse.jetty.http.HostPortHttpField.<init>(HostPortHttpField.java:48)
	at org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:914)
	at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:1088)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1320)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:350)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.IllegalArgumentException: Bad host
	at org.eclipse.jetty.util.HostPort.<init>(HostPort.java:82)
	at org.eclipse.jetty.http.HostPortHttpField.<init>(HostPortHttpField.java:44)
	at org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:914)
	at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:1088)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1320)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:350)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
```

**Comment by joakime** [comment] 2016-11-02 22:39
@gregw interestingly, the format of the request that jmeter uses is ...

Using Java Impl ...

```
PUT /foo HTTP/1.1
Connection: keep-alive
Content-Length: 52
User-Agent: Java/1.8.0_92
Host: :8080
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2

${__RandomString(102400,abcdefghijklmnopqrstuvwxyz)}
```

or with HC3.1 Impl ...

```
PUT /foo HTTP/1.1
Connection: keep-alive
Content-Length: 52
User-Agent: Jakarta Commons-HttpClient/3.1
Host: :8080

${__RandomString(102400,abcdefghijklmnopqrstuvwxyz)}
```

**Comment by sklock** [comment] 2016-11-03 00:23
Thanks for taking a look.

> This appears to perform a multi-part POST but using PUT instead? (is that right?)

That's right, although the content-type isn't intended to be used.  The test server is intended to model an application that wants to suck up the entity of the HTTP request as a byte stream.

> And not using the Servlet spec MultipartConfig behavior. (is that right?)

Also correct.  The server is not intended to perform any processing on the request beyond parsing the headers and making the bytes of the entity available as a stream.

> Looks like jmeter is creating bad HTTP content to Jetty. (...)

Interesting -- that's not what it produces for us.  (Worth noting: I should have mentioned in the original description that there's a variable "host" in the plan that needs to be set to the DNS name/IP address of the host running the server.)  If I set the "host" variable to 127.0.0.1 and disable HTTPS, this is what JMeter sends (without changing the client impl):

```
PUT /foo HTTP/1.1
Connection: keep-alive
Content-Length: 102400
Content-Type: text/plain; charset=ISO-8859-1
Host: 127.0.0.1:8443
User-Agent: Apache-HttpClient/4.3.3 (java 1.5)

... random text data...
```

This is from a machine running JMeter 2.8.  2.12 has also behaved the same way for us.

**Comment by joakime** [comment] 2016-11-03 12:56
This just isn't failing for us (once we fix the `Host` header on the jmeter testplan side).

Typical results for https/8443:

    Generate Summary Results = 637644 in  91.2s = 6994.7/s Avg:    32 Min:     0 Max:  3147 Err:     0 (0.00%)

We'll go ahead and start expanding the scope of your testplan / test project to see if we can trigger the problem you are seeing.

**Comment by joakime** [comment] 2016-11-03 13:28
Ah, there we go.

The jmeter test plan is too aggressive for its own good.

If we modify your SimpleHandler to add normal http/8080 connector, then use your jmeter testplan as-is, then there's a few issues.

Example summary http/8080:

    Generate Summary Results = 1062103 in  91.2s = 11651.0/s Avg:     1 Min:     0 Max:  1009 Err: 26761 (2.52%)
    Generate Summary Results = 1612510 in  91.1s = 17704.5/s Avg:    12 Min:     0 Max:  7055 Err: 28982 (1.80%)

> The reason it doesn't fail for us in https/8443 is that (frankly) Java's SSL/TLS implementation are simply not that performant.

First, it opens a connection, sets `Connection: keep-alive` on all requests, and doesn't close the connection.  (this is a bogus scenario and does not represent the real world usage of a web server).

The testplan should be adjusted to be more real-world.

Eg: open a connection, send a few requests using `Connection: keep-alive`, then a final request with `Connection: close` at the end.   (a single chain of requests can be a random number of requests, but not too many.  Browse a few resource heavy sites with your browser inspect tab open and you'll see some real world behavior yourself)

Jmeter also doesn't wait for the sent request to get a response before sending the next request on this pipelined connection.

This can easily result in timeouts of the later requests as they have to wait their turn on the pipelined responses. 

The timeouts you see can also be from these open (and not closed) connection needing to be cleaned up via the idle timeout features.

Any one of the following makes things behave better:

- Turning off `keep-alive`
- Using Java Impl - the java impl doesn't support `keep-alive`
- Using HC3.1 Impl - its behavior for `keep-alive` seems to force `Connection: close` every so often (almost like it has a upper limit of the number of requests per connection)
- Adjusting testplan to use keep-alive for only 10 requests (loop controller), then issuing a final GET request to close the connection.  Test over and over again for 90s with 300 threads.

Note: Using HC4 actually exacerbates the problem.

Next, your testplan simply loops over and over again for 90 seconds, and quickly exhausts the client-side ephemeral ports, resulting in ...

```
java.net.NoRouteToHostException: Cannot assign requested address
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
```

If your goal is to test the load of the server, you'll need multiple client machines to adequately generate the load.

If we make the adjustments to the testplan for 90 seconds with a loop of 100 PUT using keep-alive, followed by a single GET with no-keep-alive then there's no failures on the client side or server side (and you can handle far more requests too!)

Eg:

    Generate Summary Results = 2776151 in  91.0s = 30493.1/s Avg:     9 Min:     0 Max:  1065 Err:     0 (0.00%)


Closing this issue as it is [a typical fault in load testing / benchmarking](https://webtide.com/lies-damned-lies-and-benchmarks-2/), not a fault in jetty server.

**Comment by sklock** [comment] 2016-11-08 14:32
Not to abuse a now-closed issue, but we'd like to make a few clarifying observations.

* One question that we think merits a little more investigation: Why are we only able to reproduce this in recent Jetty 9s?  In particular: we don't observe any trouble in Jetty 8, and for that matter we only observe this in 9.3.M2 and later.  Regardless of how realistic the test plan is, in our tests there is unambiguously a change in the server's behavior across versions.
* JMeter does not behave for us the way it has for you.  It may be worth understanding why that's the case.  In particular:
  * JMeter does not pipeline requests for us.  With this test plan, we've verified that on each connection, JMeter sends exactly one request and waits for a reply before sending the next one under both HttpClient implementations.  So later requests are not being effectively backlogged behind earlier requests.
  * JMeter also does not exhaust ephemeral ports on the client side for us.  Under both HttpClient implementations, it opens and maintains 300 connections to the server; it doesn't open more than that.
  * Finally, it looks like JMeter is failing to interpolate the results of a macro function in your runs.  For us, `${__RandomString(102400,abcdefghijklmnopqrstuvwxyz)}` is interpreted (as the text suggests) as 100 KB of random text data.  In two of the sample requests from your runs, it instead used the literal string.  We think this is an important distinction; in our tests, we haven't observed this issue with small requests.
* We're certainly agreeable to the claim that the proposed test plan isn't a realistic test case, but that's not its intent.  We've observed this behavior with more complex tests that model behavior that's (for our use case) more realistic, and we wanted to build a very simple test plan (and server) that (at least in our environment) reproduces this behavior with a reasonable degree of consistency.  That's what the plan was for.
* It's also worth noting that we haven't been able to reproduce this behavior _without_ TLS.  Plaintext HTTP definitely goes faster, but the behavior doesn't seem to be directly related to raw request throughput.
* Finally, to populate our use case with a little more detail: we're using Jetty to front a REST API, so we're expecting most of our clients will not be browsers.  Instead, they're likely to be long-running applications issuing automated requests.  The use cases for our API vary across these applications, but high request rates and keep-alive are both useful for many of them.  For our testing, it really doesn't make sense to model clients that don't have those characteristics.

**Comment by joakime** [comment] 2016-11-08 15:04
Don't be afraid to reopen issues here. 

Jmeter is far too variable for this issue, let's work in a more consistent test case that can reproduce this.

**Comment by joakime** [comment] 2016-11-08 22:19
Created a test project for this issue at

https://github.com/jetty-project/issue-1062

Was able to produce some strange results during a conference call with @sbordet 

Attaching the logs for @sbordet here ...

[jmx-dump-client.log.gz](https://github.com/eclipse/jetty.project/files/579504/jmx-dump-client.log.gz)
[jmx-dump-server.log.gz](https://github.com/eclipse/jetty.project/files/579503/jmx-dump-server.log.gz)

**Comment by gregw** [comment] 2016-11-08 23:39
@joakime you have reopened this, so I probably don't need to say this...  but even with an unrealistic test plan, the failure mode of a request going dormant until it hits a timeout is not a good failure mode.

I suspect we may have a problem with large SSL request content.  So I think you are proceeding correctly to try to reproduce with eliminating variables like jmeter.

I will look to see what changed in the 9.3.0.M2 release.

**Comment by joakime** [comment] 2016-11-08 23:44
@gregw the failure mode is occurring in 9.3.14 as well.  
The attached jmx-dumps (above) are from a run with 9.3.14.

**Comment by gregw** [comment] 2016-11-08 23:48
@sklock So I'm assuming there are no indications of the read operations spinning?    Thus can we assume that those read requests have blocked and failed to wake up, even though you believe the content has arrived?

If so, I'm thinking we need to consider how we are unblocking SSL input when new content arrives.

**Comment by sklock** [comment] 2016-11-09 04:38
> So I'm assuming there are no indications of the read operations spinning? Thus can we assume that those read requests have blocked and failed to wake up, even though you believe the content has arrived?

That's right.  When the server enters the bad state with the test plan we supplied, we observe that:

* the CPU appears idle (and a thread dump from the server shows nearly all threads are blocked),
* there are 300 open connections from the client to the server, and
* according to `netstat`, there is data available in the receive buffer for a large subset of those connections.

We also notice the server becomes unresponsive to new requests from separate clients (e.g., `curl`).  After five minutes, the server closes the connections due to the idle timeout, whereupon it seems to return to a good state.

**Comment by gregw** [comment] 2016-11-09 22:59
We found the problem, which was a thread starvation issue.  All the available threads become blocked in  read and while data has arrived to unblock them, there are no threads available to run the onFillable task.

Luckily this is something that we had already partially solved in 9.3 and have an even better fix in 9.4.  We had just not applied that solution to the SSL Connection. 3b36b13 Applies the non blocking callback fix to 9.3 - it would be great if you could test it out!

**Comment by joakime** [comment] 2016-11-09 23:20
Just dropping a note that we need some better thread starvation unit tests for the SSL cases.

**Comment by sklock** [comment] 2016-11-10 17:06
We're not able to reproduce the behavior with the proposed fix.  Looks good to us, thanks!

**Comment by gregw** [comment] 2016-11-11 01:15
Great!  I will close and the fix is already in the repo ready for the next releases...
actually I wont close as we do need to make our thread starvation test check SSL.

**Comment by laeubi** [comment] 2016-11-17 08:37
> Don't be afraid to reopen issues here. 

@joakime It seems ordinarry users can't reopen issues in case another user has closed them. E.g. @janbartel  has closed this issue I reported https://github.com/eclipse/jetty.project/issues/593 but I can't open it again even though I can comment on them.

**Comment by sbordet** [comment] 2016-11-17 09:24
@laeubi see https://github.com/isaacs/github/issues/583 - a long standing feature request for GitHub.

Please comment and ask to reopen (explaining the reason), and we will reopen it for you.

**Comment by joakime** [comment] 2016-11-18 00:20
Added ssl variation of the tests for thread starvation.
Closing issue.

**Closed by joakime** 2016-11-18 00:20 UTC
Labels: Bug
