### ISSUE TITLE
org.eclipse.jetty.util.log.JettyAwareLogger#log discards argArray

### ISSUE THREAD

**Issue by juretta** [eclipse/jetty.project#1578] opened 2017-05-29 16:16 UTC
`JettyAwareLogger` explicitly discards the `argArray` when calling the underlying `LocationAwareLogger`: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/log/JettyAwareLogger.java#L617-L620

We are using structured logging with https://github.com/logstash/logstash-logback-encoder and use `StructuredArgument`s (https://github.com/logstash/logstash-logback-encoder#event-specific-custom-fields) to add additional information to the log event.

When using `org.eclipse.jetty.server.Slf4jRequestLog` (which in turns ends up using the `JettyAwareLogger` the `StructuredArgument`s are simply ignored as the `JettyAwareLogger` formats the message but discards the `argArray`.

I'm not sure what the but is that is being avoided by not passing through the `argsArray` but it does cause an unexpected behaviour given the assumption `Slf4jRequestLog` would just use the configured SLF4J/Logback logger.

**Comment by gregw** [comment] 2017-05-30 08:31
This behaviour was added to fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=357216
Note that the argArray is not ignore, but rather used to format the message prior to passing to the nested logger.

I'm unsure if that is a good solution, because we should perhaps do more to support correctly implemented loggers rather than patching over behaviour of bad ones?   @joakime @sbordet  thoughts?

**Comment by gregw** [comment] 2017-05-30 08:33
Original slf4j bug reference link is broken, but you can see email log here http://mailman.qos.ch/pipermail/slf4j-dev/2011-September/003428.html

**Comment by gregw** [comment] 2017-05-30 08:50
The suggestion made in that thread is that we format the message, but still pass the args?!?!  Hmm that's pretty ugly and probably wont help the OP much.

But the most recent version of [org.slf4j.impl.Log4jLoggerAdapter.java](
https://github.com/qos-ch/slf4j/blob/master/slf4j-log4j12/src/main/java/org/slf4j/impl/Log4jLoggerAdapter.java#L579-L582) still ignores the passed args.  So I'm not really sure what we can do here.

For custom loggers that use the args, like the OPs we are not passing them, but for standard logging bridges that ignore them by design, we have to process them.

Perhaps we can make this configurable behaviour?  It would be nice to avoid all the wrappers of wrappers as well.

@juretta during the meanwhile, perhaps you can write your own jetty logging adaptor class that does exactly what you want, it may save a few logging wrappers as well?

**Comment by juretta** [comment] 2017-05-30 09:31
Thanks @gregw - that's what I did. Just wanted to raise this issue, as I noticed the problem with `JettyAwareLogger` whilst adding structured logging information.

**Comment by joakime** [comment] 2017-05-30 13:24
New link to (broken) slf4j bug mentioned in slf4j mailing list - https://jira.qos.ch/browse/SLF4J-231

**Comment by joakime** [comment] 2017-05-31 17:37
Out of curiosity, how are you using `org.eclipse.jetty.server.Slf4jRequestLog` in a way where the `argArray` makes sense? 

The only thing that uses that logger is the internal implementation in Jetty, and it formats the request event according to NCSA request log output and sends it to that named logger without arguments.  There is no other usage of that class in Jetty, nor any way that makes sense outside of Jetty to use that class.

**Comment by joakime** [comment] 2017-05-31 17:40
Since Slf4j's own implementation doesn't use the `argArray` and according to the bug at slf4j, a future version of slf4j will remove the argArrays as well, there seems to be nothing we can do, or should do, and just wait for the eventual removal of those methods that have argArrays on the slf4j side.

Closing.

**Closed by joakime** 2017-05-31 17:40 UTC
Labels: Invalid

**Comment by juretta** [comment] 2017-06-01 15:26
> according to the bug at slf4j, a future version of slf4j will remove the argArrays as well,

Looking at the bug, I can't find that? 

https://jira.qos.ch/browse/SLF4J-231 seems to be about the **Log4J**LoggerAdapter? Isn't that possibly specific to Log4J then?

> Out of curiosity, how are you using org.eclipse.jetty.server.Slf4jRequestLog in a way where the argArray makes sense?

Sorry, my bad. I meant to write the `org.eclipse.jetty.util.log.Slf4jLog`, not the `org.eclipse.jetty.server.Slf4jRequestLog`.

So my use case was doing something like this:

```
        logger.info("{} - {} [{}] \"{} {} {}\" {} {} \"{}\"",
                value("remote_addr", addr),
                value("authentication", auth),
                value("timestamp", formattedDate),
                value("http_method", method),
                value("http_uri", uri),
                value("http_proto", protocol),
                value("status", status),
                value("size", written),
                value("agent", agent),
                keyValue("http_headers", headers)
```

(where `value` and `keyValue` returns `StructuredArgument`s).

In my first implementation I tried to use the existing `org.eclipse.jetty.util.log.Slf4jLog` as the `logger` (assuming it would just delegate to the underlying Slf4J logger) but ran into the problem described above as, due to the fact that the `argArray` is dropped.

**Comment by joakime** [comment] 2017-06-01 15:35
Its probably most appropriate in your use case to use slf4j directly, not via the jetty layer.

You'll also gain the benefits of other features, like NDC support.

**Comment by juretta** [comment] 2017-06-01 15:36
That's what I ended up doing and that is fine. I just found it surprising that it didn't work.
