### ISSUE TITLE
AsyncContext.complete fails (WritePendingException) when called right after out.write

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#259] opened 2016-02-16 23:42 UTC
migrated from Bugzilla [#483091](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483091)
status REOPENED severity *critical* in component *server* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Project Inbox

On 2015-11-26 08:36:32 -0500, Heikki Vesalainen wrote:

> When AsyncContext.complete() is called from WriteListener.onWritePossible() right after ServletOutputStream.write(bytes), it fails if the write is still pending.
> 
> The stack trace is:
> 
> 2015-11-26 13:24:37.592 [qtp1346018901-83] WARN  org.eclipse.jetty.server.HttpChannel - /
> java.nio.channels.WritePendingException: null
>         at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:665) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:627) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:508) [jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:673) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:722) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:177) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:211) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.Response.closeOutput(Response.java:987) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:436) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [jetty-io-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
>         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
> 
> Here is the test code:
> 
> import org.eclipse.jetty.server.ServerConnector;
> import org.eclipse.jetty.server.Server;
> import org.eclipse.jetty.server.HttpConnectionFactory;
> import org.eclipse.jetty.server.HttpConfiguration;
> import org.eclipse.jetty.servlet.ServletContextHandler;
> import org.eclipse.jetty.servlet.ServletHolder;
> import javax.servlet.http.*;
> import javax.servlet.*;
> import java.io.IOException;
> 
> public class JettyAsyncTest {
> 
>   public static byte[] testData = new byte[512*1024*1024];
> 
>   static {
>     for (int i = 0; i < testData.length; i++) {
>       testData[i] = (byte)('0' + (i%10));
>     }
>     testData[testData.length - 1] = '-';
>   }
> 
>   public static void main(String[] args) throws Exception {
>     Server s = createServer(5555);
>     addServlet(s, new TestServlet());
>     s.start();
>   }
> 
>   public static Server createServer(int port) {
>     ServletContextHandler context = new ServletContextHandler();
>     HttpConnectionFactory httpConnectionFactory = new HttpConnectionFactory(new HttpConfiguration());
>     Server server = new Server();
>     ServerConnector connector = new ServerConnector(server, httpConnectionFactory);
> 
>     context.setContextPath("/");
>     server.addConnector(connector);
>     server.setHandler(context);
>     connector.setPort(port);
> 
>     return server;
>   }
> 
>   public static void addServlet(Server server, Servlet servlet) {
>     ServletContextHandler c = (ServletContextHandler) server.getHandler();
>     c.addServlet(new ServletHolder(servlet), "/");
>   }
> 
>   public static class TestServlet extends HttpServlet {
>     public void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException {
>       AsyncContext ac = req.startAsync();
>       ac.setTimeout(1000L*60*60);
>       ServletOutputStream out = res.getOutputStream();
>       out.setWriteListener(new TestWriteListener(out, ac));
>     }
>   }
> 
>   public static class TestWriteListener implements WriteListener {
>     ServletOutputStream out;
>     AsyncContext ac;
> 
>     public TestWriteListener(ServletOutputStream out, AsyncContext ac) {
>       this.out = out;
>       this.ac = ac;
>     }
> 
>     public void onWritePossible() {
>       if (out.isReady()) {
>         try {
>           out.write(JettyAsyncTest.testData);
>         } catch (IOException e) {
>           e.printStackTrace();
>         } finally {
>           ac.complete();
>         }
>       }
>     }
> 
>     public void onError(Throwable t) {
>       t.printStackTrace();
>     }
>   }
> }
> 
> To use the test, use wget/curl/telnet, etc to the port 5555 and GET /. The result is an instant failure (i.e. there is not timeout).

On 2015-11-26 16:28:51 -0500, Greg Wilkins wrote:

> Heikki,
> 
> I believe that is by design.   You have done an asynchronous write that is still pending, so you are unable to do a complete() until that write is complete (signalled by isReady() returning true).
> 
> 
> You need to do something like:
> 
>     public void onWritePossible() {
>       while (out.isReady()) {
>         try {
>           if (!written) {
>             written=true;
>             out.write(JettyAsyncTest.testData);
>           } else {
>             ac.complete();
>           }   
>         } catch (IOException e) {
>           e.printStackTrace();
>           ac.complete();
>         }
>       }
>     }
> 
>     public void onError(Throwable t) {
>       t.printStackTrace(); 
>       ac.complete();
>     }

On 2015-11-26 17:25:53 -0500, Heikki Vesalainen wrote:

> Greg, are you sure Jetty's interpretation of the specification correct. The specification is not 100% clear on the subject, but it does say: 
> 
> "It is legal to call this [complete] method anytime after a call to ServletRequest.startAsync() or ServletRequest.startAsync(ServletRequest, ServletResponse) and before a call to one of the dispatch methods."
> 
> The specification doesn't say what happens if you call complete when a write is pending, but at least it doesn't say the already written data would be lost.

On 2015-11-26 18:09:32 -0500, Greg Wilkins wrote:

> Reopening while we have the discussion.
> 
> I'm not 100% and yes the spec is very ambiguous... (I have to take some of the blame there).
> 
> The text about complete being able to be called anytime was written before the async IO API was added to the spec, thus it was written before it was possible to have a write pending... ie before there was state that may need to be resolved before a lifecycle can complete.
> 
> I will raise this with the servlet EG to see what they think.   However I believe that a complete() is an implicit write (as it may have to send the end chunk) and thus cannot be attempted until the previous write is complete.

On 2015-11-26 18:17:09 -0500, Greg Wilkins wrote:

> See https://java.net/projects/servlet-spec/lists/jsr369-experts/archive/2015-11/message/0

**Comment by gregw** [comment] 2016-02-17 14:09
Closed as duplicate of #264

**Closed by gregw** 2016-02-17 14:09 UTC
Labels: Bug
