### ISSUE TITLE
JavaVersion incorrectly parses java version returned on hp-ux

### ISSUE THREAD

**Issue by zerovian** [eclipse/jetty.project#2317] opened 2018-03-12 16:23 UTC
Jetty: 9.4.8.v20171121

The java version parsing on hp-ux in JavaVersion class is broken.

hp-ux reports it "java.version" string as "1.8.0.07-hp-ux".  But the JavaVersion class throws exception parsing this, causing Jetty to be unusable on hp-ux with a java 1.8 version.

>java -version
java version "1.8.0.07-hp-ux"
Java(TM) SE Runtime Environment (build 1.8.0.07-hp-ux-b1)
Java HotSpot(TM) 64-Bit Server VM (build 25.07-b1, mixed mode)

----test-----
import org.eclipse.jetty.util.JavaVersion;

public class TestJettyVersion {

	public static void main(String[] args) {
		
		System.out.println(JavaVersion.VERSION);
	}
}

---output -----

Exception in thread "main" java.lang.ExceptionInInitializerError
        at TestJettyVersion.main(TestJettyVersion.java:7)
Caused by: java.lang.IllegalArgumentException: Invalid Java version 1.8.0.07-hp-ux
        at org.eclipse.jetty.util.JavaVersion.parsePreJDK9(JavaVersion.java:56)
        at org.eclipse.jetty.util.JavaVersion.parse(JavaVersion.java:48)
        at org.eclipse.jetty.util.JavaVersion.<clinit>(JavaVersion.java:43)

**Comment by joakime** [comment] 2018-03-12 16:34
Can you tell us the values for the following system properties on your system?

```
  java.version
  java.runtime.version
  java.vm.version
  java.specification.version
  java.vm.specification.version
```

**Comment by joakime** [comment] 2018-03-12 16:39
@gregw Didn't take long, here's "the next jvm" that broke us. (from Issue #2284)

**Comment by zerovian** [comment] 2018-03-12 21:54
on AIX (not the one causing problems):

**Comment by zerovian** [comment] 2018-03-12 21:55
On HP-UX (the one causing problems, sent that last one too fast)

java.version = 1.8.0.07-hp-ux
java.runtime.version = 1.8.0.07-hp-ux-b1
java.vm.version = 25.07-b1
java.specification.version = 1.8
java.vm.specification.version = 1.8

**Comment by gregw** [comment] 2018-03-12 22:10
@joakime indeed :) However, the fix for #2284 also better handles this value.  The interesting thing to note is that `java.version` in this case is not much better than `java.runtime.version`

@zerovian Can you try the staged jetty-9.4.9 at https://oss.sonatype.org/content/repositories/jetty-1369/ and I believe it will work for you.

However, I think we still need to do a bit better here...

**Comment by zerovian** [comment] 2018-03-13 15:02
Nope.  Still broken.

hp-ux, and linux work ...but aix doesn't.

HP-UX ia64 output

java.version = 1.8.0.07-hp-ux
java.runtime.version = 1.8.0.07-hp-ux-b1
java.vm.version = 25.07-b1
java.specification.version = 1.8
java.vm.specification.version = 1.8
JavaVersion.VERSION = 1.8.0.07-hp-ux-b1

----------------------
linux x86_64 output

java.version = 1.8.0_101
java.runtime.version = 1.8.0_101-b13
java.vm.version = 25.101-b13
java.specification.version = 1.8
java.vm.specification.version = 1.8
JavaVersion.VERSION = 1.8.0_101-b13


aix output

-------------------
java.version = 1.8.0
java.runtime.version = pap6480sr3fp10-20160720_02 (SR3 FP10)
java.vm.version = 2.8
java.specification.version = 1.8
java.vm.specification.version = 1.8
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
        at
java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
        at TestJettyVersion.main(TestJettyVersion.java:14)
Caused by: java.lang.IllegalArgumentException: Invalid version string:
'pap6480sr3fp10-20160720_02 (SR3 FP10)'
        at org.eclipse.jetty.util.JavaVersion.parse(JavaVersion.java:53)
        at org.eclipse.jetty.util.JavaVersion.<clinit>(JavaVersion.java:47)


--------------------- TestJettyVersion.java --------------

import org.eclipse.jetty.util.JavaVersion;


public class TestJettyVersion {

        public static void main(String[] args) {

            System.out.println("java.version = " +
System.getProperty("java.version"));
            System.out.println("java.runtime.version = " +
System.getProperty("java.runtime.version"));
            System.out.println("java.vm.version = " +
System.getProperty("java.vm.version"));
            System.out.println("java.specification.version = " +
System.getProperty("java.specification.version"));
            System.out.println("java.vm.specification.version = " +
System.getProperty("java.vm.specification.version"));

            System.out.println("JavaVersion.VERSION = " +
JavaVersion.VERSION);


        }
}

**Comment by joakime** [comment] 2018-03-13 15:18
Since github is filtering the sections as "replies" in this comment section, I'm copy/pasting the sections again so that it can be seen (and searched for) in the future.

## HP-UX ia64 output

java.version = 1.8.0.07-hp-ux
java.runtime.version = 1.8.0.07-hp-ux-b1
java.vm.version = 25.07-b1
java.specification.version = 1.8
java.vm.specification.version = 1.8
JavaVersion.VERSION = 1.8.0.07-hp-ux-b1


## linux x86_64 output

java.version = 1.8.0_101
java.runtime.version = 1.8.0_101-b13
java.vm.version = 25.101-b13
java.specification.version = 1.8
java.vm.specification.version = 1.8
JavaVersion.VERSION = 1.8.0_101-b13


## aix output


java.version = 1.8.0
java.runtime.version = pap6480sr3fp10-20160720_02 (SR3 FP10)
java.vm.version = 2.8
java.specification.version = 1.8
java.vm.specification.version = 1.8
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
        at TestJettyVersion.main(TestJettyVersion.java:14)
Caused by: java.lang.IllegalArgumentException: Invalid version string: 'pap6480sr3fp10-20160720_02 (SR3 FP10)'
        at org.eclipse.jetty.util.JavaVersion.parse(JavaVersion.java:53)
        at org.eclipse.jetty.util.JavaVersion.<clinit>(JavaVersion.java:47)


## TestJettyVersion.java

``` java
import org.eclipse.jetty.util.JavaVersion;

public class TestJettyVersion {
        public static void main(String[] args) {
            System.out.println("java.version = " + System.getProperty("java.version"));
            System.out.println("java.runtime.version = " + System.getProperty("java.runtime.version"));
            System.out.println("java.vm.version = " + System.getProperty("java.vm.version"));
            System.out.println("java.specification.version = " + System.getProperty("java.specification.version"));
            System.out.println("java.vm.specification.version = " + System.getProperty("java.vm.specification.version"));
            System.out.println("JavaVersion.VERSION = " + JavaVersion.VERSION);
        }
}
```

**Comment by joakime** [comment] 2018-03-13 15:25
@zerovian  A slightly updated version of your testcase ...

I'm curious to know if HPUX / AIX can return relevant/useful information from `Object.class.getPackage().getImplementationVersion()`

``` java
import org.eclipse.jetty.util.JavaVersion;

public class TestVersions
{
    public static String getObjectVersion()
    {
        return Object.class.getPackage().getImplementationVersion();
    }

    public static void main(String[] args)
    {
        System.out.println("java.version = " + System.getProperty("java.version"));
        System.out.println("java.runtime.version = " + System.getProperty("java.runtime.version"));
        System.out.println("java.vm.version = " + System.getProperty("java.vm.version"));
        System.out.println("java.specification.version = " + System.getProperty("java.specification.version"));
        System.out.println("java.vm.specification.version = " + System.getProperty("java.vm.specification.version"));
        System.out.println("Object.class.package.implementationVersion = " + getObjectVersion());
        System.out.println("JavaVersion.VERSION = " + JavaVersion.VERSION);
    }
}
```

**Comment by zerovian** [comment] 2018-03-13 15:31
**HP-UX output**

java.version = 1.8.0.07-hp-ux
java.runtime.version = 1.8.0.07-hp-ux-b1
java.vm.version = 25.07-b1
java.specification.version = 1.8
java.vm.specification.version = 1.8
Object.class.package.implementationVersion = 1.8.0.07-hp-ux
JavaVersion.VERSION = 1.8.0.07-hp-ux-b1


**AIX output**

java.version = 1.8.0
java.runtime.version = pap6480sr3fp10-20160720_02 (SR3 FP10)
java.vm.version = 2.8
java.specification.version = 1.8
java.vm.specification.version = 1.8
Object.class.package.implementationVersion = 1.8.0-internal
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
        at TestVersions.main(TestVersions.java:18)
Caused by: java.lang.IllegalArgumentException: Invalid version string: 'pap6480sr3fp10-20160720_02 (SR3 FP10)'
        at org.eclipse.jetty.util.JavaVersion.parse(JavaVersion.java:53)
        at org.eclipse.jetty.util.JavaVersion.<clinit>(JavaVersion.java:47)
        ... 1 more

**Comment by joakime** [comment] 2018-03-13 15:39
Meh, can't rely on `Object.class.getPackage().getImplementationVersion()` then. 
Looks like `java.version` is still the safest choice.

**Comment by zerovian** [comment] 2018-03-15 14:29
Tested all the official releases.  The last one that ran without the failure due to the version check is 9.3.15.v20161220.  Any release after this fails on hp-ux.

**Comment by joakime** [comment] 2018-03-15 14:31
@zerovian the current HEAD on `jetty-9.4.x` branch has a bunch of fixes for this.
Also, we are currently staging a potential 9.4.9 release.

If you are feeling up to it, you can build the `jetty-9.4.x` HEAD and test it, or you can wait till the 9.4.9 stage is ready and you can test that.

**Comment by joakime** [comment] 2018-03-15 15:29
The Jetty 9.4.9 stage is available.

> Note: this is not an official release, and only represents a potential release.
> It will only be official once adequate testing has been performed and then promoted to general release.

https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.9.v20180315
Many many fixes, see above link for list.

Staging Repository: https://oss.sonatype.org/content/repositories/jetty-1370/

**Comment by zerovian** [comment] 2018-03-15 15:32
Gave up as mvn kept building for java 9 instead of 8.

I tired the snapshot from here:
https://oss.sonatype.org/content/repositories/jetty-snapshots/org/eclipse/jetty/

HP-UX output:

**Comment by zerovian** [comment] 2018-03-15 15:37
Used this:
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.9.v20180315

Seems good:

HP-UX:
java.version = 1.8.0.07-hp-ux
java.runtime.version = 1.8.0.07-hp-ux-b1
java.vm.version = 25.07-b1
java.specification.version = 1.8
java.vm.specification.version = 1.8
Object.class.package.implementationVersion = 1.8.0.07-hp-ux
JavaVersion.VERSION = 1.8.0.07-hp-ux

AIX:

java.version = 1.8.0
java.runtime.version = pap6480sr3fp10-20160720_02 (SR3 FP10)
java.vm.version = 2.8
java.specification.version = 1.8
java.vm.specification.version = 1.8
Object.class.package.implementationVersion = 1.8.0-internal
JavaVersion.VERSION = 1.8.0

SOLARIS:

java.version = 1.8.0_101
java.runtime.version = 1.8.0_101-b13
java.vm.version = 25.101-b13
java.specification.version = 1.8
java.vm.specification.version = 1.8
Object.class.package.implementationVersion = 1.8.0_101
JavaVersion.VERSION = 1.8.0_101

Linux:

java.version = 1.8.0_101
java.runtime.version = 1.8.0_101-b13
java.vm.version = 25.101-b13
java.specification.version = 1.8
java.vm.specification.version = 1.8
Object.class.package.implementationVersion = 1.8.0_101
JavaVersion.VERSION = 1.8.0_101

**Comment by joakime** [comment] 2018-03-15 15:38
Oooh. Solaris, adding that data to our testcases too.  Thanks for that tidbit.

**Comment by joakime** [comment] 2018-03-20 17:32
We haven't made the announcement (yet), but a few minutes ago Jetty 9.4.9.v20180320 was released to central.maven.org

Link to jetty-home tarballs: http://central.maven.org/maven2/org/eclipse/jetty/jetty-home/9.4.9.v20180320/

If you can give that a whirl and confirm that our fixes are adequate for you that would be wonderful.

**Comment by zerovian** [comment] 2018-03-20 19:42
Jetty won't start from that .zip file. It complains about missing
start.ini.  I'll try to fetch that file from one of the other distributions.

>bin/jetty.sh start
Cannot find a start.ini file or a start.d directory in your JETTY_BASE
directory: <removed>/jetty-home-9.4.9.v20180320

**Comment by zerovian** [comment] 2018-03-20 19:47
Tested on aix, solaris, hpux, and aix.  Started ok on all of them once I put a start.ini in place.

**Comment by joakime** [comment] 2018-03-20 20:49
Note:  `jetty-home` is one half of the proper way to run Jetty. (the other is the `${jetty.base}` that you create)

See: https://www.eclipse.org/jetty/documentation/9.4.x/startup-base-and-home.html

`jetty-distribution` is `jetty-home` + `demo-base` (an example of `${jetty.base}`)

**Comment by joakime** [comment] 2018-03-20 20:49
Thanks for the update. closing.

**Closed by joakime** 2018-03-20 20:49 UTC
