### ISSUE TITLE
Flaky H3 in org.eclipse.jetty.ee10.test.client.transport.HttpClientContinueTest

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#11795] opened 2024-05-16 01:18 UTC
**Jetty version(s)**
jetty-12 branch fix/jetty-12/10541/byteBufferAccumulator0

**Description**
Every run of org.eclipse.jetty.ee10.test.client.transport.HttpClientContinueTest produces different failures (sometimes none) for H3.
It is potentially something due to the other changes in that branch, but the buffering for H3 has not yet been ported.

**Comment by gregw** [comment] 2024-10-01 22:25
@lorban had this been addressed? Can it be closed?

**Comment by lorban** [comment] 2024-10-02 08:50
This looks a lot like https://github.com/jetty/jetty.project/issues/12268 was the root cause.

I'm going to close this issue as I haven't seen any test related to 100-continue failing recently.

**Closed as completed by lorban** 2024-10-02 08:50 UTC
Labels: Bug, flaky-test
