### ISSUE TITLE
org.eclipse.jetty.http.BadMessageException: 500: No version

### ISSUE THREAD

**Issue by csliu** [eclipse/jetty.project#650] opened 2016-06-18 17:15 UTC
I am using Presto, which uses Jetty, from time to time, I see some random errors like: "org.eclipse.jetty.http.BadMessageException: 500: No version"

Any insight on what happened here?

Here is the full call stack:
org.glassfish.jersey.server.ServerRuntime$Responder An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: io.airlift.slice.RuntimeIOException: java.io.IOException: org.eclipse.jetty.http.BadMessageException: 500: No version
at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:91)
at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:621)
at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:377)
at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:367)
at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:828)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:858)
at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:820)
at io.airlift.http.server.AsyncResponseHandler.lambda$toCompletionCallback$3(AsyncResponseHandler.java:101)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
at io.airlift.concurrent.BoundedExecutor.executeOrMerge(BoundedExecutor.java:69)
at io.airlift.concurrent.BoundedExecutor.access$000(BoundedExecutor.java:28)
at io.airlift.concurrent.BoundedExecutor$1.run(BoundedExecutor.java:40)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: io.airlift.slice.RuntimeIOException: java.io.IOException: org.eclipse.jetty.http.BadMessageException: 500: No version
at io.airlift.slice.OutputStreamSliceOutput.writeBytes(OutputStreamSliceOutput.java:168)
at com.facebook.presto.spi.block.VariableWidthBlockEncoding.writeBlock(VariableWidthBlockEncoding.java:59)
at com.facebook.presto.block.BlockSerdeUtil.writeBlock(BlockSerdeUtil.java:50)
at com.facebook.presto.block.PagesSerde$PagesWriter.append(PagesSerde.java:83)
at com.facebook.presto.block.PagesSerde.writePages(PagesSerde.java:54)
at com.facebook.presto.block.PagesSerde.writePages(PagesSerde.java:47)
at com.facebook.presto.server.PagesResponseWriter.writeTo(PagesResponseWriter.java:91)
at com.facebook.presto.server.PagesResponseWriter.writeTo(PagesResponseWriter.java:41)
at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
... 24 more
Caused by: java.io.IOException: org.eclipse.jetty.http.BadMessageException: 500: No version
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:173)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:415)
at io.airlift.http.server.TimingFilter$TimedServletOutputStream.write(TimingFilter.java:162)
at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:298)
at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:233)
at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
at io.airlift.slice.CountingOutputStream.write(CountingOutputStream.java:56)
at java.io.DataOutputStream.write(DataOutputStream.java:107)
at io.airlift.slice.LittleEndianDataOutputStream.write(LittleEndianDataOutputStream.java:57)
at io.airlift.slice.Slice.getBytes(Slice.java:546)
at io.airlift.slice.OutputStreamSliceOutput.writeBytes(OutputStreamSliceOutput.java:165)
... 37 more
Caused by: org.eclipse.jetty.http.BadMessageException: 500: No version
at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:348)
at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:681)
at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:512)
at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:668)
at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:722)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
... 47 more

**Comment by gregw** [comment] 2016-06-18 23:11
Very strange to see that exception on the output side?    Can you tell us
the exact version you are using and we will inspect the code to see how it
could be possible that no HTTP version is set when writing a response?




-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com

**Comment by csliu** [comment] 2016-06-19 16:43
@gregw thanks, the presto we are using is 0.143, jetty version is jetty-server-9.3.8.RC0.

**Comment by gregw** [comment] 2016-06-20 07:11
On closer inspection, the problem appears to be an issue with jerseys
asynchronous error handling.  We have seen this kind of thing before from
Jersey/presto before where they call asynchronous APIs after a request has
been completed and recycled.

The thread they have spawned needs to be excluded from writing to the
response because something else has already completed the response and
request cycle.   We are actually working with the presto developers trying
to work out the exact sequence that is causing this and improve the error
handling.

regards


On 20 June 2016 at 02:43, Changshu Liu <notifications@github.com> wrote:

> @gregw <https://github.com/gregw> thanks, the presto we are using is
> 0.143, jetty version is jetty-server-9.3.8.RC0.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eclipse/jetty.project/issues/650#issuecomment-227007236>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEUrQsSuDamQGTIM87tZQQhVTOTgJ7Tks5qNXGxgaJpZM4I4_ap>
> .
>



-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com

**Comment by csliu** [comment] 2016-06-21 03:33
@gregw thanks a lot, do you have more context about how to fix it from Presto side? (like who is working on this) We have our internal presto repo, if it takes some time for Presto dev to fix it, we might fix it first in our internal branch. It currently affect many queries.

**Comment by gregw** [comment] 2016-06-21 23:56
@csliu stand by I'll see if I can organise an out-of-band introduction.

**Comment by gregw** [comment] 2016-06-22 05:49
I'm closing this as a likely duplicate of #624.    There is a fix for that on its way so please reopen if the fix does not also resolve this problem

**Closed by gregw** 2016-06-22 05:49 UTC

**Comment by csliu** [comment] 2016-06-27 07:23
@gregw thanks for the fix! BTW, I had connected with Presto team on who is working on the issue.
