### ISSUE TITLE
Closed Channel Exception in Jetty 9.4.8 due to null request method

### ISSUE THREAD

**Issue by SonaliDasgupta** [eclipse/jetty.project#3195] opened 2018-12-11 09:45 UTC
I have coded a Jetty server in Java,  using Jetty version 9.4.8.v20171121 (Java version : jdk1.8.0_161). 
I am sending POST and GET requests to the server in succession, using Apache HttpComponents Client (version 4.3) . On enabling debug logs for Jetty, I see the below error stack trace: 

java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:507) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:345) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:222) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:217) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:184) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:169) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:222) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:235) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1416) [jetty-http-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:356) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:239) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

On debugging the Jetty source code, I see that in class org.eclipse.jetty.server.HttpChannelOverHttp , the _metadata fields method is getting populated as POST for the POST request and as GET for GET request in method startRequest() for the two HTTP requests I make. However , after each request _metadata.recycle() is applied from method recycle(). After the end of the second request, I see a call to 
method earlyEof() in which the connection is closed. This results in a call to onClosed() method in class 
 org.eclipse.jetty.io.WriteFlusher , and then to onFail() method , which causes this stack trace to be logged. 

Is this expected and correct behavior, or should I modify my code to ensure this does not happen ?

**Comment by sbordet** [comment] 2018-12-15 16:58
It's expected behavior if the client closes the connection between 2 requests: Jetty will read the -1 from the client and close the connection.

**Comment by SonaliDasgupta** [comment] 2018-12-15 17:55
Thank you @sbordet. Just a query, is the server functionality or performance likely to be affected in any manner by this behavior ?

**Comment by sbordet** [comment] 2018-12-15 23:41
@SonaliDasgupta what behavior? This is the server closing a connection because the client closed it first.

**Closed** 2019-02-17 14:45 UTC
