### ISSUE TITLE
JDK8 Test failure: org.eclipse.jetty.http2.client.SessionFailureTest.testWriteFailure

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2227] opened 2018-02-22 22:49 UTC
`jetty-9.3.x` branch.
Linux build.

```
Stacktrace
java.lang.AssertionError
	at org.eclipse.jetty.http2.client.SessionFailureTest.testWriteFailure(SessionFailureTest.java:121)

Standard Error
Running org.eclipse.jetty.http2.client.SessionFailureTest.testWriteFailure()
2018-02-19 14:39:02.264:INFO:oejs.Server:main: jetty-9.3.23-SNAPSHOT, build timestamp: 2018-02-19T14:21:28Z, git hash: d41bcec681441b4123a16f6abb1f0356316cf736
2018-02-19 14:39:02.266:INFO:oejs.AbstractConnector:main: Started ServerConnector@362f4176{h2,[h2, h2-17, h2-16, h2-15, h2-14]}{0.0.0.0:35397}
2018-02-19 14:39:02.266:INFO:oejs.Server:main: Started @138980ms
2018-02-19 14:39:02.272:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@362f4176{h2,[h2, h2-17, h2-16, h2-15, h2-14]}{0.0.0.0:0}
```

**Comment by joakime** [comment] 2018-03-20 22:03
@sbordet do we care to (attempt to) fix this one?

**Comment by sbordet** [comment] 2018-03-21 10:20
@joakime cannot reproduce on 9.4.x, closing.

**Closed by sbordet** 2018-03-21 10:20 UTC
Labels: Test
