### ISSUE TITLE
Jetty store session on create even if saveOnCreate is set to false

### ISSUE THREAD

**Issue by lgangloff** [eclipse/jetty.project#1948] opened 2017-11-07 14:23 UTC
Hi,

using the config describes in #1947 , i have a strange behavior. I spent times reading session managment documentation (https://www.eclipse.org/jetty/documentation/9.4.x/sessions-details.html) and source code but maybe i'm wrong.
Here are the Jetty log if saveOnCreate is set to true:

```
2017-11-07 15:03:17.241:DBUG:oejs.session:qtp23358519-16: Creating new session id=s1idp14ixplbqkbdrr1v5y7no6bygu80
2017-11-07 15:03:17.244:DBUG:oejs.session:qtp23358519-16: Store: id=s1idp14ixplbqkbdrr1v5y7no6bygu80, dirty=true, lsave=0, period=7200000, elapsed=1510063397244
2017-11-07 15:03:17.248:DBUG:oejs.session:qtp23358519-16: Inserted session id=s1idp14ixplbqkbdrr1v5y7no6bygu80, contextpath=_idp, vhost=0.0.0.0, accessed=1510063397241, lastaccessed=1510063397241, created=1510063397241, cookieset=0, lastnode=s1idp, expiry=1510092197242, maxinactive=28800000
2017-11-07 15:03:17.248:DBUG:oejs.session:qtp23358519-16: Req count=1 for id=s1idp14ixplbqkbdrr1v5y7no6bygu80
2017-11-07 15:03:17.248:DBUG:oejs.session:qtp23358519-16: updateInactivityTimer
2017-11-07 15:03:17.249:DBUG:oejs.session:qtp23358519-16: setIdleTimeout called: old=0 new=1800000
2017-11-07 15:03:17.249:DBUG:oejs.session:qtp23358519-16: Inactivity timer set to lesser of maxInactive=28800000 and inactivityEvict=1800
2017-11-07 15:03:17.294:DBUG:oejs.session:qtp23358519-16: FinalSession=org.eclipse.jetty.server.session.Session@6df008 old_session_manager=org.eclipse.jetty.server.session.SessionHandler16275054==dftMaxIdleSec=28800 this=org.eclipse.jetty.server.session.SessionHandler16275054==dftMaxIdleSec=28800
2017-11-07 15:03:17.304:DBUG:oejs.session:qtp23358519-16: FinalSession=org.eclipse.jetty.server.session.Session@6df008 old_session_manager=null this=org.eclipse.jetty.server.session.SessionHandler16275054==dftMaxIdleSec=28800
2017-11-07 15:03:17.304:DBUG:oejs.session:qtp23358519-16: Session passivating id=s1idp14ixplbqkbdrr1v5y7no6bygu80
2017-11-07 15:03:17.304:DBUG:oejs.session:qtp23358519-16: Store: id=s1idp14ixplbqkbdrr1v5y7no6bygu80, dirty=true, lsave=1510063397244, period=7200000, elapsed=60
2017-11-07 15:03:17.309:DBUG:oejs.session:qtp23358519-16: Updated session id=s1idp14ixplbqkbdrr1v5y7no6bygu80, contextpath=_idp, vhost=0.0.0.0, accessed=1510063397241, lastaccessed=1510063397241, created=1510063397241, cookieset=0, lastnode=s1idp, expiry=1510092197242, maxinactive=28800000
```

The session is store just after created it and inserted by JDBCSessionDataStore. That works fine.
But if i set saveOnCreate to false, here are the log:

```
2017-11-07 14:59:46.024:DBUG:oejs.session:qtp23358519-16: Creating new session id=s1idp16hzzx61mzp9a95mhfo1jrrxg0
2017-11-07 14:59:46.024:DBUG:oejs.session:qtp23358519-16: Req count=1 for id=s1idp16hzzx61mzp9a95mhfo1jrrxg0
2017-11-07 14:59:46.024:DBUG:oejs.session:qtp23358519-16: updateInactivityTimer
2017-11-07 14:59:46.025:DBUG:oejs.session:qtp23358519-16: setIdleTimeout called: old=0 new=1800000
2017-11-07 14:59:46.025:DBUG:oejs.session:qtp23358519-16: Inactivity timer set to lesser of maxInactive=28800000 and inactivityEvict=1800
2017-11-07 14:59:46.073:DBUG:oejs.session:qtp23358519-16: FinalSession=org.eclipse.jetty.server.session.Session@1ba0c88 old_session_manager=org.eclipse.jetty.server.session.SessionHandler27462313==dftMaxIdleSec=28800 this=org.eclipse.jetty.server.session.SessionHandler27462313==dftMaxIdleSec=28800
2017-11-07 14:59:46.080:DBUG:oejs.session:qtp23358519-16: FinalSession=org.eclipse.jetty.server.session.Session@1ba0c88 old_session_manager=null this=org.eclipse.jetty.server.session.SessionHandler27462313==dftMaxIdleSec=28800
2017-11-07 14:59:46.080:DBUG:oejs.session:qtp23358519-16: Session passivating id=s1idp16hzzx61mzp9a95mhfo1jrrxg0
2017-11-07 14:59:46.080:DBUG:oejs.session:qtp23358519-16: Store: id=s1idp16hzzx61mzp9a95mhfo1jrrxg0, dirty=true, lsave=0, period=7200000, elapsed=1510063186080
2017-11-07 14:59:46.103:DBUG:oejs.session:qtp23358519-16: Inserted session id=s1idp16hzzx61mzp9a95mhfo1jrrxg0, contextpath=_idp, vhost=0.0.0.0, accessed=1510063186022, lastaccessed=1510063186022, created=1510063186022, cookieset=0, lastnode=s1idp, expiry=1510091986024, maxinactive=28800000
```

The session is not store after created it. Fine. But, it's inserted a few millisecond later by the session passivation.
Sorry, i don't completly understand the passivation mecanism, but it seems that the session is store even if we set saveOnCreate to false.
Note that the savePeriodSec is set to 7200.

Regards,

**Comment by janbartel** [comment] 2017-11-07 21:52
@lgangloff  if the session has never been saved when the last concurrent request exists the context, it will be saved at that point. You see the log line "FinalSession=" is indicative of a request exiting a context.

The saveOnCreate setting only controls whether the session is eagerly saved as soon as it is created. If it is false, and the session still exists by the time the last request that is referencing it leaves the context, it will be saved.  If the session has never been saved before, the savePeriodSec does not come into play - that only affects sessions that have been previously saved.

**Comment by lgangloff** [comment] 2017-11-08 13:38
Thanks,
So there is no way to store the session only after that the savePeriodSec is reached ?

**Comment by janbartel** [comment] 2017-11-13 08:23
@lgangloff when the last request that is referencing a session exits, that session will be persisted if you have configured a sessiondatastore that supports persistence.  This needs to be the case when you consider clustered deployments where requests may not be sticky, and thus the next request that refers to a session could potentially land on any node.  It's also needed if somebody plugs in a null sessioncache (the session wouldn't exist when the last request exited), or plugs in a sessioncache that evicts the session when the last request exits.

**Comment by janbartel** [comment] 2017-11-14 09:00
Closing as not a bug, working as designed.

**Closed by janbartel** 2017-11-14 09:00 UTC
