### ISSUE TITLE
Trailers preventing client from processing all the data 

### ISSUE THREAD

**Issue by imario42** [eclipse/jetty.project#2616] opened 2018-06-02 18:38 UTC
The problem I have is when I try to send "trailer" data from the (dropwizard) server to the client.
In this case, the application does not receive all of the data sent over the wire. In Wireshark I can see that the server sent all the data correctly. Anyway, the jetty-client stops processing any data it has already received from the server as soon as the trailer header arrives.
It seems, that the responseSuccess() call terminates further processing of already received data - and purges it.

When I fake an empty DataFrame (instead of calling responseSuccess) to end the stream it seems everthing is working fine.
https://github.com/eclipse/jetty.project/pull/2615/commits/f2fdd6c72087d266b734d7b9ed7ded9c90d09548

I am using the org.eclipse.jetty.client.util.InputStreamResponseListener and I am able to grab the trailer fields from within the onContent() method then.

I've hacked together a simple project which unveils this problem.
You can check it out from my github repository:  https://github.com/imario42/jettyHttp2TrailersTest

After (gradle) building the project (I've used Java 9) you simply execute
at.datenwort.jettyTrailerTest.server.ServerMain

Once the server started you can execute at.datenwort.jettyTrailerTest.client.ClientMain.

Both do DEBUG logging.

This sample provides a simple service (at.datenwort.jettyTrailerTest.server.SimpleService) which sends a long string starting with *START_MARKER* and ending with *END_MARKER*.

After three runs of ClientMain I got these three different results:

expected characters=800026 got characters=458213
start marker present=true
end marker present=false
serverTiming=total;dur=46

expected characters=800026 got characters=441870
start marker present=true
end marker present=false
serverTiming=total;dur=28

expected characters=800026 got characters=540066
start marker present=true
end marker present=false
serverTiming=total;dur=24

As soon as you remove the setTrailers() in at.datenwort.jettyTrailerTest.server.TrailersFilter you get:

expected characters =800026 got characters =800026
start marker present =true
end marker present =true
serverTiming=null

No trailer (obviously), but the entity has been processed correctly.

**Comment by sbordet** [comment] 2018-06-04 21:33
It is indeed a bug.

The problem is that in `HttpReceiverOverHTTP2.onHeaders()`, when receiving the trailers, we wrongly assume that the content has already been completely processed, and we call `onResponseSuccess()`, and this may happen _before_ all the calls to `onResponseContent()` have been made.
This of course trims the content at random places (like you observe) because there is a race between the application reading from the `InputStreamResponseListener` input stream and Jetty parsing incoming HTTP/2 frames.

**Comment by sbordet** [comment] 2018-06-05 14:12
@imario42 I pushed a fix for this issue, are you able to verify that the fix works for you?

**Closed** 2018-06-05 16:55 UTC
Labels: Bug

**Comment by imario42** [comment] 2018-06-05 18:16
I have checked it and it works now.
Thank you!
