### ISSUE TITLE
DefaultServlet wrong welcome dispatcher using non-root URL path

### ISSUE THREAD

**Issue by jmullo** [eclipse/jetty.project#1737] opened 2017-08-15 14:30 UTC
In 9.4.4 this works, serving index.html:  **https://127.0.0.1:8443/login/**

In 9.4.5 it doesn't work anymore.
But adding index.html to the URL it still works: **https://127.0.0.1:8443/login/index.html**

Most likely related to this: #1486 

I'm serving DefaultServlet with Guice:

`
serve(/login/*).with(DefaultServlet.class, initParams);
`

**Comment by joakime** [comment] 2017-08-15 14:33
What is your `resourceBase` for the alternate DefaultServlet?
Did you specify a value for `pathInfoOnly` setting on this alternate DefaultServlet?

**Comment by jmullo** [comment] 2017-08-15 14:48
`resourceBase` is the directory directly containing my index.html
`pathInfoOnly` is true, but setting it to false or omitting completely won't help.

**Comment by joakime** [comment] 2017-08-15 17:22
is your `resourceBase` a symlink / hardlink / network mount or something odd or unusual from a filesystem point of view?

**Comment by jmullo** [comment] 2017-08-15 17:45
Nope.

**Comment by joakime** [comment] 2017-08-15 21:05
I have a reproduction case of this bug at https://github.com/jetty-project/embedded-jetty-cookbook

Run the `DefaultServletMultipleBases` example and hit ...

http://localhost:8080/alt/

It should return the contents of `<project>/webapps/alt-root/index.htm` but doesn't.

**Comment by gregw** [comment] 2017-08-15 23:57
@jmullo thanks for the report.  Fix just missed the 9.4.7.RC0 release, but we should be able to squeak it into the final release in a week or two.

**Comment by joakime** [comment] 2017-08-16 13:39
Reopening due to test failures.

**Comment by joakime** [comment] 2017-08-16 18:00
Fix confirmed by CI. closing.

**Closed by joakime** 2017-08-16 18:00 UTC
Labels: Bug

**Comment by jmullo** [comment] 2017-08-16 18:01
Thanks.
