### ISSUE TITLE
External javadoc that refers to Jetty classes cannot link to there javadoc due to missing package-list file

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#4468] opened 2020-01-09 11:02 UTC
**Jetty version**

9.4.24.v20191120

**Java version**

8

**OS type/version**

All

**Description**

Jetty 9.4.24's javadoc appears to be generated using Java 11. Java 11 does not generate a `package-list` file which is required for Java 8's Javadoc tool to be able to create links correctly. This results in a warning during javadoc generation:

```
javadoc: warning - Error fetching URL: https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/
```

The failure to fetch the URL (it's actually looking for `https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/package-list`) results in any references to Jetty types not being links.

Gradle had a similar problem and worked around it by [copying `element-list` to `package-list`](https://github.com/gradle/gradle/pull/8193). Perhaps a similar change would be appropriate here as well?

**Comment by joakime** [comment] 2020-01-09 13:11
A release of Jetty has to build specific artifacts for Java 9+ (re: ALPN)
That means our release process is using Java 11 to build Jetty, including the javadoc, unfortunately.

@WalkerWatch can we fix the process for updating eclipse.org/jetty/ webpage to include this nugget of information?  (Only for Jetty 9.x, this is an irrelevant change for Jetty 10.x or Jetty 11.x)

So this file : https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/element-list
Needs to be copied to the old name as well : https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/package-list

I don't want to make this change in the generated javadoc artifacts, as that's kinda irrelevant.
But updating the public webpage, sure, that's a valid change.

**Comment by olamy** [comment] 2020-01-09 18:34
sounds something to be fixed in maven-javadoc-plugin?

**Comment by joakime** [comment] 2020-01-09 18:38
Its only relevant if you are publishing a public website.
the javadoc artifacts are sane still, as they are only relevant in isolation.

The problem is only the public websites that are generated with javadoc 11+, but need to retain compatibility with other projects that are compiled for java 8.

**Comment by joakime** [comment] 2020-01-09 19:08
Looks like https://www.eclipse.org/jetty/javadoc/9.4.25.v20191220/package-list is in place now.

**Comment by WalkerWatch** [comment] 2020-01-09 19:26
I did it for 9.4.24 as well and will do so for future 9.4 releases as they come up.

**Closed as completed by WalkerWatch** 2020-01-09 19:26 UTC
Labels: Documentation

**Comment by wilkinsona** [comment] 2020-01-09 19:51
Thanks.
