### ISSUE TITLE
Unable to get log4j2 running in Jetty 11.0.9

### ISSUE THREAD

**Issue by ghost** [eclipse/jetty.project#7948] opened 2022-05-02 22:49 UTC
**Jetty version(s)**
11.0.9

**Java version/vendor** `(use: java -version)`
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

**OS type/version**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**Description**
Hello,

I've spent the last 2 days trying to get log4j2 working with Jetty11.0.0, and Java 17, and have mostly been spinning my wheels.

I extracted the 11.0.9 zip file, and ran the start.jar --add-module=logging-log4j2, http, servlets, server command to get the modules i need.This adds some log4j2 libraries to the logging/lib folder, and adds a default log4j2.xml file to resources.

Out of the box without my war file even being installed, there's a NoClassDefFound error on startup for org.slf4j.LoggerFactory.  When the logging-log4j2 module is installed you don't pull down any slf4j-impl libraries.  If i manually pulled down the latest slf4j-imp 1.8.x and put it in the lib/logging folder the exception goes away.  The slf4j 2.0.0 alpha6 release you're using has a breaking backwards compatibility change which throws an exception, but otherwise seems to function.

The next issue is, even with the default log4j2.xml installed with the Root logger at info, hardly anything logs to the command line when i run: sudo service jetty supervise.  No matter what i do I can't get anything other than a couple of jetty lines (saying the server started and that it's listening on port 8080) to log, and my log statements to log.  nothing from other org. or com. packages ever log.  Even if i turn the root logger down to debug, nothing changes.  

The next issue is, i tried to use the console-capture module to route logging to the standard jetty log file format in the logs folder.  (Note this works fine with log4j 1.x).  But when i use the log4j2 module, the only thing that goes to the log file is my logs.  I get no jetty logging at all.

So, i guess my question is, how much of this is expected to work, vs is work in progress?  I've seen from other issue tickets in here that you guys are for some reason using an alpha version of slf4j 2.0.0, and you're waiting for apache logging to make a change to support the 2.0 version.  Not sure how much any of that is related to my issue.  All i know is log4j2 does not work out of the box, as per the jetty 11 operations guide manual.

Anything you can do to help me figure this out would be appreciated.

**How to reproduce?**

**Comment by joakime** [comment] 2022-05-03 18:18
Need to investigate this.

We have unit tests for log4j2 that pass now.

https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/LoggingOptionsTests.java

I have not verified this issue (yet).

**Comment by olamy** [comment] 2022-05-03 20:43
Agree as it's used as well without problem when running the TCK suite.

**Comment by joakime** [comment] 2022-05-03 20:58
I've been able to somewhat confirm this issue.

```
[bases]$ mkdir demo11-log4j2
[bases]$ cd demo11-log4j2/
[demo11-log4j2]$ java -jar ~/code/jetty/distros/jetty-home-11.0.9/start.jar --add-modules=http,deploy,logging-log4j2

ALERT: There are enabled module(s) with licenses.
The following 1 module(s):
 + contains software not provided by the Eclipse Foundation!
 + contains software not covered by the Eclipse Public License!
 + has not been audited for compliance with its license

 Module: logging-log4j2
  + Log4j is released under the Apache 2.0 license.
  + http://www.apache.org/licenses/LICENSE-2.0.html

Proceed (y/N)? y
INFO  : mkdir ${jetty.base}/start.d
INFO  : webapp          transitively enabled, ini template available with --add-module=webapp
INFO  : server          transitively enabled, ini template available with --add-module=server
INFO  : security        transitively enabled
INFO  : servlet         transitively enabled
INFO  : logging-log4j2  initialized in ${jetty.base}/start.d/logging-log4j2.ini
INFO  : http            initialized in ${jetty.base}/start.d/http.ini
INFO  : resources       transitively enabled
INFO  : threadpool      transitively enabled, ini template available with --add-module=threadpool
INFO  : logging/slf4j   transitive provider of logging/slf4j for logging-log4j2
INFO  : logging/slf4j   transitive provider of logging/slf4j for logging-jetty
INFO  : logging/slf4j   dynamic dependency of logging-jetty
INFO  : bytebufferpool  transitively enabled, ini template available with --add-module=bytebufferpool
INFO  : deploy          initialized in ${jetty.base}/start.d/deploy.ini
INFO  : mkdir ${jetty.base}/resources
INFO  : copy ${jetty.home}/modules/logging/log4j2/resources/log4j2.xml to ${jetty.base}/resources/log4j2.xml
INFO  : mkdir ${jetty.base}/lib/logging
INFO  : copy /home/joakim/.m2/repository/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.2/log4j-slf4j18-impl-2.17.2.jar to ${jetty.base}/lib/logging/log4j-slf4j18-impl-2.17.2.jar
INFO  : copy /home/joakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar to ${jetty.base}/lib/logging/log4j-api-2.17.2.jar
INFO  : copy /home/joakim/.m2/repository/org/apache/logging/log4j/log4j-core/2.17.2/log4j-core-2.17.2.jar to ${jetty.base}/lib/logging/log4j-core-2.17.2.jar
INFO  : mkdir ${jetty.base}/webapps
INFO  : Base directory was modified

[demo11-log4j2]$ java -jar ~/code/jetty/distros/jetty-home-11.0.9/start.jar
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
	at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:297)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382)
	at org.eclipse.jetty.xml.XmlConfiguration.<clinit>(XmlConfiguration.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:228)
	at org.eclipse.jetty.start.Main.start(Main.java:517)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
15:55:50.706 [INFO] :main: (org.eclipse.jetty.server.Server) - jetty-11.0.9; built: 2022-03-30T17:44:47.085Z; git: 243a48a658a183130a8c8de353178d154ca04f04; jvm 11.0.15+10
15:55:50.737 [INFO] :main: (org.eclipse.jetty.deploy.providers.ScanningAppProvider) - Deployment monitor [file:///home/joakim/code/jetty/distros/bases/demo11-log4j2/webapps/]
15:55:50.760 [INFO] :main: (org.eclipse.jetty.server.AbstractConnector) - Started ServerConnector@6096907d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
15:55:50.764 [INFO] :main: (org.eclipse.jetty.server.Server) - Started Server@297ea53a{STARTING}[11.0.9,sto=5000] @1109ms
^C15:55:57.563 [INFO] :JettyShutdownThread: (org.eclipse.jetty.server.Server) - Stopped Server@297ea53a{STOPPING}[11.0.9,sto=5000]
15:55:57.564 [INFO] :JettyShutdownThread: (org.eclipse.jetty.server.Server) - Shutdown Server@297ea53a{STOPPING}[11.0.9,sto=5000]
15:55:57.577 [INFO] :JettyShutdownThread: (org.eclipse.jetty.server.AbstractConnector) - Stopped ServerConnector@6096907d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
```

This is a warning and doesn't impact the use of log4j2 on Jetty 11.0.9

This is not a bug in Jetty, but rather a bug in log4j2

See https://issues.apache.org/jira/browse/LOG4J2-3139

**Comment by olamy** [comment] 2022-05-04 00:18
@joakime good finding. 
@jmihalichuber can you give us some details on what is not working? thanks

**Comment by ghost** [comment] 2022-05-04 04:21
Yes, I am aware of that issue with log4j2 and slf4j.  That's what I was referring to in my original post about slf4j's breaking non backward compatible change.  

I am unable to get as far as you did.  

I'm trying to reproduce this again.  i will post back with what i wind up with.

**Comment by ghost** [comment] 2022-05-04 05:25
OK, seriously, i cannot reproduce this now, and i have no idea why.  I was getting this consistently for 2 days.  I just unzipped a fresh jetty 11.0.9 and added the modules and now i don't get the exception anymore.

So, while i seek therapy for this, let me have you answer my other issue i mentioned, which i still have, from my original post:

>The next issue is, i tried to use the console-capture module to route logging to the standard jetty log file format in the logs folder. (Note this works fine with log4j 1.x). But when i use the log4j2 module, the only thing that goes to the log file is my logs. I get no jetty logging at all.

How can i get the jetty start/shutdown logs like these (from your post above) to go into the log file in the logs dir?

15:55:50.706 [INFO] :main: (org.eclipse.jetty.server.Server) - jetty-11.0.9; built: 2022-03-30T17:44:47.085Z; git: 243a48a658a183130a8c8de353178d154ca04f04; jvm 11.0.15+10
15:55:50.737 [INFO] :main: (org.eclipse.jetty.deploy.providers.ScanningAppProvider) - Deployment monitor [file:///home/joakim/code/jetty/distros/bases/demo11-log4j2/webapps/]
15:55:50.760 [INFO] :main: (org.eclipse.jetty.server.AbstractConnector) - Started ServerConnector@6096907d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
15:55:50.764 [INFO] :main: (org.eclipse.jetty.server.Server) - Started Server@297ea53a{STARTING}[11.0.9,sto=5000] @1109ms
^C15:55:57.563 [INFO] :JettyShutdownThread: (org.eclipse.jetty.server.Server) - Stopped Server@297ea53a{STOPPING}[11.0.9,sto=5000]
15:55:57.564 [INFO] :JettyShutdownThread: (org.eclipse.jetty.server.Server) - Shutdown Server@297ea53a{STOPPING}[11.0.9,sto=5000]
15:55:57.577 [INFO] :JettyShutdownThread: (org.eclipse.jetty.server.AbstractConnector) - Stopped ServerConnector@6096907d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}

I found this other github issue during my 2 day adventure.  Is the last message in this issue, the same problem as mine?  Meaning that this won't work till apache updates the log4j2 stuff to slf4j 2.0?  I not sure why redirecting stdout/stderr to the logfile in logs directory would have anything to do with that.

https://github.com/eclipse/jetty.project/issues/7268


Thanks,
Joe

**Comment by ghost** [comment] 2022-05-04 06:57
I guess I'm answering my own questions tonight.  I removed the console-capture module, and replaced it with a rolling file appender in the log4j2.xml file, and now everything is going to my one log file.  So this works for me.

**Comment by olamy** [comment] 2022-05-04 07:02
you can use something such `java -jar start.jar` as well to test your configuration.

**Comment by olamy** [comment] 2022-05-04 07:03
@jmihalichuber I'm closing it now. feel free to reopen if you have more questions.

**Closed as completed by olamy** 2022-05-04 07:03 UTC
Labels: Bug
