### ISSUE TITLE
Session locking not working properly

### ISSUE THREAD

**Issue by blop** [eclipse/jetty.project#2907] opened 2018-09-14 13:09 UTC
Hello 🙃

I have a case where a session fails to be invalidated, because another thread is using the session at the same time and restoring it with the previous VALID state in the SessionDataStore.

It seems AbstractSessionCache.put() is checking if the session is still valid before storing it, but the call to !session.isValid() (line 507) fails to prevent it.

isValid() depends on the _state and _lock.
But the _lock is local to the object and fail to work properly when using the HazelcastSessionDataStore.

Even in a single node configuration, multiple threads have another copy of the Session(Data)/Lock objects and lock is not working properly.

Also, this will never work in a multiple node configuration.
It should rely on a distributed lock (like com.hazelcast.core.ILock for hazelcast) to ensure there isn't any concurrent access of the same session across multiple threads on multiple machines.

I'm testing with Jetty 9.4.12.v20180830, NullSessionCacheFactory and HazelcastSessionDataStoreFactory.

**Comment by janbartel** [comment] 2018-09-15 01:13
In a multiple node configuration you really need to be using a sticky load balancer. There are no atomic operations in the session api and thus weird and seemingly unexpected things can happen to sessions, including writes happening in any order and also invalid or expired sessions being resurrected. Using a sticky load balancer is the way to go with multiple nodes.

On a single node, the ideal situation is that you use the DefaultSessionCache, which guarantees that all requests using the same session id share the same session object and thus maintain coherency of the object state.  Using the NullSessionCache means that every request operates on an individual copy of the session - you can't guarantee the order of writes or invalidates so you never know at any given moment in what the state the object will be.  There are very few situations in which you should ever use the NullSessionCache, the documentation at  http://www.eclipse.org/jetty/documentation/9.4.12.v20180830/session-management.html touches on some of the issues.

**Comment by janbartel** [comment] 2018-10-02 23:58
I'm going to close this issue, as the session code is working as intended. Hopefully the guidance I've given will resolve your problem.

**Closed by janbartel** 2018-10-02 23:58 UTC
