### ISSUE TITLE
Response chunk's terminating CRLF not sent until next chunk is started

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#154] opened 2016-02-16 23:27 UTC
migrated from Bugzilla [#442479](https://bugs.eclipse.org/bugs/show_bug.cgi?id=442479)
status ASSIGNED severity _enhancement_ in component _server_ for _9.2.x_
Reported in version _9.2.2_ on platform _PC_
Assigned to: Project Inbox

Original attachment names and IDs:
- _[442479.diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=246401)_ (ID 246401)

On 2014-08-25 08:33:44 -0400, Ãyvind BakksjÃ¸ wrote:

> Consider a servlet sending the response in two chunks, with a delay between. The client will receive the following:
> 
> <chunk-size> CRLF
> <chunk-data>
> 
> (delay)
> 
> CRLF
> <chunk-size> CRLF
> <chunk-data>
> 
> Notice how the terminating CRLF of the first chunk is received _after_ the delay. Many clients may be able to deal with this, by acting on <chunk-data> when they've received the exact number of bytes indicated by <chunk-size>. But some clients are not, awaiting the terminating CRLF required by the HTTP spec section 3.6.1. The missing CRLF causes the clients to hang.
> 
> Consider the following code from org.eclipse.jetty.http.HttpGenerator:
> 
> ```
> private void prepareChunk(ByteBuffer chunk, int remaining)
> {
>     // if we need CRLF add this to header
>     if (_needCRLF)
>         BufferUtil.putCRLF(chunk);
> 
>     // Add the chunk size to the header
>     if (remaining>0)
>     {
>         BufferUtil.putHexInt(chunk, remaining);
>         BufferUtil.putCRLF(chunk);
>         _needCRLF=true;
>     }
>     else
>     {
>         chunk.put(LAST_CHUNK);
>         _needCRLF=false;
>     }
> }
> ```
> 
> This also means that the last chunk is not getting its terminating CRLF at all.

On 2014-08-26 20:22:06 -0400, Greg Wilkins wrote:

> Note that the spec has now been updated and the corresponding section is now:
> http://tools.ietf.org/html/rfc7230#section-4.1.3
> 
> Note that there is no actual requirement in HTTP to stream content, and an intermediary (eg a caching proxy) is entitled to accept all the chunks and send them as a whole body.
> 
> Thus any client that is relying on streamed chunks is going to be fragile.
> 
> Having said that, we are always open to interesting ways to abuse the protocol... so I'll have a look and see if we can easily change to eagerly send that CRLF without too much extra expense.
> 
> Could you explain your usage some more so that we understand why the timing is important for you?
> 
> [Note that we explicitly send the last chunk as 0CRLFCRLF, so it correctly gets all the CRLFs required]

On 2014-08-26 21:28:32 -0400, Greg Wilkins wrote:

> Created attachment 246401
> potential fix
> 
> Ãyvind,
> 
> here is a potential fix.   If the generator is driven until a DONE result, then it will reuse the chunk buffer to proactively send the trailing CRLF.
> 
> However, it is only enabled if you run in STRICT mode:
> 
> ```
> public final static boolean __STRICT=Boolean.getBoolean("org.eclipse.jetty.http.HttpGenerator.STRICT"); 
> ```
> 
> because there is a cost of requiring another write after each chunk is written.
> 
> I've given this a little bit of testing, but not enough to commit to the build. 
> 
> If you could build from source with this patch applied and confirm/deny if it helps with your use case, that would be helpful.

On 2014-08-27 08:17:32 -0400, Ãyvind BakksjÃ¸ wrote:

> Thank you for your response.
> 
> I agree that a client should technically _work_ even if the chunk-terminating CRLF arrives late, but it might increase application latency in practice. When the chunk is basically received, it's a pity if the client does not act on it because it is awaiting the final CRLF. Even though Jetty is not technically violating the protocol by delaying it, the terminating CRLF _is_ part of the grammar for a chunk, which means a client might need it to consider a chunk complete and thus act on it. So by deliberately delaying the CRLF, Jetty is consciously causing a risk of increased application latency, IMO.
> 
> I tried applying your patch (to 9.2.2.v20140723), but unfortunately it does not seem to do the right thing. This the server response I get with the fix:
> 
> <chunk-size> CRLF
> <chunk-data> 0 CRLF CRLF
> 
> which obviously is not correct.
> 
> (PS: Sorry about my red-herring claim that the final zero-length chunk does not get CRLF terminators - you are right, it does. I didn't read the code well enough/made assumptions.)

**Comment by joakime** [comment] 2016-03-22 14:54
@gregw can we consider this fixed/works as intended?

**Comment by gregw** [comment] 2016-03-24 00:21
Well this might be way toooo late for the OP, but I think we should look at this to see if we can pro actively send the CRLF, at least in the majority case.   So leave open and assigned to me.

**Comment by psundar-bill** [comment] 2017-09-26 19:36
I am using http streaming and curl 7.43.0 is my client. I have a similar problem where the CRLF of the earlier chunk is sent with the next chunk. 
But locally it works good. But over the network, the curl as well as the browsers hang. Only when the server is killed, then only the curl as well as the browser display the obtained chunks. Can you please let me know if there is a workaround.

**Comment by joakime** [comment] 2018-03-13 20:23
Closing.

**Closed by joakime** 2018-03-13 20:23 UTC
Labels: Enhancement, Has Patch, Help Wanted
