### ISSUE TITLE
jetty-maven-plugin: jetty:start java.lang.NoClassDefFoundError: org/eclipse/jetty/io/ManagedSelector$CloseEndPoints

### ISSUE THREAD

**Issue by pauldaustin** [eclipse/jetty.project#1409] opened 2017-03-18 14:11 UTC
The following config

```xml
      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>9.4.2.v20170220</version>
        <dependencies>
          <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
            <version>9.4.2.v20170220</version>
          </dependency>
        </dependencies>
        <configuration>
          <skip>${jettySkip}</skip>
          <reload>manual</reload>
          <httpConnector>
            <port>${httpPort}</port>
          </httpConnector>
          <daemon>true</daemon>
          <stopPort>${stopPort}</stopPort>
          <stopKey>${stopKey}</stopKey>
          <stopWait>10</stopWait>
         </configuration>
      </plugin>
```

when running

`mvn jetty:start`

causes the following error

```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/eclipse/jetty/io/ManagedSelector$CloseEndPoints
	at org.eclipse.jetty.io.ManagedSelector.doStop(ManagedSelector.java:135)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.io.SelectorManager.doStop(SelectorManager.java:257)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.client.AbstractHttpClientTransport.doStop(AbstractHttpClientTransport.java:87)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:254)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.websocket.client.WebSocketClient.doStop(WebSocketClient.java:376)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.websocket.jsr356.ClientContainer.doStop(ClientContainer.java:214)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:138)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.io.ManagedSelector$CloseEndPoints
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 23 more

```

`mvn jetty:run` works fine

**Comment by sn42** [comment] 2017-03-21 16:46
Confirmed. Can be replicated with the following barebone project:

[issue1409.tar.gz](https://github.com/eclipse/jetty.project/files/858903/issue1409.tar.gz)

Note: Got the same behaviour with other 9.4.* versions. With  version 9.3.16.v20170120 i got:
```
Exception in thread "Thread-1" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/eclipse/jetty/http/pathmap/MappedResource
	at org.eclipse.jetty.websocket.server.NativeWebSocketConfiguration.doStop(NativeWebSocketConfiguration.java:65)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.websocket.jsr356.ClientContainer.doStop(ClientContainer.java:205)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:138)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/http/pathmap/MappedResource
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.http.pathmap.MappedResource
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 7 more
```
This looks similar to #1356.

**Comment by pauldaustin** [comment] 2017-03-21 19:36
One extra note. I have a multi module maven project. With two wars as modules. The parent project doesn't include a war.

**Comment by joakime** [comment] 2017-03-21 20:40
This is a duplicate of #1356 (on jetty stop/shutdown the maven process yanks the classloader out from underneath the jetty threads leaving random errors in its wake)

**Closed by joakime** 2017-03-21 20:40 UTC
Labels: Duplicate

**Comment by janbartel** [comment] 2017-03-21 22:10
@pauldaustin @sn42  the "start" goal is specifically designed for binding to a lifecycle phase in the pom, it is not designed to be run at the command line. Here's a link to the doco: https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html#jetty-start-goal
