### ISSUE TITLE
Spring4.1 with customer annotation will raise exception

### ISSUE THREAD

**Issue by damonchen** [eclipse/jetty.project#816] opened 2016-08-05 06:52 UTC
Define a customer annotation and then annotation to a method. When running in the Jetty 9.2.17.v20160517, it will raise an exception as the blow message:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: WRITER
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.__doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: WRITER
	at org.eclipse.jetty.server.Response.getOutputStream(Response.java:896)
	at org.springframework.http.server.ServletServerHttpResponse.getBody(ServletServerHttpResponse.java:84)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:109)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:40)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:161)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:101)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:185)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:71)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	... 29 more

the same code will run success in Tomcat 8.5.4.

**Comment by janbartel** [comment] 2016-08-05 07:04
This exception is caused by response.getWriter() having previously been called, which is illegal according to the servlet specification. So something in the filter/servlet processing chain has called reponse.getWriter() before the spring framework servlet has called reponse.getOutputStream(). Looks like some dispatching is being done in the handling hierarchy - can you trace through and see where the call to getOutputStream() is happening?

We've also seen problems with incorrectly written response wrappers causing this type of exception, so also check to see if the response is being wrapped, and if the wrapper correctly implements the servlet api methods for getOutputStream(), getWriter(), and flush().

We've also recently come across an incorrectly written response wrapper (from Dandelion project) that threw an exception on jetty but appeared to work on tomcat, which was purely by chance. So have a read of #759 as that may also give you some pointers.

**Comment by damonchen** [comment] 2016-08-05 07:51
will call the ServletServerHttpResponse in springframe as below method:
```
	@Override
	public OutputStream getBody() throws IOException {
		writeHeaders();
		return this.servletResponse.getOutputStream();
	}
```

the below message is the call stack information:

org.springframework.http.server.ServletServerHttpResponse.getBody(ServletServerHttpResponse.java:83)
	  at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:109)
	  at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:40)
	  at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)
	  at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:161)
	  at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:101)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:185)
	  at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:71)
	  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)

**Comment by janbartel** [comment] 2016-08-05 08:43
oops, sorry I meant can you trace the call to response.getWriter()?

Also, what is the exact version of springframework, so I can match up the line numbers in the stacktrace?

**Comment by damonchen** [comment] 2016-08-05 08:51
springframework version is 4.1.7.RELEASE.

I try to trace the response.getWriter().

**Comment by damonchen** [comment] 2016-08-05 10:42
I have found that the getWriter method is called by my written code, so the problem is Jetty using the getOutputStream while tomcat use getWriter

**Comment by janbartel** [comment] 2016-08-05 11:28
So according to the stack trace you provided it is the spring framework that is calling response.getOutputStream(), apparently **after** you called response.getWriter(). According to the servlet spec it is a violation to call both. Not sure why tomcat isn't throwing an exception?

**Comment by joakime** [comment] 2016-08-05 22:24
The Servlet Spec rules regarding use of `getWriter()` and `getOutputStream()` are not bypassed or handled differently by Tomcat.

Tomcat applies the same servlet spec rules we do.

See:

 * http://stackoverflow.com/questions/21039471/spring-getoutputstream-has-already-been-called-for-this-response
 * http://stackoverflow.com/questions/30560360/i-am-getting-an-exception-java-lang-illegalstateexception-getoutputstream-ha
 * https://github.com/Atmosphere/atmosphere/issues/287
 * http://stackoverflow.com/questions/31992382/getoutputstream-has-already-been-called-for-this-response
 * http://stackoverflow.com/questions/12325382/spring-mvc-controller-code-getoutputstream-has-already-been-called-for-this-r

**Comment by damonchen** [comment] 2016-08-06 07:39
@joakime 

I found that the all above links of stackoverflow are using getOutputStream() to write the binary data to the client, and then render the jsp or other template. It is not the same of the problem I asked.

I use getWriter() to write the plain text, the code like this

```java
out = response.getWriter();
out.write(JSON.toJSONString(r));
```

then return true in springframework of HandlerInterceptorAdapter's method preHandle.

**Comment by damonchen** [comment] 2016-08-06 07:43
the simplified code is

```java
@Override
public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
	response.setHeader("Content-Type", "application/json; charset=utf-8");
	out = response.getWriter();
	out.write(JSON.toJSONString(r));
	out.flush();
	out.close();

	return super.preHandle(request, response, handler);
}
```

**Comment by janbartel** [comment] 2016-08-07 00:26
@damonchen 

Can you put a breakpoint everywhere where Response.getOutputStream() and Response.getWriter() is called? If you see Response.getWriter() called BEFORE Response.getOutputStream() then the call to Response.getOutputStream() is illegal according to the spec. 

It is my understanding of what you've said, and the stacktraces provided, that it is not jetty calling Response.getOutputStream(), but spring instead. However, if you put the breakpoints in, you will easily be able to see who is calling it.

You might also like to print out the class of the reponse object: that way you can check to see if it is a response wrapper, and if so, if it has correctly overridden the getWriter() and getOutputStream(), and flush() etc methods.

**Comment by janbartel** [comment] 2016-08-10 22:20
@damonchen ?

**Comment by damonchen** [comment] 2016-08-13 06:30
sorry, I use tomcat for current publish, and now have the time to debug the problem.

**Comment by damonchen** [comment] 2016-08-13 09:15
sorry, I lose the environment, and it does not throw the exception. I think it may some error in my code.

**Comment by damonchen** [comment] 2016-08-13 09:52
so sorry. I have no idea to reproduce the issue.

**Comment by janbartel** [comment] 2016-08-16 01:11
@damonchen  OK, I will close this issue for now. If you can repro, please reopen with full info.

**Closed by janbartel** 2016-08-16 01:11 UTC

**Comment by damonchen** [comment] 2016-08-16 07:43
My colleague have found the problem is that I does not return false in HandlerInterceptorAdapter.preHandle method when using getWriter method to write the message.
