### ISSUE TITLE
CompleteListener.onComplete() called multiple times unexpectedly

### ISSUE THREAD

**Issue by FrankTaylorLieder** [eclipse/jetty.project#967] opened 2016-09-28 18:25 UTC
When using the HTTP2 client to make an async request I get the completeListener callback twice for builds: jetty-9.3.12.v20160915 and jetty-9.4.0.M1

When using an earlier build (jetty-9.3.0.M2) I only get called once, which is what I would expect.

Here is the output for three runs of sample code below, one for each build mentioned:

19:06:58,739 INFO - Logging initialized @279ms
19:06:58,839 INFO - jetty-9.3.0.M2
19:06:58,900 INFO - Started o.e.j.s.ServletContextHandler@3b6eb2ec{/,null,AVAILABLE}
19:06:58,938 INFO - Started ServerConnector@856d295{h2-17,[h2-17, h2-16, h2-15, h2-14, h2]}{0.0.0.0:58529}
19:06:58,938 INFO - Started @483ms
Complete callback
Done

---

19:06:21,995 INFO - Logging initialized @349ms
19:06:22,196 INFO - jetty-9.3.12.v20160915
19:06:22,272 INFO - Started o.e.j.s.ServletContextHandler@482f8f11{/,null,AVAILABLE}
19:06:22,310 INFO - Started ServerConnector@29774679{h2,[h2, h2-17, h2-16, h2-15, h2-14]}{0.0.0.0:58521}
19:06:22,311 INFO - Started @668ms
Complete callback
Complete callback
Done

---

19:14:27,194 INFO - Logging initialized @361ms to org.eclipse.jetty.util.log.Slf4jLog
19:14:27,409 INFO - jetty-9.4.0.M1
19:14:27,409 WARN - THIS IS NOT A STABLE RELEASE! DO NOT USE IN PRODUCTION!
19:14:27,411 WARN - Download a stable release from http://download.eclipse.org/jetty/
19:14:27,491 WARN - No workerName configured for DefaultSessionIdManager, using node0
19:14:27,492 WARN - No SessionScavenger set, using defaults
19:14:27,511 INFO - Started o.e.j.s.ServletContextHandler@6093dd95{/,null,AVAILABLE}
19:14:27,547 INFO - Started ServerConnector@3fee9989{h2,[h2]}{0.0.0.0:58826}
19:14:27,547 INFO - Started @727ms
Complete callback
Complete callback
Done

---

-----------------------------
Sample code:

import java.io.IOException;
import java.util.function.BiConsumer;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.http2.client.HTTP2Client;
import org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2;
import org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory;
import org.eclipse.jetty.server.HttpConfiguration;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.eclipse.jetty.util.thread.QueuedThreadPool;

public class DoubleCallbackBug {

    static class WebServer {

        private final String path;
        private final ServerConnector connector;
        private final Server server;

        public static WebServerBuilder servlet(HttpServlet servlet) {
            return new WebServerBuilder(servlet, "/", 0);
        }

        public static WebServerBuilder handler(BiConsumer<HttpServletRequest, HttpServletResponse> handler) {

            HttpServlet servlet = new HttpServlet() {
                private static final long serialVersionUID = -7741340028518626628L;

                @Override
                protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
                    handler.accept(req, resp);
                }
            };

            return servlet(servlet);
        }

        public WebServer(String path, HttpServlet servlet, int port) {
            this.path = path;

            QueuedThreadPool serverExecutor = new QueuedThreadPool();
            serverExecutor.setName("server");

            server = new Server(serverExecutor);
            connector = new ServerConnector(server, 1, 1, new HTTP2ServerConnectionFactory(new HttpConfiguration()));
            connector.setPort(port);
            server.addConnector(connector);

            ServletContextHandler context = new ServletContextHandler(server, "/", true, false);
            context.addServlet(new ServletHolder(servlet), path);
        }

        void start() {
            try {
                server.start();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

        public void stop() {
            try {
                server.stop();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

        public int getLocalport() {
            return connector.getLocalPort();
        }

        public String getBasepath() {
            return "http://localhost:" + getLocalport() + path;
        }

        public static class WebServerBuilder {
            private final HttpServlet servlet;
            private final String path;
            private final int port;

            private WebServerBuilder(HttpServlet servlet, String path, int port) {
                this.servlet = servlet;
                this.path = path;
                this.port = port;
            }

            public WebServerBuilder path(String path) {
                return new WebServerBuilder(this.servlet, path, this.port);
            }

            public WebServerBuilder port(int port) {
                return new WebServerBuilder(this.servlet, this.path, port);
            }

            public WebServer start() {
                WebServer webServer = new WebServer(path, servlet, port);
                webServer.start();
                return webServer;
            }
        }
    }

    public static void main(String[] args) {
        try {
            WebServer server = WebServer.servlet(new HttpServlet() {
                protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
                    resp.getOutputStream().write("RESPONSE DATA".getBytes());
                }
            }).start();

            HTTP2Client lowLevelClient = new HTTP2Client();
            lowLevelClient.start();

            HttpClient client = new HttpClient(new HttpClientTransportOverHTTP2(lowLevelClient), null);
            client.start();

            String url = "http://localhost:" + server.getLocalport();
            client.newRequest(url).send(result -> {
                System.out.println("Complete callback");
            });

            // Allow the callbacks to happen before we finish.
            Thread.sleep(1000L);

            System.out.println("Done");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by sbordet** [comment] 2016-09-28 19:50
Duplicate of #959.

**Comment by sbordet** [comment] 2016-09-28 19:50
Thanks for reporting this !

**Closed by sbordet** 2016-09-28 19:50 UTC

**Comment by FrankTaylorLieder** [comment] 2016-09-28 21:19
Glad its fixed.

Thanks.
