### ISSUE TITLE
request.getParameterNames returns Enum with no elements intermittently on Jetty 9.4.14

### ISSUE THREAD

**Issue by suzith** [eclipse/jetty.project#3486] opened 2019-03-26 00:53 UTC
We recently upgraded from Jetty 9.3.14 to 9.4.14 and intermittently get enumeration with no elements when called request.getParameterNames(). The request contains parameters sent as post data.

I enabled Jetty debug logging but could not find any useful information.  Any help will be appreciated.

**Comment by janbartel** [comment] 2019-03-26 01:34
How are you calling request.getParameterNames()? Are you calling it in a filter or a servlet? Are you calling it in async mode? Are you calling it from a forward or include? Is the request a multipart post? etc etc etc ...

A small reproduction case would be great.

**Comment by gregw** [comment] 2019-03-26 01:34
Can you give us more information?  Can you capture the raw request with wireshark or tell us more about the body of the post data?
Perhaps attached the debug logging anyway, as it may contain something useful for us?
Do you have any other filters etc.
if getParameterNames returns null, can you still see any params can be seen with getParameter?

**Comment by suzith** [comment] 2019-03-26 03:34
The getParameterNames() is being called from an async servlet  through an executor thread(async mode). The request is neither forward nor include, its a normal request. The async servlet is a long poll request that is held on server for 30 sec to push messages from server to the client. 
The request that is failing is not multipart post. 
The issue is not just limited to async servlet, it might happen to any other request as well. All the resources(jsps/servlets) are behind a Servlet filter which performs session validation(reading cookies and a request parameter which could come as query string or post data). The problem is not about reading input stream in one filter where it is consumed and not available down the line in filter chain. I have confirmed that and also since this issue is intermittent and works other times.

In the attached log.txt, search for "Command missing from the Request from Client" string. This exception is logged when the a specific parameter is not received in the request.
[log.txt](https://github.com/eclipse/jetty.project/files/3006404/log.txt)

**Comment by gregw** [comment] 2019-03-26 04:48
Are you really sure it happens outside of async?   It would be good to see such and example.

If there is a problem, being async is a good suspect as to the problem.    Can I get you to modify your code so that immediately prior to calling `request.startAsync()`, you call `request.getParamaterMap()`, to ensure the parameters are read and setup before starting async handling.

**Comment by suzith** [comment] 2019-03-26 05:52
I have verified that earlier itself, I had added code to check if the enum returned by getParameterNames() has elements way before my first filter(session validation) intercepts the request. I could see that the getParameterNames() returned enum with no elements as well as getParameter had returned null for a specific command. Also, as I mentioned earlier, the getParameter() also returns null for random non-async requests.

I was referring to https://github.com/eclipse/jetty.project/issues/660, if I understood correctly, it talks about recycled request object getting used resulting into getParameter/getParameterNames calls not returning expected output.

FYI : The exact same application code worked well without any issues on Jetty 9.3.14.

I will try to get some working standalone that can reproduce this issue and share it with you.
Meanwhile are you aware of any known issues around async servlet usage that might result into such issues ? Also, how thread safe are asynch contexts, request/response objects derived from async context when used with thread executors ?

**Comment by joakime** [comment] 2019-03-26 13:49
@suzith if you use non-servlet / non-asynccontext threading then you'll have issues if you use the HttpServletRequest after it has been recycled.
Example of this would be @sbordet 's example https://github.com/eclipse/jetty.project/issues/660#issuecomment-228380226

The scope of the `HttpServletRequest` is outlined in the _Servlet Spec 3.1 - Section 3.12 (page 3-31)_ ...

> Each request object is valid only within the scope of a servlet’s `service` method, or
> within the scope of a filter’s `doFilter` method, unless the asynchronous processing
> is enabled for the component and the `startAsync` method is invoked on the request
> object. In the case where asynchronous processing occurs, the request object remains
> valid until `complete` is invoked on the `AsyncContext` . Containers commonly recycle
> request objects in order to avoid the performance overhead of request object
> creation. The developer must be aware that maintaining references to request objects
> for which `startAsync` has not been called outside the scope described above is not
> recommended as it may have indeterminate results.
> 
> In case of upgrade, the above is still true.

So, if you use an `AsyncContext` the `HttpServletRequest` is only valid until such time that the `AsyncContext` is completed.
You can setup an `AsyncListener` that will notify you of `onComplete` (or `onError`) to know if this is the cause of your issues.

Alternatively, if your parameters are being sent via POST body content only, and when you call `getParameterNames()` it returns an empty set, it could be that something else has read the body content already.
The `org.eclipse.jetty.server.Request` object has a variable called [`__inputState`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L203) which starts out as [`__NONE`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L141), indicating that nothing has attempted to access the request body content.
That variable can move to `__STREAM` or `__READER` indicating that something has attempted to access the request body content via `HttpServletRequest.getInputStream()` or `HttpServletRequest.getReader()`.

I would setup a breakpoint in [`Request.getParameters()`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L378) with a conditional of `_inputState != __NONE`.  If that breakpoint triggers, that means something has accessed the request body content BEFORE you attempted to use `.getParameters()`.

**Comment by gregw** [comment] 2019-09-10 23:59
closing as no more info received

**Closed by gregw** 2019-09-10 23:59 UTC
Labels: More Info Required
