### ISSUE TITLE
Jetty 9.4 not utilizing all the threads equally

### ISSUE THREAD

**Issue by pawaramol** [eclipse/jetty.project#2005] opened 2017-11-29 22:57 UTC
Hi all,

We are trying to upgrade our jetty server to 9.4.7.v20170914 however we noticed strange behaviour when our application using 9.4.7 vs 9.3.11.v20160721 (currently used by our application) vs 9.3.21.v20170918.

Some details about our application configurations:
- We are using Embedded Jetty server
- With min-threads=100, max-threads-250, keep-alive-10sec
- 4 acceptors, acceptor queue size 500 and default number of selectors 
- We tested application dev and prod servers. Dev number of CPUs 4 

What we noticed is we are seeing server is accepting/processing half the number of requests when running with 9.4 version vs both 9.3 versions. Please see attached graph (Green line is for 9.4 version).

We also got the thread dump for all 3 versions of our application, there is a notable difference between how Jetty 9.4 utilizing threads vs how both 9.3 versions utilizing threads. Note that all the configs were kept same, only jetty version is upgraded. While running in 9.4 we noticed that server only utilizes 50-60% of threads (those which are used running 80-90% of the time) and all other threads are waiting with 0ms processing time (never used). On the other hand both Jetty 9.3 versions utilize all the threads almost equally so they are running 30-40% of the time.
Also 9.4 version started with 72 threads even though min-thread setting is 100, though running application for 24 hours it started additional 28 threads.

I am not sure when running 9.4 version if above behaviour causing application to process only 50% of the load or there is something else. But we want to be able to at least process same number of requests as 9.3 version. I am also attaching thread dumps (stripped off unrelated info) for all 3 versions.

Please let me know if you need more information, really appreciate your help.
  

<img width="607" alt="number of requests processed per second" src="https://user-images.githubusercontent.com/19481864/33403339-d97d5620-d514-11e7-8a4a-f14d65e4895a.png">

[9.4.7 Thread dump.txt](https://github.com/eclipse/jetty.project/files/1515843/9.4.7.Thread.dump.txt)
[9.3.21 Thread dump.txt](https://github.com/eclipse/jetty.project/files/1515846/9.3.21.Thread.dump.txt)
[9.3.11 Thread dump.txt](https://github.com/eclipse/jetty.project/files/1515848/9.3.11.Thread.dump.txt)

**Comment by gregw** [comment] 2017-11-29 23:26
9.4.7 had some poor heuristics for some internal configuration. 9.4.8 has
just been released so give that a try before we look closer.

**Comment by pawaramol** [comment] 2017-11-29 23:28
Thanks for the reply @gregw, will run another test with 9.4.8

**Comment by pawaramol** [comment] 2017-11-30 01:01
@gregw I am not seeing much difference with 9.4.8 except it started all 100 threads vs 9.4.7 started only 72 even min-thread set to 100. Otherwise there are bunch of threads still waiting and have not been utilized.
Please see attached 9.4.8 thread dump.

[9.4.8 Thread dump.txt](https://github.com/eclipse/jetty.project/files/1516144/9.4.8.Thread.dump.txt)

**Comment by sbordet** [comment] 2017-11-30 09:25
@pawaramol the thread dumps show a completely idle server.
Also, it's not clear what the graph is showing. What are X and Y axis ?
How do you know that it's not the client sending half the load ?
Can you share your code so that we can reproduce the test ?

**Comment by pawaramol** [comment] 2017-11-30 19:45
@sbordet Server has some traffic if not overloaded, as you can see some threads are in runnable state. I think thread dump is not a good way to describe this problem because it tells at that point of time which threads are running and which are waiting. I am attaching screen shot from visualvm for 9.4.8 server vs 9.3.11 server. You can see in 9.4.8 most of the threads are not utilized (running for 0ms) and those which are active are running for 90+% for the time vs 9.3.11 almost all threads are running for equal amount of time.

About previously attached graph X axis is timelime for 2 hrs and Y axis is number of requests per second. We know client is sending a proper load as our other server running jetty 9.3.11 (Yellow line) receiving more traffic. Our load balance checks the load/response time on on server to determine which server will receive how much, This is a graph from last month but I know both server load/response time was similar.

I will share snippet of code handling request shortly.

<img width="1077" alt="9 4 8-thread usage snapshot" src="https://user-images.githubusercontent.com/19481864/33451425-e0cd5c72-d5c3-11e7-9438-c7324396acaf.png">

<img width="1182" alt="9 3 11 thread usage snapshot" src="https://user-images.githubusercontent.com/19481864/33451452-f350a3cc-d5c3-11e7-9839-6ddf592ca532.png">

**Comment by sbordet** [comment] 2017-11-30 20:00
I would like to see both client and server code.
From your previous graph, I see in the first half that the 2 Jetty versions are basically performing the same, then something changed. What did it change ?

**Comment by pawaramol** [comment] 2017-12-01 22:04
Sorry for the late reply.
I am attaching our server code, our APIs are called by called by our partners so cant really provide client code.
Between I was trying earlier 9.4 release (9.4.2) and I did not notice lot of threads are in waiting state so I think something got introduced in between 9.4.2 and 9.4.7. Please see image for 9.4.2

[JettyBidder.java.txt](https://github.com/eclipse/jetty.project/files/1523107/JettyBidder.java.txt)

![9 4 2 thread usage snapshot](https://user-images.githubusercontent.com/19481864/33505538-8b108f60-d6a0-11e7-8c6a-0e6c7edd2b6f.png)

**Comment by gregw** [comment] 2017-12-02 09:21
@pawaramol I do not think that changes to the distribution of work over the threads is itself a problem.  In fact we actually prefer to use recently busy threads so that idle threads can timeout.  At best, this is a symptom rather than a cause.

The problem is the dramatic change in through put you observe.  Obviously something changed in the server at some point.   It would be really good to get these graphs for when 9.4.x is handling the load and then again after when it's throughput drops.   If the graphs look more or less the same, then I don't think this is the issue.

Eitherway, we need as much info from before and after that mode change: thread graphs,  Thread dumps and the output from server.dumpStdErr (can be triggered from JMX) would all be great to see from before and after the mode change.

**Comment by pawaramol** [comment] 2017-12-06 21:59
Sorry for the late reply. I have had a chance to test 9.4.5 on our prod env and it is working fine.
I could not test 9.4.7/8 because we are in blackout and since it had issues in previous test. Once we are out of blackout I will try to get info you guys need but so far like I said till 9.4.5 things are looking fine.

**Comment by sbordet** [comment] 2018-03-28 19:43
@pawaramol closing this issue as you reported it solved with 9.4.5.

**Closed by sbordet** 2018-03-28 19:43 UTC
