### ISSUE TITLE
How acceptThreads and acceptQueueSize impact concurrent requests?

### ISSUE THREAD

**Issue by arjunballa** [eclipse/jetty.project#8461] opened 2022-08-14 23:23 UTC
@sbordet
@Joakim Erdfelt

**Jetty version**
Jetty version is 7.4

**Java version**
OS: OpenAdopt JDK 8

**Question**

I am new to Jetty.

*We are running into an issue with an application using Jetty 7.4 under a load test. Any requests to the Jetty server gets stuck and there is no response returned, even after several hours. Also, new requests seem to behave the same way, just waiting for a response forever. The thread dump does not show any deadlocks and but does show a good number of threads in TIMED_WAITING state. There are no Jetty exceptions in the logs.*

**Details:**

Jetty version is 7.4

OS: OpenAdopt JDK 8

acceptQueueSize: 100

acceptTimeout: 1800000 (30 mins)

acceptors: 1

lingerTime: 10000 (milli secs)

min number of thread: 5

max number of thread: 500

Concurrent request: 700 (70 APIs and 10 per API)

```
SelectChannelConnector result = new MySelectChannelConnectorImpl();
result.setThreadPool(createThreadPool(url, config/* min and max threads*/));
result.setPort((url.getPort() > 0) ? url.getPort() : port);
result.setMaxIdleTime((int)acceptTimeout);
result.setAcceptors(acceptThreads);
result.setAcceptQueueSize(acceptQueueSize);
result.setSoLingerTime(linger);
```

I know Jetty 7.4 is end of life but customer is not in a position to upgrade.
We need to prove to the customer that, issue is with jetty version and will be fixed with jetty upgrade.

Can I tweak the acceptThreads and acceptQueueSize for better results?

I want to understand acceptors threads, selectors, jetty worker thread, acceptQueueSize, acceptTimeout.

Any pointer to learn the concepts.

![Screen Shot 2022-08-14 at 4 18 07 PM](https://user-images.githubusercontent.com/613351/184558665-6d350c42-7ecc-42b1-ab38-82105f4a0683.png)

![Screen Shot 2022-08-14 at 4 17 40 PM](https://user-images.githubusercontent.com/613351/184558673-412b6af1-1a9f-40ce-9183-372db39e355d.png)

**Comment by olamy** [comment] 2022-08-14 23:33
Thanks for using Jetty.
Please first use a supported Jetty version at least 10.0.11 (see https://www.eclipse.org/jetty/download.php and read this https://github.com/eclipse/jetty.project/issues/7958)
Then if you still think you have issue.
Please report a thread dump.

**Comment by arjunballa** [comment] 2022-08-14 23:42
@olamy @joakime
I know Jetty 7.4 is end of life but customer is not in a position to upgrade to new version of our product where we upgraded Jetty. 

I want to understand acceptors threads, selectors, jetty worker thread, acceptQueueSize, acceptTimeout. Any pointer to learn the concepts?

We need to prove to the customer that, issue is with jetty version and will be fixed with jetty upgrade.

I need pointers to prove the same to customer.

Can I tweak the acceptThreads and acceptQueueSize for better results?

**Comment by arjunballa** [comment] 2022-08-15 03:03
@joakime I want to understand acceptors threads, selectors, jetty worker thread, acceptQueueSize, acceptTimeout. Any pointer to learn the concepts?

**Comment by gregw** [comment] 2022-08-15 04:09
@arjunballa te key word in your request for support on jetty 7.4 is "customer".   Support for old versions can be available, but not on an opensource basis.  Please contact sales@webtide.com for commercial support.

But whilst I'm here... the number of acceptors is almost certainly unrelated.   Probably the same for acceptQueue.   The issue is more likely to be in the thread pool or thread pool queue.
I would try not setting any jetty configuration for acceptors, selectors, threads, thread pools etc. and going with the jetty defaults.

**Comment by joakime** [comment] 2022-08-15 14:42
@arjunballa we are currently working on Jetty 12 at the moment, know that Jetty 7.4 represents nearly 10 major versions of Jetty difference. 

Reminder: Jetty versioning since 1995 has been `<servlet-support>.<major-version>.<minor-ver>`.    (See [Jetty Versions Table](https://www.eclipse.org/jetty/download.php#version-table))
Jetty 12 has broken from this old versioning scheme and will be the first of Jetty using a more contemporary versioning scheme of `<major>.<minor>.<patch>`

Major versions I am talking about: 12.0, 11.0, 10.0, 9.4, 9.3, 9.2, 9.1, 9.0, 8.1, 8.0, 7.4

As you can probably imagine, the effort to support a version 10 major versions ago is very high.

Jetty 7 opensource support ended in 2014 (we support if for commercial customers, and help them upgrade when they are ready)

**Comment by sbordet** [comment] 2022-08-15 15:15
@arjunballa from the only stack trace that you posted, the server thread is blocked trying to write content to the client.
This means that the client is not reading the content that the server sends, or it does not read fast enough.

This is typical for load tests, where the client is typically the bottleneck and it is not configured to sustain the load that itself generates towards the server. 
For example, in our load tests we use at least 4 clients machines for a single server machine, and even in this way the server barely breaks a sweat at 240k requests/s.

Your problem is probably just a misconfigured load test.

You can read about Jetty's architecture for Jetty 10+ here:
https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-arch

**Comment by arjunballa** [comment] 2022-08-15 16:46
@sbordet Thanks for the response.
Is there a configuration for how much time Jetty should wait for client to ack that it has read the response?
Customer says, server got stuck for more than 2 hrs on all load test requests and any new request is also getting stuck.

They are using Jmeter  to do load test and I dont know why Jmeter is not able to read the response quickly.

**Comment by joakime** [comment] 2022-08-15 18:54
> They are using Jmeter to do load test and I dont know why Jmeter is not able to read the response quickly.

This is the reason that JMeter has a distributed/remote testing configuration.

https://jmeter.apache.org/usermanual/remote-test.html

**Comment by gregw** [comment] 2022-08-16 02:12
Closing as jetty-7 is well beyond end of life and 4 engineers have already spent time on this!

**Closed as completed by gregw** 2022-08-16 02:12 UTC
Labels: Question, Unsupported Release
