### ISSUE TITLE
org.eclipse.jetty.websocket.jsr356.ClientContainer doesn't provide a way to configure SslContextFactory

### ISSUE THREAD

**Issue by mohanrao** [eclipse/jetty.project#403] opened 2016-03-07 20:59 UTC
While using the jsr356 way of websockets , jetty doesn't provide a way to configure sslcontextfactory for secured websockets.

The overloaded constructor which takes WebSocketContainerScope is not using the scope sslcontextfactory while creating the websocketclient instance in the below code 

 client = new WebSocketClient(scope, new SslContextFactory(trustAll));

**Comment by joakime** [comment] 2016-03-07 21:01
This is a duplicate of Issue #155

**Closed by joakime** 2016-03-07 21:01 UTC
