### ISSUE TITLE
Getting "Unexpected wrap result BUFFER_OVERFLOW"

### ISSUE THREAD

**Issue by shimon-cherny** [eclipse/jetty.project#5006] opened 2020-06-29 21:40 UTC
**Jetty version**
9.4.24.v20191120
**Java version**
Oracle Corporation 1.8.0_201 Vendor: Oracle Corporation
**OS type/version**
Windows Server 2016 Arch:amd64 Version:10.0
**Description**
My app server log files full of these errors.
The application is running on Azure.

This is the stack trace i see:

```
ERROR | Unexpected wrap result BUFFER_OVERFLOW
java.lang.IllegalStateException: Unexpected wrap result BUFFER_OVERFLOW
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1101) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:378) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1507) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:132) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:823) ~[jetty-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:221) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onSessionFailure(HTTP2ServerConnection.java:261) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:128) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1156) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:1060) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Flusher.onCompleteFailure(HTTP2Flusher.java:344) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.IteratingCallback.failed(IteratingCallback.java:402) ~[jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.fail(WriteFlusher.java:348) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:405) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1507) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:132) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:823) ~[jetty-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:221) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onSessionFailure(HTTP2ServerConnection.java:261) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:128) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1156) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:1060) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Flusher.onCompleteFailure(HTTP2Flusher.java:344) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.IteratingCallback.failed(IteratingCallback.java:402) ~[jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.fail(WriteFlusher.java:348) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:405) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1507) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:132) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:823) ~[jetty-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:221) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onSessionFailure(HTTP2ServerConnection.java:261) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:128) ~[http2-server-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1156) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:1060) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.http2.HTTP2Flusher.onCompleteFailure(HTTP2Flusher.java:344) ~[http2-common-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.IteratingCallback.failed(IteratingCallback.java:402) ~[jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.fail(WriteFlusher.java:348) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:405) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1507) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:132) ~[jetty-io-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.24.v20191120.jar:9.4.24.v20191120]
		at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by joakime** [comment] 2020-06-29 22:06
If you can easily replicate, can you try again on Jetty version `9.4.30.v20200611`? (there's been several improvements in the HTTP/2 code since 9.4.24)

**Comment by shimon-cherny** [comment] 2020-06-30 08:33
Thank you for prompt response. Will definitely do that.
Simply i have this system in production and i can't upgrade jetty that fast. Anything else i can check or disable to workaround this issue?

**Comment by sbordet** [comment] 2020-07-03 17:45
Also, will be great if you can replicate with DEBUG logs enabled.

This is one of those errors that should never happen, and we have a code path that throws an `IllegalStateException` for this reason.

Also, consider upgrading the JDK to something newer than 8u201 - could be a JVM bug.

**Comment by prateekkohli2112** [comment] 2020-07-28 17:14
I got this issue even with Jetty version 9.4.30.v20200611.

@scherny1 were you able to find the root cause for this issue.

**Comment by sbordet** [comment] 2020-07-28 17:30
@prateekkohli2112 can you get DEBUG logs?

**Comment by prateekkohli2112** [comment] 2020-08-01 08:05
I was unable to reproduce this issue when I ran Jetty in debug mode.

But I changed the maxConcurrentStreams to 20 from default 128 and I am not getting this error anymore.

Not sure how they are related, but earlier I was getting this error very frequently, but after changing the maxConcurrentStreams to 20 I did not get this error even after running my application for more than 2 days.

**Comment by VasilVasilev93** [comment] 2020-11-20 11:42
@sbordet
I have the same issue, using Conscrypt as provider(conscrypt-openjdk-uber, version 2.5.0) on jetty 9.4.30.v20200611, jdk 1.8.0_231 and trying a server push. Attaching the debug logs
[log.zip](https://github.com/eclipse/jetty.project/files/5573250/log.zip)

**Comment by sbordet** [comment] 2020-11-21 16:04
@VasilVasilev93 from your logs, you are attempting to push a large number of images (some 300-400 of them) - which generates a large number of buffers whose encryption overflows the single output buffer.

While we may try to take this case into account, I would recommend to not push these many images at once.

**Comment by VasilVasilev93** [comment] 2020-11-21 16:14
@sbordet Thanks for the quick response. Btw, this issue cannot be reproduced when not using Conscrypt provider. 1000 images are being pushed with no issues.

**Comment by sbordet** [comment] 2020-11-21 21:30
@VasilVasilev93 did you report a bug to Conscrypt? If so, can you link it here? This does not seem like a Jetty issue.

**Comment by VasilVasilev93** [comment] 2020-11-21 22:16
@sbordet No, but I just created, here's the [issue](https://github.com/google/conscrypt/issues/929)

**Comment by joakime** [comment] 2022-02-24 10:50
Closing as this appears to have been solved at https://github.com/google/conscrypt/issues/929

**Closed as completed by joakime** 2022-02-24 10:50 UTC
Labels: Third Party
