### ISSUE TITLE
org.eclipse.jetty:jetty-client:12.0.10 unit test cases are failing

### ISSUE THREAD

**Issue by aylenfer** [eclipse/jetty.project#12073] opened 2024-07-22 17:22 UTC
Hi,
I am having the following log for test failures:

```
[19 23:41:51.985] | Running org.eclipse.jetty.util.resource.FileSystemResourceTest.testResolveRootPath(WorkDir)
[19 23:41:51.990] | [WARNING] Tests run: 44, Failures: 0, Errors: 0, Skipped: 6, Time elapsed: 0.045 s -- in org.eclipse.jetty.util.resource.FileSystemResourceTest
[19 23:41:52.065] | [INFO]
[19 23:41:52.065] | [INFO] Results:
[19 23:41:52.065] | [INFO]
[19 23:41:52.065] | [ERROR] Failures:
[19 23:41:52.065] | [ERROR]   UrlResourceFactoryTest.testHttps:67 expected: <true> but was: <false>
[19 23:41:52.065] | [INFO]
[19 23:41:52.065] | [ERROR] Tests run: 2541, Failures: 1, Errors: 0, Skipped: 136
[19 23:41:52.065] | [INFO]
[19 23:41:52.068] | [INFO] ------------------------------------------------------------------------
[19 23:41:52.068] | [INFO] Reactor Summary for Jetty :: Project 12.0.10:
[19 23:41:52.068] | [INFO]
[19 23:41:52.068] | [INFO] Build :: Resources ................................. SUCCESS [  0.688 s]
[19 23:41:52.068] | [INFO] Jetty :: Project ................................... SUCCESS [  1.401 s]
[19 23:41:52.068] | [INFO] Build .............................................. SUCCESS [  0.019 s]
[19 23:41:52.068] | [INFO] Core ............................................... SUCCESS [  0.014 s]
[19 23:41:52.068] | [INFO] Core :: SLF4J Implementation ....................... SUCCESS [  0.523 s]
[19 23:41:52.068] | [INFO] Core :: Utilities .................................. FAILURE [02:27 min]
[19 23:41:52.069] | [INFO] Core :: JMX ........................................ SKIPPED
[19 23:41:52.069] | [INFO] Core :: IO ......................................... SKIPPED
[19 23:41:52.069] | [INFO] Core :: ALPN ....................................... SKIPPED
[19 23:41:52.069] | [INFO] Core :: ALPN :: Client ............................. SKIPPED
[19 23:41:52.069] | [INFO] Tests .............................................. SKIPPED
[19 23:41:52.069] | [INFO] Tests :: Multipart Test Tools ...................... SKIPPED
...
[19 23:41:52.081] | [INFO] ------------------------------------------------------------------------
[19 23:41:52.081] | [INFO] BUILD FAILURE
[19 23:41:52.081] | [INFO] ------------------------------------------------------------------------
[19 23:41:52.081] | [INFO] Total time:  02:31 min
[19 23:41:52.081] | [INFO] Finished at: 2024-07-19T23:41:52Z
[19 23:41:52.081] | [INFO] ------------------------------------------------------------------------
[19 23:41:52.081] | [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project jetty-util: There are test failures.
[19 23:41:52.081] | [ERROR]
[19 23:41:52.081] | [ERROR] Please refer to /tmp/pkgs_raw/jetty-client/12.0.10/jetty-core/jetty-util/target/surefire-reports for the individual test results.
[19 23:41:52.081] | [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[19 23:41:52.081] | [ERROR] -> [Help 1]
```

Please help me to resolve this issue and have the corresponding tests completed successfully.

**TEST COMMAND:  mvn test
 JAVA_VERSION         | 17.0.8  
 MAVEN_VERSION: 3.9.4**

**Comment by joakime** [comment] 2024-07-22 17:25
Duplicate of #11068

**Closed as not planned by joakime** 2024-07-22 17:25 UTC
Labels: Bug
