### ISSUE TITLE
ClassCastException in Jetty

### ISSUE THREAD

**Issue by jansupol** [eclipse/jetty.project#5525] opened 2020-10-28 13:17 UTC
Jetty version: 11.0.0.beta3 (jetty-maven-plugin)
Java version "11.0.7" 2020-04-14 LTS

The following stacktrace occurs:
> java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
    at org.eclipse.jetty.util.resource.ResourceCollection.list (ResourceCollection.java:426)
    at org.eclipse.jetty.util.resource.Resource.getListHTML (Resource.java:479)
    at org.eclipse.jetty.server.ResourceService.sendDirectory (ResourceService.java:626)
    at org.eclipse.jetty.server.ResourceService.sendWelcome (ResourceService.java:445)
    at org.eclipse.jetty.server.ResourceService.doGet (ResourceService.java:253)
    at org.eclipse.jetty.servlet.DefaultServlet.doGet (DefaultServlet.java:455)
    at jakarta.servlet.http.HttpServlet.service (HttpServlet.java:500)
    at jakarta.servlet.http.HttpServlet.service (HttpServlet.java:587)
    at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service (ServletHolder.java:1381)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:731)
    at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter (ServletHandler.java:1665)
    at org.eclipse.jetty.websocket.util.server.WebSocketUpgradeFilter.doFilter (WebSocketUpgradeFilter.java:156)
    at org.eclipse.jetty.servlet.FilterHolder.doFilter (FilterHolder.java:207)
    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter (ServletHandler.java:1641)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:528)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:136)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:585)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:228)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:1563)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1354)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:181)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:472)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:1536)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:179)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1278)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:134)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:188)
    at org.eclipse.jetty.server.handler.HandlerList.handle (HandlerList.java:56)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
    at org.eclipse.jetty.server.Server.handle (Server.java:567)
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$0 (HttpChannel.java:370)
    at org.eclipse.jetty.server.HttpChannel.dispatch (HttpChannel.java:567)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:362)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:291)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:324)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:105)
    at org.eclipse.jetty.io.SocketChannelEndPoint$1.run (SocketChannelEndPoint.java:106)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask (EatWhatYouKill.java:338)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce (EatWhatYouKill.java:315)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce (EatWhatYouKill.java:173)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run (EatWhatYouKill.java:131)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run (ReservedThreadExecutor.java:375)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:790)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:912)
    at java.lang.Thread.run (Thread.java:834)

**Comment by janbartel** [comment] 2020-10-28 14:54
Thanks, I think this is the same as https://github.com/eclipse/jetty.project/pull/5527 which co-incidentally we filed a couple of minutes ago ;)

**Comment by janbartel** [comment] 2020-11-03 11:46
Closing as a duplicate of #5527

**Closed as completed by janbartel** 2020-11-03 11:46 UTC
