### ISSUE TITLE
Leak detected during client tests

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1580] opened 2017-05-30 15:45 UTC
```
Running org.eclipse.jetty.fcgi.server.HttpClientTest.testGZIPContentEncoding()
2017-05-30 17:43:42.597:INFO:oejs.Server:main: jetty-9.4.6-SNAPSHOT
2017-05-30 17:43:42.658:INFO:oejs.AbstractConnector:main: Started ServerConnector@66ad7bf0{fcgi/1.0,[fcgi/1.0]}{0.0.0.0:34466}
2017-05-30 17:43:42.668:INFO:oejs.Server:main: Started @3407ms
2017-05-30 17:43:42.740:WARN:oeji.LeakTrackingByteBufferPool:: ByteBuffer java.nio.HeapByteBuffer[pos=0 lim=0 cap=2048] leaked at:
java.lang.Throwable
	at org.eclipse.jetty.util.LeakDetector$LeakInfo.<init>(LeakDetector.java:183)
	at org.eclipse.jetty.util.LeakDetector$LeakInfo.<init>(LeakDetector.java:172)
	at org.eclipse.jetty.util.LeakDetector.acquired(LeakDetector.java:79)
	at org.eclipse.jetty.io.LeakTrackingByteBufferPool.acquire(LeakTrackingByteBufferPool.java:66)
	at org.eclipse.jetty.http.GZIPContentDecoder.acquire(GZIPContentDecoder.java:408)
	at org.eclipse.jetty.http.GZIPContentDecoder.decodeChunks(GZIPContentDecoder.java:174)
	at org.eclipse.jetty.http.GZIPContentDecoder.decode(GZIPContentDecoder.java:71)
	at org.eclipse.jetty.client.HttpReceiver.responseContent(HttpReceiver.java:336)
	at org.eclipse.jetty.fcgi.client.http.HttpReceiverOverFCGI.responseContent(HttpReceiverOverFCGI.java:57)
	at org.eclipse.jetty.fcgi.client.http.HttpChannelOverFCGI.content(HttpChannelOverFCGI.java:121)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI$ResponseListener.onContent(HttpConnectionOverFCGI.java:408)
	at org.eclipse.jetty.fcgi.parser.ResponseContentParser$ResponseParser.notifyContent(ResponseContentParser.java:277)
	at org.eclipse.jetty.fcgi.parser.ResponseContentParser$ResponseParser.parse(ResponseContentParser.java:131)
	at org.eclipse.jetty.fcgi.parser.ResponseContentParser.onContent(ResponseContentParser.java:74)
	at org.eclipse.jetty.fcgi.parser.StreamContentParser.parse(StreamContentParser.java:69)
	at org.eclipse.jetty.fcgi.parser.Parser.parse(Parser.java:82)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI.parse(HttpConnectionOverFCGI.java:180)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI.process(HttpConnectionOverFCGI.java:150)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI.onFillable(HttpConnectionOverFCGI.java:114)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbordet** [comment] 2017-06-05 17:49
Duplicate of #1509.

**Closed by sbordet** 2017-06-05 17:50 UTC
Labels: Bug
