### ISSUE TITLE
If the BaseResource contain blank space, the Handler don't work?

### ISSUE THREAD

**Issue by beibm** [eclipse/jetty.project#4399] opened 2019-12-04 14:41 UTC
**Jetty version**
9.4.20
**Java version**
1.8.202
**OS type/version**
window 10
**Description**
I Embedding jetty as a server, code like this:

``` java
public class myServer {
... ...
String myBaseResource="file:/C:/Program Files/rptServer";
server = new Server(9011);
System.setProperty("org.eclipse.jetty.util.UrlEncoding.charset", "GBK");
ServletContextHandler contextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);
contextHandler .setContextPath("/");
contextHandler .setResourceBase(myBaseResource);
contextHandler .addServlet(new ServletHolder(new myServlet()), "/myServlet");

ResourceHandler resourceHandler = new ResourceHandler();
resourceHandler.setResourceBase(myBaseResource)
HandlerCollection handlers = new HandlerCollection();
handlers.addHandler(resourceHandler);
handlers.addHandler(contextHandler );

server.setHandler(handlers);
server.start();
... ...
}
```

I start the myServer , post a quest to the server, it do not work!
but, if i use version 6.1.23 of jetty, it work fine.

then, I change the follow statement
String myBaseResource="file:/C:/Program Files/rptServer";
to:
String myBaseResource="file:/C:/rptServer";
it work fine in version 9.4.20.

So, I think if the BaseResource contain blank space, the jetty will not work, maybe this is a bug?

**Comment by joakime** [comment] 2019-12-04 15:52
That's because `file:/C:/Program Files/rptServer` is not a valid URI.

``` java
package uri;

import java.net.URI;
import java.net.URISyntaxException;

public class URITest
{
    public static void main(String[] args) throws URISyntaxException
    {
        URI uri = new URI("file:/C:/Program Files/rptServer");
    }
}
```

causes ...

```
Exception in thread "main" java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/rptServer
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at uri.URITest.main(URITest.java:10)
```

The space in "Program Files" is supposed to be URL Encoded to `%20`.

Here's a demo of what URI and URL values you get from either `Path` or `File` objects.

``` java
package fs;

import java.io.File;
import java.net.MalformedURLException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class PathUriDemo
{
    public static void main(String[] args)
    {
        demo("C:/Program Files/Microsoft/");
        demo("C:\\Program Files\\Microsoft/");
        demo("C:/Program Files (x86)/Common Files/");
    }

    public static void demo(String rawPath)
    {
        System.out.println("Raw Path: " + rawPath);
        Path path = Paths.get(rawPath);
        System.out.println("  Path: " + path);
        System.out.println("  Path.toUri: " + path.toUri());
        try
        {
            File file = new File(rawPath);
            System.out.println("  File: " + file);
            System.out.println("  File.toURI: " + file.toURI());
            System.out.println("  File.toURL: " + file.toURL());
        }
        catch (MalformedURLException e)
        {
            e.printStackTrace();
        }
    }
}
```

The results of which are ...

```
Raw Path: C:/Program Files/Microsoft/
  Path: C:\Program Files\Microsoft
  Path.toUri: file:///C:/Program%20Files/Microsoft
  File: C:\Program Files\Microsoft
  File.toURI: file:/C:/Program%20Files/Microsoft
  File.toURL: file:/C:/Program Files/Microsoft
Raw Path: C:\Program Files\Microsoft/
  Path: C:\Program Files\Microsoft
  Path.toUri: file:///C:/Program%20Files/Microsoft
  File: C:\Program Files\Microsoft
  File.toURI: file:/C:/Program%20Files/Microsoft
  File.toURL: file:/C:/Program Files/Microsoft
Raw Path: C:/Program Files (x86)/Common Files/
  Path: C:\Program Files (x86)\Common Files
  Path.toUri: file:///C:/Program%20Files%20(x86)/Common%20Files/
  File: C:\Program Files (x86)\Common Files
  File.toURI: file:/C:/Program%20Files%20(x86)/Common%20Files/
  File.toURL: file:/C:/Program Files (x86)/Common Files/
```

You might be looking at the results of `File.toURL` and going "hey! that's what I'm using!".

Note that [the `File.toURL()` method has been deprecated for quite a while now](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#toURL--), go read the javadoc and you'll understand why it's been deprecated.

But all is not lost, you have several different paths to success from here.

**Option 1: Use the Type specific Resource implementation**

You could use `PathResource` directly.

``` java
Path basePath = Paths.get("C:\\Program Files\\rptServer");
if (!Files.exists(basePath))
    throw new FileNotFoundException(basePath.toString());
Resource myBaseResource = new PathResource(basePath); // Use type specific resource

ServletContextHandler contextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);
contextHandler.setContextPath("/");
contextHandler.setBaseResource(myBaseResource); // use Resource instance directly
```

**Option 2: Obtain the proper URI from the File System itself**

You could use a `java.nio.file.Path` and ask for it's URI, which in turn will use the FileSystem implementation to obtain the properly encoded URI for that FileSystem resource.

``` java
Path basePath = Paths.get("C:\\Program Files\\rptServer");
if (!Files.exists(basePath))
    throw new FileNotFoundException(basePath.toString());
URI uri = basePath.toUri(); // Ask the FileSystem implementation for it's path specific URI representation.
Resource myBaseResource = Resource.newResource(uri);

ServletContextHandler contextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);
contextHandler.setContextPath("/");
contextHandler.setBaseResource(myBaseResource); // use Resource instance directly
```

**Comment by joakime** [comment] 2019-12-04 20:16
Closing as not a bug.

**Closed as completed by joakime** 2019-12-04 20:16 UTC
Labels: Not a bug
