### ISSUE TITLE
WebAppClassLoader does not define packages when ClassFileTransformer is present

### ISSUE THREAD

**Issue by kurbatov** [eclipse/jetty.project#1068] opened 2016-11-03 07:50 UTC
`WebAppClassLoader#findClass(String)` has no code that defines the package of a found class if the class-loader has `ClassFileTransformer` registered. It may lead to various errors that provide no clear information about root causes of the issue.

Examples of the errors I got:
 - java.lang.IncompatibleClassChangeError: Class com.sun.xml.ws.api.server.Container$NoneContainer does not implement the requested interface com.sun.xml.ws.api.Component
 - com.sun.org.apache.xerces.internal.impl.dv.DVFactoryException: DTD factory class com.sun.org.apache.xerces.internal.impl.dv.dtd.DTDDVFactoryImpl does not extend from DTDDVFactory
 - java.lang.IllegalAccessError: class sun.reflect.GeneratedConstructorAccessor19 cannot access its superclass sun.reflect.ConstructorAccessorImpl
 - javax.xml.bind.JAXBException: <attributeName> is not a valid property on class <className>

This bug reveals itself only if the web-application adds `ClassFileTransformer` to its class-loader (in case of enabling load-time weaving in Spring for examle) and if the web-application uses information about packages somehow (`jaxb` uses that for namespace mapping). If there is no `ClassFileTransformer` , it delegates the class-loading to its ancestor and all is fine.

Please, fix `WebAppClassLoader#findClass` because it leads to really annoying and hard-to-debug issues.

Here I provide quick and dirty fix of the class-loader for those who desperately needs it:

```java
import java.io.IOException;
import java.io.InputStream;
import java.lang.instrument.ClassFileTransformer;
import java.lang.instrument.IllegalClassFormatException;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.List;
import java.util.jar.Manifest;
import org.eclipse.jetty.util.IO;
import org.eclipse.jetty.util.log.Log;
import org.eclipse.jetty.util.log.Logger;
import org.eclipse.jetty.webapp.WebAppClassLoader;
import sun.misc.Resource;
import sun.misc.URLClassPath;

/**
 * Fixes {@link WebAppClassLoader}'s behavior when class transformers are
 * registered. Original {@link WebAppClassLoader} fails to define a package of
 * the found class.
 *
 * @author Oleg Kurbatov &lt;oleg.kurbatov@nitka.com&gt;
 */
public class TransformingWebAppClassLoader extends WebAppClassLoader {

    private final List<ClassFileTransformer> transformers;

    private final URLClassPath ucp;

    private static final Logger LOGGER = Log.getLogger(WebAppClassLoader.class);

    public TransformingWebAppClassLoader(Context context) throws IOException {
        this(null, context);
    }

    public TransformingWebAppClassLoader(ClassLoader parent, Context context) throws IOException {
        super(parent, context);
        try {
            Field ucpField = URLClassLoader.class.getDeclaredField("ucp");
            ucpField.setAccessible(true);
            ucp = (URLClassPath) ucpField.get(this);
            Field transformersField = WebAppClassLoader.class.getDeclaredField("_transformers");
            transformersField.setAccessible(true);
            transformers = (List<ClassFileTransformer>) transformersField.get(this);
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    protected Class<?> findClass(String name) throws ClassNotFoundException {
        Class<?> clazz = null;
        if (transformers.isEmpty()) {
            clazz = super.findClass(name);
        } else {
            String path = name.replace('.', '/').concat(".class");
            URL url = getResource(path);
            if (url == null) {
                throw new ClassNotFoundException(name);
            }
            // define package
            int i = name.lastIndexOf('.');
            if (i != -1) {
                String pkgname = name.substring(0, i);
                try {
                    Resource res = ucp.getResource(path, false);
                    if (res != null) {
                        // Check if package already loaded.
                        Manifest man = res.getManifest();
                        Method definePackageInternal = URLClassLoader.class.getDeclaredMethod("definePackageInternal", String.class, Manifest.class, URL.class);
                        definePackageInternal.setAccessible(true);
                        definePackageInternal.invoke(this, pkgname, man, url);
                    } else {
                        return null;
                    }
                } catch (IOException | ReflectiveOperationException e) {
                    LOGGER.warn("Cannot register a package " + pkgname, e);
                    return null;
                }
            }
            InputStream content = null;
            try {
                content = url.openStream();
                byte[] bytes = IO.readBytes(content);
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("foundClass({}) url={} cl={}", name, url, this);
                }
                for (ClassFileTransformer transformer : transformers) {
                    byte[] tmp = transformer.transform(this, name, null, null, bytes);
                    if (tmp != null) {
                        bytes = tmp;
                    }
                }
                clazz = defineClass(name, bytes, 0, bytes.length);
            } catch (IOException e) {
                throw new ClassNotFoundException(name, e);
            } catch (IllegalClassFormatException e) {
                throw new ClassNotFoundException(name, e);
            } finally {
                if (content != null) {
                    try {
                        content.close();
                    } catch (IOException e) {
                        throw new ClassNotFoundException(name, e);
                    }
                }
            }
        }
        return clazz;
    }

}
```

**Comment by joakime** [comment] 2016-11-04 16:20
Been doing a little reading on `ClassFileTransformer`.

How is that compliant/compatible to the Servlet 3.x spec??

The bytecode being scanned per the requirements for the Servlet spec would wind up not being the ones used later?  That's a bit spec breakage point.

This would also be incompatible with our efforts to support JDK9.

**Comment by kurbatov** [comment] 2016-11-04 21:43
I guess the issue here has nothing to do with `ClassFileTransformer` by itself. The error appears if the instance is **present** in the list of registred transformers.

The missing part is in `WebAppClassLoader`'s method `findClass`, specifically in the following piece:

```java
        if (transformers.isEmpty()) {
            clazz = super.findClass(name);
        } else {
            ...
        }
```

The super class defines not only the class but also its package if neccessary. `WebAppClassLoader` though never defines the package (in the else branch).  Hence the `clazz` instance returns `null` when `getPackage` invoked right after the class is defined. I think it is incorrect regardless any spec.

**Comment by joakime** [comment] 2017-03-15 22:21
@janbartel please review (close if invalid / unable to replicate)

**Comment by atokle** [comment] 2017-10-04 07:11
Any fix for this problem yet? I'm stuck with this fault now.

**Comment by gregw** [comment] 2017-10-04 07:19
@atokle not yet.  I'll have a look now, but really need a test to confirm that it is fixed.  Do you have one?

**Comment by gregw** [comment] 2017-10-04 07:50
actually looking at this, I think we need to understand a lot more before we try to fix this, specially with java9 coming out.

Also, why is this not a JVM bug?  the package definition is done in their private defineClass method, but that is only invoked via some calling paths.  I think it is a bug that the `protected final Class<?> defineClass(String name, byte[] b, int off, int len)` method that we call does not define the package, even thought the javadoc says:

> This method defines a package in this class loader corresponding to the package of the Class (if such a package has not already been defined in this class loader). The name of the defined package is derived from the binary name of the class specified by the byte array b. Other properties of the defined package are as specified by Package.

So perhaps raise a bug against openjdk?

You have the work around above if you really need it.

**Comment by atokle** [comment] 2017-10-04 09:34
I don't have a good test. I got a project at a customer where it fail, but I can't upload source, and it's also to big to use as a good test.

But I have investigated a bit more, and think I got more detail about when it happends. The project is wired with spring 4.3.2, and use cxf 3.1.7 to implement webservices.

The fault happends when cxf is loading jaxb-generated classes in the method org.apache.cxf.jaxb.Utils.getFieldXJTA(final Field f)
    static XmlJavaTypeAdapter getFieldXJTA(final Field f) {
        XmlJavaTypeAdapter adapter = f.getAnnotation(XmlJavaTypeAdapter.class);
        if (adapter == null) {
            adapter = f.getType().getAnnotation(XmlJavaTypeAdapter.class);
        }
        if (adapter == null) {
            XmlJavaTypeAdapters adapters = f.getDeclaringClass().getPackage().getAnnotation(XmlJavaTypeAdapters.class);
            if (adapters != null) {
                for (XmlJavaTypeAdapter candidate : adapters.value()) {
                    if (candidate != null && candidate.type().equals(f.getType())) {
                        adapter = candidate;
                        break;
                    }
                }
            }
        }
        return adapter;
    }

f.getDeclaringClass() finds the class, but getPackage() on it returns null. But I found that this only happends when <context:load-time-weaver/> is defined in spring.
And I also found that if I add the following parameter to jvm start, it don't fail anymore. 
-javaagent:%M2_HOME%\repository\org\springframework\spring-instrument\4.3.2.RELEASE/spring-instrument-4.3.2.RELEASE.jar

I hope this info can give you some clues to figure out what's wrong.
But my workaround now is to add the javaagent argument to startup

**Comment by joakime** [comment] 2017-10-04 15:45
`getPackage()` can return null in many scenarios, that code should handle those situations.

**Comment by atokle** [comment] 2017-10-05 09:22
I'm no expert i classloading, but according to javadoc for class, the `getPackage()` only return null if classloader don't initialize when loading class.

cxf which implements jaxb need the Package, since it will contain the annotations that is in the package-info files in the generated code.

And then I don't understand how cxf should handle it if it did a null check. Should it throw a more descriptive exception, which would not make things work. Or should it classload the package itself?

It feels like a deadlock. Jetty should definitly be able to run jaxb. And if I understand correctly that is broken after WebAppClassLoader start to support ClassFileTransformer. If I'm wrong tell me, and I will instead report it to cxf.

**Comment by gregw** [comment] 2017-10-05 22:44
@atokle yes jetty should definitely be able to run jaxb.
The problem is that when we have transformers we call [defineClass](http://download.java.net/java/jdk9/docs/api/java/lang/ClassLoader.html#defineClass-java.lang.String-byte:A-int-int-), whose javadoc in java9 says:

> This method defines a package in this class loader corresponding to the package of the Class (if such a package has not already been defined in this class loader). The name of the defined package is derived from the binary name of the class specified by the byte array b. Other properties of the defined package are as specified by Package.

Which indicates the classloader should be loading the package for us.  So I do not think we should be updating our code to do this.

The problem may be that in java8 javadoc, it says nothing to this effect, so perhaps it is a bug in java8 that it does not define the package.   In order for jetty to define the package, we have to use reflection and access internal APIs with are subject to change (as per the work around).

Can you try running with java 9 to see if it does work?  If so, then perhaps somebody should raise a bug on openjdk 8?

**Comment by gregw** [comment] 2017-10-05 22:46
Alternately, if somebody can supply us with a simple jar that demonstrates the problem, then we will test in 9 and submit a bug report if there is a difference in behaviour.

**Comment by atokle** [comment] 2017-10-06 08:48
I tried to install java 9 and run it with that, but it failed earlier.
I will try make a jar that reproduce the fault, but need a few days to have it ready.

**Comment by atokle** [comment] 2017-10-08 14:05
I have attached a zip [ClassLoaderTransformerNoPackageTest.zip](https://github.com/eclipse/jetty.project/files/1366912/ClassLoaderTransformerNoPackageTest.zip) with a maven project with two modules.
Build it from the top project using mvn install. I used maven version 3.3.9 when building and testing.

To reproduce the fault, you can move to the ClassLoaderTransformerNoPackageTestWebservice directory and run:
`mvn jetty:run`

To add the spring instrumentation that fixes the problem (but if I understand correct should be unnecessary with new classloader in jetty9) you can from same folder run:
`mvn jetty:run-forked`

If you wanna send a request to the service using i.e. SoapUI you can send 
```
   <soapenv:Header/>
   <soapenv:Body>
      <urn:NoPackageDefinedRequest>
         <urn:domain>
            <urn1:Id>aaaa</urn1:Id>
         </urn:domain>
      </urn:NoPackageDefinedRequest>
   </soapenv:Body>
</soapenv:Envelope>
```
to address `http://localhost:8080/services/service`

The wsdl if you need it is under resource directory of codegen module

I hope this give you what you need to fix or to make bug report to java. Tell me if anything is missing.

**Comment by atokle** [comment] 2017-10-08 14:13
Btw. if you need to run the test that works in debugger, then it's probably easiest to set the javaagent parameter that is configured for jetty-maven-plugin in MAVEN_OPTS and run `mvn jetty:run` instead of `mvn jetty:run-forked`

**Comment by gregw** [comment] 2017-10-10 05:53
@atokle thanks for that.  Using that project I was able to write a [little test class](https://gist.github.com/gregw/b10a710bf19fc95474ab0a73a54326f2) that verified my suspicions.  When run with java8 it produces the output:
```
class org.eclipse.jetty.classloader.transformer.message.nopackagedefinedmessage.ObjectFactory
org.eclipse.jetty.classloader.transformer.message.nopackagedefinedmessage
class org.eclipse.jetty.classloader.transformer.message.nopackagedefinedmessage.ObjectFactory
```
yet run with java9 it produces:
```
class org.eclipse.jetty.classloader.transformer.message.nopackagedefinedmessage.ObjectFactory
org.eclipse.jetty.classloader.transformer.message.nopackagedefinedmessage
class org.eclipse.jetty.classloader.transformer.message.nopackagedefinedmessage.ObjectFactory
org.eclipse.jetty.classloader.transformer.message.nopackagedefinedmessage
```

This does indicate that under java9 the method defineClass will define the package, but it is not doing so under java8.   I really think this is a JVM bug, so I will simplify the example and raise it on openJDK.  Meanwhile, there are several work arounds you can use until we hear from oracle.

**Comment by atokle** [comment] 2017-10-10 07:03
Thank you

**Comment by gregw** [comment] 2017-10-11 00:05
Bug raised on java8, but nothing heard yet if they have accepted it or not.

**Comment by gregw** [comment] 2017-10-12 23:51
They have accepted the JDK bug report: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8189231
So we will monitor anything they have to say on that before deciding if there is any action we should take in Jetty.

**Comment by sbordet** [comment] 2017-10-13 06:15
The JDK bug has been resolved as "not a bug".

**Comment by joakime** [comment] 2017-10-13 12:26
The JDK bug comment for "not a bug" (captured here) ...

> The spec was changed in Java SE 9 so that the defineClass method defines a package if not already been defined. This behavior was not specified in Java SE 8.

**Comment by atokle** [comment] 2017-10-13 13:31
I can see in java8 source that URLClassLoader that extends ClassLoader via SecureClassloader do call a definePackage() in it's defineClass(). I guess that shows how it's intended to be done.

```
    private Class<?> defineClass(String var1, Resource var2) throws IOException {
        long var3 = System.nanoTime();
        int var5 = var1.lastIndexOf(46);
        URL var6 = var2.getCodeSourceURL();
        if (var5 != -1) {
            String var7 = var1.substring(0, var5);
            Manifest var8 = var2.getManifest();
            this.definePackageInternal(var7, var8, var6);
        }

        ByteBuffer var11 = var2.getByteBuffer();
        if (var11 != null) {
            CodeSigner[] var13 = var2.getCodeSigners();
            CodeSource var14 = new CodeSource(var6, var13);
            PerfCounter.getReadClassBytesTime().addElapsedTimeFrom(var3);
            return this.defineClass(var1, var11, var14);
        } else {
            byte[] var12 = var2.getBytes();
            CodeSigner[] var9 = var2.getCodeSigners();
            CodeSource var10 = new CodeSource(var6, var9);
            PerfCounter.getReadClassBytesTime().addElapsedTimeFrom(var3);
            return this.defineClass(var1, var12, 0, var12.length, var10);
        }
    }

```

**Comment by gregw** [comment] 2017-10-13 22:04
@atokle it is true that java8 does define the package in some paths, but not in others.    This makes it really rather difficult for us, as anything we do for java8 will be broken for java9.    Looks like we may have to consider a java9 MR jar after all!

**Comment by nigredo-tori** [comment] 2018-09-11 05:55
Just hit this as well. `javax.xml.bind` wiring relies on `Class.getPackage()` for finding `jaxb.properties` files, which leads to context factory not being found.

**Comment by joakime** [comment] 2018-11-06 16:12
@nigredo-tori @gregw can this issue be closed?  Seems like there's nothing for Jetty to do in this scenario?

**Comment by nigredo-tori** [comment] 2018-11-06 16:21
@joakime, I've found a workaround for my use case, so I'm not really invested in this issue anymore... To be honest, I didn't really read into this discussion, but I'm OK as long as the behavior gets in line with newer Java versions eventually.

**Comment by joakime** [comment] 2018-11-06 16:26
Closing the issue then.

**Closed by joakime** 2018-11-06 16:26 UTC
Labels: More Info Required

**Comment by andrei-ivanov** [comment] 2019-04-09 07:43
So, I've just upgraded to Java 11 (_jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 11.0.2+9-Debian-3bpo91_) and it still doesn't work 😟
```
java.lang.SecurityException: class "org.eclipse.persistence.jaxb.BeanValidationMode"'s signer information does not match signer information of other classes in the same package
   at java.lang.ClassLoader.checkCerts(ClassLoader.java:1150) ~[?:?]
   at java.lang.ClassLoader.preDefineClass(ClassLoader.java:905) ~[?:?]
   at java.lang.ClassLoader.defineClass(ClassLoader.java:1014) ~[?:?]
   at java.lang.ClassLoader.defineClass(ClassLoader.java:877) ~[?:?]
   at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass(WebAppClassLoader.java:689) ~[?:?]
   at org.eclipse.jetty.webapp.WebAppClassLoader.loadAsResource(WebAppClassLoader.java:640) ~[?:?]
   at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:546) ~[?:?]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
   at JaxbConfiguration$EclipseJaxbConfiguration.init(JaxbConfiguration.java:94) ~[server-core-impl-1.0.22-SNAPSHOT.jar:?]
```
So, [defineClass](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L707) is invoked without a `ProtectionDomain` and the newer Java [uses](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/ClassLoader.java#L901) a defaultDomain which is [empty](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/ClassLoader.java#L316).

**Comment by andrei-ivanov** [comment] 2019-04-12 13:50
Is there anything I can do to help?

**Comment by joakime** [comment] 2019-04-12 14:21
> class "org.eclipse.persistence.jaxb.BeanValidationMode"'s signer information does not match signer information of other classes in the same package

That sounds like you have the same class in two different jar files, and (at least) one of those jar files has signed classes in its `META-INF/MANIFEST.MF`.

**Comment by andrei-ivanov** [comment] 2019-04-12 16:47
It doesn't seem to be the case, I've searched for it and it's found only in one jar:
`jar:file:/tmp/jetty/jetty-0.0.0.0-8080-transaction-management.war-_transaction-management-any-7121610277063667005.dir/webapp/WEB-INF/lib/org.eclipse.persistence.moxy-2.7.4.jar!/org/eclipse/persistence/jaxb/BeanValidationMode.class`

And, as I've shown above, [defineClass](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L707) is invoked without a `ProtectionDomain` and the newer Java [uses](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/ClassLoader.java#L901) a defaultDomain which is [empty](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/ClassLoader.java#L316).

Not sure where the package certificates get loaded by the JDK, but the since `defineClass` isn't invoked with a domain, the JDK doesn't load it by itself, it just passes an empty one.

**Comment by andrei-ivanov** [comment] 2019-04-12 17:20
As far as I see, the JAXB implementation detection mechanism invokes `ServiceLoaderUtil.safeLoadClass(className, PLATFORM_DEFAULT_FACTORY_CLASS, getContextClassLoader())` with a `Thread.currentThread().getContextClassLoader()`, that ends up with the `WebAppClassLoader` without any `_transformers` in it, so the JDK `ClassLoader` then populates the package certificates from the `org.eclipse.persistence.moxy-2.7.4.jar` and saves it in the cache.

That's why when later `org.eclipse.persistence.jaxb.BeanValidationMode` gets loaded, it has access to the package certificates but not the ones of the class.

**Comment by andrei-ivanov** [comment] 2019-04-23 08:43
So, the problem seems to be caused by the fact that the Spring `LoadTimeWeaver` gets initialized a bit later in the application initialization process and some classes from `org.eclipse.persistence.moxy-2.7.4.jar` already get [loaded](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L689) with the package certificates.
After the `ClassFileTransformer` gets added, the rest of the classes from that jar go through a different [path](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L707) and that doesn't load the package certificates, even on Java 11 😞

I did find a workaround by forcing the `LoadTimeWeaver` to get initialized as early as possible and by removing a class reference from that jar from an annotation.

Is there anything that can be done to improve this behavior?
From Jetty's `WebAppClassLoader` or from the JDK's `ClassLoader`?
