### ISSUE TITLE
Threading bug causes server thread to hang

### ISSUE THREAD

**Issue by markap14** [eclipse/jetty.project#2952] opened 2018-10-03 14:41 UTC
I am running Jetty 9.4.11.v20180605 as embedded web server. I have an issue with server threads  hanging. In some environments, it's very rare or even un-reproducible, while in other environments it is triggered quickly and continually. I have code that is essentially the following (I say 'essentially' because this is implemented as part of framework so I am extracting out the relevant bits here so that it makes sense):

``` java
final Server server = new Server(port);
final ServerConnector http = new ServerConnector(server, new HttpConnectionFactory(httpConfiguration));
http.setHost(host);
http.setPort(port);
http.setIdleTimeout(30000);
server.setConnectors(new Connector[]{http});

server.setHandler(new AbstractHandler() {
    @Override
    public void handle(final String target, final Request baseRequest, final HttpServletRequest request, final HttpServletResponse response) throws IOException, ServletException {

      final InputStream requestIn = request.getInputStream();
      final OutputStream outStream = getOutput(); // part of framework that obtains an output stream
      final byte[] buffer = new byte[8192];
      int len;
      while ((len = requestIn.read(buffer)) > 0) {
            outStream.write(buffer, 0, len);
      }
}});

server.start();
```

I then start several threads that are issuing POST requests to the server (18 KB randomly generated text). The client issuing the request times out after 3 seconds. I let this run for hours most of the time without issue. Occasionally, though, I'll hit an issue where the call to `requestIn.read(byte[])` blocks indefinitely:

```
"Timer-Driven Process Thread-12" Id=75 WAITING  on java.util.ArrayDeque@4f65949f
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.eclipse.jetty.server.HttpInput.blockForContent(HttpInput.java:570)
        at org.eclipse.jetty.server.HttpInput$1.blockForContent(HttpInput.java:1095)
        at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:310)
        at java.io.InputStream.read(InputStream.java:101)
        ... other stack trace elements specific to my application...
```

It appears that the Idle timeout does not take effect. In trying to debug this, I found that if I set a breakpoint at HttpInput.java, on line 570 (`_inputQ.wait()`) and then each time it hits, I wait a small amount of time (from 1 second to 5 seconds or so), it makes it much easier to reproduce. This is partly why I believe it to be a threading bug.

I also tried setting a breakpoint in the HttpChannelOverHttp.java class at the first line of the `onIdleTimeout(Throwable)` method to try to understand why that is not getting called. The `onIdleTimeout` method is called after 30 seconds. However, the first line checks `if (_delayedForContent) {` and `_delayedForContent` is `false` when the breakpoint hits. So it returns immediately without doing anything.

Once this issue is encountered, we also see it happening continually, quickly locking up all the threads that we make available to it.

**Comment by joakime** [comment] 2018-10-03 14:43
I don't see a `baseRequest.setHandled(true);` in your code snippet.
Do you have that in your real code?

**Comment by joakime** [comment] 2018-10-03 14:48
Also, what does the request look like?
How is the POST provided?
Does it use a `Transfer-Encoding`?  If so, what is the value?
Does it use a `Content-Encoding`?  If so, what is the value?
Is the `Content-Length` present on the Request headers?
Is it accurate to the actual size of the content you are sending?

**Comment by markap14** [comment] 2018-10-03 15:13
@joakime thanks for the response. The Content-Length is provided and is the correct size. The Content-Encoding and Transfer-Encoding headers are not set.

The POST is coming from Apache NiFi (which is also where the server is running). The POST is happening via the OkHttp client. Not sure exactly what you mean by "How is the POST provided"?

I am not calling `baseRequest.setHandled(true);` - is that something that needs to happen? What does the method do (aside from the obvious setting of _handled = true? Should this be called before or after reading from the InputStream? The JavaDocs for this method simply indicate `/* ------------------------------------------------------------ */`

**Comment by joakime** [comment] 2018-10-03 15:48
Since you are using Handlers, and not the ServletContext, the `Request.setHandled(true);` tells the Jetty server that the request has been handled by that particular handler and not to send the request to other handlers in the server handler hierarchy.

Once you know that you will be handling the request (eg: reading the Request body content via the input stream) you should call `Request.setHandled(true);`

**Comment by markap14** [comment] 2018-10-03 16:02
OK, I updated the handler so that the first line calls `baseRequest.setHandled(true);` but it made no difference - the issue still occurs.

**Comment by sbordet** [comment] 2018-10-03 16:06
@markap14 since you can reproduce it, enable DEBUG logging and attach the log here.
Also, take a [server dump](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html) when it hangs.

**Comment by markap14** [comment] 2018-10-03 16:36
[jetty.log.gz](https://github.com/eclipse/jetty.project/files/2442862/jetty.log.gz)
[jetty-dump.txt](https://github.com/eclipse/jetty.project/files/2442863/jetty-dump.txt)

**Comment by markap14** [comment] 2018-10-03 16:36
@sbordet please see attached.

**Comment by sbordet** [comment] 2018-10-03 17:12
@markap14 you are not doing in the code what you showed in the snippet above.

The server dump shows that your connections are in state `ASYNC_WAIT` which means that you have called `request.startAsync()` (this is also visible in the logs, e.g. line 536820).
For all of them the parser is waiting for 1 MiB of content, but there is no interest to read the content, as no thread is blocked on reads.

Seems to me you have coded your application in the wrong way.

The dump also shows 4 selector threads in `SELECTING`, but one of them apparently could not return the list of keys within 5 seconds, reporting `No dump keys retrieved`.
This is really strange - could be a Mac issue - it should not happen and may lead to a hung selector, so connections to that selector would be dead (old and new).
The last activity from that selector in the logs was about 1'40" before the dump (line 538458), and it was working fine.

I would start by fixing the problems in your application.
After that, if you still have problems, post further details.

**Comment by markap14** [comment] 2018-10-03 18:17
Wow @sbordet my apologies. I have taken my code and made a few variations to try to simplify it outside of the framework to make it easier to understand. That's where the snippet above came from. Within the framework, where the dump that I sent you is coming from, it does work slightly different. The above code still happens except that in the Handler, I'm calling:

```
baseRequest.setHandled(true); // Just added per @joakmie's suggestion

// validate that we are in a good state, or else just send SERVICE_UNAVAILABLE response.
if (!isReadyToHandleRequest()) {
    response.sendError(HttpServletResponse.SC_SERVICE_UNAVAILABLE);
    return;
}

               // Start Async() because we want to handle the request/response within NiFi's callbacks
                final AsyncContext async = baseRequest.startAsync();
                async.setTimeout(requestTimeout);
                final boolean added = containerQueue.offer(new HttpRequestContainer(request, response, async));

                if (added) {
                    getLogger().debug("Added Http Request to queue for {} {} from {}",
                            new Object[]{request.getMethod(), requestUri, request.getRemoteAddr()});
                } else {
                    getLogger().info("Sending back a SERVICE_UNAVAILABLE response to {}; request was {} {}",
                            new Object[]{request.getRemoteAddr(), request.getMethod(), request.getRemoteAddr()});

                    response.sendError(Status.SERVICE_UNAVAILABLE.getStatusCode());
                    response.flushBuffer();
                    async.complete();
                }
```

Here, `HttpRequestContainer` is just a simple 3-tuple to hold those objects:

```
    private static class HttpRequestContainer {

        private final HttpServletRequest request;
        private final HttpServletResponse response;
        private final AsyncContext context;

        public HttpRequestContainer(final HttpServletRequest request, final HttpServletResponse response, final AsyncContext async) {
            this.request = request;
            this.response = response;
            this.context = async;
        }

        public HttpServletRequest getRequest() {
            return request;
        }

        public HttpServletResponse getResponse() {
            return response;
        }

        public AsyncContext getContext() {
            return context;
        }
    }
```


From within the `onTrigger()` method (NiFi's callback mechanism), we do:


```
public void onTrigger(final ProcessContext context, final ProcessSession session) throws ProcessException {
       // Check if there is an outstanding HTTP Request
        HttpRequestContainer container;
        try {
            container = containerQueue.poll(2, TimeUnit.MILLISECONDS);
        } catch (final InterruptedException e1) {
            Thread.currentThread().interrupt();
            return;
        }

        // no request - nothing to do.
        if (container == null) {
            return;
        }

        // Write the contents of the HTTP Request to a FlowFile object.
        final long start = System.nanoTime();
        final HttpServletRequest request = container.getRequest();
        FlowFile flowFile = session.create();
        try (OutputStream flowFileOut = session.write(flowFile)) {
            StreamUtils.copy(request.getInputStream(), flowFileOut);
        } catch (final IOException e) {
            // There may be many reasons which can produce an IOException on the HTTP stream and in some of them, eg.
            // bad requests, the connection to the client is not closed. In order to address also these cases, we try
            // and answer with a BAD_REQUEST, which lets the client know that the request has not been correctly
            // processed and makes it aware that the connection can be closed.
            getLogger().error("Failed to receive content from HTTP Request from {} due to {}",
                    new Object[]{request.getRemoteAddr(), e});
            session.remove(flowFile);

            try {
                HttpServletResponse response = container.getResponse();
                response.sendError(Status.BAD_REQUEST.getStatusCode());
                response.flushBuffer();
                container.getContext().complete();
            } catch (final IOException ioe) {
                getLogger().warn("Failed to send HTTP response to {} due to {}",
                        new Object[]{request.getRemoteAddr(), ioe});
            }
            return;
        }

        // Generate a random UUID to use as an identifier for the HTTP Request & Response objects
        // and the AsyncContext object. Associate that UUID with the FlowFile object so that when the
        // next component in our flow encounters the FlowFile, it will be able to lookup the
        // Response object to send back a success/error status code and complete the async context.
        // Here, contextMap is similar to a ConcurrentHashMap with a max capacity.
        final String contextIdentifier = UUID.randomUUID().toString();
        flowFile = session.putAttribute(flowFile, "http.context.identifier", contextIdentifier);
        final boolean registered = contextMap.register(contextIdentifier, request, container.getResponse(), container.getContext());

        if (!registered) {
            // We failed to associate the UUID with the HTTP Request, Response & AsyncContext
            // objects. So we need to send back an error and not forward on the FlowFile.

            getLogger().warn("Received request from {} but could not process it because too many requests are already outstanding; responding with SERVICE_UNAVAILABLE",
                    new Object[]{request.getRemoteAddr()});

            try {
                container.getResponse().setStatus(Status.SERVICE_UNAVAILABLE.getStatusCode());
                container.getResponse().flushBuffer();
                container.getContext().complete();
            } catch (final Exception e) {
                getLogger().warn("Failed to respond with SERVICE_UNAVAILABLE message to {} due to {}",
                        new Object[]{request.getRemoteAddr(), e});
            }

            session.remove(flowFile);
            return;
        }

        // Transfer the FlowFile on to the next part of the flow.
        session.transfer(flowFile, REL_SUCCESS);
```

So the idea here is that this component in our system will receive the HTTP Request and call startAsync() and enqueue the Request/Response/AsyncContext.

When triggered by the NiFi framework, it will then dequeue those, write the Request content to a "FlowFile" (this is just the basic data unit in NiFi) and then transfer that FlowFile on to the next part of the system (the next component in the configured flow).

The corresponding component that then responds to the request then will receive the FlowFile and from it call getAttribute("http.context.identifier") to get that unique UUID. It will then lookup the Response object from the shared `contextMap`. It then sets the configured status code & any headers and writes the configured response to the body. Then calls `response.flushBuffer();` and `asyncContext.complete();`

Unfortunately trying to explain all that is going on here is very non-trivial. So I was trying to focus solely on the Jetty portion but in doing so, I left out the detail that we are using an AsyncContext, and that is likely very key. Sorry about that.

**Comment by sbordet** [comment] 2018-10-03 19:48
@markap14 I did not see any `read()` in your last post which, BTW, is crossing the line: it's your code and this is the Jetty Project, sorry.

If you think there is a problem in Jetty, please build a small reproducible test case.
There are a million things that can go wrong in your code (and frameworks) posted above and none seems imputable to Jetty.

**Comment by markap14** [comment] 2018-10-04 13:38
@sbordet my apologies if it came across like I was asking you to debug my (fairly complex) code. I didn't mean to ask you to do that. Rather, I posted that to try to lend context and really to prove out the point that you're making: what I'm doing is fairly complex, and it is definitely possible that I am doing something wrong.

With that being said, though, we can see from the stack trace that I included in the description that there is a call to `HttpInput.read(byte[], int, int)` that blocks indefinitely. I would make the assertion that, even if I am doing something wrong in handling the Jetty API, that the call to read() should not block indefinitely (with the assumption that I am setting the Idle Timeout on the connector to 30000). Do you agree with that? Or is there something there that I am missing, that could cause that still to occur?

I can certainly try to separate this out into a small reproducible test case.

**Comment by joakime** [comment] 2018-10-04 13:52
There's multiple timeouts in play here.
Just from your example code, I see ...

```
AsyncContext.setTimeout()
ServerConnector.setIdleTimeout()
```

Lets start with the simple stuff first.

``` java
```

**Comment by sbordet** [comment] 2018-10-04 13:54
@markap14 where do you see the blocking call to `read()`? The server dump you posted does not show it.

If you were blocking in `read()` then yes, the idle timeout mechanism should wake it up with an exception.

Can you verify that your logic does not call `startAsync()` and then just return, without reading or writing?
Perhaps some exceptional case or branch that is taken only rarely?

**Comment by markap14** [comment] 2018-10-04 17:05
@sbordet I have been successful in creating a simpler test case that still exhibits the behavior. I then performed the call to "server.dump()" and grabbed a thread dump. I will attach the test code, the server dump, thread dump, and output of running the test here.

[JettyBlockIndefinitely.java.txt](https://github.com/eclipse/jetty.project/files/2447321/JettyBlockIndefinitely.java.txt)
[test-run-output.txt](https://github.com/eclipse/jetty.project/files/2447322/test-run-output.txt)
[jetty-server-dump.txt](https://github.com/eclipse/jetty.project/files/2447326/jetty-server-dump.txt)
[jetty-thread-dump.txt](https://github.com/eclipse/jetty.project/files/2447329/jetty-thread-dump.txt)

Now, the interesting thing in the output is 2 stack traces:
```
java.lang.IllegalStateException: s=DISPATCHED i=false a=NOT_ASYNC
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:684)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:99)
	at playground.JettyBlockIndefinitely$Reader.run(JettyBlockIndefinitely.java:148)
	at java.lang.Thread.run(Thread.java:745)
```
and
```
java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:99)
	at playground.JettyBlockIndefinitely$Reader.run(JettyBlockIndefinitely.java:148)
	at java.lang.Thread.run(Thread.java:745)
```

When I run this several times, I do see the second stack trace from time to time. However, very often it does continue to accept messages and process them for quite a while after that. I'll sometimes see it 6 or 8 times before the call to read() blocks. So it's not clear to me that the Exception is causing the issue. Looking back in my server logs in the framework I can also see the stack trace from time to time, but again it isn't clear that this is what causes it to stop, since it generally keeps processing after it.

**Comment by joakime** [comment] 2018-10-04 17:09
Added your code to a gist at https://gist.github.com/joakime/0b86b6c2e7eb68e06606ce693ef6934b
Tip: gists can be cloned (like any other git repo), plus references to the code (like line numbers) can be made easier.

**Comment by markap14** [comment] 2018-10-04 17:09
And just a quick explanation of what I'm doing in that .java file, in case I'm just doing something completely stupid without realizing it :)

Main method:
Create the Jetty Server. Set a handler that simply calls `Request.setHandled(true);` then starts async and sets timeout & puts the `Request`, `Response`, and `AsyncContext` on a queue. Start 2 more threads.

Reader Thread:
Just get the Request/Response/AsyncContext, consume the body of the Request, then send back a 200 response and complete the async context.

Sleep Thread:
This only exists so that I can easily set a breakpoint in a debugger and call `Server.dump()` when I see the condition occur... there are probably much easier ways to do this but hey...

And the only reason that I use a separate Reader Thread and start async is to mimic my actual environment that I'm trying to run this in.

**Comment by markap14** [comment] 2018-10-04 17:12
@joakime good call. I renamed to .txt so i could attach it here... didn't even cross my mind to create a gist. Thanks!

**Comment by joakime** [comment] 2018-10-04 17:21
So we have a raw Handler, (no ServletContext, no ServletContextHandler, no WebAppContext).
It's creating an AsyncContext (a servlet concept) via `.startAsync()`, adding the request + response + AsyncContext to a  a `HttpRequestContainer ` object and offering it into an object queue.
At this point, the request handling has completed for this Request (as you exited the raw Handler).

Meanwhile, a previously started `Reader` thread is polling the queue, popping out the `HttpRequestContainer` and reading the entire `Request.inputStream`, followed by a `Response.setStatus(200)` and `Response.flushBuffer()` then finally the `AsyncContext.complete()`.

**Comment by joakime** [comment] 2018-10-04 17:31
@gregw @sbordet does `AsyncContext` work outside of a valid `ServletContext`?

**Comment by sbordet** [comment] 2018-10-04 17:59
@markap14 your code contains 2 bugs and 2 mistakes.

The first bug is that when you read you must check for `>=0`, not just `>0` (https://gist.github.com/joakime/0b86b6c2e7eb68e06606ce693ef6934b#file-jettyblockindefinitely-java-L140).

The second bug is that if an exception is thrown by `read()` (as it happens when it idle times out), then you just ignore it and go to the next request. Instead, you should write an error response and complete the `AsyncContext`.

The first mistake is setting the `AsyncContext.timeout` equal to the idle timeout.
This creates a race between the idle timeout mechanism and the `AsyncContext` timeout mechanism, which causes uncertainty because sometime one will win some other time the other will win.

The second mistake is the expression `Math.max(http.getIdleTimeout(), timeout)` that does not set the timeout you want: the default connector timeout is 30s, yours is 20s, and the expression yields 30s (the default timeout, not yours).

I recommend you fix the bugs and the mistakes.

Also, be sure you understand what happens when the `AsyncContext.timeout` expires.
The container will generate an error response on your behalf that may run concurrently with a response you are generating.

I tried your example with the fixes and works fine for me.

@joakime yes.

**Comment by markap14** [comment] 2018-10-04 19:29
@joakime @sbordet first let me say thank you for continuing to take the time to look into this!

re: the first bug mentioned - it probably is best to check `>=0` as opposed to `>0`, though both really are correct, as `InputStream.read(byte[])` cannot return 0 - it must either return -1 signifying end of stream or block until data is available. But I suppose checking `>=0` is safer, as the latter could result in an infinite loop if the `InputStream` does not adhere to the contract. And you are right - the error handling around `read()` in this simple example is not there and should be.

You also make a good point around `AsyncContext.timeout` being the same as the Idle Timeout. The `Math.max(http.getIdleTimeout(), timeout)` is also silly, as it was a copy-paste, where the code it was copied from had a configurable value for `timeout`.

Unfortunately, though, after making all 4 mods suggested here, though, I see the same result.

In my case, I've run this in 3 different environments. The first environment is a Linux test server. This has run for a few months, and I've seen the blocking read happen once or twice (not sure if the second time was the same issue or not, as I restarted without a thread dump or gathering many details).

The second environment is a Windows Server environment. This is the most problematic environment, where every time the clients hit it with a large number of requests (there are up to 30 clients, which may buffer data and unload at large rates), this starts to happen. The unfortunate thing is that this is not a machine that I have access to - is a client's machine that I have been trouble-shooting. All works fine under normal/low load but this happens consistently when large loads occur.

The third environment is my Macbook. On my macbook, i've only ever seen this once "in normal mode". During debugging, however, I found that if i set a breakpoint on line 570 of HttpInput where it calls `_inputQ.wait()` and press F6 in my IDE to step over this line, then F8 to continue Running, then I can do this maybe 20-50 times before this condition occurs. I did this to understand when exactly the blocking was occurring. But I found that it triggers the behavior pretty quickly. While this doesn't change the code being executed, it certainly changes the timing of the execution. And yes - this is absolutely a hack. No argument there. But it does result in different timing, while executing the exact same code (similar to what happens when a sudden heavy load is encountered) which can help to trigger threading-related issues. The fact that it triggers this behavior is what sent me down the whole path of thinking that this could perhaps be a threading issue.

**Comment by sbordet** [comment] 2018-10-04 19:38
> Unfortunately, though, after making all 4 mods suggested here, though, I see the same result.

What result do you see exactly?
And what do you expect instead?

And you never told how you load this server with the client; 1 connection? N connections?

Can we get a fully reproducible case then? The client is missing.

**Comment by joakime** [comment] 2018-10-04 20:03
> The second environment is a Windows Server environment. This is the most problematic environment, where every time the clients hit it with a large number of requests (there are up to 30 clients, which may buffer data and unload at large rates), this starts to happen. The unfortunate thing is that this is not a machine that I have access to - is a client's machine that I have been trouble-shooting. All works fine under normal/low load but this happens consistently when large loads occur.

When this occurs on Windows, do you see a high CPU usage for the Java process?
If so, you've hit a JVM Bug with NIO on Windows.
See #2205

**Comment by markap14** [comment] 2018-10-04 20:06
> What result do you see exactly?
The result that I see is that a call to `HttpInput.read(byte[])` never returns.

> And what do you expect instead?
I expect to see content returned if any is available or otherwise an Exception being thrown when the timeout is exceeded.

> And you never told how you load this server with the client; 1 connection? N connections?

I generally have been using NiFi's PostHTTP processor (https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PostHTTP.java) to issue the requests. Have also reproduced following same behavior using the InvokeHTTP processor. The former is using Apache HTTP library while the latter uses the OkHttp client library.

In both cases, they issue HTTP POST requests consisting of randomly generated binary data. They set `Content-Length` header rather than using chunked encoding (with the appropriate length). Do not specify `Content-Encoding` or `Transfer-Encoding` headers. I run the test using 8 concurrent threads/connections and a timeout of 3 seconds on the client side.

In the case of the Windows Server environment, the requests were sent from up to 30 different client machines, each using a single connection (I believe only a single connection), from Oracle's XML Gateway (https://docs.oracle.com/cd/B12166_01/web/B12099_01/adx17gat.htm).

**Comment by markap14** [comment] 2018-10-04 20:08
@joakime no, we have never seen the CPU spike above 8% utilization, generally shows a CPU Load of something like 4-5% when I've investigated.

**Comment by joakime** [comment] 2019-04-30 21:44
Closing due to lack of updates

**Closed by joakime** 2019-04-30 21:44 UTC
Labels: More Info Required, Unable To Replicate, Windows
