### ISSUE TITLE
`IllegalStateException`: Form with too many keys [1001 > 1000] on Jetty 12.x (regression from 10.x)

### ISSUE THREAD

**Issue by basil** [eclipse/jetty.project#11959] opened 2024-06-25 22:49 UTC
**Jetty version(s)**
Problem occurs on Jetty 12.0.10.
Problem does _not_ occur on Jetty 10.0.20.

**Jetty Environment**
Problem occurs on Jetty 12.0.10 (both EE 8 and EE 9).
Problem does _not_ occur on Jetty 10.0.20 (EE 8).

**Java version/vendor** `(use: java -version)`
```
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Ubuntu-122.04.1, mixed mode, sharing)
```

**OS type/version**
Ubuntu 22.04.4 LTS x86_64

**Description**
While testing the upgrade from Jetty 10.0.20 to 12.0.10, one of our testers reported [JENKINS-73285](https://issues.jenkins.io/browse/JENKINS-73285). To summarize, the Jenkins UI POSTs `application/x-www-form-urlencoded` forms with over 1,000 total key-value pairs but only a few hundred unique keys. In Jetty 10.x, this worked fine; but in Jetty 12.x, this results in an `IllegalStateException` "Form with too many keys [1001 > 1000]".

**How to reproduce?**

https://github.com/jenkinsci/winstone/pull/393 adds an automated test to Winstone, the Jetty wrapper used by Jenkins. On the client side, the test is as follows:

```java
String queryString = "foo=bar" + "&foo=bar".repeat(1000);
HttpRequest request = HttpRequest.newBuilder(new URI("http://127.0.0.2:" + port + "/AcceptFormServlet"))
        .header("Content-Type", "application/x-www-form-urlencoded")
        .POST(HttpRequest.BodyPublishers.ofString(queryString))
        .build();
HttpResponse<String> response = HttpClient.newHttpClient().send(request, HttpResponse.BodyHandlers.ofString());
assertEquals(HttpURLConnection.HTTP_OK, response.statusCode());
```

On the server side, the test merely calls `HttpServletRequest#getParameterNames`. On Jetty 10, this succeeds; on Jetty 12, this throws the exception described above.

**Comment by joakime** [comment] 2024-06-25 23:23
``` java
String queryString = "foo=bar" + "&foo=bar".repeat(1000);
```

That looks like 1001 keys on the URL query section to me. (what that limitation exists to limit, not the number of keys in the resulting HashMap)

The original introduction of that limitation is due to a Java Hash collision DoS attack.

IMO, the fact that it doesn't trigger in Jetty 10, would point to a bug in Jetty 10, not Jetty 12.
Yup, just took a look, in Jetty 10, the maxFormKeys and maxFormContentSize limits are not applied to query section (they are applied to x-form-urlencoded and multipart-form request body contents)
In Jetty 10, the protection is provided by the HttpConfiguration.setRequestHeaderSize() values instead.

In Jetty 12, the query section also applies the limits on both maxFormKeys and maxFormContentSize.
Confirmed, a bug in Jetty 10, fixed in Jetty 12.

**Closed as completed** 2024-06-26 03:09 UTC
Labels: Bug
