### ISSUE TITLE
Configuration jetty.httpConfig.uriCompliance doesn't work

### ISSUE THREAD

**Issue by wodeidaiga** [eclipse/jetty.project#11565] opened 2024-03-25 10:18 UTC
**Jetty version(s)**

12.0.6
**Jetty Environment**

ee10
**Java version/vendor** `(use: java -version)`
openjdk 17
**OS type/version**
ubuntu 22.04
**Description**

We have some legacy urls in our client which has a //  empty segment in the request URI. We try to by pass the 400 bad request message by configuring`<Set name="uriCompliance"><Call class="org.eclipse.jetty.http.UriCompliance" name="from"><Arg><Property name="jetty.httpConfig.uriCompliance" default="LEGACY"/></Arg></Call></Set>`
in jetty.xml, but the exception is still thrown because when trying to create the  
protected ServletApiRequest newServletApiRequest()
    {
        if (getHttpURI().hasViolations() && !getServletChannel().getServletContextHandler().getServletHandler().isDecodeAmbiguousURIs())
        {
            // TODO we should check if current compliance mode allows all the violations?

            for (UriCompliance.Violation violation : getHttpURI().getViolations())
            {
                if (UriCompliance.AMBIGUOUS_VIOLATIONS.contains(violation))
                    return new ServletApiRequest.AmbiguousURI(this);
            }
        }

        return new ServletApiRequest(this);
    }
It always checks if there's a violation.
**How to reproduce?**
Access /webapp//index.html

**Comment by joakime** [comment] 2024-03-25 12:10
Duplicate of #11448

**Comment by joakime** [comment] 2024-03-25 12:11
Upgrade to Jetty 12.0.7, this code has already been fixed/addressed.

**Closed as not planned by joakime** 2024-03-25 12:10 UTC
Labels: Bug
