### ISSUE TITLE
Provide a more specific exception when exceeding the filesize during uploads

### ISSUE THREAD

**Issue by ghillert** [eclipse/jetty.project#1306] opened 2017-02-07 05:14 UTC
When uploading large files, users may exceed the permissible file-size. In that case, Jetty throws an
`IllegalStateException` with a message like the following: 

`Multipart Mime part pictureFile exceeds max filesize`

I thing it would be desirable for some users to be able to handle that error condition, e.g. catch the exception and ultimately show a page to users that the file-size was too large.

However, the `IllegalStateException` is too generic. It would be nice if there was a more specific exception I could catch. In Tomcat you have e.g. `Sizelimitexceededexception` (Request size) and `FileSizeLimitExceededException`.

**Comment by janbartel** [comment] 2017-02-07 08:14
@ghillert the problem is that the parsing is done before any application code runs.  If you're talking about the IllegalStateException from a call to Request.getPart/getParts() then the servlet spec mandates that we have to throw that exception. Of course, user code can always catch that exception and do something ....

**Comment by janbartel** [comment] 2017-02-14 23:38
@ghillert  I think you should open an issue on the servlet spec group for more specific error handling with multipart requests. See https://java.net/jira/browse/SERVLET_SPEC/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel.

Closing for now.

**Closed by janbartel** 2017-02-14 23:38 UTC
