### ISSUE TITLE
Failing while building all modules of jetty-project using mvn clean install

### ISSUE THREAD

**Issue by pranopowar** [eclipse/jetty.project#11666] opened 2024-04-18 10:51 UTC
Package artifact id:  jetty-project
 
source code url: https://github.com/jetty/jetty.project
 
Issue Description: Failing while building all modules of jetty-project using mvn clean install
 
JDK Version: 21
 
Build CMD: mvn clean install
 
MVN Version: 3.9.6
 
Error Log:
 
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.12 s -- in org.eclipse.jetty.server.ServerConnectorTimeoutTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ContextHandlerTest.afterAll:134->ensureWritable:791 expected: <true> but was: <false>
[ERROR]   ContextHandlerTest.okTempDirs:815 expected: <true> but was: <false>
[ERROR] Errors:
[ERROR]   ServerConnectorCloseTest>ConnectorCloseTestBase.testCloseBetweenChunks:164 ┬╗ Socket Connection reset by peer
[INFO]
[ERROR] Tests run: 1580, Failures: 2, Errors: 1, Skipped: 47

 
attach
[Failed_jdk_21.txt](https://github.com/jetty/jetty.project/files/15023709/Failed_jdk_21.txt)
ment: build log attached (jdk 21)
 
OS: windows 10

[Failed_jdk_21.txt](https://github.com/jetty/jetty.project/files/15023711/Failed_jdk_21.txt)

**Comment by joakime** [comment] 2024-04-18 12:35
Jetty 9.x is now at End of Community Support.

* #7958 
* #10485 

You should be using Jetty 12 at this point in time.

Closing, duplicate of #11545

**Closed as not planned by joakime** 2024-04-18 12:35 UTC
Labels: Bug

**Comment by pranopowar** [comment] 2024-04-19 10:01
> Jetty 9.x is now at End of Community Support.
> 
> * [End of Community Support for Jetty 9.x - June 2022 #7958](https://github.com/jetty/jetty.project/issues/7958)
> * [End of Community Support for Jetty 10 / Jetty 11 - January 2024 #10485](https://github.com/jetty/jetty.project/issues/10485)
> 
> You should be using Jetty 12 at this point in time.
> 
> Closing, duplicate of #11545

Hi, I'm Building jetty 12 latest code only. I have taken Source code using this url ( https://github.com/jetty/jetty.project/tree/jetty-12.0.x ). If I am not wrong, Please confirm , you are suggesting to use latest jetty 12.0.X code(https://github.com/jetty/jetty.project/tree/jetty-12.0.x).

**Comment by joakime** [comment] 2024-04-19 13:46
Yes, that is the branch for for Jetty 12 (and is also the default branch of this git repository)

**Comment by shivsrivastava** [comment] 2024-04-22 07:25
> Yes, that is the branch for for Jetty 12 (and is also the default branch of this git repository)

Hi ,

I am also facing same issue in 12.x also.  Can we build this 12.x package with test cases success? 
I am also using mvn clean install and getting same exception as above mentioned. 
Please help and confirm. I have also attached log.
here are the details-

JDK Version used: 21

Build CMD: mvn clean install

MVN Version: 3.9.6

Operating system - Windows 10

Error in log :

Error Log:

[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.12 s -- in org.eclipse.jetty.server.ServerConnectorTimeoutTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] ContextHandlerTest.afterAll:134->ensureWritable:791 expected: but was:
[ERROR] ContextHandlerTest.okTempDirs:815 expected: but was:
[ERROR] Errors:
[ERROR] ServerConnectorCloseTest>ConnectorCloseTestBase.testCloseBetweenChunks:164 ┬╗ Socket Connection reset by peer
[INFO]
[ERROR] Tests run: 1580, Failures: 2, Errors: 1, Skipped: 47
[Log_failed_jdk_21_jetty_12.txt](https://github.com/jetty/jetty.project/files/15103227/Log_failed_jdk_21_jetty_12.txt)

**Comment by shivsrivastava** [comment] 2024-05-03 03:31
> Yes, that is the branch for for Jetty 12 (and is also the default branch of this git repository)

Please update on it.

> > Yes, that is the branch for for Jetty 12 (and is also the default branch of this git repository)
> 
> Hi ,
> 
> I am also facing same issue in 12.x also. Can we build this 12.x package with test cases success? I am also using mvn clean install and getting same exception as above mentioned. Please help and confirm. I have also attached log. here are the details-
> 
> JDK Version used: 21
> 
> Build CMD: mvn clean install
> 
> MVN Version: 3.9.6
> 
> Operating system - Windows 10
> 
> Error in log :
> 
> Error Log:
> 
> [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.12 s -- in org.eclipse.jetty.server.ServerConnectorTimeoutTest [INFO] [INFO] Results: [INFO] [ERROR] Failures: [ERROR] ContextHandlerTest.afterAll:134->ensureWritable:791 expected: but was: [ERROR] ContextHandlerTest.okTempDirs:815 expected: but was: [ERROR] Errors: [ERROR] ServerConnectorCloseTest>ConnectorCloseTestBase.testCloseBetweenChunks:164 ┬╗ Socket Connection reset by peer [INFO] [ERROR] Tests run: 1580, Failures: 2, Errors: 1, Skipped: 47 [Log_failed_jdk_21_jetty_12.txt](https://github.com/jetty/jetty.project/files/15103227/Log_failed_jdk_21_jetty_12.txt)

Please update on it.
