### ISSUE TITLE
Upgrade to eclipse licence 2.0

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4426] opened 2019-12-16 20:42 UTC
We need to upgrade to EPL-2.0.  This should be done immediately for jetty-10... However I'm not sure if we should do a licence change in a dot release of jetty 9.4.x ?

**Comment by sbordet** [comment] 2020-01-09 19:06
Duplicate of #3578.

**Closed as completed by sbordet** 2020-01-09 19:06 UTC
Labels: High Priority, Task
