### ISSUE TITLE
TLS close_notify() is not guaranteed

### ISSUE THREAD

**Issue by hwasin** [eclipse/jetty.project#3481] opened 2019-03-21 15:34 UTC
Hi. I've caught javax.net.ssl.SSLException: SSL peer shut down incorrectly exception on a client side. After debug enabled on jetty side i found out that Jetty failed to flush TLS close_notify(). I think this might be caused by socket sender buffer being full. I also read jetty source code and for some reason flushing close_notify() does not happen even it is commented in SSLConnection.flush() method:

```

switch (wrapResultStatus) {
        case CLOSED:
        // The SSL engine has close, but there may be close handshake that needs to be written
        if (BufferUtil.hasContent(_encryptedOutput)) {
           _cannotAcceptMoreAppDataToFlush = true;
           getEndPoint().flush(_encryptedOutput);
           getEndPoint().shutdownOutput();
           // If we failed to flush the close handshake then we will just pretend that
           // the write has progressed normally and let a subsequent call to flush
           // (or WriteFlusher#onIncompleteFlushed) to finish writing the close handshake.
           // The caller will find out about the close on a subsequent flush or fill.
           if (BufferUtil.hasContent(_encryptedOutput))
               return false;
           }
```

false returned value is not checked by caller:

```
else if (!oshut) {
           try {
               _sslEngine.closeOutbound();
               flush(BufferUtil.EMPTY_BUFFER); // Send close handshake // <--- returned value is not checked!
               SslConnection.this.fillInterested(); // seek reply FIN or RST or close handshake
```

Following WA for CLOSED case helps:

```
while(!getEndPoint().flush(_encryptedOutput) && i < 10) {
               try {
                   Thread.sleep(10);
               } catch (InterruptedException e) {
                   LOG.ignore(e);
               }
               i++;
}
getEndPoint().shutdownOutput();
```

**Comment by sbordet** [comment] 2019-03-21 15:48
> I found out that Jetty failed to flush TLS close_notify()

"failed" how? An exception?
How do you know it failed?

Looping 10 times with blocking sleeps is not something we want to do.
We try our best to write the close_notify, and if we fail that, there is not much else that we can do.

**Comment by hwasin** [comment] 2019-03-21 16:04
> How do you know it failed?

I run jetty server in debug mode and got following debug output after flush():

```
[qtp6673112-233 - /service/bl] ChannelEndPoint - flushed 38 SelectChannelEndPoint@20323228{/[o:4|5b41659bb412]:6186<->10210,Open,in,out,-,-,0/200000,SslConnection}{io=0,kio=0,kro=1}
[qtp6673112-233 - /service/bl] ChannelEndPoint - oshut SelectChannelEndPoint@20323228{/[o:4|5b41659bb412]:6186<->10210,Open,in,out,-,-,0/200000,SslConnection}{io=0,kio=0,kro=1}
[qtp6673112-233 - /service/bl] AbstractConnection - fillInterested SslConnection@6273c55{NEED_UNWRAP,eio=-1/15,di=-1} -> HttpConnection@37a26354{IDLE}
[qtp6673112-233 - /service/bl] AbstractConnection - IDLE-->FILL_INTERESTED SslConnection@6273c55{NEED_UNWRAP,eio=-1/15,di=-1} -> HttpConnection@37a26354{IDLE}
```

**Comment by sbordet** [comment] 2019-03-21 16:38
@hwasin those lines show that the close_notify has been written successfully.

**Comment by hwasin** [comment] 2019-03-21 17:01
Please check this line:

```
[qtp6673112-233 - /service/bl] AbstractConnection - fillInterested SslConnection@6273c55{NEED_UNWRAP,eio=-1/15,di=-1} -> HttpConnection@37a26354{IDLE}
```

and these source code:

```
else if (!oshut) {
           try {
               _sslEngine.closeOutbound();
               flush(BufferUtil.EMPTY_BUFFER); // Send close handshake // <--- returned value is not checked!
               SslConnection.this.fillInterested(); // seek reply FIN or RST or close handshake
```

If i am not wrong this line is debug-printed after flush(BufferUtil.EMPTY_BUFFER) inside SslConnection.this.fillInterested(); and it shows that there still 15 bytes unflushed

**Comment by sbordet** [comment] 2019-03-21 17:12
Okay, so there were 38+15 bytes generated, and only 38 were written.
As I said, we can't loop as you suggest, and we have already tried to write but the connection is congested, so trying again is probably going to be a waste of time.

If the other peer does not send any data, we are going to idle timeout this connection and eventually close it.

We cannot really close it immediately because the other peer may just be slow, and will eventually read, decongest the connection and so we will be able to write the last 15 bytes.
Or maybe not, because we don't set up for write interest.

@gregw opinions?

**Comment by hwasin** [comment] 2019-03-21 17:18
> As I said, we can't loop as you suggest

of course. This is just WA to let you understand the issue more clearly

**Comment by hwasin** [comment] 2019-03-25 11:37
Hello @sbordet, @gregw. Any updates?

**Comment by gregw** [comment] 2019-03-25 21:32
@sbordet well we do generally register for write interest in onIncompleteFlush.    Perhaps we are not doing that in this case? @hwasin can you give use some test code that reproduces so we can examine more clearly?

**Comment by gregw** [comment] 2019-03-25 21:40
@sbordet the `doShutdownOutput` method includes the following code:
```java
                if (flush)
                    flush(BufferUtil.EMPTY_BUFFER); // Send the TLS close message.
                if (close)
                    getEndPoint().close();
                else
                    ensureFillInterested();
```

So if the flush does not complete, we can continue on to close anyway!
Apparently we can be fill interested after this method, so perhaps we can also be write interested? 

@hwasin Note that a lot of implementation don't send the close handshake anyway, so it should not be a fatal thing... but obviously it would be better to send it if we can.

**Comment by gregw** [comment] 2019-03-26 04:29
@hwasin Have a look at branch https://github.com/eclipse/jetty.project/tree/jetty-9.4.x-3481-TLS-Close with commit 495a62f08d6fba9eb027d946461325ca48804a65  Any chance you could test that?

**Comment by hwasin** [comment] 2019-03-26 11:29
@gregw

> can you give use some test code that reproduces so we can examine more clearly?

I am working on this right now to make it least environment dependent. I will share test source code as soon as i finish it. (Right now i can share decrypted tcpdump of this test: [tcpdump.tar.gz](https://github.com/eclipse/jetty.project/files/3007876/tcpdump.tar.gz)


> Note that a lot of implementation don't send the close handshake anyway, so it should not be a fatal thing

My client notifies server with Level: fatal, Description: Unexpected Message not warning. I am using jdk1.7_80 

> Have a look at branch https://github.com/eclipse/jetty.project/tree/jetty-9.4.x-3481-TLS-Close with commit 495a62f Any chance you could test that?

Thanks. Sure i will test it.

**Comment by hwasin** [comment] 2019-03-26 12:39
> Note that a lot of implementation don't send the close handshake anyway, so it should not be a fatal thing... but obviously it would be better to send it if we can

I agree with you. I've performed additional tests and found out that SSLException:"SSL peer shut down incorrectly" is thrown for me when both close_nofity() and TCP FIN are failed to flush. If TCP FIN is received by client but not close_notify() then my application works fine.

**Comment by hwasin** [comment] 2019-03-27 11:46
@gregw Your patch didnt help but i found why this might happen:

After first failed flush i am getting NEED_UNWRAP SSLEngine handshake status in other 15 attempts, but expected NEED_WRAP. This happens because releaseEncryptedOutputBuffer() is invoked in finally section of flush method for first attempt:

```
                    finally
                    {
                        releaseEncryptedOutputBuffer();
                        if (LOG.isDebugEnabled())
                            LOG.debug("<flush {} {}", result, SslConnection.this);
                    }
                }
```

**Comment by hwasin** [comment] 2019-03-27 11:58
Your patch do not help: After first failed flush i am getting NEED_UNWRAP SSLEngine handshake status in other 15 attempts, but as i understand NEED_WRAP is the one expected.

**Comment by joakime** [comment] 2019-03-27 20:59
I wonder if this behavior is _Yet Another Microsoft Windows Specific Networking Quirk_?

**Comment by gregw** [comment] 2019-03-27 21:00
@hwasin thanks for trying that one... yes the code expects that the generated code has already been flushed, so it does not flush again.  
The current version of that branch now has a work around that as it directly flushes the encrypted buffer and I have a unit test that reproduced the problem and appears to confirm that it is now fixed... can you try:  
d13b0d7

**Comment by gregw** [comment] 2019-03-27 22:36
@joakime no it is a real issue.  when closing we may generate a close handshake but be unable to flush it.  If we don't flush it, then we may just let the connection hang.  We need to either make a better effort to flush or always close.  I have a test harness that reproduces the problem and the current fix is to look at the close state to decide if we try to write or just close anyway.

**Closed** 2019-04-05 06:20 UTC
