### ISSUE TITLE
ClassNotFoundException: org.apache.geronimo.components.jaspi.AuthConfigFactoryImpl

### ISSUE THREAD

**Issue by rijkr** [eclipse/jetty.project#4746] opened 2020-04-02 15:19 UTC
**Jetty version**

9.4.25.v20191220 and 9.4.27.v20200227

**Java version**

openjdk version "1.8.0_242"

**OS type/version**

Ubuntu 16.04-b08

**Description**

I use embedded Jetty for several years now and upgrade regularly without any problems. But now suddenly, when upgrading from 9.4.22.v20191022 to 9.4.25.v20191220 (or 9.4.27.v20200227) this exception occurs at startup:

```
2020-03-14 19:36:09,289  WARN WebAppContext:533 - Failed startup of context o.e.j.w.WebAppContext@129b4fe2{savapage-server,/,file:///path-to-project/src/main/webapp/,UNAVAILABLE}{src/main/webapp} [main]
java.lang.SecurityException: AuthConfigFactory error: java.lang.ClassNotFoundException: org.apache.geronimo.components.jaspi.AuthConfigFactoryImpl
	at javax.security.auth.message.config.AuthConfigFactory.getFactory(AuthConfigFactory.java:75)
	at org.eclipse.jetty.security.jaspi.JaspiAuthenticatorFactory.getAuthenticator(JaspiAuthenticatorFactory.java:90)
	at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:382)
	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	...
```

	
And server.dumpStdErr() ends with a NullPointerException ...

```
Server@1e4d3ce5{STARTED}[9.4.25.v20191220] - STARTED
+= QueuedThreadPool[jetty-threadpool]@3c0be339{STARTED,20<=20<=200,i=14,r=4,q=0}[ReservedThreadExecutor@3918c187{s=0/4,p=0}] - STARTED
|  += ReservedThreadExecutor@3918c187{s=0/4,p=0} - STARTED...

...

+= HandlerList@366ef90e{STARTED} - STARTED
|  += o.e.j.w.WebAppContext@5b444398{savapage-server,/,file:///path-to-project/src/main/webapp/,UNAVAILABLE}{src/main/webapp} - STARTED
|     += org.eclipse.jetty.server.session.SessionHandler882471736==dftMaxIdleSec=1200 - FAILED
|     |  += ConstraintSecurityHandler@33e01298{FAILED} - FAILED
|     |  |  +- knownAuthenticatorFactories size=2
|     |  |  |  +> org.eclipse.jetty.security.jaspi.JaspiAuthenticatorFactory@31e75d13
|     |  |  |  +> org.eclipse.jetty.security.DefaultAuthenticatorFactory@a5b0b86
|     |  |  += ServletHandler@4b3c354a{STOPPED} - STOPPED
|     |  |  |  +> listeners ServletHandler@4b3c354a{STOPPED} size=4
|     |  |  |  |  +> ListenerHolder@78fb9a67{STARTED}: org.eclipse.jetty.servlet.listener.ELContextCleaner - STARTED
|     |  |  |  |  +> ListenerHolder@73ff4fae{STARTED}: org.eclipse.jetty.servlet.listener.IntrospectorCleaner - STARTED
|     |  |  |  |  +> ListenerHolder@21aa6d6c{STARTED}: org.savapage.server.SpContextListener - STARTED
|     |  |  |  |  +> ListenerHolder@b968a76{STARTED}: org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer$ContextDestroyListener - STARTED
|     |  |  |  +> filters ServletHandler@4b3c354a{STOPPED} size=3
|     |  |  |  |  +> cross-origin@2f9a01c1==org.eclipse.jetty.servlets.CrossOriginFilter,inst=false,async=true - STOPPED
|     |  |  |  |  |  +> null
|     |  |  |  |  +> wicket.savapage@2611b9a3==org.apache.wicket.protocol.http.WicketFilter,inst=false,async=true - STOPPED
|     |  |  |  |  |  +> null
|     |  |  |  |  |  +> initParams size=1
|     |  |  |  |  |     +> applicationClassName=org.savapage.server.WebApp
|     |  |  |  |  +> Jetty_WebSocketUpgradeFilter@5bd82fed==org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter,inst=false,async=true - STOPPED
|     |  |  |  |     +> class org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|     |  |  |  |     +> initParams size=1
|     |  |  |  |        +> contextAttributeKey=org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|     |  |  |  +> filterMappings ServletHandler@4b3c354a{STOPPED} size=3
|     |  |  |  |  +> 2020-03-14 12:23:45,613 ERROR WebServer:967 -  [main]
java.lang.NullPointerException
	at org.eclipse.jetty.servlet.FilterMapping.appliesTo(FilterMapping.java:157)
	at org.eclipse.jetty.servlet.FilterMapping.appliesTo(FilterMapping.java:163)
...
```

Any idea what could be wrong?

--
Best regards,
Rijk Ravestein

**Comment by joakime** [comment] 2020-04-02 15:35
Duplicate of #4621, fixed in PR #4710 (will be available in future 9.4.28 release)

**Comment by lachlan-roberts** [comment] 2020-04-07 06:17
@joakime I think this is actually slightly different and won't be fixed by PR #4710.

In this case there is no `ServiceConfigurationError` discovering the `JaspiAuthenticatorFactory` with the `ServiceLoader`. Instead there is a `ClassNotFoundException` when the authenticator factory is used.

**Comment by janbartel** [comment] 2020-06-23 08:56
@rijkr with regard to the server.dump() error: how are you adding filters and mappings? Are you using the jetty api? Or are you using the servlet api (via  a ServletContextInitializer?)? Or are you using an xml file?

With regard to the CNFE, what version of geronimo-jaspi are you using, and is it on the server classpath or the webapp classpath? Have you tweaked any of the system/server class settings?

**Comment by rijkr** [comment] 2020-06-23 11:05
@janbartel There is no geronimo-jaspi in the dependency hierarchy of my pom.xml. It has a dependency on jetty-all, that has a dependency on jetty-jaspi though (both 9.4.30.v20200611), and jetty-jaspi has a ...
```
    <dependency>
      <groupId>org.apache.geronimo.components</groupId>
      <artifactId>geronimo-jaspi</artifactId>
      <version>2.0.0</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.geronimo.specs</groupId>
          <artifactId>geronimo-jaspic_1.0_spec</artifactId>
        </exclusion>
      </exclusions>
      <scope>test</scope>
    </dependency>
```
But since it has `<scope>test</scope>` the geronimo-jaspi component is not used to build and run the project. As a test I included the geronimo-jaspi dependency in my own pom.xml, and removed the test scope. This solved the error.

Can I conclude that the geronimo-jaspi test scope must be removed from the jetty-jaspi pom.xml?

**Comment by janbartel** [comment] 2020-06-23 12:42
@rijkr  in 9.4.23 via #4237 we added a services file for jaspi, which means that its AuthenticationFactory is now being discovered. As you don't actually have the jars present to satisfy that class, you're getting the CNFE. If I were you, as you're not using jaspi at all, I would exclude it from jetty-all. 

And any info on the filter mappings?

**Comment by rijkr** [comment] 2020-06-23 17:51
@janbartel Filters and mappings are configured in web.xml and additionally programmed with @WebServlet annotations. There is also a @ WebListener.

No explicit usage of ServletContextInitializer, but may be it is used under the hood by 3rd party components in web.xml (org.cometd.server.CometDServlet, org.apache.wicket.protocol.http.WicketFilter)?

Jetty API is used to add a REST servlet to org.eclipse.jetty.webapp.WebAppContext:

```
final ServletHolder jerseyServlet = context.addServlet(
                org.glassfish.jersey.servlet.ServletContainer.class,
                RestApplication.SERVLET_URL_PATTERN);
jerseyServlet.setInitParameter("javax.ws.rs.Application",
                RestApplication.class.getCanonicalName());
```

Basic Authentication is implemented for this REST servlet with an instance of type javax.ws.rs.container.ContainerRequestFilter.

Indeed, exclusion of jetty-jaspi from jetty-all solves the problem:

```
<dependency>
    <groupId>org.eclipse.jetty.aggregate</groupId>
    <artifactId>jetty-all</artifactId>
    <version>${jetty.version}</version>
    <exclusions>
        <exclusion>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-jaspi</artifactId>
        </exclusion>
    </exclusions>
    <type>pom</type>
</dependency>

```
Is this the solution or just a workaround?

**Comment by janbartel** [comment] 2020-06-24 08:29
@rijkr I think it is always best to have only the minimum necessary. The other alternative would be to use the jetty-bom for version management, and just include only those artifacts you really need.

For the filter problem, if you remove the jetty-jaspi dependency, did that resolve the filter issue, or is it still a problem? If it's still a problem, are there any log warnings apart from the server.dump() NPE? Can you post the filters and mappings from web.xml and from any `@WebFilters` and programmatic sources?

**Comment by rijkr** [comment] 2020-06-24 09:11
@janbartel The exclusion of the jetty-jaspi dependency did solve the problem. If this is the way to go, that's fine. Thanks for your help! If you are interested in details, server code of my project can be found at this [Gitlab repository](https://gitlab.com/savapage/savapage-server). Shortcuts: [web.xml](https://gitlab.com/savapage/savapage-server/-/blob/develop/src/main/webapp/WEB-INF/web.xml) , [WebServer.java](https://gitlab.com/savapage/savapage-server/-/blob/develop/src/main/java/org/savapage/server/WebServer.java)

**Comment by janbartel** [comment] 2020-06-24 09:41
Thanks @rijkr, I will close this issue now.

**Closed as completed by janbartel** 2020-06-24 09:41 UTC

**Comment by eyal20** [comment] 2022-08-21 13:08
Hello,
I'm having exactly the same issue after upgrading from 9.4.40 to 10.0.11
and I get it also when trying to upgrade to 9.4.48
I'm not really sure if it’s possible to remove jetty-jaspi in my case so I prefer to leave it there.
My question is how to avoid this exception without removing this lib

Thanks!
  Eyal

**Comment by lachlan-roberts** [comment] 2022-08-23 04:54
@eyal20 I think you should either add the `geronimo-jaspi` dependency. Or you should register the `org.eclipse.jetty.security.jaspi.DefaultAuthConfigFactory` with the static `javax.security.auth.message.config.AuthConfigFactory.setFactory` method.

should be a bit more info on that here
https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-jaspi
