### ISSUE TITLE
QuicServerConnector should support externally used KeyStore

### ISSUE THREAD

**Issue by jhkst** [eclipse/jetty.project#9526] opened 2023-03-22 14:40 UTC
**Jetty version(s)**
11.0.14 (but applies to last 12.0.x too according to the same source code)

**Enhancement Description**
The `QuicServerConnector` does not support custom keyStore implementation and is failing. The same probably applies to trustStore:
```
KeyStore keyStore = KeyStore.getInstance(new File("myfile.p12"), "mypassword".toCharArray()); // but can be anything e.g. in-memory implementation
SslContextFactory.Server sslContextFactory = new SslContextFactory.Server();
sslContextFactory.setKeyStore(keyStore);
sslContextFactory.setKeyStorePassword("mypassword"); //seems inevitable since KeyStore#getKey used in SSLKeyPair constructor requires password too.
// ^^ also if not set, QuicServerConnector#doStart throws NPE

...
Server server = new Server();
...
server.start();
```

causes this to be popped up:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.util.resource.Resource.getFile()" because the return value of "org.eclipse.jetty.util.ssl.SslContextFactory$Server.getKeyStoreResource()" is null
	at org.eclipse.jetty.quic.server.QuicServerConnector.doStart(QuicServerConnector.java:170)
	at org.eclipse.jetty.http3.server.HTTP3ServerConnector.doStart(HTTP3ServerConnector.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:428)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
...
```

Even the `quiche.SSLKeyPair` constructor is creating such KeyStore again from file and do not count with custom `KeyStore`.
I suggest to add constructor to `SSLKeyPair` and adjust `QuicServerConnector` accordingly:

```
    public SSLKeyPair(File storeFile, String storeType, char[] storePassword, String alias, char[] keyPassword) throws KeyStoreException, UnrecoverableKeyException, NoSuchAlgorithmException, IOException, CertificateException
    {
        KeyStore keyStore = KeyStore.getInstance(storeType);
        try (FileInputStream fis = new FileInputStream(storeFile))
        {
            keyStore.load(fis, storePassword);
            this.alias = alias;
            this.key = keyStore.getKey(alias, keyPassword);
            this.certChain = keyStore.getCertificateChain(alias);
        }
    }

    public SSLKeyPair(KeyStore keyStore, String alias, char[] keyPassword)
            throws UnrecoverableKeyException, KeyStoreException, NoSuchAlgorithmException {
        this.alias = alias;
        this.key = keyStore.getKey(alias, keyPassword);
        this.certChain = keyStore.getCertificateChain(alias);
    }
```

**Comment by zugazagoitia** [comment] 2023-03-27 18:10
It seems to use [this](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-quic/quic-quiche/quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/SSLKeyPair.java) implementation. Is there a reason why and not the java [KeyPair](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/KeyPair.html)? I can't reuse my SSL code from Http 1 and 2 connectors

**Comment by lorban** [comment] 2023-05-16 13:53
Duplicate of #8694

**Closed as not planned by lorban** 2023-05-16 13:53 UTC
Labels: Enhancement
