### ISSUE TITLE
Max local stream count 100 exceeded | HTTP/2 Client

### ISSUE THREAD

**Issue by s0j0urn** [eclipse/jetty.project#363] opened 2016-02-24 23:25 UTC
Test Case:
```
Client Jar: HTTP/2v9.3.7
Server: h2ov1.7.0
```
I am requesting about 219 resources from the server and 1 resource is being pushed. Irrespective of push or not, I have observed this issue: 

```
2016-02-24 16:09:26.794:WARN:oeju.Promise$Adapter:main: 
java.lang.IllegalStateException: Max local stream count 100 exceeded
	at org.eclipse.jetty.http2.HTTP2Session.createLocalStream(HTTP2Session.java:633)
	at org.eclipse.jetty.http2.HTTP2Session.newStream(HTTP2Session.java:443)
	at http2.client.Http2ClientBenchMark.main(Http2ClientBenchMark.java:110)
```
I did not observe this issue while using Jetty Server `v9.3.6`. I still think it may be something related to the client because of this discussion on [http://stackoverflow.com/questions/34717793/http-2-and-jetty-max-local-stream-count-100-exceeded/34719115](http://stackoverflow.com/questions/34717793/http-2-and-jetty-max-local-stream-count-100-exceeded/34719115) @sbordet 

In different runs, I receive true for about 100 stream end for my resources and the remaining 220-100 = 120 error as `java.lang.IllegalStateException: Max local stream count 100 exceeded`

In case, You would like to see my client code: [https://github.com/eclipse/jetty.project/issues/357](https://github.com/eclipse/jetty.project/issues/357).
I am also attaching the complete terminal output file.
[output.txt](https://github.com/eclipse/jetty.project/files/145642/output.txt)

**Comment by sbordet** [comment] 2016-02-24 23:48
I think `h20` sends down to the client a `SETTINGS` frame with `MAX_CONCURRENT_STREAMS` to be 100. The HTTP/2 specification requires the receiving side to honor that setting.
That's why Jetty throws `IllegalStateException`.

The client cannot shove 219 resources in a tight loop when the server tells the client that it can only handle 100.

Having said that, it's not difficult for the client to find what is the max number of concurrent streams that the server can handle.

You can override `Session.Listener.onSettings()` (that you pass to `HTTP2Client.connect()`) to be aware of the max number of concurrent streams.

A simple getter is missing, I'll think about adding that.

Closing the issue because this is expected behavior.

**Closed by sbordet** 2016-02-24 23:48 UTC

**Comment by varadharajan** [comment] 2017-11-23 12:17
@sbordet Any idea on how we can override default MAX_CONCURRENT_STREAMS set by  HttpClientTransportOverHTTP2?

**Comment by sbordet** [comment] 2017-11-23 18:44
As explained above, `MAX_CONCURRENT_STREAMS` is set by the server and the client must honor it.

You cannot change the value locally on the client to a larger value, since the server would eventually cancel additional streams.

@varadharajan please explain exactly what your problem is, and why you think changing `MAX_CONCURRENT_STREAMS` would help you.

**Comment by varadharajan** [comment] 2017-11-27 04:42
@sbordet We currently have two services, one written in C++ using [nghttp2](https://github.com/nghttp2/nghttp2) serving as the HTTP2 server and a Dropwizard service acting as the HTTP2 client in this case (using Jetty HttpClientTransportOverHTTP2 on top of HTTP2Client). When we were doing performance benchmark on the C++ HTTP2 service, we noticed that it was able to handle more than 100 concurrent streams at any point in time. However, while benchmarking the Java service, it started to fail right after 100 concurrent streams with this exception. Our services are expected to handle around 200 concurrent streams at its peak workload and hence i was wondering if increasing the MAX_CONCURRENT_STREAMS would fix this. We are actually sharing the HTTP2Client across multiple requests that the Dropwizard service would be hit with. 

Right now, the way we get around it is to create around 5 HTTP2Client instances at the start of the Dropwizard service and pool them for all the incoming requests. Are there cleaner ways to approach this?

**Comment by sbordet** [comment] 2017-11-27 10:02
Can't you just configure the server with more than 100 concurrent streams ?

**Comment by varadharajan** [comment] 2017-11-27 10:34
@sbordet Yeah.. That's what we are trying to do now.

**Comment by qingdaoheze** [comment] 2021-04-23 10:30
Shouldn't the Jetty client use values configured by the server? Why is it over? @sbordet

**Comment by sbordet** [comment] 2021-04-23 11:45
> Shouldn't the Jetty client use values configured by the server?

It does.

**Comment by qingdaoheze** [comment] 2021-04-23 12:08
When I send multiple API concurrently using h2c protocol, there are many timeout and cause some error "Max local stream count 100 exceeded". According to my research, these timeout requests were not sent out to other server. Do you know why?
@sbordet

**Comment by sbordet** [comment] 2021-04-23 12:15
@qingdaoheze you don't provide much details about the error and your code, so I cannot really tell what's going on.

Consider that the Jetty implementation does respect the server value, so I would double check your code first.
If you still have a problem, please open a new issue with exact details about your code, DEBUG logging, what happens, and what you expect instead.
