### ISSUE TITLE
Apache Solr fails to startup with multi domain SSL certificates

### ISSUE THREAD

**Issue by ttaranov** [eclipse/jetty.project#4874] opened 2020-05-13 00:40 UTC
**Jetty version**
Jetty version used by Apache Solr 8.5.1 (appears to be jetty version 9.4.24)

**Java version**
Java 8, Java 11

**OS type/version**
Linux

**Description**
When trying to startup single node Apache Solr instance configured with multi domain SSL certificate signed by a CA (although I don't think it matters), server fails to start up with stacktrace outlined in https://issues.apache.org/jira/browse/SOLR-14105

The issue appears to be caused by Solr server trying to establish a connection to itself using jetty's SslContextFactory.Client

**Comment by sbordet** [comment] 2020-05-13 08:25
@ttaranov on a second inspection, the issue is fixed in Jetty 9.4.25+.

If you update Solr to use Jetty 9.4.28, does it work?

**Comment by ttaranov** [comment] 2020-05-13 11:52
Thank you Simone, we’ll investigate (this issue was created based on some pre production testing of released 8.5.1 solr, although it looks like we’ll need to delay this upgrade and try out some possible work arounds).

**Comment by sbordet** [comment] 2020-05-19 07:52
@ttaranov news about this issue from Solr?

**Comment by ttaranov** [comment] 2020-05-19 14:31
@sbordet we've rolled back our deploy to solr 8.3.1 (the one with previous jetty version) and it worked ok with the specific ssl setup we use. There is apparently an upgraded version of jetty in solr's snapshot build (8.6), although its hard to test this in specific production configuration where the issue came up - we'll retest this again as new solr is released.

**Comment by sbordet** [comment] 2021-05-05 09:10
Closing as resolved.

**Closed as completed by sbordet** 2021-05-05 09:10 UTC
