### ISSUE TITLE
addServerClasses = filepath didn't work in use logging-logback

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5036] opened 2020-07-09 08:17 UTC
**Jetty version**
9.4.19.v20190610
**Java version**
1.8
**Question**
I used logging-back module in start.ini，

![image](https://user-images.githubusercontent.com/33625419/87014498-d2c1ed80-c1fe-11ea-8f8e-6704c172b3d7.png)

When i start Jetty with logback debug level，i have a Debug message：

15:43:10.972 [WrapperTasMain] DEBUG o.eclipse.jetty.webapp.WebAppContext - isServerClass==false class ch.qos.logback.classic.servlet.LogbackServletContainerInitializer

I hava see The Code
```
@Override
    public boolean isServerClass(Class<?> clazz)
    {
        if (_serverClasses == null)
            loadServerClasses();

        boolean result = _serverClasses.match(clazz);
        if (LOG.isDebugEnabled())
            LOG.debug("isServerClass=={} {}",result,clazz);
        return result;
    }
```

It looks like this just did a regular match, like addServerClasses didn't work here. As if the file path doesn't work, it should be written as a package path

**Comment by janbartel** [comment] 2020-07-09 09:46
I suspect that you have the logback jars inside your webapp because I can't reproduce this log message at all, as the logback jars that are on the server's classpath are not normally interrogated for ServletContainerInitializers. As they are "serverClasses" this means that they are normally hidden from the webapp, but if a webapp explicitly includes them in WEB-INF/lib, then they can be seen.

**Comment by janbartel** [comment] 2020-07-20 09:04
@zhengshundong01 if this issue is now resolved, please close the issue, or otherwise please provide more information to help diagnose the problem, such as a DEBUG level log output for org.eclipse.jetty.annotations and org.eclipse.jetty.webapp.

**Comment by janbartel** [comment] 2020-07-29 08:18
I'm closing this issue for now as there  hasn't been any further activity. If the problem persists after following the advice given, please reopen with the DEBUG log information requested.

**Closed as completed by janbartel** 2020-07-29 08:18 UTC
Labels: Question
