### ISSUE TITLE
Reading the httpinput takes too long

### ISSUE THREAD

**Issue by zhangtianxiao** [eclipse/jetty.project#3062] opened 2018-11-06 14:09 UTC
version: 9.3.0.M1,
framework: spring-mvc,
I tried to upload a large file, 
debug -> passed the  method of controller ->　C:/Users/zhangtianxiao/.ideaLibSources/jetty-all-9.3.0.M1-sources.jar!/org/eclipse/jetty/server/HttpInput.java:328

the method name is **isFinished**,   it returns false always, 
I think this is the reason

**Comment by janbartel** [comment] 2018-11-06 15:44
@zhangtianxiao  there is not enough information in this bug report. Please provide more details of the problem, including a reproduction if possible. Also, jetty-9.3.0.M1 is very old, it's not even the most recent in the 9.3.x series (which is 9.3.25.v20180904).

**Comment by joakime** [comment] 2018-11-06 16:03
The `9.3.0.M1` is an unstable milestone release.

In terms of stability of a release (least to most) ...

* `*-SNAPSHOT` = Snapshot build - in progress features, not expected to be stable. available via https://oss.sonatype.org/content/repositories/jetty-snapshots/
* `*-M#` = Milestone build - probably not feature complete, should be vaguely stable, likely to still have problems, good for starting integration testing with other projects that use Jetty.
* `*-RC#` = Release candidate - almost feature complete, should be pretty stable, problems should be rare and/or minor.
* `*.v<datestamp>` = A General Availability Release - feature complete, and be very stable

**Comment by joakime** [comment] 2018-11-06 16:21
@zhangtianxiao please update to a stable (and recent) version of Jetty and try again.

Also note that there are quirks with regards to large file uploads on Windows.
See issue #1864

**Comment by joakime** [comment] 2019-02-17 14:52
Closing due to lack of updates.
Will happily reopen once more details are provided.

**Closed by joakime** 2019-02-17 14:52 UTC
Labels: More Info Required
