### ISSUE TITLE
Jetty WebSocketServerFactory NPE in toString()

### ISSUE THREAD

**Issue by bmahaj2** [eclipse/jetty.project#2724] opened 2018-07-16 22:57 UTC
I see that this bug is fixed in  https://github.com/eclipse/jetty.project/issues/1603

On which version of Jetty is this bug fixed ? I'm using spring boot version 1.5.7 which uses jetty 9.4.6.v20170531 and I see this bug. How do I make it work with spring 1.5.7 ?

org.springframework.boot:spring-boot-starter-jetty:jar:1.5.7.RELEASE:compile
[INFO] | +- org.eclipse.jetty:jetty-servlets:jar:9.4.6.v20170531:compile

**Comment by bmahaj2** [comment] 2018-07-16 22:58
Opened this new issue as the previous issue https://github.com/eclipse/jetty.project/issues/1603 was closed

**Comment by joakime** [comment] 2018-07-17 11:19
Duplicate of #1603

**Closed by joakime** 2018-07-17 11:19 UTC
