### ISSUE TITLE
Seeing a lot of TimeoutExceptions and ClosedChannelExceptions

### ISSUE THREAD

**Issue by tipsy** [eclipse/jetty.project#2314] opened 2018-03-10 20:43 UTC
I'm noticing a bunch of these exceptions for every request, so it seems likely that something is wrong.

I write to the `HttpServletResponse`s `OutputStream` manually, then close it and set the request to handled:

```
resultStream.copyTo(httpServletResponse.outputStream)
httpServletResponse.outputStream.close()
jettyRequest.isHandled = true
```

Here is a my debug log: https://pastebin.com/raw/WZfvTn79

I set the timeout to 1s for testing, but it happens at the default 30s too.

My jetty-server code is pretty simple: https://github.com/tipsy/javalin/blob/master/src/main/java/io/javalin/embeddedserver/jetty/EmbeddedJettyServer.kt#L36-L48

This is how I write to the response: https://github.com/tipsy/javalin/blob/master/src/main/java/io/javalin/core/JavalinServlet.kt#L88-L98

**Comment by joakime** [comment] 2018-03-11 11:26
Why are you gzipping your own content?  

That's what GzipHandler is for (which handles gzip in the interceptor layer on the server side, and handles all of the http cache headers properly for when the content is compressed).
If you are using ServletContextHandler, don't mix it with ResourceHandler, use the DefaultServlet and properly declared Resource Bases (either for your context, or 1...n DefaultServlet entries) the DefaultServlet also participates with the GzipHandler/Interceptor to make cached responses correct.

Why are you closing the outputStream?  that's not in line with recommendations with the servlet spec.    
Let the container manage the open/close state of the streams.
(With Servlet 3.0+ the containers are async primarily)

Why are you not specifying the Content-Length on the responses?

**Comment by tipsy** [comment] 2018-03-11 12:35
@joakime I'll make a note of all of those things and fix some of them, but I don't think they are relevant. I get the exact same exceptions with this as my entire program: 

```kotlin
fun main(args: Array<String>) {
    Server().apply {
        handler = object : ServletContextHandler(null, "/", SESSIONS) {
            override fun doHandle(target: String, jettyRequest: Request, request: HttpServletRequest, response: HttpServletResponse) {
                ByteArrayInputStream("Hello, Exceptions!".toByteArray()).copyTo(response.outputStream)
                jettyRequest.isHandled = true
            }
        }
        connectors = arrayOf(ServerConnector(server).apply {
            this.idleTimeout = 1000
            this.port = 7000
        })
    }.start()
}
```

**Comment by joakime** [comment] 2018-03-11 12:41
don't override `doHandle()` in `ServletContextHandler` (you break `ServletContextHandler` doing that)
Add a Servlet, at a url-pattern, and perform your handling there.

**Comment by tipsy** [comment] 2018-03-11 13:15
@joakime Also noted, however...! The exceptions are still there if I run the Hello World example from http://www.eclipse.org/jetty/documentation/9.4.x/embedding-jetty.html, 

```
public class OneHandler {
    public static void main(String[] args) throws Exception {
        Server server = new Server();
        server.setHandler(new HelloHandler());
        ServerConnector serverConnector = new ServerConnector(server);
        serverConnector.setPort(7001);
        serverConnector.setIdleTimeout(1000);
        server.setConnectors(new Connector[]{serverConnector});
        server.start();
        server.join();
    }
}```

**Comment by joakime** [comment] 2018-03-11 13:26
if you are seeing exception during Hello World, then you are likely using a non-compliant http client/browser.

Just ran that code against Jetty version 9.4.8.v20171121
Using Java 9.0.4+11 (and also tried on Java 1.8.0_162+b12)

That example, tested this morning, on the following http clients, produces no exceptions/timeouts ...

* Google Chrome 64.0.3282.186 (Official Build) (64-bit)
  * Windows 10
  * OSX 10.12.6
  * Linux / Fedora core 25
* Firefox 57.0.4 (64-bit)
  * Windows 10
  * OSX 10.12.6
  * Linux / Fedora core 25
* curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
  * Linux / Ubuntu 16.04.3 LTS
* curl 7.51.0 (x86_64-redhat-linux-gnu) libcurl/7.51.0 NSS/3.31 zlib/1.2.8 libidn2/2.0.4 libpsl/0.17.0 (+libidn2/0.11) libssh2/1.8.0 nghttp2/1.13.0
  * Linux / Fedora core 25
* GNU Wget 1.19.2 built on linux-gnu.
  * LInux / Fedora core 25
* Safari 11.0.3 (12604.5.6.1)
  * OSX 10.12.6

Even tried the HTTP2Server ...
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/Http2Server.java

Which works with curl + chrome + firefox without exception/error as well (using the HTTP/2 protocol)

**Comment by joakime** [comment] 2018-03-11 13:29
Updated my Google Chrome on Windows and OSX a moment ago.
Now on 65.0.3325.146 (Official Build) (64-bit)

Still cannot reproduce your report of exceptions / timeouts on Hello World.

**Comment by tipsy** [comment] 2018-03-11 13:41
I get them regardless of browser. Uploaded my test-project: https://github.com/tipsy/jetty-bug

**Comment by joakime** [comment] 2018-03-11 13:47
A sample project is useful to help diagnose, thanks for that.

But your project doesn't compile under maven 3.5.0, java 1.8.0_162.

**Comment by tipsy** [comment] 2018-03-11 13:55
That's... interesting. I can update to maven 3.5.0. and java 1.8.0_162, but the example only contains the hello-world snippet from the docs and a logging profile, what is it complaining about?

**Comment by joakime** [comment] 2018-03-11 14:01
The pom.xml is missing a valid `<build>` section declaring the compiler version.

see my fork: https://github.com/joakime/jetty-bug

Running your code produces no errors or warnings about timeouts or closed channel exceptions.

![issue-2314-results](https://user-images.githubusercontent.com/191721/37254379-b7a910fc-250a-11e8-8bfe-adaa0e754fa3.png)

**Comment by joakime** [comment] 2018-03-11 14:10
Looking again at your pastebin, you have no ERRORS or WARNINGS about timeouts or closed channel exceptions.

What you do have, and are likely seeing, are DEBUG (not an error, not a warning) announcements for idle timeouts on HTTP/1.1 persistent connections that have not had a subsequent request, and the ClosedChannelException you see in your pastebin is also a DEBUG for when the connection was terminated (because of that idle timeout).

A browser will use HTTP/1.1 persistent connections by default.
This is normal.

If you use a http client that offers to close the connection after the request (normal behavior of command line clients, and even HttpURLConnection), or your server specifies to close the connection (via `response.setHeader("Connection", "close")`) then the idle timeout is canceled on completion of the request/response.   

You seem to be confusing DEBUG events as a problem / error / issue.
If you see a DEBUG severity event, that only tells you what is going on internally, and does not indicate a problem that needs to be fixed or addressed.
It does however tell you what is going on, and you can choose to change that behavior.

Closing as Invalid.

**Closed by joakime** 2018-03-11 14:10 UTC
Labels: Invalid

**Comment by tipsy** [comment] 2018-03-11 14:24
Alright, sorry about the confusion. I also thought these were expected, but during my conversation on Gitter with @sbordet I became unsure. Thanks for your help.

**Comment by sbordet** [comment] 2018-03-12 18:26
@tipsy sorry about that, I thought you were seeing those exceptions at INFO/WARN level, not DEBUG.

**Comment by tipsy** [comment] 2018-03-12 18:33
No worries, I should have been clearer. I really appreciate the work you all do on Jetty, keep it up!
