### ISSUE TITLE
WebSocket `DeploymentException` is not thrown by client nor server

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#9466] opened 2023-03-06 15:24 UTC
**Jetty version(s)**
verified:
11.0.x
12.0.x.beta0
still needs confirmation:
9.4.x
10.0.x

**Description**
In the client code, the multiple `jakarta.websocket.WebSocketContainer.connectToServer()` methods declare throwing `DeploymentException` in certain conditions, but only `IOException` is ever thrown.

In the server code, `jakarta.websocket.server.ServerContainer.upgradeHttpToWebSocket()`  also declares throwing `DeploymentException` in certain conditions, while only `IOException` is ever thrown.

`javax.websocket` implementations should be checked too.

**Comment by lorban** [comment] 2023-03-06 15:26
@lachlan-roberts your opinion & analysis are more than welcome.

**Comment by sbordet** [comment] 2023-04-12 19:57
@lorban can this be closed?

**Comment by lachlan-roberts** [comment] 2023-04-13 00:56
I was reviewing this a while ago and think I even had a branch for it with some small improvements which I seem to have lost.

But the `connectToServer` implementations can actually throw Deployment exception, and so can `upgradeHttpToWebSocket`. So I don't think the description in the issue is correct.

**Comment by lorban** [comment] 2023-04-13 09:14
If @joakime is happy about how we interpreted the spec, then this can be closed.

**Comment by lachlan-roberts** [comment] 2023-05-01 04:28
closing as #9678 has been merged

**Closed as completed by lachlan-roberts** 2023-05-01 04:28 UTC
Labels: Bug
