### ISSUE TITLE
Getting "IllegalStateException: Unexpected wrap result BUFFER_OVERFLOW" in my Jetty server logs

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#5089] opened 2020-07-28 16:23 UTC
**9.4.30.v20200611**

**jdk1.8.0_221**

I can see below exception in my Jetty server logs coming very frequently:

2020-07-28 17:56:10.880:WARN:oejs.HttpChannel:test/SBIFE/SBI F-E-1091-pool-134: /test/
java.lang.IllegalStateException: Unexpected wrap result BUFFER_OVERFLOW
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1106)
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)
        at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:264)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
        at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:717)
        at org.eclipse.jetty.http2.HTTP2Session.data(HTTP2Session.java:704)
        at org.eclipse.jetty.http2.HTTP2Stream.data(HTTP2Stream.java:125)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.sendDataFrame(HttpTransportOverHTTP2.java:299)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.lambda$send$6(HttpTransportOverHTTP2.java:213)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2$TransportCallback.send(HttpTransportOverHTTP2.java:399)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2$TransportCallback.access$100(HttpTransportOverHTTP2.java:378)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:212)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:838)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:910)
        at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:283)
        at org.eclipse.jetty.server.HttpOutput.complete(HttpOutput.java:479)
        at org.eclipse.jetty.server.Response.completeOutput(Response.java:889)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:521)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:335)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:748)

Corresponding to this error I can also see org.eclipse.jetty.io.EofException exception in my Jetty client logs as well.

What could be the reason for this exception in server logs?

**Comment by sbordet** [comment] 2020-07-28 17:34
Duplicate of #5006.

**Closed as completed by sbordet** 2020-07-28 17:35 UTC
Labels: Question
