### ISSUE TITLE
20%-30% CPU usage in Jetty threads on Linux when there is no load.

### ISSUE THREAD

**Issue by Vighnesh123** [eclipse/jetty.project#3257] opened 2019-01-14 07:59 UTC
We are using jetty 9.4.5 in our product on linux and jdk version is 1.8.0_131-b11. We have performed stress test. We have observed that our server is not coming to idle state after the Stress test. CPU utilizations are continuously spinning and average utilization is around 20%-30%.
When we analysed the threadump we observed jetty related threads in runnable state.Excerpts of Thread dump is captured below.
When we ran stress test on our product without jetty , we did not observe this issue. 
In jetty issues list we observed similar issue https://github.com/eclipse/jetty.project/issues/3022. Is it related?

"HTTP Administration Connector-118-acceptor-0@3b139782-Jetty Connector 0.0.0.0 port 8444@35d46e90{SSL,[ssl, http/1.1]}{0.0.0.0:8444}" #118 prio=3 os_prio=0 tid=0x00007f8258154000 nid=0x40df runnable [0x00007f81914d5000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        - locked <0x0000000597e37c40> (a java.lang.Object)
        at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378)
        at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:639)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
        at java.lang.Thread.run(Thread.java:748)

"HTTP Connection Handler-124-acceptor-0@3b9b2c7b-Jetty Connector 0.0.0.0 port 8080@f2d4947{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}" #124 prio=3 os_prio=0 tid=0x00007f8154010800 nid=0x40e9 runnable [0x00007f81902cb000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        - locked <0x0000000597e37b68> (a java.lang.Object)
        at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378)
        at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:639)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
        at java.lang.Thread.run(Thread.java:748)

"HTTP Connection Handler-133-acceptor-0@4f1368f8-Jetty Connector 0.0.0.0 port 10443@41d49f6a{SSL,[ssl, http/1.1]}{0.0.0.0:10443}" #133 prio=3 os_prio=0 tid=0x00007f817c004000 nid=0x40fa runnable [0x00007f814b7f6000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        - locked <0x0000000597e37ac0> (a java.lang.Object)
        at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378)
        at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:639)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sbordet** [comment] 2019-01-14 08:13
Please upgrade to the latest Jetty version - 9.4.14, that incorporates many TLS changes.

The stack traces you report are normal - the thread is marked as `RUNNALE` but it's actually blocked in the `accept()` call to accept new connections.

**Comment by Vighnesh123** [comment] 2019-01-14 08:59
Thanks we will upgrade and check. Though stack trace seems normal, weird part is that these threads are consuming CPU when there is no load. Before stress test, this was not the case.  Jdk version is 1.8.0_131-b11 is not issue right?

**Comment by sbordet** [comment] 2019-01-14 09:03
I don't think the JDK version is an issue although you should really be on the latest version, 8u192.

That the acceptor threads are consuming CPU when there is no load is highly unlikely - if that's the case we would like to see proof of that via a reproducible case.
What makes you think are the acceptor threads that consume CPU?

**Comment by Vighnesh123** [comment] 2019-01-14 10:39
We ran our application with and without jetty. We performed stress test in both cases, once the test is completed, when there is no request at that time we are seeing cpu consumption 20-30% with jetty. Cpu consumption will not come down after many hours also.
Without jetty cpu consumption will become 1% as soon stress test is completed.

**Comment by sbordet** [comment] 2019-01-14 10:51
That is not enough information for us to replicate the issue.

If you perform 2 stress tests in 2 different configurations, all the bets are off, as we don't know what you're doing.
For all we know, when you do the test with Jetty you are executing additional logic and it's the additional logic that consumes CPU - not Jetty.

We need evidence that it's a Jetty problem - it may well be, but we need evidence.

**Comment by romankarpenko** [comment] 2019-01-23 15:00
@Vighnesh123 have you managed to update jetty and check? Seems we have the same case.. after a high load, Jetty threads start to consume CPU
(jetty 9.3.6, jdk 1.8.0_101-b13)

**Comment by sbordet** [comment] 2019-01-23 15:32
@romankarpenko please update to the latest Jetty (9.4.14) and latest JDK.

Are you able to profile the JVM when the CPU increase happens?

**Comment by Vighnesh123** [comment] 2019-01-23 15:52
@romankarpenko I have upgraded jetty, but that did not solve the issue.

**Comment by romankarpenko** [comment] 2019-01-23 16:11
@sbordet yes I'm able, what I need to check?

**Comment by sbordet** [comment] 2019-01-23 17:27
@romankarpenko we cannot reproduce it, so we need information about this issue.

If you can put the server in high CPU, first thing take a `Server` dump (https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html).
If you can reproduce it with DEBUG logs enabled, that would help tremendously, because from the logs we will know if it's Jetty running code in a loop.

If you cannot reproduce it with DEBUG logs, can you attach `async-profiler` (https://github.com/jvm-profiling-tools/async-profiler) to the JVM and profile it for say 30-60 seconds, producing a flame graph?
That would give us hints of where to look in absence of DEBUG logs.

**Comment by romankarpenko** [comment] 2019-01-25 15:42
@sbordet seems in my case CPU consumption is caused by our own logic and not by Jetty.

**Comment by sbordet** [comment] 2019-01-25 18:01
@romankarpenko thanks for getting back to us!

**Comment by joakime** [comment] 2019-01-25 21:03
@romankarpenko @sbordet can this issue be closed then?

**Comment by joakime** [comment] 2019-09-06 01:33
No updates from @Vighnesh123 , closing due to lack of information.

**Closed by joakime** 2019-09-06 01:33 UTC
Labels: More Info Required, Unable To Replicate
