### ISSUE TITLE
Use interpolation of versions from pom in mod files

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#3514] opened 2019-04-01 04:18 UTC
Currently all mod files have a hardcoded version of libraries we used. So they can be out dated compared from version we use in test because require some manual changes.
We can can use maven interpolation to get the exact same version as used in test and declared in poms

**Comment by joakime** [comment] 2019-04-01 10:20
seems like a duplicate of #315

**Comment by olamy** [comment] 2019-04-01 10:25
@joakime good point except my current changes do not include managing transitive dependencies. Should we? (this will need more work)

**Comment by joakime** [comment] 2019-04-01 10:31
@olamy you might want to take a look at https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-gcloud/jetty-gcloud-session-manager/

That's the big one, and the process we came up with in there is kinda noisy.
See the various maven plugins `dependency:list` and `antrun:run` (regexp and concat)

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-gcloud/jetty-gcloud-session-manager/pom.xml

**Comment by olamy** [comment] 2019-04-01 10:34
doh I don't really this antrun... I would  prefer writing a maven plugin :)

**Comment by joakime** [comment] 2019-04-01 10:40
Yup, i understand, just pointing out the history of this issue.
A feature in a maven-plugin would be nice.

**Comment by janbartel** [comment] 2019-04-02 01:00
It's essential to manage the dependencies - that's the real pain point in the modules. Also have a look at the branch jetty-9.4.x-2140-InfinispanExpiredSessions and you'll see even more modules that need to do the antrun trick in order to manage the large number of transitive deps.

**Comment by olamy** [comment] 2021-09-16 02:06
to prevent issues with the current usage of ${} in mod files. Interpolation of values from pom will be based on the delimiter `@....@` such `@log4j2.version@`

**Comment by joakime** [comment] 2021-09-22 22:17
PR #6839 is merged.

**Closed by joakime** 2021-09-22 22:17 UTC
Labels: Test, Build
