### ISSUE TITLE
Problem with websocket over http/2

### ISSUE THREAD

**Issue by hiepth** [eclipse/jetty.project#1424] opened 2017-03-24 02:21 UTC
My WebSocketServlet code
```
public class ServletServer extends WebSocketServlet
{
	private static final java.util.logging.Logger logger = Log.getLogger();

	@Override
	public void configure(WebSocketServletFactory factory)
	{
		factory.register(WebSocketClient.class);
		logger.log(GU.NETWORK,"Web socket game server started");
	}
}
```
Work fine when connector config with HttpConnectionFactory.
When config with h2, h2c
var ws = new WebSocket("wss://binhkhang.ftl.vn:40443/ws/gameServer");
I got error (in chrome console): WebSocket connection to 'wss://binhkhang.ftl.vn:40443/ws/gameServer' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE

**Comment by joakime** [comment] 2017-03-27 14:03
Duplicate of Issue #1364

**Closed** 2017-03-27 14:09 UTC
Labels: Duplicate
