### ISSUE TITLE
Custom PushBuilder unable to push resources + NullPointerException

### ISSUE THREAD

**Issue by s0j0urn** [eclipse/jetty.project#369] opened 2016-02-27 02:56 UTC
Hello,

Following @sbordet reply here [http://stackoverflow.com/questions/35162252/how-to-do-server-push-with-standalone-jetty](http://stackoverflow.com/questions/35162252/how-to-do-server-push-with-standalone-jetty), I tried to implement a very simple custom filter, to have a control on what files gets pushed:

```

public final class MyPushFilter implements Filter {

	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
		
		
		// if http/1.1 then return. HTTP/2 is running only on secure ports.
		if (request.isSecure()==false)
		{
			chain.doFilter(request, response);
            return;
        }
		HttpServletRequest httpRequest = (HttpServletRequest) request;
		//System.out.println("HttpRequest is" + httpRequest );
		String uri = httpRequest.getRequestURI();
		//System.out.println("Switch uri is is" + uri );
		switch(uri)
		{
			case "/my-gallery/index.css":
				PushBuilder pushBuilder = Request.getBaseRequest(request).getPushBuilder();
				pushBuilder.path("/my-gallery/index.js").push();
				pushBuilder.path("/my-gallery/data.js").push();
                break;
            default:
                break;
			
		}
		// pass the request along the filter chain
		chain.doFilter(request, response);
	}

}
```
 
I then copied the generated `MyPushFilter.class`  to `/my-gallery/WEB-INF/classes` and declared it in `/my-gallery/WEB-INF/web.xml`.

```
 <filter>
        <filter-name>MyPushFilter</filter-name>
        <filter-class>MyPushFilter</filter-class>
        <async-supported>true</async-supported>
        <init-param>
            <param-name>ports</param-name>
            <param-value>8443</param-value>
        </init-param>
</filter>
    <filter-mapping>
        <filter-name>MyPushFilter</filter-name>
        <url-pattern>*.css</url-pattern>
    </filter-mapping>

```

however the file on which push is defined in `MyPushFilter.java` in this case `index.css` does not get downloaded from the server. Also, no push takes place. Also, if I try to directly browser to the url  `index.css` it gives me `java.lang.NoClassDefFoundError` on `Request.getBaseRequest(request).getPushBuilder();`. Adding the required jars to lib folder leads to NullPointerException.

After studying more through the documentation, I added a deplyment descriptor in `/jetty-base/webapps/jetty-context.xml` to set the `parentLoaderProperty`

```
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
<Set name="contextPath">/my-gallery/</Set>
  <Set name="parentLoaderPriority">true</Set>
</Configure>
```
However the issue still stands :(

**Comment by s0j0urn** [comment] 2016-02-27 07:56
I have updated the issue with new details.

In case, server debug log can help:


While directly accessing index.css in browser : 
[index.css_stderrout.log.txt](https://github.com/eclipse/jetty.project/files/149258/index.css_stderrout.log.txt)


While trying to load the application: 
[index.html_stderrout.log.txt](https://github.com/eclipse/jetty.project/files/149259/index.html_stderrout.log.txt)

**Comment by gregw** [comment] 2016-02-29 10:01
I think the problem here is as you have identified, one of classloading.
The Jetty filter can access the jetty APIs because it is loaded from the server classloader and the default settings of systemClasses and serverClasses in the webapp allow the filter to be seen.

So you either have to mimic this (putting your filter on the server classpath);  or you have to setup the system/server classes to not hide the jetty APIs.

Alternately, write this as a handler that is configured on the server rather than as a filter configured in the webapp.

**Comment by s0j0urn** [comment] 2016-02-29 10:32
Hello,

> So you either have to mimic this (putting your filter on the server classpath);

I did try that as well. I copied my filter .class file to the same jar as PushCacheFilter and specified my filter similarly but it didn't work.

> or you have to setup the system/server classes to not hide the jetty APIs.

umm sorry I didn't get this. Isn't when I set parentLoaderPriority to true it makes sure that server classes are accessed first. 

> Alternately, write this as a handler that is configured on the server rather than as a filter configured in the webapp.

Sadly, I am a bit inexperienced with configuring server side stuff. A small example will surely help me out.

I came across this issue on stackoverflow : [http://stackoverflow.com/questions/29461749/how-to-use-org-eclipse-jetty-server-request-in-a-webapp](http://stackoverflow.com/questions/29461749/how-to-use-org-eclipse-jetty-server-request-in-a-webapp) . It look similar to what I am facing except that I am deploying my webapp simply on Jetty distribution and configuring the server directly.

**Comment by s0j0urn** [comment] 2016-03-01 21:34
@gregw 

> (putting your filter on the server classpath)

Thanks a lot for mentioning this. :)

I read and reread the documentation and finally figured it out because of the below line in the documentation:

> Adding the directory $jetty.home/resources to the classpath (may contain classes or other resources).

I don't think it is a bug with Jetty. I believe it is my inexperience with server side configurations. 
Please close it if it is not an actual bug.

**Comment by sbordet** [comment] 2016-03-01 22:45
@s0j0urn if the issue is resolved for you, since you were the reporter, please close it yourself.

Thanks!

**Closed** 2016-03-01 22:46 UTC
Labels: Bug
