### ISSUE TITLE
websocket.tests.client.ClientConnectTest is flakey in 9.4

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4031] opened 2019-08-28 02:30 UTC
[INFO] Running org.eclipse.jetty.websocket.tests.client.ClientConnectTest
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.226 s <<< FAILURE! - in org.eclipse.jetty.websocket.tests.client.ClientConnectTest
[ERROR] testAltConnect  Time elapsed: 0.034 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: ConnectionState@493250cf[HANDSHAKING]
	at org.eclipse.jetty.websocket.tests.client.ClientConnectTest.stopServer(ClientConnectTest.java:156)
Caused by: java.lang.IllegalStateException: ConnectionState@493250cf[HANDSHAKING]
	at org.eclipse.jetty.websocket.tests.client.ClientConnectTest.stopServer(ClientConnectTest.java:156)

**Comment by lachlan-roberts** [comment] 2019-08-28 05:43
Had the test run almost 1000 times and could not reproduce this error.

But it sounds like the Session is being closed in `server.stop()` through the `SessionTracker` before the `ConnectionState` moves from HANDSHAKING to OPENING. 

I think this has to do with the change where Sessions are added to the `SessionTracker` as the are created rather than when they are opened. This was done so the `WebSocketSession` lifecycle could be managed properly but now this means `SessionTracker.doStop()` can try to close connections before they have been opened.

**Comment by joakime** [comment] 2019-09-06 14:04
PR #4046 is now merged.

**Closed by joakime** 2019-09-06 14:04 UTC
Labels: Bug
