### ISSUE TITLE
Capture Timestamps of request processing

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#164] opened 2016-02-16 23:28 UTC
migrated from Bugzilla [#446377](https://bugs.eclipse.org/bugs/show_bug.cgi?id=446377)
status ASSIGNED severity _enhancement_ in component _server_ for _9.2.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Greg Wilkins

On 2014-10-08 17:36:11 -0400, Greg Wilkins wrote:

> Debugging mode that captures timestamp of first packet, parsed header, dispatched request,suspended, resumed, committed, complete etc.

**Comment by sbordet** [comment] 2017-09-14 09:14
Duplicate of #1807.

**Closed by sbordet** 2017-09-14 09:14 UTC
Labels: Enhancement
