### ISSUE TITLE
slfj4-simple-impl module error in 9.4.0.RC1

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1042] opened 2016-10-27 01:00 UTC
```
[2794] java -jar ../start.jar --add-to-start=slf4j-simple-impl
INFO  : slf4j-simple-impl initialized in ${jetty.base}/start.d/slf4j-simple-impl.ini
DOWNLD: http://central.maven.org/maven2/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar to ${jetty.base}/lib/slf4j/slf4j-simple-1.7.21.jar
java.lang.IllegalArgumentException: File does not exist: basehome:modules/slf4j-impl
	at org.eclipse.jetty.start.fileinits.BaseHomeFileInitializer.create(BaseHomeFileInitializer.java:52)
	at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:282)
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:321)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:248)
	at org.eclipse.jetty.start.Main.start(Main.java:405)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
WARN  : Failed to process all file resources.
 - [IllegalArgumentException] File does not exist: basehome:modules/slf4j-impl - null
java.lang.RuntimeException: Failed to process all file resources.
 - [IllegalArgumentException] File does not exist: basehome:modules/slf4j-impl - null
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:341)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:248)
	at org.eclipse.jetty.start.Main.start(Main.java:405)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
```

**Comment by gregw** [comment] 2016-10-27 02:15
Duplicate of #1023.  Fixed already.

**Closed by gregw** 2016-10-27 02:15 UTC
