### ISSUE TITLE
Flaky H2 tests

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#11735] opened 2024-05-02 02:11 UTC
**Jetty version(s)**
12

**Description**
two unrelated PR builds failed with similar H2 issues:

 + https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-11598/49/pipeline/
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[2024-05-01T05:31:58.047+0000][info][gc] Using G1
WARNING: Unknown module: org.eclipse.jetty.http2.server specified to --add-reads
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment Temurin-22+36 (build 22+36)
OpenJDK 64-Bit Server VM Temurin-22+36 (build 22+36, mixed mode, sharing)
[INFO] Running org.eclipse.jetty.http2.tests.TrailersTest
[INFO] Running org.eclipse.jetty.http2.tests.AsyncIOTest
Running org.eclipse.jetty.http2.tests.TrailersTest.testRequestTrailerInvalidHpackReceived()
Running org.eclipse.jetty.http2.tests.AsyncIOTest.testLastContentAvailableBeforeService()
2024-05-01 05:31:59.168:INFO :oejs.Server:ForkJoinPool-1-worker-1: jetty-12.0.9-SNAPSHOT; built: 2024-04-30T06:22:08.522Z; git: 52346e1574adb25994c66e320c9699c402e2ce18; jvm 22+36
2024-05-01 05:31:59.168:INFO :oejs.Server:ForkJoinPool-1-worker-2: jetty-12.0.9-SNAPSHOT; built: 2024-04-30T06:22:08.522Z; git: 52346e1574adb25994c66e320c9699c402e2ce18; jvm 22+36
2024-05-01 05:31:59.208:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-2: Started ServerConnector@3ca2ab87{h2c, (h2c)}{0.0.0.0:35859}
2024-05-01 05:31:59.208:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-1: Started ServerConnector@1157a1e9{h2c, (h2c)}{0.0.0.0:34631}
2024-05-01 05:31:59.216:INFO :oejs.Server:ForkJoinPool-1-worker-2: Started oejs.Server@ed77b26{STARTING}[12.0.9-SNAPSHOT,sto=0] @1171ms
2024-05-01 05:31:59.216:INFO :oejs.Server:ForkJoinPool-1-worker-1: Started oejs.Server@740d7a59{STARTING}[12.0.9-SNAPSHOT,sto=0] @1171ms
2024-05-01 05:32:09.653:WARN :oejut.QueuedThreadPool:ForkJoinPool-1-worker-1: Couldn't stop Thread[#44,client-44,5,main]
2024-05-01 05:32:09.653:WARN :oejut.QueuedThreadPool:ForkJoinPool-1-worker-2: Couldn't stop Thread[#43,client-43,5,main]
2024-05-01 05:32:09.654:INFO :oejs.Server:ForkJoinPool-1-worker-2: Stopped oejs.Server@ed77b26{STOPPING}[12.0.9-SNAPSHOT,sto=0]
2024-05-01 05:32:09.654:INFO :oejs.Server:ForkJoinPool-1-worker-1: Stopped oejs.Server@740d7a59{STOPPING}[12.0.9-SNAPSHOT,sto=0]
Sending interrupt signal to process
```

 + https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-11501/17/pipeline
```
Hypertext Transfer Protocol Version 2 (HTTP/2)
  3. Starting HTTP/2
    3.5. HTTP/2 Connection Preface
      using source address 172.17.0.8:43102
      × 2: Sends invalid connection preface
        -> The endpoint MUST terminate the TCP connection.
           Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                     Connection closed
             Actual: Error: unexpected EOF
```

**Comment by gregw** [comment] 2024-10-01 22:24
@sbordet @lorban had this been addressed? Can this be closed?

**Comment by lorban** [comment] 2024-10-02 09:06
The h2spec plugin was disabled in https://github.com/jetty/jetty.project/pull/12209, IIRC the last failure we spent time troubleshooting a failure the cause was the h2spec test itself.

@sbordet do you remember anything specific about this failure?

**Comment by sbordet** [comment] 2024-10-02 16:26
I am closing this.

**Closed as completed by sbordet** 2024-10-02 16:26 UTC
Labels: Bug, flaky-test
