### ISSUE TITLE
infinte loop after approx 1 week with no jetty/java code involved?

### ISSUE THREAD

**Issue by paulpalaszewski** [eclipse/jetty.project#10793] opened 2023-10-26 07:40 UTC
**Jetty version(s)**

10.0.11 - 10.0.15

**Jetty Environment**

Custom build with core web server + default session manager + h2. Our own lets encrypt client + custom webapp handler/class loader that's reduced to servlet 1.0 deployments.

**Java version/vendor** `(use: java -version)`
openjdk 18 - 21.0.1

**OS type/version**
Up to now the issue occurred on an intel mac running macOS 12.6.9 and various Debian Linux versions. We also have lots of Windows boxes running these configurations but those are not public. I think I did not see the issue on any of them, but I suppose it's more likely to be because of the box being not public rather than because of Windows. 

**Description**
It occurs on web servers reachable through the net. After approximately 1 week the machine runs with 100% cpu. Looked like the classic infinite loop, used jstack and our own web tool with similar functionality to identify the thread/code that's causing the issue, but there was no active thread. No (visible) code from us and no jetty code. 

Restarting the service helps. For +/- a week.
Did not have the issue with older jdks + jetty versions, but it's hard to say which part went wrong since we regularly update both as soon as updates are available. 

**How to reproduce?**
That's part of the issue - don't know.

**Comment by sbordet** [comment] 2023-10-26 08:18
For the machine to go 100% CPU, some thread must be scheduled, so you should see something in the stack trace dump with `jstack`.

Is it even the Java process causing the 100% CPU, or something else that runs on the same box?

**Comment by ekupcik** [comment] 2023-10-26 08:41
Sounds like GarbageColleciton  / OutOfMemory problem with the JVM spending all the time in the GC

**Comment by paulpalaszewski** [comment] 2023-10-26 11:35
Thanks for the first comments!

On linux + mac I've checked with ssh + top, that it's always the java process consuming the time. And with the process id from top I've retrieved the jstack dumps. Though I made the mistake to not archive most of them. Will definitely get fresh jstack dumps + check on the memory usage next time it happens. Attached is a dump from june of the mac.

[jstack_2023-06-29.txt](https://github.com/jetty/jetty.project/files/13176582/jstack_2023-06-29.txt)
Did I miss something usefull there?

Regarding gc ... we actively monitor heap. In case of the that mac we have on avg 70% of 4gb available. We automatically create heap dumps on out of memory + check those for causes. Have not seen one of them for years. Not sure about other memory types .. eg. we use String.intern() in some places to deduplicate data + reduce memory consumption. I know the jvm used a different memory area for them but have not looked into that for a long time. 

Speaking of memory management, we have a few libraries using native code in the classpath: sqllite jdbc 3.14, jna 5.12.1, jSerialComm 2.6.2. I did not think of them, since the instances that go to 100% don't use any of their features.

**Comment by joakime** [comment] 2023-10-26 11:48
@paulpalaszewski according to your jstack, the following threads are using all of your CPU...

```
"FileSystemWatcher" #44 [35843] daemon prio=5 os_prio=31 cpu=4017956.39ms elapsed=766149.19s tid=0x00007fa92fa90e00 nid=35843 waiting on condition  [0x000070000940e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x000000071852ec18> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@20.0.1/LockSupport.java:269)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@20.0.1/AbstractQueuedSynchronizer.java:1758)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@20.0.1/ThreadPoolExecutor.java:1070)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@20.0.1/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@20.0.1/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"FileSystemWatcher" #48 [30979] daemon prio=5 os_prio=31 cpu=146869859.77ms elapsed=766149.07s tid=0x00007fa92fa8b800 nid=30979 runnable  [0x0000700009716000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixPath.compareTo(java.base@20.0.1/UnixPath.java:736)
	at sun.nio.fs.UnixPath.equals(java.base@20.0.1/UnixPath.java:743)
	at java.util.HashMap.getNode(java.base@20.0.1/HashMap.java:578)
	at java.util.HashMap.get(java.base@20.0.1/HashMap.java:564)
	at sun.nio.fs.PollingWatchService$PollingWatchKey.poll(java.base@20.0.1/PollingWatchService.java:372)
	- locked <0x00000007094d5330> (a sun.nio.fs.PollingWatchService$PollingWatchKey)
	at sun.nio.fs.PollingWatchService$PollingWatchKey$1.run(java.base@20.0.1/PollingWatchService.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@20.0.1/Executors.java:577)
	at java.util.concurrent.FutureTask.runAndReset(java.base@20.0.1/FutureTask.java:358)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@20.0.1/ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@20.0.1/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@20.0.1/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"Watcher for file changes in /" #49 [34819] prio=1 os_prio=31 cpu=27.36ms elapsed=766148.98s tid=0x00007fa92fa90800 nid=34819 waiting on condition  [0x000070000981a000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x000000070c23b138> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@20.0.1/LockSupport.java:371)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@20.0.1/AbstractQueuedSynchronizer.java:519)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@20.0.1/ForkJoinPool.java:3780)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@20.0.1/ForkJoinPool.java:3725)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@20.0.1/AbstractQueuedSynchronizer.java:1707)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(java.base@20.0.1/LinkedBlockingDeque.java:485)
	at java.util.concurrent.LinkedBlockingDeque.take(java.base@20.0.1/LinkedBlockingDeque.java:673)
	at sun.nio.fs.AbstractWatchService.take(java.base@20.0.1/AbstractWatchService.java:118)
	at com.edgar.site.WebSite.lambda$startWatcherThread$2(Unknown Source)
	at com.edgar.site.WebSite$$Lambda$185/0x0000000801162fa8.run(Unknown Source)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"FileSystemWatcher" #44 [35843] daemon prio=5 os_prio=31 cpu=4017956.39ms elapsed=766149.19s tid=0x00007fa92fa90e00 nid=35843 waiting on condition  [0x000070000940e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x000000071852ec18> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@20.0.1/LockSupport.java:269)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@20.0.1/AbstractQueuedSynchronizer.java:1758)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@20.0.1/ThreadPoolExecutor.java:1070)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@20.0.1/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@20.0.1/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"FileSystemWatcher" #48 [30979] daemon prio=5 os_prio=31 cpu=146869859.77ms elapsed=766149.07s tid=0x00007fa92fa8b800 nid=30979 runnable  [0x0000700009716000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixPath.compareTo(java.base@20.0.1/UnixPath.java:736)
	at sun.nio.fs.UnixPath.equals(java.base@20.0.1/UnixPath.java:743)
	at java.util.HashMap.getNode(java.base@20.0.1/HashMap.java:578)
	at java.util.HashMap.get(java.base@20.0.1/HashMap.java:564)
	at sun.nio.fs.PollingWatchService$PollingWatchKey.poll(java.base@20.0.1/PollingWatchService.java:372)
	- locked <0x00000007094d5330> (a sun.nio.fs.PollingWatchService$PollingWatchKey)
	at sun.nio.fs.PollingWatchService$PollingWatchKey$1.run(java.base@20.0.1/PollingWatchService.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@20.0.1/Executors.java:577)
	at java.util.concurrent.FutureTask.runAndReset(java.base@20.0.1/FutureTask.java:358)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@20.0.1/ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@20.0.1/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@20.0.1/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"Watcher for file changes in /" #49 [34819] prio=1 os_prio=31 cpu=27.36ms elapsed=766148.98s tid=0x00007fa92fa90800 nid=34819 waiting on condition  [0x000070000981a000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x000000070c23b138> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@20.0.1/LockSupport.java:371)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@20.0.1/AbstractQueuedSynchronizer.java:519)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@20.0.1/ForkJoinPool.java:3780)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@20.0.1/ForkJoinPool.java:3725)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@20.0.1/AbstractQueuedSynchronizer.java:1707)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(java.base@20.0.1/LinkedBlockingDeque.java:485)
	at java.util.concurrent.LinkedBlockingDeque.take(java.base@20.0.1/LinkedBlockingDeque.java:673)
	at sun.nio.fs.AbstractWatchService.take(java.base@20.0.1/AbstractWatchService.java:118)
	at com.edgar.site.WebSite.lambda$startWatcherThread$2(Unknown Source)
	at com.edgar.site.WebSite$$Lambda$185/0x0000000801162fa8.run(Unknown Source)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"FileSystemWatcher" #64 [44039] daemon prio=5 os_prio=31 cpu=5737558.94ms elapsed=766148.18s tid=0x00007fa92fa94000 nid=44039 waiting on condition  [0x000070000a135000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x00000007093bf490> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@20.0.1/LockSupport.java:269)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@20.0.1/AbstractQueuedSynchronizer.java:1758)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@20.0.1/ThreadPoolExecutor.java:1070)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@20.0.1/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@20.0.1/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"Watcher for file changes in Unnamed" #67 [85763] prio=1 os_prio=31 cpu=0.22ms elapsed=766148.03s tid=0x00007fa93239bc00 nid=85763 waiting on condition  [0x000070000a33b000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x00000007093bf678> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@20.0.1/LockSupport.java:371)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@20.0.1/AbstractQueuedSynchronizer.java:519)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@20.0.1/ForkJoinPool.java:3780)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@20.0.1/ForkJoinPool.java:3725)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@20.0.1/AbstractQueuedSynchronizer.java:1707)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(java.base@20.0.1/LinkedBlockingDeque.java:485)
	at java.util.concurrent.LinkedBlockingDeque.take(java.base@20.0.1/LinkedBlockingDeque.java:673)
	at sun.nio.fs.AbstractWatchService.take(java.base@20.0.1/AbstractWatchService.java:118)
	at com.edgar.site.WebSite.lambda$startWatcherThread$2(Unknown Source)
	at com.edgar.site.WebSite$$Lambda$297/0x0000000801338f68.run(Unknown Source)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"FileSystemWatcher" #70 [84739] daemon prio=5 os_prio=31 cpu=363118.93ms elapsed=766147.94s tid=0x00007fa92fabaa00 nid=84739 waiting on condition  [0x000070000a644000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x000000070c240038> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@20.0.1/LockSupport.java:269)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@20.0.1/AbstractQueuedSynchronizer.java:1758)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@20.0.1/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@20.0.1/ThreadPoolExecutor.java:1070)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@20.0.1/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@20.0.1/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

"Watcher for file changes in Unnamed" #71 [84483] prio=1 os_prio=31 cpu=0.22ms elapsed=766147.93s tid=0x00007fa92fabd000 nid=84483 waiting on condition  [0x000070000a747000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@20.0.1/Native Method)
	- parking to wait for  <0x000000070c240190> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@20.0.1/LockSupport.java:371)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@20.0.1/AbstractQueuedSynchronizer.java:519)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@20.0.1/ForkJoinPool.java:3780)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@20.0.1/ForkJoinPool.java:3725)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@20.0.1/AbstractQueuedSynchronizer.java:1707)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(java.base@20.0.1/LinkedBlockingDeque.java:485)
	at java.util.concurrent.LinkedBlockingDeque.take(java.base@20.0.1/LinkedBlockingDeque.java:673)
	at sun.nio.fs.AbstractWatchService.take(java.base@20.0.1/AbstractWatchService.java:118)
	at com.edgar.site.WebSite.lambda$startWatcherThread$2(Unknown Source)
	at com.edgar.site.WebSite$$Lambda$324/0x000000080136e220.run(Unknown Source)
	at java.lang.Thread.runWith(java.base@20.0.1/Thread.java:1636)
	at java.lang.Thread.run(java.base@20.0.1/Thread.java:1623)

etc ... 
```

Looks like your FileWatcher setup in `com.edgar.site.WebSite.lambda$startWatcherThread$2` is using all of your CPU.
Some of those threads have used over 146869859.77 ms (or 1.7 days) of CPU.

Of the Jetty threads, most have under 300ms of total CPU time.
Only the `main` thread (the one on `Server.start` + `Server.join`) is higher, at 2217 ms CPU.

This isn't a Jetty issue.

**Comment by jmcc0nn3ll** [comment] 2023-10-26 11:52
Could this be that classic problem of temp files being written someplace
and a weekly O/S process cleaning things up, driving the JVM insane?

**Comment by joakime** [comment] 2023-10-26 11:59
@jmcc0nn3ll Doesn't look like it.
The FileWatcher that's going nuts is in the `com.edgar.site.WebSite` codebase.
AFAIK, Jetty 10 doesn't use a FileWatcher.

**Comment by paulpalaszewski** [comment] 2023-10-26 13:02
Thanks for the help! That FileSystemWatchers are definitely mine. Missed them by looking at the WAITING state.

A quick first check our code looks ok .. will need to dig further into it to understand if the issue is with us or within jdks FileWatcher. Can confirm, it's not jetty related!

**Comment by joakime** [comment] 2023-10-26 13:28
> A quick first check our code looks ok .. will need to dig further into it to understand if the issue is with us or within jdks FileWatcher. Can confirm, it's not jetty related!

Add some DEBUG logging to the events that FileWatcher generates.
You can always turn it on/off DEBUG at runtime to gather information for a short time.
It might point to something either about your FileSystem, or how you are processing the events.

**Comment by joakime** [comment] 2023-10-26 13:28
Closing, as Not A Bug.

**Closed as not planned by joakime** 2023-10-26 13:28 UTC
Labels: Not a bug
