### ISSUE TITLE
Client waits forever for cancelled large uploads

### ISSUE THREAD

**Issue by LG987234122** [eclipse/jetty.project#2530] opened 2018-05-14 07:38 UTC
The test below simply POSTs a payload of increasing size to a Jetty server. With Jetty 9.4.9+ the client waits forever once it reaches 64KB payload size. With Jetty 9.4.8 the client receives an EOF exception @ 32KB payload size.

The client is a Jetty HttpClient, though I've tried using HttpURLConnection also and the behaviour appears the same, so seems to be server related.

[JettyIssueVersion_9_4_9.zip](https://github.com/eclipse/jetty.project/files/1999743/JettyIssueVersion_9_4_9.zip)

**Comment by sbordet** [comment] 2018-05-14 08:59
I tried your example with Jetty 9.4.9.v20180320, and I don't see Jetty waiting forever.
The client sees the server closing the connection because the server does not read the request content.

**Comment by LG987234122** [comment] 2018-05-14 09:36
Hi

Yes the server closing the connection is what I would expect as well, though that's not what I'm seeing in Jetty 9.4.9 and Jetty 9.4.10 - the client gets stuck as it appears not to receive any response in this trivial test case. Jetty 9.4.8 works fine.

Client gets stuck seemingly forever:

Unsafe.park(boolean, long) line: not available [native method]	
LockSupport.park(Object) line: 175	
CountDownLatch$Sync(AbstractQueuedSynchronizer).parkAndCheckInterrupt() line: 836	
CountDownLatch$Sync(AbstractQueuedSynchronizer).doAcquireSharedInterruptibly(int) line: 997	
CountDownLatch$Sync(AbstractQueuedSynchronizer).acquireSharedInterruptibly(int) line: 1304	
CountDownLatch.await() line: 231	
FutureResponseListener.get() line: 100	
HttpRequest.send() line: 684	
JettyIssueVersion_9_4_9.performAttackJettyClient() line: 78	
JettyIssueVersion_9_4_9.main(String[]) line: 28

**Comment by sbordet** [comment] 2018-05-14 09:44
As I said, I cannot reproduce running your class - works fine for me.
Do you have evidence via DEBUG logs or network trace that the server is not closing the connection ?

**Comment by LG987234122** [comment] 2018-05-14 10:14
Hi - see attached debug logs. Hopefully this shows the issue. Thanks.

[output.txt](https://github.com/eclipse/jetty.project/files/2000245/output.txt)

**Comment by sbordet** [comment] 2018-05-15 16:12
Windows; JDK 8u162; Jetty 9.4.10.

What seems to happen is this:

* the client starts to write the request content
* the server returns a 404 without reading the request content
* client continues to write the request content
* server closes the connection because of unconsumed input
* client tries to write more request content, but writes 0 because it  becomes TCP congested
* client registers for OP_WRITE and waits

The pending write from the client should have generated an `IOException` because the server closed the connection, but I can't see this `IOException` in the logs and I always see it on Linux.

**Comment by sbordet** [comment] 2018-05-15 16:12
@joakime when back, can you look at this on Windows ?

**Comment by joakime** [comment] 2018-06-28 16:58
This can be replicated using the project - https://github.com/joakime/jetty-client-issue-2530
Which is slightly modified from @LG987234122 

```
2018-06-28 11:54:12.590:INFO::main: Logging initialized @189ms to org.eclipse.jetty.util.log.StdErrLog
2018-06-28 11:54:12.715:INFO:oejs.Server:main: jetty-9.4.9.v20180320; built: 2018-03-20T07:21:10-05:00; git: 1f8159b1e4a42d3f79997021ea1609f2fbac6de5; jvm 1.8.0_162-b12
2018-06-28 11:54:12.904:INFO:oejs.AbstractConnector:main: Started ServerConnector@3419866c{HTTP/1.1,[http/1.1]}{0.0.0.0:8888}
2018-06-28 11:54:12.904:INFO:oejs.Server:main: Started @504ms
****************** REQUEST size=32768
****************** REQUEST size=32768; RESPONSE=404
****************** REQUEST size=65536
****************** REQUEST size=65536; RESPONSE=404
...(snip)...
****************** REQUEST size=753664
****************** REQUEST size=753664; RESPONSE=404
****************** REQUEST size=786432
```

**Comment by joakime** [comment] 2018-06-28 17:01
NIO Hang also occurs in 9.4.11.v20180605 (with JDK 8u162)

**Comment by joakime** [comment] 2018-06-28 17:06
The NIO Hang also occurs on Java 9.0.4, 10.0.1, and 11+ea19

**Comment by sbordet** [comment] 2018-07-04 17:07
@joakime let's schedule a hangout to debug this when you're free.

**Comment by sbordet** [comment] 2018-07-06 16:21
The difference between 9.4.8 and 9.4.11 is that in 9.4.8 we wake up the selector after `SocketChannel.close()` because we run `DestroyEndPoint` as a selector action (while in 9.4.9+ is run as a job by the thread pool).

Waking up the selector apparently tells the TCP stack that the socket is closed and the server replies with a TCP RST to what the client writes.

In 9.4.11 the selector is not woken up and the TCP stack continues to send TCP ACKs to the client until the client socket is congested, at which point the client registers for `OP_WRITE` but nobody on the server is there to drain the buffers - the client is now stuck.

We modified 9.4.11 by adding an empty selector wakeup after `DestroyEndPoint` is submitted to the thread pool, and the error goes away.

This seems a Windows NIO bug to me.

**Comment by sbordet** [comment] 2018-07-06 16:22
http://mail.openjdk.java.net/pipermail/nio-dev/2018-July/005294.html

**Comment by sbordet** [comment] 2018-07-09 07:41
@gregw as per discussion link above, we must wake up the selector after closing a socket.

**Comment by joakime** [comment] 2018-07-09 13:56
On Windows, running JDK 11-ea+21 the NIO bug is not present (no need for PR/patch to function).
Perhaps any patch for this issue should be disabled for JDK 11+?

**Closed** 2018-07-11 10:02 UTC
Labels: Bug, Windows
