### ISSUE TITLE
Jetty rejects encoded URIs with HTTP/2

### ISSUE THREAD

**Issue by npantelic** [eclipse/jetty.project#7766] opened 2022-03-22 08:13 UTC
**Jetty version(s)**
`9.4.44.v20210927`

**Java version/vendor**
`Open JDK version 11.0.14.1`

**OS type/version**
Both MacOS and Linux.

**Description**
Jetty does not accept encoded URIs over HTTP/2. It returns `<h1>Bad Message 400</h1><pre>reason: Ambiguous path separator</pre>`

**How to reproduce?**
- Use HTTP/2 connector (with ALPN; in my case with chained protocols `h2, h2-17, http/1.1`).
- Encode URI - `/` -> `%2f` 
- Jetty returns `<h1>Bad Message 400</h1><pre>reason: Ambiguous path separator</pre>`

Notes: 
- with HTTP/1.1 it works just fine (with default http compliance mode)
- URIs in canonical form does not make a problem
     - `https://{host}:{port}/path%2Fsomething%2fsomethingelse` -> works with `HTTP/1.1`, but not with `HTTP/2`
     - `https://{host}:{port}/path/something/somethingelse`-> works with both `HTTP/1.1` and `HTTP/2`
- other encoded chars also make a problem
     
Could http compliance mode be set on http 2 connection factory or is there any workaround. Is this a known issue?

**Comment by joakime** [comment] 2022-03-22 12:52
Seems that Issue #7710 is related

**Comment by joakime** [comment] 2022-03-22 12:52
Or you can move to Jetty 10.0.x which has HttpCompliance and UriCompliance across all Connection Factories.

**Comment by sbordet** [comment] 2022-03-23 20:57
Duplicate of #7710.

**Closed as completed by sbordet** 2022-03-23 20:57 UTC
Labels: Bug

**Comment by npantelic** [comment] 2022-03-24 08:02
@joakime Thanks for the answer, it helped 😄
