### ISSUE TITLE
WebSockClient handling large websocket messages causes increased heap usage within MappedByteBufferPool

### ISSUE THREAD

**Issue by dcitron** [eclipse/jetty.project#6127] opened 2021-04-02 14:58 UTC
**Jetty version**
9.4.31.v20200723

**Java version**
1.8.0_282

**OS type/version**
CentOS Linux release 7.7.1908 (Core)

**Description**
We are experiencing a large amount of memory consumption when using `org.eclipse.jetty.websocket.client.WebSocketClient` with Jetty version 9.4.31.v20200723. 

We traced the memory utilization back to `org.eclipse.jetty.io.MappedByteBufferPool`. If we understand correctly, this class allocates `ByteBuffers` for different storage sizes in factor increments. When a request to `acquire()` comes into that class, the buffer is granted to the requestor, and the bucket is checked back into the map when the requestor calls `release()`. If multiple threads request the same bucket while the correct sized bucket is already checked out, a new bucket will be created. This all appears to function as expected. The issue we are facing is the large number of large-ish buckets that are allocated.

Our WebSocket maximums are below. As we can see, we can have a maximum overall message size of 20MB. Are these sizes realistic?
```
   - MaxBinaryMessageBufferSize(1024 * 512)
   - MaxTextMessageBufferSize(1024 * 512)
   - MaxTextMessageSize(1024 * 1024 * 20)
   - MaxBinaryMessageSize(1024 * 1024 * 20)
   - InputBufferSize(1024 * 256)
```

Notably, a buffer is acquired for the entire message size for each received message. As such, the factors that we can see contributing to this class utilizing a large amount of memory are:
- Multiple large allocation requests that are only a factor away in size from each other
- Many threads all asking for large allocations of the same size at the same time
- A low factor for a large max allocation size
- A large variation in bucket allocation request sizes

A few notes:

1. Our WebSocket implementation uses the Singleton pattern. We use one `WebSocketClient` for all our WebSocket connections (max of let's say 40 per JVM invocation) and we use a new Session for each one. Is this a valid way to use this class?
2. With the above sizes, we've see over 7GB of heap usage from thousands of `ByteBuffers`, ultimately exhausting the heap of an 8GB JVM

I know that recent Jetty updates have allowed the specification of `maxHeapMemory` and `maxDirectMemory` for the Jetty `ByteBufferPool`s -- is the client expected to always call `WebSocketClient.setBufferPool()` with a custom-configured instance?

Noting that, and also the fact that the "servlet" side of the WebSocket communication pair uses an `ArrayByteBufferPool` instantiated by `org.eclipse.jetty.server.ServerConnector` on startup, we ended up simply doing this:

```
webSocketClient.setBufferPool(new ArrayByteBufferPool());
```

Although this means that most calls to `acquire()` will result in non-pooled allocations, performance testing showed that the impact on CPU was negligible, and the (positive) impact on heap is massive.

What is the intended use-case for the default `MappedByteBufferPool` on the client side such that heap is not exhausted? And why does the client-side use `MappedByteBufferPool` but the server side use `ArrayByteBufferPool`?

I see many discussions of this topic from others in various mailing lists but no real resolution.

Thanks so much!
Your heap-exhausting friends.

**Comment by joakime** [comment] 2021-04-02 15:41
I'm assuming you are using Whole Message Delivery (String and ByteBuffer), and not Streaming Message Delivery (InputStream or Reader) to your endpoints.

> 1. Our WebSocket implementation uses the Singleton pattern. We use one WebSocketClient for all our WebSocket connections (max of let's say 40 per JVM invocation) and we use a new Session for each one. Is this a valid way to use this class?

Yes, this is actually the recommended way.

> 2. With the above sizes, we've see over 7GB of heap usage from thousands of ByteBuffers, ultimately exhausting the heap of an 8GB JVM

That's a fair bit of memory usage, but a small maximum memory size for that JVM, especially as you have designed your webapp endpoints to depend on whole message delivery of 20MB messages.

You've actually configured a lower maximum memory that the default in the JVM.

I would recommend disabling `permessage-deflate` extension for a maximum memory configuration like you have.
That's going to be your biggest memory consumer of the buffer pools.

> I know that recent Jetty updates have allowed the specification of `maxHeapMemory` and `maxDirectMemory` for the Jetty ByteBufferPools -- is the client expected to always call `WebSocketClient.setBufferPool()` with a custom-configured instance?

Your configuration for websocket is rather aggressive and will require more memory.
Also, just a small niggle, the WebSocketClient defers to the HttpClient's ByteBufferPool, so you are technically just configuring the `HttpClient.setByteBufferPool(ByteBufferPool)`

And yes, if you want to continue to use that configuration and that JVM maximum memory configuration, you'll have more work on your hands to configure the ByteBufferPool.

What happens if you _do not configure_ the following, and leave them at default? (this will also reduce the memory demands on the ByteBufferPool).

* MaxBinaryMessageBufferSize(1024 * 512)
* MaxTextMessageBufferSize(1024 * 512)
* InputBufferSize(1024 * 256)

But continue to leave these as configured, as they don't use the ByteBufferPool.

* MaxTextMessageSize(1024 * 1024 * 20)
* MaxBinaryMessageSize(1024 * 1024 * 20)

We have many load testing scenarios with thousands of active websocket connections.
We have scenarios with default message size configs, medium whole message delivery sizes, greater whole message sizes, and scenarios with partial message delivery.
We test with default JVM memory settings on OpenJDK 8 and OpenJDK 11.

**Comment by joakime** [comment] 2021-04-02 15:46
Do you have a reproducer?

We are attempting to to reproduce, but are lacking details of your usage of the websocket APIs.

**Comment by joakime** [comment] 2021-04-02 15:49
There's also the `org.eclipse.jetty.io.NullByteBufferPool` implementation that doesn't pool buffers.
Probably a good thing for JVM that is as memory constrained as yours.

**Comment by joakime** [comment] 2021-04-06 15:26
This appears to be fixed in WebSocket on Jetty 10.0.2 already, with the introduction of synthetic frames / autoFragment configuration on WebSocket read.

The problem in Jetty 9.4.x the read of a Frame is done in it's entirety, so a 10MB Frame results in a 20MB ByteBuffer allocated for each frame.
And if you mix in things like Streaming APIs (InputStream, Reader, etc) then there's even a double 20MB ByteBuffer allocation! (eek!)

In Jetty 10.0.x this large frame can be split into smaller synthetic Frames via the autoFragment configuration (which is set to true by default).
This fixes the memory issue for large frames in WebSocket.
Backporting this feature will result in far too many Jetty 9.4.x API incompatible changes to the WebSocket layer to support synthetic frames properly.

**Comment by dcitron** [comment] 2021-04-07 02:00
Oh, thank you for getting back to me on that, @joakime 

I was going to work on a reproducer this week but if it's already fixed in 10.0.2 then there's no point. Rather, let me spend a little time to ensure that the issue is solved for us in 10.0.2 and I'll reply back here with my results within a day or two. Thank you again!

**Comment by qtxo** [comment] 2021-04-12 04:58
Is 10 version production ready?

Is there a guide on how to migrate from 9.4.x to 10? I tried changing the version and adding dependencies by trial and error but still having compilation errors:
- Configuration.ClassList cannot be resolved to a type
- The constructor ServletHolder(ChatWebsocket) is undefined
- ServletUpgradeRequest cannot be resolved to a type
- WebSocketServlet cannot be resolved to a type

**Comment by lachlan-roberts** [comment] 2021-04-12 05:16
@qtxo yes Jetty 10 is production ready. I don't think there is any migration guide yet.

The websocket classes you need to use for the Jetty WebSocket Server API were previously in the `websocket-servlet` jar but are now in the `websocket-jetty-server` jar. The following classes have been renamed and moved from the `org.eclipse.jetty.websocket.servlet` package into `org.eclipse.jetty.websocket.server`:

`WebSocketCreator` -> `JettyWebSocketCreator`
`ServletUpgradeRequest` -> `JettyServerUpgradeRequest`
`ServletUpgradeResponse` -> `JettyServerUpgradeResponse`
`WebSocketServlet` -> `JettyWebSocketServlet`
`WebSocketServletFactory` -> `JettyWebSocketServletFactory`


As for the `Configuration.ClassList`, I think that has been replaced by `org.eclipse.jetty.webapp.Configurations`.

**Comment by dcitron** [comment] 2021-04-13 05:50
Alright, @joakime -- I got our codebase working (temporarily) with JDK11 and Jetty 10.0.2. 

As a side-note, it was a slight challenge to figure out how to migrate to Jetty 10. The current [WebSocket documentation](https://www.eclipse.org//jetty/documentation/jetty-10/programming-guide/index.html#pg-client-websocket) is a TODO and I wasn't able to find any migration guides for 9 -> 10 migration, but I finally cloned the **jetty.project** repo and used the examples and tests in there to figure out what to do.

I was going to ask if there was better migration guide somewhere that I didn't happen to come across, but I guess from the discussion above, there isn't.

In any case, my testing indicated that, yes, the new `autoFragment` behavior (which [obeys](https://github.com/eclipse/jetty.project/issues/4152) `maxFrameSize`) works beautifully and our application is able to run properly without massive heap requirements.

I **did** notice that `org.eclipse.jetty.websocket.core.internal.messages.MessageInputStream.read()` is taking a larger percentage of time in Jetty 10 than Jetty 9. In Jetty 9 it kicked around in `java.nio.Buffer.hasRemaining()` a bit, but in Jetty 10 it's taking quite a bit of time in the following call stack:

```
MessageInputStream.read() 
    -> org.eclipse.jetty.util.BufferUtil.append() 
         -> org.eclipse.jetty.util.BufferUtil.flipToFill() 
              -> java.nio.HeapByteBuffer.compact()
```

In a simple test that I ran, processing 1,000 messages, it actually seemed to spend 24% of its time in `HeapByteBuffer.compact()` so maybe that's something you might want to look into further, or maybe it's just a memory-vs-CPU tradeoff.

I **_am_** curious about one thing you said above, regarding our Xmx of 8GB:

> That's a fair bit of memory usage, but a small maximum memory size for that JVM, especially as you have designed your webapp endpoints to depend on whole message delivery of 20MB messages.
> You've actually configured a lower maximum memory that the default in the JVM.

Why do you say that an Xmx of 8GB is lower than the default in the JVM? The JVM defaults to 25% of system RAM, but I never said how much system RAM we have ... What would you think a reasonable Xmx would be for our configuration?

A final question: I'm curious about the architectural decision to use a `MappedByteBufferPool` by default on the WebSockClient side but an `ArrayByteBufferPool` by default on the WSServlet (`ServerConnector`) side -- WebSocket connections are kinda symmetrical once established, so why the difference in pooling strategy?

**Comment by lachlan-roberts** [comment] 2021-04-13 13:35
> In a simple test that I ran, processing 1,000 messages, it actually seemed to spend 24% of its time in HeapByteBuffer.compact() so maybe that's something you might want to look into further, or maybe it's just a memory-vs-CPU tradeoff.

I have been looking into this one and think I have a fix. I have opened a separate issue to track this (see #6166).

**Comment by sbordet** [comment] 2021-05-20 09:18
@lachlan-roberts is this resolved?

**Comment by lachlan-roberts** [comment] 2021-05-20 14:09
I'm going to close this as it seems to have been fixed from upgrading to 10.

> A final question: I'm curious about the architectural decision to use a MappedByteBufferPool by default on the WebSockClient side but an ArrayByteBufferPool by default on the WSServlet (ServerConnector) side -- WebSocket connections are kinda symmetrical once established, so why the difference in pooling strategy?

@dcitron This is due to historical reasons I think, but you should not notice any difference between using the two of them.

>it was a slight challenge to figure out how to migrate to Jetty 10. The current WebSocket documentation is a TODO and I wasn't able to find any migration guides for 9 -> 10 migration

In the upcoming 10.0.3 release which should be in the next few days, there is documentation for websocket in the "Operations Guide", documentation for the websocket client usage in the "Programming Guide", and also a 9.4 -> 10 websocket migration guide.

**Closed as completed by lachlan-roberts** 2021-05-20 14:09 UTC
