### ISSUE TITLE
WebSocket connection fails on 9.2.15

### ISSUE THREAD

**Issue by tananaev** [eclipse/jetty.project#395] opened 2016-03-05 03:16 UTC
I have embedded Jetty version 9.2.15.v20160210 in my application.

Sometimes (possibly under high load) server fails to accept WebSocket connection. Digging into the problem I found that browser sends `Connection:Upgrade` header, but when it gets to the web socket servlet it changes to `Connection:keep-alive`.

Does Jetty replace request header for some reason? If yes, what is the reason?

After I restart my app it works for some time, but then starts to fail again with the same problem. Maybe there is some limit or leaked resource that results in this behaviour?

Any ideas on why it could be happening and how to fix it?

Thanks

**Comment by gregw** [comment] 2016-03-05 09:29
Jetty should not be adding any Connection headers to an incoming request.

It is far more likely that such a header has been added by an intermediary/proxy and probably an old one at that.  `Connection:keep-alive` is a HTTP/1.0 header and is not required by HTTP/1.1.   I suspect that either your clients network or your network has an old proxy in it?

**Comment by tananaev** [comment] 2016-03-05 11:44
Looks like you are right. I just captured network packets on my server and headers are already changed by the time request reaches the server.

**Comment by joakime** [comment] 2016-03-07 23:14
Closing as not a bug

**Closed by joakime** 2016-03-07 23:14 UTC
