### ISSUE TITLE
Emit warning when invoking deprecated method in Jetty XML

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3713] opened 2019-05-30 15:55 UTC
Jetty XML files are essentially Java code in XML format.

However, it is easy to remove a deprecated method/getter/setter and forgetting to update the relevant XML.

We should emit a WARN log when invoking a deprecated method/getter/setter so that users can see it in the logs and update their custom XML files.

**Comment by joakime** [comment] 2019-06-04 22:05
The warnings are good.
However now we need to evaluate if our deprecations still make sense. ;-)

Take for example, the weld configuration ...
http://docs.jboss.org/weld/reference/latest/en-US/html/environments.html#_class_loading

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
   <Call name="prependServerClass">
      <Arg>-org.eclipse.jetty.util.Decorator</Arg>
   </Call>
   <Call name="prependServerClass">
      <Arg>-org.eclipse.jetty.util.DecoratedObjectFactory</Arg>
   </Call>
   <Call name="prependServerClass">
      <Arg>-org.eclipse.jetty.server.handler.ContextHandler.</Arg>
   </Call>
   <Call name="prependServerClass">
      <Arg>-org.eclipse.jetty.server.handler.ContextHandler</Arg>
   </Call>
   <Call name="prependServerClass">
      <Arg>-org.eclipse.jetty.servlet.ServletContextHandler</Arg>
   </Call>
</Configure>
```

This will trigger for each `WebAppContext.prependServerClass` call.
Do we want to keep this? 
Or change the deprecation?  and/or notify Weld of a better way?
@gregw what do you think?

**Comment by gregw** [comment] 2019-06-05 07:23
@joakime, I don't mind verbose deprecated warnings.... it will encourage the bad configs to be changed.   In this case the xml can probably be updated to:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Get name="serverClasspathPattern">
   <Call name="add">
      <Arg>-org.eclipse.jetty.util.Decorator</Arg>
   </Call>
   <Call name="add">
      <Arg>-org.eclipse.jetty.util.DecoratedObjectFactory</Arg>
   </Call>
   <Call name="add">
      <Arg>-org.eclipse.jetty.server.handler.ContextHandler.</Arg>
   </Call>
   <Call name="add">
      <Arg>-org.eclipse.jetty.server.handler.ContextHandler</Arg>
   </Call>
   <Call name="add">
      <Arg>-org.eclipse.jetty.servlet.ServletContextHandler</Arg>
   </Call>
  </Get>
</Configure>
```

**Comment by joakime** [comment] 2019-06-06 14:59
@sbordet the errors produced are not 100% correct.

For example, when using the CDI2 module, I see the following with "null" present as for where the problem is ...

```
2019-06-06 09:56:31.039:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 2019-06-06 09:56:31.039:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///Users/joakim/Code/Jetty/jetty.project-9.4.x/tests/test-distribution/target/tests/test-bases/jetty_base_8092586306892231175/webapps/] at interval 1
2019-06-06 09:56:31.086:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 2019-06-06 09:56:31.086:WARN:oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.webapp.WebAppContext.prependServerClass(java.lang.String) in null
2019-06-06 09:56:31.086:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 2019-06-06 09:56:31.086:WARN:oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.webapp.WebAppContext.prependServerClass(java.lang.String) in null
2019-06-06 09:56:31.086:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 2019-06-06 09:56:31.086:WARN:oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.webapp.WebAppContext.prependServerClass(java.lang.String) in null
2019-06-06 09:56:31.086:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 2019-06-06 09:56:31.086:WARN:oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.webapp.WebAppContext.prependServerClass(java.lang.String) in null
2019-06-06 09:56:31.087:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 2019-06-06 09:56:31.087:WARN:oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.webapp.WebAppContext.prependServerClass(java.lang.String) in null
```

**Comment by joakime** [comment] 2019-06-06 15:03
@sbordet the `jetty-9.4.x-3731-cdi-testing` branch can be used to reproduce the above "null" result in the logs.
Use the `CDITests` class in `/test-distribution/` on that branch.

**Comment by joakime** [comment] 2019-06-06 16:06
Closing this (again), as the "in null" is a result of bad XmlConfiguration usage in Jetty.
Opening new issue #3743 to correct that fundamental issue instead.

**Closed by joakime** 2019-06-06 16:06 UTC
