### ISSUE TITLE
Connection reset by server if file upload exceeds size limit

### ISSUE THREAD

**Issue by daniel-kr** [eclipse/jetty.project#12079] opened 2024-07-23 10:12 UTC
**Jetty version(s)**
12.0.10
**Jetty Environment**
ee10
Spring Boot 3.2.7
**Java version/vendor**
openjdk 17.0.11 2024-04-16
**OS type/version**
Mac OS 15.6
**Description**
Our application is based on Spring Boot and uses the embedded Jetty as a web werver.
We recently upgraded from Spring Boot version `3.1.11` to `3.2.7`. With that, Jetty was upgraded from `11.0.20` to `12.0.10`.

After the upgrade, we recognized an odd behavior when it comes to file uploads:

If the uploaded file(s) exceed the configured size limits of `spring.servlet.multipart.max-file-size` or `spring.servlet.multipart.max-request-size`, the server closes the connection instead of responding with an HTTP error response.

I used Firefox for test which clearly indicates the aborted connection. With other browsers, the indication is not that clear.

We then recognized that the same behavior applies to Tomcat as a web server already on Spring Boot version `3.1.11`. For that reason we assumed the issue to be independent of the web server and filed [an issue](https://github.com/spring-projects/spring-boot/issues/41581) on the Spring Boot project. They pointed us to the fact that for Tomcat, this behavior is on purpose and is controlled by the property `maxSwallowSize` as documented [here](https://tomcat.apache.org/tomcat-10.0-doc/config/http.html). We tested it and indeed, changing the mentioned property influences the behavior on Tomcat.

We have not found a similar property for Jetty or a documentation of such a behavior.

Question: Did Jetty 12 introduce a similar feature or is this a bug? If it is a feature, can one influence it via a property?

**How to reproduce?**

1. Clone Spring Boot's [example app](https://github.com/spring-guides/gs-uploading-files)
2. Apply the following changes to the `build.gradle` of the `complete` module in order to use Jetty instead of Tomcat:
```
implementation('org.springframework.boot:spring-boot-starter-web') {
	exclude group:'org.springframework.boot', module:'spring-boot-starter-tomcat'
}
implementation 'org.springframework.boot:spring-boot-starter-jetty'
```
3. Rebuild and execute `UploadingFilesApplication` of the `complete` module
4. Open `localhost:8080` (at best in Firefox) and try to upload a file of at least 4 MB.
5. You should see an error that indicates a reset connection.

**Comment by daniel-kr** [comment] 2024-08-14 13:40
Hello!
Can you already tell if this is a bug or a feature? This would help us to decide if we should adapt our code to the new behavior or if it will be fixed. 🙏 
Thank you!

**Comment by joakime** [comment] 2024-08-14 15:10
Things take longer to debug on spring for us as we ourselves do not use spring.

Jetty doesn't abort with no response if the form is too large.

See https://github.com/jetty/jetty-examples/tree/12.0.x/embedded/ee10-form-post
That is setup to accept `application/x-www-form-urlencoded` and `multipart/form-data` based forms (same as the Servlet spec)
It has been setup to only allow forms up to 128,000 bytes.

Pay particular attention to the test cases https://github.com/jetty/jetty-examples/blob/12.0.x/embedded/ee10-form-post/src/test/java/examples/FormEndpointsTest.java

* `testFormUrlEncodedPostTooBig()` which uses `application/x-www-form-urlencoded` to send a 4MB form, the request fails, the client sees a 400 response, and the response body contents it expects.
* `testMultipartFormPostTooBig()` which uses `multipart/form-data` to send a 180,000 byte form entry, the request fails, the client sees a 400 response, and the response body contents it expects.

**Comment by joakime** [comment] 2024-08-14 15:19
![Screenshot from 2024-08-14 10-16-50](https://github.com/user-attachments/assets/604cfcf8-6945-42ed-bf0b-21eb9e2f266a)

Running the `complete` project on https://github.com/spring-guides/gs-uploading-files results in the above.

The output on console is ...

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.0)

2024-08-14T10:15:17.070-05:00  INFO 53277 --- [           main] c.e.u.UploadingFilesApplication          : Starting UploadingFilesApplication using Java 21.0.3 with PID 53277 (/home/joakim/code/jetty/github/spring-boot-uploading-files/complete/target/classes started by joakim in /home/joakim/code/jetty/github/spring-boot-uploading-files/complete)
2024-08-14T10:15:17.074-05:00  INFO 53277 --- [           main] c.e.u.UploadingFilesApplication          : No active profile set, falling back to 1 default profile: "default"
2024-08-14T10:15:18.106-05:00  INFO 53277 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8080
2024-08-14T10:15:18.110-05:00  INFO 53277 --- [           main] org.eclipse.jetty.server.Server          : jetty-12.0.9; built: 2024-05-03T13:03:17.262Z; git: efe8023327e67287f9bfd006700e6a71d45b5dd6; jvm 21.0.3+9-LTS
2024-08-14T10:15:18.143-05:00  INFO 53277 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2024-08-14T10:15:18.144-05:00  INFO 53277 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1019 ms
2024-08-14T10:15:18.191-05:00  INFO 53277 --- [           main] o.e.j.session.DefaultSessionIdManager    : Session workerName=node0
2024-08-14T10:15:18.196-05:00  INFO 53277 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started osbwej.JettyEmbeddedWebAppContext@78c1372d{application,/,b=file:/tmp/jetty-docbase.8080.15066994030887537288/,a=AVAILABLE,h=oeje10s.SessionHandler@9aa2002{STARTED}}
2024-08-14T10:15:18.197-05:00  INFO 53277 --- [           main] o.e.j.e.servlet.ServletContextHandler    : Started osbwej.JettyEmbeddedWebAppContext@78c1372d{application,/,b=file:/tmp/jetty-docbase.8080.15066994030887537288/,a=AVAILABLE,h=oeje10s.SessionHandler@9aa2002{STARTED}}
2024-08-14T10:15:18.200-05:00  INFO 53277 --- [           main] org.eclipse.jetty.server.Server          : Started oejs.Server@7c551ad4{STARTING}[12.0.9,sto=0] @1768ms
2024-08-14T10:15:18.525-05:00  INFO 53277 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-08-14T10:15:18.525-05:00  INFO 53277 --- [           main] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-08-14T10:15:18.527-05:00  INFO 53277 --- [           main] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2024-08-14T10:15:18.541-05:00  INFO 53277 --- [           main] o.e.jetty.server.AbstractConnector       : Started ServerConnector@cb39552{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2024-08-14T10:15:18.544-05:00  INFO 53277 --- [           main] o.s.b.web.embedded.jetty.JettyWebServer  : Jetty started on port 8080 (http/1.1) with context path '/'
2024-08-14T10:15:18.555-05:00  INFO 53277 --- [           main] c.e.u.UploadingFilesApplication          : Started UploadingFilesApplication in 1.812 seconds (process running for 2.124)
2024-08-14T10:16:17.674-05:00  WARN 53277 --- [tp199000084-109] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded]
2024-08-14T10:16:17.678-05:00  WARN 53277 --- [tp199000084-109] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded]
```

This is not aborting, it is producing a response a 413 in the case of that project.
But that's not what Jetty would produce, that looks like a Spring specific behavior.

**Comment by joakime** [comment] 2024-08-14 15:22
Cannot replicate the bug report.
Jetty is behaving as expected, no abort seen.
Spring boot example is also behaving within the norms of HTTP, no abort seen.
Command line and firefox cannot trigger this report.

I'm closing this as unable to replicate, if you have a solid example project that can replicate the situation, we can reopen this issue.

**Comment by daniel-kr** [comment] 2024-08-16 11:12
Hm, strange. Me and 2 of my colleagues can reproduce this 100%. We use Firefox version `129.0.1`. Two of us use Mac OS and one uses Windows. Which Firefox version and which OS did you use?
<img width="1487" alt="grafik" src="https://github.com/user-attachments/assets/9215fffb-34da-4008-a76d-20ccb09aaa89">

**Comment by sbordet** [comment] 2024-08-16 13:34
@daniel-kr we need more evidence from you, as apparently we cannot replicate.

Do you have the Jetty server DEBUG logs that show that it is a Jetty issue?

**Comment by daniel-kr** [comment] 2024-08-19 13:32
I managed to reproduce the issue with [this example](https://github.com/jetty/jetty-examples/blob/12.0.x/embedded/file-upload/src/main/java/examples/MultipartMimeUploadExample.java) from the jetty project. Specifically, with the "Upload to Servlet version" upload function.

I modified it a bit by removing the SSL stuff to be able to run it with http connection, and by changing `maxFileSize` and `maxRequestSize` to 128 KB.

I also enabled debug logging and analyzed the network traffic with Wireshark. [Attached](https://github.com/user-attachments/files/16660732/logs.zip) you find the results.

I compared Jetty 11, Jetty 12 with Firefox and Chrome.

Both browsers with Jetty 11: HTTP 500 is returned and the connection is **not** closed.
<img width="1653" alt="grafik" src="https://github.com/user-attachments/assets/67af3a64-f169-4dd2-9824-ec7fe6603907">

Both browsers with Jetty 12: HTTP 400 is returned and the server closes the connection afterwards.
<img width="1620" alt="grafik" src="https://github.com/user-attachments/assets/7084819c-f755-4060-8803-ddd909925188">

It seems as if the two browsers can only cope differently with the situation of a closed connection. While Chrome shows the HTTP 400, Firefox shows the connection reset.

I don't know if this is related but in the debug logs of Jetty 12, this exception is logged when the connection is closed:
```
org.eclipse.jetty.io.RuntimeIOException: Parser is terminated
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:558)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:383)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by joakime** [comment] 2024-08-19 13:53
If the parser is failing, then your client terminated, not the server.
Do you have any kind of web security software installed on your workstation that is interacting with this test?

Tried your latest report on firefox...

![Screenshot from 2024-08-19 08-52-24](https://github.com/user-attachments/assets/be0aaa07-6a62-4b28-b080-f563b1e809ca)

It works there too.

**Comment by joakime** [comment] 2024-08-19 13:55
Actually, I see the parser now as as the parsing of the request buffer, (so it's past the request line and headers).
This is probably you catching the parsing of the Multipart form.

Let me commit the SSL fix and maxFileSize changes to that example ...

**Comment by joakime** [comment] 2024-08-19 14:03
Committed a change for how SSL is enabled in that example project.
I left the max file size settings alone, and just uploaded a 400MB file instead to trip over the 10MB limit.

In both SSL and non-SSL the abort can be seen.

![Screenshot from 2024-08-19 09-03-12](https://github.com/user-attachments/assets/e271c2f0-98c3-4e34-b730-af9f906e6a8d)

**Comment by daniel-kr** [comment] 2024-08-19 14:25
Great that you could reproduce it. 😃 

> If the parser is failing, then your client terminated, not the server.

If I interpret the Wireshark logs correctly, the server closes the connection but I might be mistaken.
<img width="1087" alt="grafik" src="https://github.com/user-attachments/assets/78a85234-9f46-4986-a4bf-f226fa3489f3">

> Do you have any kind of web security software installed on your workstation that is interacting with this test?

Not that I am aware of. 🤔 I also executed in a private tab with all extension disabled.

Maybe timing influences if Firefox shows the HTTP error result or the connection reset. 🤷‍♂️

**Comment by joakime** [comment] 2024-08-19 17:38
Looks like the 400 response is actually sent.
And then we close.

![Screenshot from 2024-08-19 12-37-08](https://github.com/user-attachments/assets/67fc1e80-29b1-47ab-bb5c-5ee49cbeaac1)

This is turning out to be a strange behavior of the web browser.

**Comment by daniel-kr** [comment] 2024-08-20 08:46
Is this behavior change of Jetty 12 intentional? As said in the initial description, Tomcat does something similar and there it is a feature which can be influenced by a property. If it is intentional, then maybe Firefox is not dealing with it correctly.

On the other hand, we also have some [rest-assured](https://rest-assured.io/) tests dealing with file uploads that occasionally fail with a broken pipe error after we updated to Jetty 12. There, it occurs only randomly. But it seems to be related. 

Is it maybe possible that Jetty closes the connection prematurely somehow? 🤔

**Comment by sbordet** [comment] 2024-08-20 09:41
> Is it maybe possible that Jetty closes the connection prematurely somehow? 🤔

The logs and the wireshark capture show that we read the request content up to the max configured.
At that point, Jetty stops reading the request content and sends the response.

As part of sending the response, Jetty makes an effort to read "leftover" request content, with the idea that if there is only a little bit more to read, Jetty can read it asynchronously ("consuming"), and if it succeeds to read the whole request content, then it may avoid closing the connection.

If it cannot read the whole request content, Jetty will close the connection.

If the connection is closed, the browser may still be busy sending the large request content, and it may not look at the response yet, even if it is already arrived.
The browser will try to write more request content, until it sees a TCP RST due to the fact that the server sent the response and closed the connection, and complain, even if the response arrived already.

The "consuming" we do seems similar to Tomcat's "maxSwallowSize", but not quite the same.
We have `HttpConfiguration.setMaxUnconsumedRequestContentReads(int)` to configure the max number of reads to "consume" request content.

I'm not sure what your expectations are here, but trying to get a predictable behavior for failure cases is hard.
In this case the behavior is influenced by the way the content is split by TCP, by the speed of the network, by the speed of the CPU reading the content, etc., etc., etc. so I am not sure what you're aiming for.

If you're aiming for browsers to report the response rather than a connection reset, you should file an issue with the browsers.

Even configuring Jetty's `maxUnconsumedRequestContentReads` or Tomcat's `maxSwallowSize` will result in unpredictable behavior, depending on the network: sometimes the server will be able to read the whole request content, some other times it won't be able to.

From the Jetty point of view, I don't see what else we can do?
We try to read the request, it's too large, we send the proper response, we even try harder to "consume" in order to not close the connection, but eventually we have to.
We also have to be really careful to not allocate too many resources (network bandwidth, CPU to read request content, memory, etc.) for a failed request, or that would be an attack vector.

**Comment by daniel-kr** [comment] 2024-08-20 11:40
Thanks for your detailed explanation.
I basically want to understand if this is a bug or a feature. For us, this behavior of closing the connection after sending the error response suddenly appeared when updating to Jetty 12. And we just did not know where that came from. Jetty 11 does not close the connection in this situation and we haven't found anything regarding this in the release notes of Jetty 12.

If I understood you correctly, this is intentional behavior of Jetty 12 in order to prevent certain attack vectors similar to how Tomcat does it. Right?

In that case, we will adapt our code accordingly and probably file an issue on Mozilla Firefox.

**Comment by sbordet** [comment] 2024-08-20 11:57
> For us, this behavior of closing the connection after sending the error response suddenly appeared when updating to Jetty 12.

I doubt. It was probably the case that in Jetty 11 you were somehow luckier.

> Jetty 11 does not close the connection in this situation and we haven't found anything regarding this in the release notes of Jetty 12.

Also Jetty 11 is closing the connection.

So this is not a bug or a feature. It's the same behavior that was in Jetty 11, just now a little more evident.

It is intentional behavior that we send a response and then we close the connection, this is how HTTP/1.1 must be handled, independently of everything else.

The mention I made about the attack vector was just informative, applications should not be concerned.
It was only to avoid you asking "can you please avoid closing the connection or reading the whole request content so that the browser displays the correct response page" (or similar) -- something that we cannot do.

FTR, Jetty's `HttpClient` would present the response and all its information, and report that the request failed to complete.
So, from the client library perspective, it is doable to understand what's going on: the request failed to complete the upload, but the response arrived completely.

I have to say that it is unfortunate that browsers display a crappy page, rather than the response that arrives (which may have been a nicely formatted application response in case of errors).

**Comment by daniel-kr** [comment] 2024-08-20 12:27
> Also Jetty 11 is closing the connection.

That is not what I have seen when executing the mentioned example in the Jetty project with Jetty 11. In the Wireshark logs you do not see a connection reset. Strangely, it returns a 500 in that case instead of a 400. Maybe this is rather a bug in Jetty 11 then? 🤔 

Don't get me wrong, it is not about blaming. I just wanted to understand the root cause. Could have been a bug so I thought it would be a good idea to report it.

It makes sense to close the connection in that case. So Jetty 12 seems to do this more correctly than Jetty 11. 👍 Also, it is consistent with Tomcat's behavior in this case. 👍 

So after you confirmed that this is intentional behavior, I think we can close the issue.

Thank you!

**Comment by sbordet** [comment] 2024-08-20 12:49
Could just be that Jetty 11 was slower at replying, and gave time to the whole request content to arrive at the server so it could be fully "consumed".

Change the request content to be larger, and you'd see the connection close.

Or change to Jetty 12 where perhaps the response is faster, so less time to read fully the request content, and most of the times the connection is closed.

Or slow down the network.

Or change from bare metal hardware to Docker/Kubernetes.

Or tomorrow we deploy an optimization in Jetty 11 and now it behaves like Jetty 12.

My point being the following: writing a reliable test for this case is hard, and relying on some specific behavior is wrong, because there are so many variables at play.
You see one combination working, you assume from that, but then a butterfly flaps its wings, and everything changes.

**Closed as completed** 2024-08-27 12:54 UTC
Labels: Bug

**Comment by jesa29** [comment] 2024-11-26 12:05
Issue is still happening. The funny thing is: if I enable TRACE logs, or if I enable jetty.accesslog - server slows down and all works fine. Is this an expected behavior?
