### ISSUE TITLE
Setuid module incorrect JAR reference

### ISSUE THREAD

**Issue by chiralsoftware** [eclipse/jetty.project#5815] opened 2020-12-16 00:18 UTC
Steps to reproduce:

```
$ wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/10.0.0/jetty-home-10.0.0.tar.gz
...
$ md5sum jetty-home-10.0.0.tar.gz 
3b2f412ae80ec916248edd7860d77b1d  jetty-home-10.0.0.tar.gz
$ tar xf jetty-home-10.0.0.tar.gz
$ mkdir jetty-base
$ cd jetty-base/
$ java -jar ../jetty-home-10.0.0/start.jar --add-module=setuid
....
$ java -jar ../jetty-home-10.0.0/start.jar 
2020-12-15 16:12:31.169:WARN :oejx.XmlConfiguration:main: Config error java.lang.ClassNotFoundException: org.eclipse.jetty.setuid.SetUIDListener 
....
$ java -jar ../jetty-home-10.0.0/start.jar --show-modules=setuid

     Module: setuid 
           : Enables the UNIX setUID configuration.
           : The server may be started as root to open privileged ports/files before
           : changing to a restricted user (e.g. Jetty).
     Depend: server
        LIB: lib/setuid/jetty-setuid-java-1.0.4.jar
        XML: etc/jetty-setuid.xml
    Enabled: ${jetty.base}/start.d/setuid.ini
$ ls ../jetty-home-10.0.0/lib/setuid/jetty-setuid-java-1.0.*
../jetty-home-10.0.0/lib/setuid/jetty-setuid-java-1.0.3.jar

```

The JAR is wrong.

**Comment by olamy** [comment] 2020-12-16 07:16
I can definitely reproduce.
But it's really strange as those files has not been touched for a while and I can't reproduce with current head of jetty-10.0.x branch

**Comment by janbartel** [comment] 2020-12-16 15:07
It is a bit of a mystery. The versions were definitely updated in jetty-10.0.x branch back in February this year: https://github.com/eclipse/jetty.project/commit/95f20ddfebd27ed05962c849316e6a9df072cf70. How the jetty-10.0.0 tag only has the changes from the .mod file, but not the jetty-home/pom.xml file is ... weird.  If we can work out how the tag came to be missing changes, then we can confidently say this will be fixed by the next release, because HEAD of jetty-10.0.x is consistent.

**Comment by joakime** [comment] 2020-12-16 15:20
The diff between the tag and 10.0.x doesn't show this difference in the jetty-home/pom.xml ??

https://github.com/eclipse/jetty.project/compare/jetty-10.0.0...jetty-10.0.x

The command line shows the difference though ...

``` shell
[joakim@hyperion jetty.project-10.0.x][jetty-10.0.x]$ git log -1 --oneline
6769a83d3d (HEAD -> jetty-10.0.x, origin/jetty-10.0.x) Merge branch 'jetty-9.4.x' into jetty-10.0.x
[joakim@hyperion jetty.project-10.0.x][jetty-10.0.x]$ cd jetty-home
[joakim@hyperion jetty-home][jetty-10.0.x]$ git diff jetty-10.0.0..HEAD -- pom.xml
diff --git a/jetty-home/pom.xml b/jetty-home/pom.xml
index 500acdffa9..7333199363 100644
--- a/jetty-home/pom.xml
+++ b/jetty-home/pom.xml
@@ -3,7 +3,7 @@
   <parent>
     <artifactId>jetty-project</artifactId>
     <groupId>org.eclipse.jetty</groupId>
-    <version>10.0.0</version>
+    <version>10.0.1-SNAPSHOT</version>
   </parent>
   <modelVersion>4.0.0</modelVersion>
   <artifactId>jetty-home</artifactId>
@@ -13,7 +13,8 @@
   <properties>
     <assembly-directory>${basedir}/target/jetty-home</assembly-directory>
     <source-assembly-directory>${basedir}/target/jetty-home-sources</source-assembly-directory>
-    <jetty-setuid-version>1.0.3</jetty-setuid-version>
+    <jetty-setuid-version>1.0.4</jetty-setuid-version>
+    <spotbugs.skip>true</spotbugs.skip>
   </properties>
 
   <build>
@@ -539,14 +540,6 @@
           <skip>true</skip>
         </configuration>
       </plugin>
-      <!-- No point performing Findbugs in assembly project -->
-      <plugin>
-        <groupId>org.codehaus.mojo</groupId>
-        <artifactId>findbugs-maven-plugin</artifactId>
-        <configuration>
-          <skip>true</skip>
-        </configuration>
-      </plugin>
     </plugins>
   </build>
   <dependencies>
[joakim@hyperion jetty-home][jetty-10.0.x]$ 

```

**Comment by joakime** [comment] 2020-12-16 15:56
Here's something equally bizaree, asking git itself which branches and tags the 95f20ddfebd27ed05962c849316e6a9df072cf70 commit is in.

```
$ git log -1 95f20ddfebd27ed05962c849316e6a9df072cf70
commit 95f20ddfebd27ed05962c849316e6a9df072cf70
Author: Greg Wilkins <gregw@webtide.com>
Date:   Thu Feb 27 18:56:16 2020 +0100

    Use updated setuid with clearSupplementalGroups (#4609)
    
    * Use updated setuid with clearSupplementalGroups
    
    Signed-off-by: Greg Wilkins <gregw@webtide.com>
    
    * remove version from setuid.mod
    
    Signed-off-by: Greg Wilkins <gregw@webtide.com>
```

Branches:

```
$ git branch -a --contains 95f20ddfebd27ed05962c849316e6a9df072cf70
* jetty-10.0.x
  jetty-11.0.x
  jetty-9.4.x
  remotes/origin/jetty-10.0.x
  remotes/origin/jetty-11.0.x
  remotes/origin/jetty-9.4.x
```

Tags:

```
$ git tag --contains 95f20ddfebd27ed05962c849316e6a9df072cf70
contains
jetty-10.0.0
jetty-10.0.0.alpha2
jetty-10.0.0.beta1
jetty-10.0.0.beta2
jetty-10.0.0.beta3
jetty-11.0.0
jetty-11.0.0-alpha0
jetty-11.0.0.beta1
jetty-11.0.0.beta2
jetty-11.0.0.beta3
jetty-9.4.27.v20200227
jetty-9.4.28.v20200408
jetty-9.4.29.v20200521
jetty-9.4.30.v20200611
jetty-9.4.31.v20200723
jetty-9.4.32.v20200930
jetty-9.4.33.v20201020
jetty-9.4.34.v20201102
jetty-9.4.35.v20201120
```

So, git thinks that commit is present in tag `jetty-10.0.0`.
That means something else replaced that line of code.

**Comment by olamy** [comment] 2020-12-17 09:31
fixed by https://github.com/eclipse/jetty.project/commit/9b100a5bfb5267635de33ee6317204ccfa04e468

**Closed as completed** 2020-12-17 09:31 UTC
Labels: Bug
