### ISSUE TITLE
NPE - Inflater has been closed

### ISSUE THREAD

**Issue by bistvan** [eclipse/jetty.project#2882] opened 2018-09-04 07:51 UTC
Sometimes when the websocket connection is closed, the exception below is logged out on the server side. After googleing, we figured out, probably it's fine, but this exception, similar the others should be handled by the WebsocketHandler @OnWebSocketError method.

Please help us to find a workaround to be able to handle this issue correctly.
(we are using Jetty library on server and client side as well, version: 9.4.11.)

```
2018-09-03 11:52:51:577 WARN qtp12:
        Error: java.lang.NullPointerException: Inflater has been closed
        Stack trace: org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException: Inflater has been closed
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:228)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:245)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:560)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Inflater has been closed
        at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
        at java.util.zip.Inflater.inflate(Inflater.java:257)
        at java.util.zip.Inflater.inflate(Inflater.java:280)
        at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.decompress(CompressExtension.java:175)
        at org.eclipse.jetty.websocket.common.extensions.compress.DeflateFrameExtension.incomingFrame(DeflateFrameExtension.java:67)
        at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:183)
        at org.eclipse.jetty.websocket.common.extensions.fragment.FragmentExtension.incomingFrame(FragmentExtension.java:57)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        ... 14 more
```

**Comment by joakime** [comment] 2018-09-10 19:31
This appears to be an incoming (compressed) frame after websocket closure.

What we don't know is if the closure was clean (close handshake completed), or if it was abnormal (closed on local side due to error/failure).
This stacktrace alone is insufficient to make that call.

**Comment by joakime** [comment] 2018-11-05 19:13
Closing as we've been unable to replicate this issue.

**Closed by joakime** 2018-11-05 19:13 UTC
Labels: More Info Required, Unable To Replicate

**Comment by leonchen83** [comment] 2019-04-23 06:39
Hi we met this issue too 
```
19-04-22 23:20:33.974 WARN [qtp1682999176-92 AbstractWebSocketConnection.readParse:579]
org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException: Inflater has been closed
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:227)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:244)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:560)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Inflater has been closed
        at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
        at java.util.zip.Inflater.inflate(Inflater.java:257)
        at java.util.zip.Inflater.inflate(Inflater.java:280)
        at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.decompress(CompressExtension.java:175)
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:79)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:219)
        ... 14 common frames omitted
```

**Comment by zcs100** [comment] 2019-11-17 14:33
i encounter same question,can i resolve it?

**Comment by zcs100** [comment] 2019-11-17 14:35
version: 9.4.14
```
org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException: Inflater has been closed
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:227)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:244)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:559)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:390)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
	at java.util.zip.Inflater.inflate(Inflater.java:257)
	at java.util.zip.Inflater.inflate(Inflater.java:280)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.decompress(CompressExtension.java:175)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:79)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:219)
	... 14 common frames omitted
```

**Comment by joakime** [comment] 2019-11-17 14:44
@zcs100 we need a reproduction case, as we are unable to reproduce.
Can you provide one?
