### ISSUE TITLE
What is the proper way to upload a file from a browser to jetty-12 when using Handler.Abstract

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse/jetty.project#10410] opened 2023-08-26 07:24 UTC
I am trying to convert jetty-ee9-servlet to Handler.Abstract.

I have done some testing, and this is what I have.

Test 1: Success
Test 2: Fail

**Test 1:** The client is org.eclipse.jetty.client.HttpClient

On the client side I use this code:

```
			final PathRequestContent pathRequestContent = new PathRequestContent(path);

			final Consumer<HttpFields.Mutable> consumer = httpFields -> {
				httpFields.add(Path.class.getSimpleName(), path.getFileName().toString());
			};

			final Request request = httpClient.POST(uri).body(pathRequestContent).headers(consumer);
			
			final ContentResponse contentResponse = request.send();
```			
**As you can see I passed the file name as part of the headers. is that the proper way ?** 			

On the server side, I use this code: 

I am using ServletToHandlerDocs.java as a guide. (https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/migration/ServletToHandlerDocs.java)

I have Handler.Abstract and the code is similar to the one in ServletToHandlerDocs.java RequestContentAPIsInputStream :

```
try (InputStream inputStream = Content.Source.asInputStream(request)) {
				while (true) {
					final int read = inputStream.read();

					// EOF was reached, stop reading.
					if (read < 0) {
						break;
					}

					// Process the read byte here.
				}
			}
			
```

The handler code IS working just fine. 	

The request.getMethod() I am getting is "POST" 		
			
**Test 2:** The client is a web browser .

On the client side, I use this code:

This is HTML: 

```
<p>
<form method="post" action="/myUploadH" enctype="multipart/form-data">
<label>myServerTests_1.myHandlers.MyHandlerForUpload<br></label><input type="file" name="myUploadFile" required><input type="submit" value="Upload selected file">
</form>
</p>
```

AFAIK, this is the way to upload a file from the browser.  

The request gets to the same Handler.Abstract as test 1. 

The request.getMethod() I am getting is "GET"

Content.Source.asInputStream(request) is empty.

As part of my Handler.Abstract I send back a response that contains the results of calling various request methods:
 
    --------------------------------------------------------------------------------------------------------------------------------
    getHeaders
    Host == localhost:8080
    User-Agent == Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
    Accept == text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Language == en-US,en;q=0.5
    Accept-Encoding == gzip, deflate, br
    Referer == http://localhost:8080/
    Connection == keep-alive
    Upgrade-Insecure-Requests == 1
    Sec-Fetch-Dest == document
    Sec-Fetch-Mode == navigate
    Sec-Fetch-Site == same-origin
    Sec-Fetch-User == ?1
    --------------------------------------------------------------------------------------------------------------------------------
    getMethod == GET
    getHttpURI == http://localhost:8080/myUploadH/
    extractQueryParameters == []
    getParameters == []
    getAttributeNameSet == []
    getTrailers == null
    --------------------------------------------------------------------------------------------------------------------------------

What I need to do ? 

Thanks for any response.

**Comment by sbordet** [comment] 2023-08-26 11:59
Can you show how you set up your `Handler`s?

I ask because what you seem to experience is a redirect from `/myUploadH`, which you have in the form, to `/myUploadH/` (slash at the end), which is typically done by `ResouceHandler` via `ResourceService`.

If that's the case, I suggest that you change the `action` attribute to something that is not a directory on the file system, for example "/myUploadH.action" or similar.

Note also that browsers upload files via `multipart/form-data` so you cannot read the request content with an `InputStream` (well you can, but it's not the file you uploaded). You must use the multipart APIs instead.

**Comment by eitan-rosenberg** [comment] 2023-08-26 18:34
Many thanks for responding.

This is the log when the server starts:

21:06:19.609 [main] INFO org.eclipse.jetty.server.Server -- jetty-12.0.0; built: 2023-08-07T17:14:07.160Z; git: 52d94174e2c7a6e794c6377dcf9cd3ed0b9e1806; jvm 20+36-2344
21:06:19.664 [main] INFO org.eclipse.jetty.server.RequestLogWriter -- Opened C:\Users\USER\AppData\Local\Temp\RequestLog.6149687619698736073.log
21:06:19.665 [main] INFO org.eclipse.jetty.server.handler.ContextHandler -- Started oejsh.ContextHandler@1ffe63b9{ROOT,/,b=null,a=AVAILABLE,h=m1m.MyHandlerForRoot@51e5fc98{STARTED}}
21:06:19.665 [main] INFO org.eclipse.jetty.server.handler.ContextHandler -- Started oejsh.ContextHandler@7c469c48{/handlers/uploadAction,/handlers/uploadAction,b=null,a=AVAILABLE,h=m1m.MyHandlerForUpload@12e61fe6{STARTED}}
21:06:19.701 [main] INFO org.eclipse.jetty.server.AbstractConnector -- Started ServerConnector@412bc1e4{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
21:06:19.712 [main] INFO org.eclipse.jetty.server.Server -- Started oejs.Server@275710fc{STARTING}[12.0.0,sto=0] @464ms

MyHandlerForUpload (/handlers/uploadAction) is the handler that get called from a form generated in MyHandlerForRoot(/) .

And the code: 
```
	public static final String contextPath = String.format("/%s/%s", MyContext.handlers, MyContext.uploadAction);

	final ContextHandlerCollection contextHandlerCollection = new ContextHandlerCollection();

{

	final ContextHandler contextHandler = new ContextHandler("/");

	final MyHandlerForRoot myHandlerForRoot = new MyHandlerForRoot(server);

	contextHandler.setHandler(myHandlerForRoot);

	contextHandlerCollection.addHandler(contextHandler);

}

{

	final ContextHandler contextHandler = new ContextHandler(MyHandlerForUpload.contextPath);

	final MyHandlerForUpload myHandlerForUpload = new MyHandlerForUpload();

	contextHandler.setHandler(myHandlerForUpload);

	contextHandlerCollection.addHandler(contextHandler);

}

	server.setHandler(contextHandlerCollection);
	
```
The generated form from MyHandlerForRoot:

```
<p>
   <form method="post" action="/handlers/uploadAction" enctype="multipart/form-data">
    <label>myServerTests_1.myHandlers.MyHandlerForUpload<br></label><input type="file" name="myUploadFile" required><input type="submit" value="Upload selected file">
   </form>
</p>

```	
	
You mention "You must use the multiple APIs instead." is there such api used in ServletToHandlerDocs.java ?
(https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/migration/ServletToHandlerDocs.java)

**Comment by sbordet** [comment] 2023-08-26 20:11
> You mention "You must use the multiple APIs instead." 

I meant "multipart".
The documentation is coming.
You can find an example here: https://github.com/eclipse/jetty.project/blob/jetty-12.0.0/jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/util/MultiPartRequestContentTest.java#L431

You code setup is correct.
I assume it is now working and you see the POST with multipart data?

**Comment by eitan-rosenberg** [comment] 2023-08-28 11:06
I am giving up... 
For the time being, I will stick with jetty-ee9-servlet.
I suggest that someone conduct a test using a **browser** as a client. IMHO, using jetty.client is not enough.

**Comment by sbordet** [comment] 2023-08-28 13:48
> I am giving up...

Do you have a complete reproducer that we can try?
We have tons of tests and demos that do the same and actually work.

I bet it's a simple one-liner fix, but we don't have the full reproducer.

**Comment by eitan-rosenberg** [comment] 2023-08-28 18:46
I just created a quick and dirty small Maven project that have 2 handlers.

- MyHandlerForRoot: present a form to upload
- MyHandlerForUpload: respond with the result of various api calls

![image](https://github.com/eclipse/jetty.project/assets/48506054/2dd06e9f-7e9e-4e1a-8401-26074809ec70)

Will that do ?

If yes, I can send it by mail.

**Comment by sbordet** [comment] 2023-08-28 19:50
Yes, please zip and attach to this issue.

**Comment by eitan-rosenberg** [comment] 2023-08-28 20:29
[JettyUploadTests.zip](https://github.com/eclipse/jetty.project/files/12458000/JettyUploadTests.zip)

This is from Eclipse .

Thanks.

**Comment by sbordet** [comment] 2023-08-29 09:36
@eitan-rosenberg you are making a mistake in the form `action` attribute.

You have setup an upload `ContextHandler` whose context path is `/handlers/uploadAction`.
You also use that same path as upload action, and that is wrong.
This is the reason you get a redirect to `/handlers/uploadAction/` (final `/`) with a GET method.

You should instead setup the upload `ContextHandler` with a context path of `/handlers`, and set your upload action to be `/handlers/uploadAction`.

I have done that, and the result is:

```

    --------------------------------------------------------------------------------------------------------------------------------
    getHeaders
    Host == localhost:8080
    User-Agent == Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0
    Accept == text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Language == en-US,en;q=0.5
    Accept-Encoding == gzip, deflate, br
    Content-Type == multipart/form-data; boundary=---------------------------2192141553562069203386700536
    Content-Length == 223768
    Origin == http://localhost:8080
    Connection == keep-alive
    Referer == http://localhost:8080/
    Cookie == wp-settings-time-1=1684795761
    Upgrade-Insecure-Requests == 1
    Sec-Fetch-Dest == document
    Sec-Fetch-Mode == navigate
    Sec-Fetch-Site == same-origin
    Sec-Fetch-User == ?1
    --------------------------------------------------------------------------------------------------------------------------------
    getMethod == POST
    getHttpURI == http://localhost:8080/handlers/uploadAction
    extractQueryParameters == []
    getParameters == []
    getAttributeNameSet == []
    getTrailers == null
    --------------------------------------------------------------------------------------------------------------------------------
```

As you can see, the method is POST, the `Content-Type` is multipart, etc. all correct.

Closing the issue as it is not a Jetty bug.

**Closed as completed by sbordet** 2023-08-29 09:36 UTC
Labels: Question

**Comment by eitan-rosenberg** [comment] 2023-08-29 16:05
Magic !!!

You were right to say "I bet it's a simple one-liner fix"

I was under the impression that upload action should be the same as the ContextHandler (Can you share please any reference material about the subject)

I added the rest of the code based on MultiPartRequestContentTest.java and we have a liftoff !!!

Thank you very.
