### ISSUE TITLE
Annotation scanning fails on JDK10

### ISSUE THREAD

**Issue by davidkarlsen** [eclipse/jetty.project#2397] opened 2018-03-29 10:58 UTC
I get
```
java.lang.RuntimeException: Error scanning entry com/edb/fs/tac/jfr/srv/ApplicationConfiguration.class from jar file:///eos/d1/jfr-srv/i1/tmp/jetty-0.0.0.0-20591-jfr
-srv-ws-5.1.1-SNAPSHOT.war-_jfr-srv-ws-5.1.1-SNAPSHOT-any-1765657363367185674.dir/webapp/WEB-INF/lib/jfr-srv-common-5.1.1-SNAPSHOT.jar
        at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:880)
        at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:872)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:836)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:932)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:917)
        at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:876)
        at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:872)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:836)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

when running on Oracle JDK 10

**Comment by sbordet** [comment] 2018-03-29 13:21
@janbartel possibly an ASM update issue ? ASM 6.1 is the version that supports JDK 10.

@davidkarlsen can you update to ASM 6.1 and see if the problem persists ?

**Comment by joakime** [comment] 2018-03-29 15:37
@jmcc0nn3ll i think we'll need a CQ for ASM 6.1, right?

**Comment by davidkarlsen** [comment] 2018-03-29 20:54
@sbordet My app runs with asm 6.1, but I think this is from the eclipse classloader - so not so much I can do about that.

**Comment by olamy** [comment] 2018-03-29 22:47
Hi @davidkarlsen 
by chance do you have any simple project to share so we could reproduce?

**Comment by davidkarlsen** [comment] 2018-04-02 16:28
It's closed source - so not so easily. I could try to create a stripped down version.

**Comment by joakime** [comment] 2018-04-02 20:34
@olamy check the `jetty-9.4.x-issue-2397-jdk10-support` branch.

I added an example in commit 9e199cfdf7b9c42acfed83b36cd5bcff65a1700f

It has a new testcase - `TestAnnotationParser.testJep238MultiReleaseInJar_JDK10()`

That fails in the following way (when the test is run with JDK10)

```
2018-04-02 15:31:04.955:INFO::main: Logging initialized @470ms to org.eclipse.jetty.util.log.StdErrLog
2018-04-02 15:31:04.968:DBUG:oeja.AnnotationParser:main: Scanning jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar
2018-04-02 15:31:04.978:DBUG:oeja.AnnotationParser:main: Not a class: META-INF/MANIFEST.MF
2018-04-02 15:31:04.978:DBUG:oeja.AnnotationParser:main: Not a class: README.txt
2018-04-02 15:31:04.980:DBUG:oeja.AnnotationParser:main: Scanning class from jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar!/hello/DetailedVer.class->META-INF/versions/10/hello/DetailedVer.class[10]
2018-04-02 15:31:04.987:DBUG:oeja.AnnotationParser:main: Not a class: hello/DetailedVer.java
2018-04-02 15:31:04.988:DBUG:oeja.AnnotationParser:main: Scanning class from jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar!/hello/Greetings.class->META-INF/versions/10/hello/Greetings.class[10]
2018-04-02 15:31:04.988:DBUG:oeja.AnnotationParser:main: Not a class: hello/Greetings.java
2018-04-02 15:31:04.988:DBUG:oeja.AnnotationParser:main: Scanning class from jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar!/hello/Hello.class->hello/Hello.class[0]
2018-04-02 15:31:04.996:DBUG:oeja.AnnotationParser:main: Not a class: hello/Hello.java

Multiple exceptions
MultiException[java.lang.RuntimeException: Error scanning entry hello/DetailedVer.class from jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar, java.lang.RuntimeException: Error scanning entry hello/Greetings.class from jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:869)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:836)
	at org.eclipse.jetty.annotations.TestAnnotationParser.testJep238MultiReleaseInJar_JDK10(TestAnnotationParser.java:231)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.eclipse.jetty.toolchain.test.TestingDir$1.evaluate(TestingDir.java:89)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: java.lang.RuntimeException: Error scanning entry hello/Greetings.class from jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar
		at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:880)
		at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)
		at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
		at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:872)
		... 26 more
	Caused by: java.lang.IllegalArgumentException
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
		at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:932)
		at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:917)
		at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:876)
		... 29 more
Caused by: java.lang.RuntimeException: Error scanning entry hello/DetailedVer.class from jar file:///C:/code/jetty/jetty.project-9.4.x/jetty-annotations/src/test/resources/jdk10/multirelease-10.jar
	at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:880)
	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:872)
	... 26 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:932)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:917)
	at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:876)
	... 29 more
```

**Note: testcase does not fail when runnning JDK8 or JDK9**

**Comment by olamy** [comment] 2018-04-03 00:03
works for me using asm 6.1 or 6.1.1
OpsCode for jdk10 has been introduced with asm 6.1 (see https://gitlab.ow2.org/asm/asm/commit/f8357974a1a958b0769d50d8d3307e450973ba4c )
so we definitely need a CQ for asm 6.1.1
@davidkarlsen really sure to use asm 6.1+?

**Comment by janbartel** [comment] 2018-04-03 00:53
Classes that are jdk 10 require the update to asm 6.1 to correctly parse the class version header. Classes pre jdk 10 should be absoutely fine with asm 6.0.

I'll start the procedure to get permission from Eclipse to use asm 6.1, meanwhile @davidkarlsen  please check which version of asm is actually being used in your environment.

**Comment by janbartel** [comment] 2018-04-03 00:54
Actually, I'll ask permission for 6.1.1 as it is in maven central.

**Comment by janbartel** [comment] 2018-04-03 01:16
CQ 16052 for use of asm-6.1.1 opened at Eclipse.

**Comment by davidkarlsen** [comment] 2018-04-03 17:53
@olamy 
```
-eos-g-app01 i1]$ ls -l tmp/jetty-0.0.0.0-20591-jfr-srv-ws-5.1.1-SNAPSHOT.war-_jfr-srv-ws-5.1.1-SNAPSHOT-any-10842935322587649897.dir/webapp/WEB-INF/lib/*asm*
-rw-r--r-- 1 eosd1 eosd1 108252 Apr  3 14:11 tmp/jetty-0.0.0.0-20591-jfr-srv-ws-5.1.1-SNAPSHOT.war-_jfr-srv-ws-5.1.1-SNAPSHOT-any-10842935322587649897.dir/webapp/WEB-INF/lib/asm-6.1.1.jar
[eosd1@ald-eos-g-app01 i1]$ 
```
so that looks ok, but from the stack trace it seems this is asm from inside Jetty, don't you agree?

**Comment by olamy** [comment] 2018-04-03 21:38
@davidkarlsen  ok got it I was thinking you were using jetty in embedded mode.

**Comment by joakime** [comment] 2018-04-03 21:46
@davidkarlsen the asm from the server level should not be available/present within your webapp due to classloader isolation (and vice-versa).

**Comment by janbartel** [comment] 2018-04-03 23:58
@davidkarlsen if you want to test asm-6.1.x then you need to put it on the jetty server's classpath, not on the webapp's classpath.

**Comment by davidkarlsen** [comment] 2018-04-05 21:29
@joakime @janbartel sure, hence my "but I think this is from the eclipse classloader" comment, I was just conused by Oliviers request. It looks like this will go into 9.4.10 - do you have any ca ETA on that?

**Comment by janbartel** [comment] 2018-04-06 02:02
We have another couple of changes that we need to get into a release, so I expect that there will be another release in the next couple of weeks.

Closing.

**Closed by janbartel** 2018-04-06 02:02 UTC
Labels: Java 10
