### ISSUE TITLE
Question regarding abnormal

### ISSUE THREAD

**Issue by ohassidi** [eclipse/jetty.project#604] opened 2016-05-31 09:13 UTC
Why all except NORMAL closing is Abnormal? How can I use custom error codes like defined in the JSR without jetty look at it like abnormal?

**Comment by sbordet** [comment] 2016-05-31 12:09
You want to be more precise about what you are asking. I have no idea what you are talking about. What JSR ? What Jetty version ? What is "NORMAL" ?

**Comment by ohassidi** [comment] 2016-05-31 13:16
I'll try to elaborate...
The websocket protocol as defined [here](https://tools.ietf.org/html/rfc6455#page-45) define two ways for closing sessions
- Normal
- Abnormal

The protocol also defines error codes, and the range from 4000-4999 are defined as:
> Status codes in the range 4000-4999 are reserved for private use
      and thus can't be registered.  Such codes can be used by prior
      agreements between WebSocket applications.  The interpretation of
      these codes is undefined by this protocol.

The question is why mu custom error code 4400 for instance is interpreted as abnormal? 

Hope that I made myself clearer :)

**Comment by joakime** [comment] 2016-05-31 13:22
Status code 1000 are listed as the one and only normal closure, hence, all other codes are [abnormal](http://www.dictionary.com/browse/abnormal).

Note: Jetty follows the browser standard for identifying an abnormal closure. (which is different from an unclean closure, or harsh closure)

**Comment by elyrank** [comment] 2016-05-31 14:19
The problem is that when sending a custom close code, and doing an abnormal close - there is no close handshake, which causes some clients to get error code 1001 instead of the real code that was sent.

This causes a bug in the client which expects a specific code, but sometimes do not get it because the connection was closed abnormally.

My suggestion is to be able to config "normal" codes and in the check of isAbnormal in CloseInfo - check that the codes provided are considered as normal.

A simpler implementation can be:

`public boolean isAbnormal()    {
        final boolean applicativeCode = statusCode >= 4000 && statusCode < 5000;
        return (statusCode != StatusCode.NORMAL && !applicativeCode);
}`

**Comment by eitan101** [comment] 2016-05-31 16:01
@joakime,

The RFC lets the closing side to send close codes during the closing handshake ([section 7.1.2](https://tools.ietf.org/html/rfc6455#section-7.1.2)).
The closing side has to send the reason and then **wait to the frame of the other side** before closing the connection.

The [current implementation](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java#L157) does that only for CloseReason code 1000. For the rest of the codes it does not wait for the response and closes the socket immediately.
If this had been the right behaviour, there would have been no point to give the option the send reason code during the handshake, since it would have been always 1000.

You are right about that "Status code 1000 is the only code listed as a normal closure".
But 1006 is the the only code that is listed as [CLOSED_ABNORMALLY](http://docs.oracle.com/javaee/7/api/javax/websocket/CloseReason.CloseCodes.html#CLOSED_ABNORMALLY).

So I think that jetty should not bother itself if it is normal/abnormal closure. Instead
* If the underlying connection was closed - call the application onClose
* if the closure was initiated by a close frame from the remote side - send close frame back and call onClose.
* In any other case send close frame and wait to a close frame from the remote side.

Isn't it?

**Comment by joakime** [comment] 2016-05-31 16:36
Status Codes as follows:

(blank): normal, undeclared closure
1000: normal, declared closure
1001:going away, abnormal, declared/sent closure
1002: protocol error, abnormal, declared/sent closure
1003: unsupported data, abnormal, declared/sent closure
1004: (reserved) forbidden to be used
1005: no status rcvd, normal, never sent, local interpretation of no-status code closure from remote
1006: abnormal closure, abnormal, never sent, local indication of closure without handshake
1007: invalid frame payload, abnormal, declared/sent closure
1008: policy violation, abnormal, declared/sent closure
1009: message too big, abnormal, declared/sent closure
1010: mandatory extension, abnormal, declared/sent closure
1011: internal error, abnormal, declared/sent closure
1012: service restart, abnormal, declared/sent closure
1013: try again later, abnormal, declared/sent closure
1014: (unassigned) forbidden to be used
1015: tls handshake, abnormal, declared/sent closure
1016-3999 (unassigned) forbidden to be used
4000-4999 (reserved for private use) all abnormal (like all of the others above that are not blank or 1000)

Codes 1012 thru 1015 are not listed in RFC6455, but exist only as registered codes on the IANA registry - http://www.iana.org/assignments/websocket/websocket.xhtml#close-code-number

@elyrank adding 4000-4999 as normal is invalid.  Just because you declare something in 4000-4999 as normal doesn't mean the next person wants it that way.  The status codes above show you how the codes are interpreted.  (Incidentally, this interpretation is the same as it is on any web browser with websocket support)

@eitan101 you are confusing the local only 1006 with the meaning of normal vs abnormal for all other codes.  The difference is if it was declared/sent (not 1000 or blank) or not (1006).

1006 is typically seen as a local only closure if the connection ended without a close handshake.

4000-4999 is also undefined beyond the general meaning of the rest of the close codes. 

> Fun fact, you can't send codes 1001-4999 on any web browser (only blank and 1000 are allowed), and many web proxies with websocket support will terminate the connection abruptly on codes 4000+ as the meaning of 4000-4999 is undefined (the proxy actually doesn't send that frame at all in these cases)

**Comment by eitan101** [comment] 2016-05-31 19:31
@joakime 
Thanks for your answer.
Are you sure about that the 4000-4999 ?
I see that Chrome sends 4xxx. I used ```websocket.close(4407,"hey")``` from the browser and got this in the jetty:
```
DEBUG [2016-05-31 18:29:02,488] org.eclipse.jetty.io.SelectorManager: Running change org.eclipse.jetty.io.SelectChannelEndPoint$1@71f7f5b9
DEBUG [2016-05-31 18:29:02,488] org.eclipse.jetty.io.SelectorManager: Selector loop waiting on select
DEBUG [2016-05-31 18:29:02,488] org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection: SERVER onFillable()
DEBUG [2016-05-31 18:29:02,488] org.eclipse.jetty.io.ChannelEndPoint: filled 11 SelectChannelEndPoint@7a43c831{/127.0.0.1:51557<->8080,Open,in,out,-,-,13043/300000,WebSocketServerConnection}{io=0,kio=0,kro=1}
DEBUG [2016-05-31 18:29:02,488] org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection: Filled 11 bytes - DirectByteBuffer@4e22eebc[p=0,l=11,c=4096,r=11]={<<<\x88\x85\x88\x90\xDe`\x99\xA7\xB6\x05\xF1>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
DEBUG [2016-05-31 18:29:02,488] org.eclipse.jetty.websocket.common.Parser: SERVER Parsing 11 bytes
DEBUG [2016-05-31 18:29:02,489] org.eclipse.jetty.websocket.common.Parser: SERVER OpCode CLOSE, fin=true rsv=...
DEBUG [2016-05-31 18:29:02,489] org.eclipse.jetty.websocket.common.Parser: SERVER Payload Length: 5 - Parser@4421d65c[ExtensionStack,s=PAYLOAD_LEN,c=0,len=5,f=CLOSE[len=0,fin=true,rsv=...,masked=true],p=WebSocketPolicy@2d60a0d9[behavior=SERVER,maxTextMessageSize=65536,maxTextMessageBufferSize=32768,maxBinaryMessageSize=65536,maxBinaryMessageBufferSize=32768,asyncWriteTimeout=60000,idleTimeout=300000,inputBufferSize=4096]]
DEBUG [2016-05-31 18:29:02,489] org.eclipse.jetty.websocket.common.Parser: SERVER Window: DirectByteBuffer@301335f1[p=0,l=5,c=5,r=5]={<<<\x99\xA7\xB6\x05\xF1>>>}
DEBUG [2016-05-31 18:29:02,491] org.eclipse.jetty.websocket.common.Parser: SERVER Parsed Frame: CLOSE[len=5,fin=true,rsv=...,masked=true]
DEBUG [2016-05-31 18:29:02,491] org.eclipse.jetty.websocket.common.Parser: SERVER Notify ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.jsr356.JsrSession,outgoing=org.eclipse.jetty.websocket.server.WebSocketServerConnection]
DEBUG [2016-05-31 18:29:02,491] org.eclipse.jetty.websocket.common.events.AbstractEventDriver: incomingFrame(CLOSE[len=5,fin=true,rsv=...,masked=true])
DEBUG [2016-05-31 18:29:02,491] org.eclipse.jetty.websocket.common.io.IOState: onCloseRemote(CloseInfo[code=4407,reason=hey])
DEBUG [2016-05-31 18:29:02,492] org.eclipse.jetty.websocket.common.io.IOState: onCloseRemote(), input=false, output=true
DEBUG [2016-05-31 18:29:02,492] org.eclipse.jetty.websocket.common.io.IOState: Notify State Listeners: CLOSING
DEBUG [2016-05-31 18:29:02,492] org.eclipse.jetty.websocket.common.io.IOState: WebSocketServerConnection.onConnectionStateChange(CLOSING)
DEBUG [2016-05-31 18:29:02,492] org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection: SERVER Connection State Change: CLOSING
DEBUG [2016-05-31 18:29:02,492] org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection: outgoingFrame(CLOSE[len=5,fin=true,rsv=...,masked=false], org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$OnCloseLocalCallback@1d94c106)
DEBUG [2016-05-31 18:29:02,493] org.eclipse.jetty.websocket.common.io.FrameFlusher: Flusher[queueSize=1,aggregateSize=0,failure=null] queued FrameEntry[CLOSE[len=5,fin=true,rsv=...,masked=false],org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$OnCloseLocalCallback@1d94c106,OFF,null]
DEBUG [2016-05-31 18:29:02,493] org.eclipse.jetty.websocket.common.io.FrameFlusher: Flusher[queueSize=0,aggregateSize=0,failure=null] processing 1 entries: [FrameEntry[CLOSE[len=5,fin=true,rsv=...,masked=false],org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$OnCloseLocalCallback@1d94c106,OFF,null]]
DEBUG [2016-05-31 18:29:02,493] org.eclipse.jetty.websocket.common.io.FrameFlusher: Flusher[queueSize=0,aggregateSize=0,failure=null] flushing 1 frames: [FrameEntry[CLOSE[len=5,fin=true,rsv=...,masked=false],org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$OnCloseLocalCallback@1d94c106,OFF,null]]
DEBUG [2016-05-31 18:29:02,493] org.eclipse.jetty.io.WriteFlusher: write: WriteFlusher@992c3ff{IDLE} [DirectByteBuffer@518c48b4[p=0,l=2,c=28,r=2]={<<<\x88\x05>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00},HeapByteBuffer@67a0b2f8[p=0,l=5,c=5,r=5]={<<<\x117hey>>>}]
DEBUG [2016-05-31 18:29:02,493] org.eclipse.jetty.io.WriteFlusher: update WriteFlusher@992c3ff{WRITING}:IDLE-->WRITING
DEBUG [2016-05-31 18:29:02,494] org.eclipse.jetty.io.ChannelEndPoint: flushed 7 SelectChannelEndPoint@7a43c831{/127.0.0.1:51557<->8080,Open,in,out,-,W,6/300000,WebSocketServerConnection}{io=0,kio=0,kro=1}
DEBUG [2016-05-31 18:29:02,495] org.eclipse.jetty.io.WriteFlusher: update WriteFlusher@992c3ff{IDLE}:WRITING-->IDLE
DEBUG [2016-05-31 18:29:02,495] org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection: SERVER disconnect(outputOnly)
DEBUG [2016-05-31 18:29:02,495] org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection: Shutting down output SelectChannelEndPoint@7a43c831{/127.0.0.1:51557<->8080,Open,in,out,-,-,0/300000,WebSocketServerConnection}{io=0,kio=0,kro=1}
```

Nginx proxy also passes 4xxx.

I read again the RFC and I think that it does not match what you says.

1.  What is the point of sending close code (according to the [rfc]((section 7.1.2))) during the closing handshake if it is always 1000 (according to jetty implementation) ? I think that the 

2. The RFC [requires](https://tools.ietf.org/html/rfc6455#section-5.5.1) the endpoint that get close frame to response immediately with the same code. According to the current implementation of jetty, if this code is not 1000 jetty will close the connection so the client won't be able to send the response. (We encountered this problem while using some client library).

3. The rfc section that talks about [abnormal closure](https://tools.ietf.org/html/rfc6455#section-7.2) does not mention any control frames or close codes, just disconnection of the underling socket.

So, for my understanding for all of the codes, the handshake process is required. For 1006 which is local code, there is not handshake process, since it is abnormal disconnection without any control frame.

In jetty code I find to methods with similar names but different functions:
[wasAbnormalClose](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/IOState.java#L611), and [isAbnormal](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/CloseInfo.java#L208).

While the first one tests if the underling tcp connection was closed (which is very similar to what I understood from the RFC, the second one checks the close codes based on the logic that you've described.

**Comment by joakime** [comment] 2016-05-31 20:42
About 2), the RFC makes says it SHOULD send the close response, but allows for a half-closed websockets (in our experience, this half-closed state is *surprisingly common* in the real world)

There are are no expectations of "immediately" or "MUST" language in the RFC when it comes to close handshake.

There are many many more proxies then nginx btw.

Per the spec, the codes 1005 and 1006 are the only oddballs with regards to the handshake process.
1005 is a local only indicator of a blank / undeclared closure from the remote.
1006 is a local only indicator of a closure that had no handshake from the remote.

The rest of the codes can have handshake, but as they are all abnormal/error conditions, the handshake cannot be expected in 100% of cases.

Take for example 1002 (protocol error), if the remote sent it, then the remote is saying the local is talking nonsense, meaning there's no valid way to respond, the remote has likely forcibly closed the connection after sending that closure.  If the local sent 1002, then there is no expectation of the remote to respond, as the framing is bad, further data from the remote is just tossed.

If you take the time to think about it, all of the codes outside of 1000/blank fall into this situation, they are all error conditions like 1002 is.  If the remote send those closures, then the rest of the incoming frames are tossed (due to close frame rules), and the rest of the outgoing frames are invalid (as the remote is immediately going away due to the error).  If the local sent those closure codes, then no further outgoing frames are valid (again, due to close frame rules), and the incoming frames are also assumed to be bad/invalid due to this error condition.

**Comment by elyrank** [comment] 2016-06-01 05:12
I agree with you on regards to the 1000 codes , but there is no support for custom codes than should be treated like normal.

right now we have a bug in production because of it.
what is your suggestion?

**Comment by elyrank** [comment] 2016-06-01 07:22
BTW - I have checked Tomcat's implementation of Websocket and I see that all codes are doing the close handshake (except 1006 close abnormally)- unless there is an actual IO exception and the connection is closed.

**Comment by litomSegal** [comment] 2016-06-01 08:15
node.js websocket standard library also closes the web socket gracefully, allowing the close handshake to complete.
[https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L101](url)

**Comment by joakime** [comment] 2016-11-01 20:48
Seeing as we pass the autobahn websocket testsuite (client and server, used by most of the industry interested in compliance with websocket), along with the pywebsocket websocket testsuite (used by both chrome and firefox), the behavior you are seeing with the close handshake is valid.

Making changes to force close handshake actually fails many of the close handshake validation tests in both of those testsuites.

So we are at this point.

We are compliant to the RFC6455 spec.
We are compliant to the library testsuites from autobahn (our client and server implementations, both jetty native websocket, and our JSR356 websocket).
We are compliant to the same browser testsuites (our server implementation, both the jetty native websocket, and our JSR356 websocket).
This means, as far as we can prove, we are compliant to the rest of the websocket implementations out there.

This doesn't seem like a bug that can be addressed without causing more problems.

Closing as not a bug / will break compliance if implemented.

**Closed by joakime** 2016-11-01 20:48 UTC
Labels: Question
