### ISSUE TITLE
Default application/json to utf-8 encoding in encoding.properties

### ISSUE THREAD

**Issue by auniverseaway** [eclipse/jetty.project#2280] opened 2018-03-05 18:43 UTC
According to [RFC 7159](https://www.ietf.org/rfc/rfc7159.txt) JSON's mimeType should be `application/json` and according to Section 8.1, it should be encoded UTF-8 / 16 / 32.

Not having `application/json` added to `encoding.properties` means JSON's default output is `ISO-8859-1`, which is incorrect.

Technically, `text/json` as listed in the current properties file shouldn't even exist, but I probably wouldn't want to remove it for fear of downstream issues. My suggestion is to only add `application/json=-utf-8` to the list.

**Comment by joakime** [comment] 2018-03-05 18:45
I think this is a duplicate of #1269

**Comment by joakime** [comment] 2018-03-13 19:25
Fixed in commit aafda1a279573d07eb084185ff0dcc793c9d0b15

**Closed by joakime** 2018-03-13 19:25 UTC
