### ISSUE TITLE
Jetty 9.3.15 throwing ClosedChannelException on cert name mismatch error

### ISSUE THREAD

**Issue by johngmyers** [eclipse/jetty.project#1199] opened 2016-12-23 00:16 UTC
#444 / #464 has regressed in Jetty 9.3.15. My unit test for a cert name mismatch is now failing with an uninformative ClosedChannelException what appears to be at least 2/3 of the time.

```
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:498)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:113)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.close(SslConnection.java:1017)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:217)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by joakime** [comment] 2016-12-23 01:13
This seems a bit different, as the close stacktrace seems to be outside of the handshake.

**Comment by joakime** [comment] 2017-03-01 18:42
@sbordet this is a jetty-client reported issue.

**Comment by sbordet** [comment] 2019-02-01 11:37
@johngmyers closing this old bug. If you are still affected in 9.4.x, let know and we'll reopen it.

**Closed by sbordet** 2019-02-01 11:37 UTC
Labels: Bug

**Comment by steffyP** [comment] 2019-09-16 11:25
I may have a similar problem with a newer version (9.4.19.v20190610).
I have a test case that should ensure that a SSLHandshakeException is thrown, if the certificate is not loaded, but sometimes, instead I get a EOFException similar to this one:
`java.io.EOFException: HttpConnectionOverHTTP@54f9b511::DecryptedEndPoint@4d551e76{localhost/127.0.0.1:10005<->/127.0.0.1:59453,CLOSED,fill=-,flush=C,to=18/0}
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:209)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:147)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1309)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:293)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.needsFillInterest(SslConnection.java:747)
	at org.eclipse.jetty.io.AbstractEndPoint$1.needsFillInterest(AbstractEndPoint.java:45)
	at org.eclipse.jetty.io.FillInterest.tryRegister(FillInterest.java:83)
	at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:55)
	at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:361)
	at org.eclipse.jetty.io.AbstractConnection.fillInterested(AbstractConnection.java:134)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.fillInterested(HttpReceiverOverHTTP.java:193)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:141)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)`

I enabled the debugging for jetty, and could verify that a SSLHandshakeException was logged, however, the client's websocket only receives the _EOFException_ in the _onError_ callback.
Most of the time, however, it works as expected.

Is this problem related to the already fixed bug?

**Comment by joakime** [comment] 2019-09-16 11:33
@steffyP If you can reproduce this, please try Jetty 9.4.20.v20190813 (the latest stable release).
If you can still reproduce it, then please file a new issue.
