### ISSUE TITLE
Abort HttpChannel onCompletion if wrong content length set

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1045] opened 2016-10-27 10:32 UTC
I insufficient data is written, abort the channel to indicate a problem to the client

**Comment by sbordet** [comment] 2016-10-27 12:56
@gregw, this is a duplicate of #1034 ? Are we checking that we behave correctly also for both the blocking write and async writes and for both sync processing and async processing ?

**Comment by gregw** [comment] 2016-10-28 02:24
I was trying to do this on 9.3.x, but it is actually moderately disruptive, as many tests fail and methods like sendContent are not rigorous about updating the bytes written.   So this will be 9.4 only.

**Comment by laeubi** [comment] 2016-10-28 07:45
This sounds great, is there already any plan when jetty 9.4 gets released?

**Comment by gregw** [comment] 2016-11-02 21:19
See also #553

**Comment by gregw** [comment] 2016-11-03 05:16
@laeubi we have release candidates out... but I think we are one more RC and a few weeks away from a 9.4.0. I'm really hoping this month.

**Closed** 2016-11-03 05:17 UTC

**Comment by joakime** [comment] 2017-06-05 19:42
@gregw can we delete [the 2 issue branches for this](https://github.com/eclipse/jetty.project/branches/all?utf8=%E2%9C%93&query=issue-1045) now?

`issue-1045-9.4.x` Updated 7 months ago by gregw 
`issue-1045-9.3.x` Updated 7 months ago by gregw

**Comment by gregw** [comment] 2017-06-06 07:04
deleted
