### ISSUE TITLE
Flaky test org.eclipse.jetty.ee9.servlet.ServletTest.testSimpleIdleRead

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#12114] opened 2024-07-31 20:57 UTC
**12.0.x**
CI build failure: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-12107/4/tests

**Comment by sbordet** [comment] 2024-08-03 17:06
Duplicate of #11327.

**Closed as completed by sbordet** 2024-08-03 17:06 UTC
Labels: Bug, flaky-test
