### ISSUE TITLE
Detect Network failures , OnClose/OnError does not work

### ISSUE THREAD

**Issue by iamjamalkhan** [eclipse/jetty.project#1534] opened 2017-05-04 21:34 UTC
Hi ,

I am using Jetty 9.2.9 with Groovy and it seems on a network failure like Internet connection lost the OnClose/OnError method of WebSocket are not getting called. I would like to know is there a good way to detect network failures between Server/Client using Jetty WebSocket Api?

**Comment by joakime** [comment] 2017-05-08 19:32
Duplicate of #1547

**Closed by joakime** 2017-05-08 19:32 UTC
Labels: Duplicate
