### ISSUE TITLE
Support rfc7239 Forwarded header in AbstractProxyServlet

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3977] opened 2019-08-14 01:52 UTC
The `AbstractProxyServlet` only supports the defacto standard of X_FORWARDED_FOR headers.
It should also support `Forwarded` as defined by [rfc7239](https://tools.ietf.org/html/rfc7239).

The rfc7239 should be the default in jetty-10

**Comment by sbordet** [comment] 2019-08-14 13:48
Duplicate of #842.

**Closed by sbordet** 2019-08-14 13:48 UTC
Labels: Enhancement
