### ISSUE TITLE
Some Jetty threads stuck on AbstractWebSocketConnection.onFillable indefinitely

### ISSUE THREAD

**Issue by anpur** [eclipse/jetty.project#4582] opened 2020-02-17 12:02 UTC
**Jetty version**
Last know working: 9.4.15.v20190215
Affected: 9.4.22.v20191022, 9.4.25.v20191220

**Java version**
JAVA_VERSION 11.0.6
JAVA_VERSION_DATE 2020-01-14
Azul Systems, Inc.
Zulu11.37+18-SA

**OS type/version**
Amazon Linux AMI release 2018.03

**Description**
We have a highly loaded websocket service (up to 5k concurrent connections with 400 new connections per second on each node) based on DW13.
After updating to jetty `9.4.22.v20191022` (from 9.4.15.v20190215) we noticed that some of the nodes had one-two threads stuck in an a loop, consuming as much CPU as they can (at least we think it should be some kind of a loop).
Updating to the latest available for us version 9.4.25.v20191220 didn't helped. Rolling back to `9.4.15.v20190215` helped.
It didn't showed up on stage environment where nodes are less loaded.

Those rogue threads are remain for weeks even if no more connections done to the service.

![image](https://user-images.githubusercontent.com/7848097/74651787-5108ef00-518d-11ea-809d-a205c18fbfb6.png)

We did a thread dump which revealed that those threads belong to jetty:
```
"dw-527831" id=527831 state=RUNNABLE
    at app//org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:451)
    at app//org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:441)
    at app//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
    at app//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
    at app//org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
    at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
    at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
    at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
    at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
    at app//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
    at app//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
    at app//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
    at java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
``` 
Unfortunately we can't currently investigate it as it happens only in prod for us, but we'll try to provide as much information as possible.

**Comment by joakime** [comment] 2020-02-17 14:28
This is a duplicate of Issue #4537 (identical stacktrace)
It has been addressed in the upcoming 9.4.27 release.

**Closed as completed by joakime** 2020-02-17 14:28 UTC
Labels: Duplicate
