### ISSUE TITLE
Jetty Logger based on MethodHandles

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2513] opened 2018-05-07 17:49 UTC
https://speakerdeck.com/forax/java-dot-lang-dot-invoke-whisper-to-the-jit-for-speed-gain

**Comment by gregw** [comment] 2018-05-09 03:15
https://github.com/forax/beautiful_logger

**Comment by gregw** [comment] 2018-05-09 07:14
@olamy could you do an experiment - could you come up with a script to remove all logging from jetty, then do some performance testing to see if there is any difference... ie how much logging is costing us (even when turned off).
If it is significant and measurable, then I think we should look at either just using beautiful_logger, or borrowing it's techniques for our logger.

**Comment by gregw** [comment] 2018-07-04 18:14
I've had another look at the beautiful logger.  It may be an option to use directly, but it would be a very big change.

We already have switchable implementations of loggers, so I'm wondering if we could get most of the benefit of this by simply creating:

```java
class StdErrNoDebugLog extends StdErrLog
{
    @Override public boolean isDebugEnabled() { return false }

    @Override
    public void debug(String msg, long arg) {}

    @Override
    public void debug(String msg, Object... args) {}
}
```

@olamy and @lachlan-roberts  can you collaborate to create this as an optional logging implementation that can be configured in the jetty-logging.properties file.  You can then both use the techniques you've got to validate if that gives us the benefit or not (@olamy use the load generator and @lachlan-roberts generate some flame graphs for HttpParser and see the difference).

**Comment by olamy** [comment] 2018-07-04 20:53
ATM I did this in a branch called experiment/logging_debug_false (for testing reason just modifying StdErrLog class). Having a new logger implementation looks good to me.

**Comment by gregw** [comment] 2018-07-05 07:16
@lachlan-roberts can you try your HttpParser benchmark on @olamy 's branch and produce some flame graphs

**Comment by lachlan-roberts** [comment] 2018-07-06 06:31
@gregw I can't seem to reproduce the `isDebugEnabled()` on any flamegraph in 9.4.x

In HttpParser this is used
`private final boolean DEBUG=LOG.isDebugEnabled(); // Cache debug to help branch prediction`
so it might not be the best one to test it on

However I created flamegraphs for a bunch of other things like the EWYK benchmark which has the `isDebugEnabled()` being called regularly and it still failed to show up in the flamegraph taken with 15 million samples over 2 min.

**Comment by sbordet** [comment] 2018-07-06 06:39
@lachlan-roberts and if you re-enable the normal logging, do you see `isDebugEnabled()` in flame graphs?

**Comment by lachlan-roberts** [comment] 2018-07-06 06:49
@sbordet this is just in the `jetty-9.4.x` branch not the `experiment/logging_debug_false`, shouldnt this branch still have normal logging

**Comment by gregw** [comment] 2018-07-06 07:50
@lachlan-roberts Do you still have the graphs you generated previously?   I definitely recall seeing isDebugEnabled as 3 or 4 0.5% peaks... hmmm sounds like the graph that Simone must have generated from the cometd test.

Try a load test - perhaps the client load test ?

**Comment by olamy** [comment] 2018-07-06 07:53
@lachlan-roberts this branch has been created for testing purpose so I can have different version for load testing. See https://jenkins.webtide.net/job/load_testing/job/load-test-pipeline/472/ there is 3 versions the normal one, the one with code branch if (logger.isDebug...) removed and this one with logger returning false for isDebugEnabled method.

**Comment by olamy** [comment] 2018-07-06 07:54
TBH there is no such 3/4% difference.

**Comment by gregw** [comment] 2018-07-06 08:04
@olamy could you instruct @lachlan-roberts how to run your load test, then he can produce flame graphs for the load test.

Not sure I understand your comment about no 3/4% difference.   In a flame graph, I saw 3 or 4 peaks, each about 0.5%, resulting in an approximate total time of around 2%.   I thought that correlated reasonably well with your results?

**Comment by olamy** [comment] 2018-07-06 08:09
@gregw oops my bad. Wrong reading of your comment on my side :-) Actually this is running on our ci server/jenkins infra so we need to find a way to generate flamegraph and store them attached to jenkins jobs.

**Comment by lachlan-roberts** [comment] 2018-07-11 05:53
@gregw the problem was that it `isDebugEnabled()` was not getting enough samples to actually show up in the flamegraph but is still in the results when outputting to a text file

in the EWYKBenchmark I got `isDebugEnabled()` appearing for 0.02% of the samples, and this figure is the same for the experiment/logging_debug_false branch

**Comment by gregw** [comment] 2018-07-11 07:42
0.02% is not enough to chase. But it is also nothing like what we were seeing before where the total was around 2%

There are two avenues I want explored:

1) find a test that does have significant isDebugEnabled time (or more than 1%) in a flame graph. We know it is there, we have seen it before. So keep looking and work with to reproduce. @sbordet can you help here.


2) create a jmh benchmark of a single `if(log.isDebugEnabled()) log.debug("test");` and evaluate the difference (if any) with the modified log impl that has just return false

We need to make progress on this or give up as we've spent a bit of time already on this.

**Comment by olamy** [comment] 2018-07-12 09:48
Some results here:
9.4.12-SNAPSHOT, qps 45000 :
mean: 431717.160, value50 mean: 410530.840, value90 mean: 462263.320, runs: 50
9.4.12-LOGGER-DEBUG-DISABLED-SNAPSHOT, qps 45000 :
mean: 417005.660, value50 mean: 409721.880, value90 mean: 461884.440, runs: 50
9.4.12-NO-LOGGER-SNAPSHOT, qps 45000 :
mean: 417118.780, value50 mean: 409865.240, value90 mean: 461444.120, runs: 50


9.4.12-LOGGER-DEBUG-DISABLED-SNAPSHOT means isDebugEnabled() always returning false
9.4.12-NO-LOGGER-SNAPSHOT version with source code modified to remove if(LOG.isDebugEnabled()) block removed

Please note the load tests are based on using the jetty-load-base project (https://github.com/jetty-project/jetty-load-base) so maybe this use case is not using that much isDebugEnabled to give us the most of the benefit.
The simple implementation (i.e a new logger) simply returning false seems to be the easiest way to get an easy performance improvement:
```
    public boolean isDebugEnabled()
    {
        return false;
    }
```

**Comment by olamy** [comment] 2018-07-12 10:17
pr #2714

**Comment by lachlan-roberts** [comment] 2018-07-13 06:18
The results of my JMH benchmark suggest that there is no real benefit to the `StdErrNoDebugLog` approach.

```
Benchmark               (loggerType)   Mode  Cnt       Score      Error  Units
TestBenchmark.test  StdErrNoDebugLog  thrpt   10  147963.592 ± 1593.581  ops/s
TestBenchmark.test         StdErrLog  thrpt   10  145693.753 ± 1549.607  ops/s
```
Benchmark Code
https://gist.github.com/lachlan-roberts/f4635471fba07aa9891ac4f3ced0f6d3

**Comment by gregw** [comment] 2018-07-13 08:14
So this is proving to be a hard one to get a definitive answer on.   @olamy's data shows a 4-5% improvement in latency for either no debugger or nodebug-debugger, which is in line with expectations raised by the beautiful logger presentation.

But we've not been able to see that in flame graphs... well not when we have actually looked.  We saw it in a flame graph when we were looking at something else, but have not seen it since?

More over @lachlan-roberts JMH results indicate no difference between a false return and the normal implementation that checks a field before doing a false return?   This kind of matches the presentation, which suggested a false return was not enough... but it contradicts olamy's results?

But a 4% latency improvement is seen in the load test, so something real is happening.   I think we should just go forward with merging the alternative implementation and update some examples and property files to show its usage.  

We also need to be bit more careful with how much debug we put into critical parts of the code.

**Comment by olamy** [comment] 2018-07-13 08:29
@gregw well if you consider value50 and value90 it's not 4-5% but less than 1%. And to be fair I would consider only those values. The mean can include some bad values.

**Comment by gregw** [comment] 2018-07-13 09:42
@olamy,
true... perhaps we shelve this one for a while and do nothing?   Unless we can get something more definitive in the results.

**Comment by gregw** [comment] 2018-07-17 15:40
closing as not enough savings apparent to justify

**Closed by gregw** 2018-07-17 15:40 UTC
Labels: Performance
