### ISSUE TITLE
Jetty doesn't set the date header on error responses

### ISSUE THREAD

**Issue by markslater** [eclipse/jetty.project#9685] opened 2023-04-27 20:17 UTC
**Jetty version(s)**
11.0.15

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

**OS type/version**

Linux 5.4.0-147-generic

**Description**

Jetty's default error responses don't include the `date` header, but [RFC 9110 specifies that it's mandatory](https://www.rfc-editor.org/rfc/rfc9110.html#field.date) for an "origin server with a clock".

**How to reproduce?**

Run the following class:

```java
package com.example;

import org.eclipse.jetty.server.Server;

public class ErrorServer {
    public static void main(String[] args) throws Exception {
        new Server(8080).start();
    }
}
```
Navigate to http://localhost:8080 in a browser, and view the response headers.  I get:

```
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 435
Content-Type: text/html;charset=iso-8859-1
Server: Jetty(11.0.15)
```
This appears to be caused by a call to [`Response.resetContent()`](https://github.com/eclipse/jetty.project/blob/jetty-11.0.15/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java#L1225) in the default error handling flow, which erases the `date` header that had previously been set by [`HttpChannel.onRequest(MetaData.Request)`](https://github.com/eclipse/jetty.project/blob/jetty-11.0.15/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L892).

**Comment by gregw** [comment] 2023-04-28 08:00
@markslater your analysis of the cause is indeed correct. We've been aware for a while that `resetContent` does reset headers that the server itself has generated.... but we'd not acted because it was not clear if that really was the intended semantic of reset or not.   However, as you say, RFC9110 makes it pretty clear that we should be including at least the Date header.

Now we have a choice between:
 1. preserving it as it was (but an app may have modified it)
 2. re-adding server headers in reset.
 3. changing to only generate the server headers during commit.

I think 2. is least change and probably the correct semantic for when to set the date header.

@sbordet thoughts?

**Comment by gregw** [comment] 2023-04-28 08:24
Ah, we had already changed resetContent to only reset specific headers:
```java                case CONTENT_TYPE:
                case CONTENT_LENGTH:
                case CONTENT_ENCODING:
                case CONTENT_LANGUAGE:
                case CONTENT_RANGE:
                case CONTENT_MD5:
                case CONTENT_LOCATION:
                case TRANSFER_ENCODING:
                case CACHE_CONTROL:
                case LAST_MODIFIED:
                case EXPIRES:
                case ETAG:
                case DATE:
                case VARY:
```

So why is `DATE` considered a content header?   We should definitely take it out of the list.  

I think that would be enough.  I'm not sure we need to worry about applications that deliberately remove the Date header.

**Comment by gregw** [comment] 2023-04-29 11:49
This has been fixed in jetty 10,11 and the ee environments of 12.

However, in the core APIs, there is only a response reset method that removes all headers.   We probably need to modify that to restore (or not remove) any server provided headers.

**Comment by joakime** [comment] 2023-05-10 21:27
Closing as it is merged

**Closed as completed by joakime** 2023-05-10 21:27 UTC
Labels: Bug
