### ISSUE TITLE
test: PathWatcherTest takes over 6 minutes to run

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse/jetty.project#9131] opened 2023-01-07 19:48 UTC
**Jetty version(s)**
jetty-12.0.x commit 1dc175efac094449e0707efa215789f2688012fc

**Java version/vendor** `(use: java -version)`
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode)

**OS type/version**
macOS 13.1

**Description**
junit tests in PathWatcherTest take over 6 minutes to complete.
Given that this code looks pretty stable / hasn't dramatically changed over the years, I wonder how much value this test has. Can this test perhaps be disabled except for integration testing?

**How to reproduce?**
Check out jetty.project, branch  jetty-12.0.x
`mvn clean install`

unit testing hangs around:
```
[INFO] Running org.eclipse.jetty.util.PathWatcherTest
Running org.eclipse.jetty.util.PathWatcherTest.testStartupFindFiles()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesUpdateDelete()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesModifyWarLargeSlowCopy()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesBeyondDepthLimit()
Running org.eclipse.jetty.util.PathWatcherTest.testGlobPattern()
Running org.eclipse.jetty.util.PathWatcherTest.testWatchFile()
Running org.eclipse.jetty.util.PathWatcherTest.testRestart()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesNewDir()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesNewWar()
Running org.eclipse.jetty.util.PathWatcherTest.testSequence()
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 382.141 s - in org.eclipse.jetty.util.PathWatcherTest
```

**Comment by sbordet** [comment] 2023-01-07 21:45
I don't see that on Linux with OpenJDK 64-Bit Server VM Temurin-19.0.1+10 (build 19.0.1+10, mixed mode).

```
[INFO] Running org.eclipse.jetty.util.PathWatcherTest
Running org.eclipse.jetty.util.PathWatcherTest.testStartupFindFiles()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesUpdateDelete()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesModifyWarLargeSlowCopy()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesBeyondDepthLimit()
Running org.eclipse.jetty.util.PathWatcherTest.testGlobPattern()
Running org.eclipse.jetty.util.PathWatcherTest.testWatchFile()
Running org.eclipse.jetty.util.PathWatcherTest.testRestart()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesNewDir()
Running org.eclipse.jetty.util.PathWatcherTest.testDeployFilesNewWar()
Running org.eclipse.jetty.util.PathWatcherTest.testSequence()
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.429 s - in org.eclipse.jetty.util.PathWatcherTest
```

@kohlschuetter, can you try Java 19, to isolate whether it's the JDK or the OS?
Do you have a Linux to try on?

@joakime do you still have a MacOS machine?

**Comment by kohlschuetter** [comment] 2023-01-07 23:37
Still reproduces with Java 19

openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Temurin-19.0.1+10 (build 19.0.1+10)
OpenJDK 64-Bit Server VM Temurin-19.0.1+10 (build 19.0.1+10, mixed mode)

**Comment by olamy** [comment] 2023-01-08 05:10
I can confirm this as well with jdk 17.

```
mvn install -Dtest=PathWatcherTest -pl :jetty-util -am

[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:06 min
[INFO] Finished at: 2023-01-08T11:13:33+08:00
[INFO] ------------------------------------------------------------------------

```
with 
```
➜  jetty.project git:(jetty-12.0.x) mvn -v
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /Users/olamy/softs/maven/apache-maven-3.8.5
Java version: 17-ea, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "13.1", arch: "x86_64", family: "mac"
```

similar time with jetty-10.0.x (so nothing to do with jetty-12.0.x)
```
mvn clean install -Dtest=PathWatcherTest -pl :jetty-util -am
[INFO] Total time:  06:43 min
```

**Comment by kohlschuetter** [comment] 2023-01-08 13:41
with the above patch:
```
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.256 s - in org.eclipse.jetty.util.PathWatcherTest
```

**Comment by gregw** [comment] 2023-01-09 05:01
We really need to consider the whole Pathwatcher support. It was meant to replace the Scanner, but OS differences meant that we never completed the switch. Perhaps fine to get rid of the whole class as well as the test?

**Comment by gregw** [comment] 2023-01-09 06:47
> We really need to consider the whole Pathwatcher support. It was meant to replace the Scanner, but OS differences meant that we never completed the switch. Perhaps fine to get rid of the whole class as well as the test?
We are currently using the class only in maven plugin and in the property user-store (ee8, ee9 and ee10 versions there of).
I think it is low risk to switch these back to the Scanner and only have a single mechanism.  We could also look at extracting common ee8/ee9/ee10 code.

So I definitely think we should look at getting rid of this class entirely before GA.

**Comment by joakime** [comment] 2023-01-09 18:47
There's been oodles of changes to PathWatcher support in the JVM since we attempted this back in Java 7.

Case in point, on OSX, the PathWatcher implementation is now native (it wasn't back in Java 7).
It's native on Linux and Windows too.

**Comment by gregw** [comment] 2023-01-10 03:59
Yet we still see big difference between platforms.  We don't have need for 2 mechanisms doing the same thing, so let's just go with the scanner

**Comment by gregw** [comment] 2023-01-10 06:05
I've created https://github.com/eclipse/jetty.project/tree/jetty-12.0.x-9131-removePathWatcher to remove the PathWatcher.   I noticed that there were tests for hot reload of user properties that were disabled on MacOS, so this is definitely the right thing to do.

@janbartel can you fix up the jetty maven plugin usage in that branch?

**Comment by joakime** [comment] 2023-01-10 12:29
> Yet we still see big difference between platforms. We don't have need for 2 mechanisms doing the same thing, so let's just go with the scanner

What you are seeing in this Issue is a test case specific workaround from the Java 7 days. (it was slowing down the test on OSX to allow the non-native implementation to work)
A workaround that PR #9138 is removing.

The end result of PR #9138 is actually that all platforms are now the same.

**Comment by joakime** [comment] 2023-01-27 21:35
Closing, the PathWatcher has been removed from Jetty 12

**Closed as completed by joakime** 2023-01-27 21:35 UTC
Labels: Bug
