### ISSUE TITLE
NullPointerException adding Servlet via Class

### ISSUE THREAD

**Issue by nicoloboschi** [eclipse/jetty.project#4067] opened 2019-09-09 10:05 UTC
1) Add servlet using ServletContext method 
```
public ServletRegistration.Dynamic addServlet(String servletName,
        Class <? extends Servlet> servletClass);
```
2) Run `mvn jetty:run`
3) The application starts
4) Executing a request to the mapped servlet, it results into:

```
java.lang.NullPointerException
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at matilda.servlet.RequestHandler.executeFilter(RequestHandler.java:99)
	at matilda.servlet.RequestHandler.doFilter(RequestHandler.java:84)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1583)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.base/java.lang.Thread.run(Thread.java:835)
```
 
Using directly class instance, it works fine.

Running on version 9.4.20.v20190813

**Comment by joakime** [comment] 2019-09-09 15:04
We have multiple test cases for this method.

org.eclipse.jetty.servlet.ServletContextHandlerTest
* testAddServletFromFilter
* testAddServletFromSCL
* testAddServletFromSCI
* testServletRegistrationByClass
* testPartialServletRegistrationByClass
* testNullServletRegistration

Can you detail how you are using this method?  some sample code? (this method is context / lifecycle sensitive, meaning it can only be used during a limited timeframe during servlet context initialization)

**Comment by nicoloboschi** [comment] 2019-09-09 15:59
The method is called inside Filter#init
Looking test  `testAddServletFromFilter ` I see that this behaviour is tested but it should fail because I get a NPE instead of a IllegalStateException

If not inside the "init" method, when could I add the servlet? why passing a servlet class instance, it works fine? It is a wanted behaviour?

**Comment by janbartel** [comment] 2019-09-09 23:52
@nicoloboschi I think you are seeing the same problem as https://github.com/eclipse/jetty.project/issues/4022.

It is illegal to add a Servlet from a Filter, but prior to the upcoming 9.4.21 release, we weren't handling that nicely. Try building the jetty-9.4.x branch locally and running with the 9-4.21-SNAPSHOT version, you should now obtain an IllegalStateException.

**Comment by janbartel** [comment] 2019-09-19 06:49
@nicoloboschi I'm going to close this as a duplicate of #4022 - please reopen if you can reproduce with current head of 9.4.x, or the upcoming 9.4.21.

**Closed by janbartel** 2019-09-19 06:49 UTC
