### ISSUE TITLE
Idle sessions created by startAsync are not scavenged.

### ISSUE THREAD

**Issue by akhanzode** [eclipse/jetty.project#1930] opened 2017-10-31 15:50 UTC
- Start a Async handling in doGet()
- Do ctx.complete() to make sure we did everything
- Looks like session.complete is not called which results in session hanging with _requests == 1

Is this a known issue? I use a simple servlet use curl to hit the servlet. I am using embedded jetty.
I am using 9.4.x branch.

**Comment by janbartel** [comment] 2017-10-31 23:16
@akhanzode do you have a reproduction test case? I haven't been able to reproduce this using the jetty async-rest example.

**Comment by janbartel** [comment] 2017-10-31 23:40
@akhanzode I also suggest you enable DEBUG for:

org.eclipse.jetty.server.HttpChannelState and org.eclipse.jetty.server.session

**Comment by janbartel** [comment] 2017-11-23 09:28
@akhanzode  do you have the reproduction test case? I can't make any progress on this because I can't reproduce it without your help.

**Comment by janbartel** [comment] 2018-01-04 15:06
@akhanzode  any progress?

**Comment by janbartel** [comment] 2018-03-22 04:21
No info supplied, so I'm going to close this issue for now. If you can provide a repro test case, please reopen.

**Closed by janbartel** 2018-03-22 04:21 UTC
Labels: More Info Required
