### ISSUE TITLE
Jetty ssl KeyStorePath and TrustStorePath doesn't work with absolute path

### ISSUE THREAD

**Issue by wass9085** [eclipse/jetty.project#5863] opened 2021-01-08 06:31 UTC
**Jetty version**
9.4.34.v20201102   9.4.35.v20201120 

**Java version**

**OS type/version**

**Description**

Error:

I updated jetty to  9.4.34.v20201102 and 9.4.35.v20201120 and got an error with the absolute path to KeyStorePath and TrustStorePath

It seems other users have faced the same issue https://github.com/eclipse/jetty.project/issues/5689.

Solution:
I modified the jetty-ssl-context.xml by removing the `<Property name="jetty.base" default="." />.` This solved my problem

**Comment by sbordet** [comment] 2021-01-08 20:43
Duplicate of #5689.

**Closed as completed by sbordet** 2021-01-08 20:43 UTC
