### ISSUE TITLE
Unexpected encoding in request.getPathInfo() with Jetty 12 beta 0

### ISSUE THREAD

**Issue by Artur-** [eclipse/jetty.project#9444] opened 2023-02-28 13:09 UTC
**Jetty version(s)**
12.0.0.beta0

**Java version/vendor**
openjdk version "19.0.1" 2022-10-18

**OS type/version**
mac os

**Description**
When requesting a URL like

http://localhost:8888/view/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file%20name

with a servlet mapping of `/view/*` then `request.getPathInfo()` in 

Jetty < 12 returns `"/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file name"` while 
Jetty 12 returns `"/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file%20name"`

Is this an intentional change in some spec or accidental?

This breaks handling of resources like "file name" in Vaadin when run in 12 beta0 as Vaadin assumes the path info is decoded and then encodes it to match with a stored, encoded value.

**Comment by joakime** [comment] 2023-02-28 14:02
Which ee level are you using when this happens?

**Comment by Artur-** [comment] 2023-02-28 14:36
`jetty-ee10-maven-plugin`

**Comment by joakime** [comment] 2023-02-28 15:07
I suspect this is some fallout from the discussion at jakartaee/servlet#18 with Servlet 6.x

**Comment by Artur-** [comment] 2023-02-28 15:33
So https://github.com/jakartaee/servlet/pull/424/commits/e1292f9bdc2cb831ee2117946bf6d1cbd8dd366d changes the text for `getPathInfo` from
```
a <code>String</code>, decoded by the web container
```
to
```
a <code>String</code> specifying extra path information that comes after the servlet path but before the query string in the request URL
```

which seems to indicate that this has changed. But then there is
```
This method will not return any encoded characters unless the container is configured specifically to allow them.
```
which I am not sure what it tries to say

**Comment by joakime** [comment] 2023-02-28 16:34
This section of the spec is a bit confusing.  Bear with us.

Until we get a definitive answer ... 

If you write Vaadin for multiple containers, be aware that this part of the spec says that the container can decide what to return here (regarding what's encoded or not).

**Comment by Artur-** [comment] 2023-02-28 17:57
> the container can decide what to return here (regarding what's encoded or not).

That sounds horrible

I tested with https://github.com/Artur-/servlet-demo on Jetty 12 beta 0 and Tomcat 10.1.1 to request "hello world"

```
Server name localhost
Server info jetty/12.0.0.beta0

Request URI: /hello%20world
Request URL: http://localhost:8080/hello%20world
Request path info: /hello%20world
Request path translated: null
Request context path: 
```

```
Server name localhost
Server info Apache Tomcat/10.1.1

Request URI: /servlet-demo/hello%20world
Request URL: http://localhost:8080/servlet-demo/hello%20world
Request path info: /hello world
Request path translated: /.../apache-tomcat-10.1.1/webapps/servlet-demo/hello world
Request context path: /servlet-demo
```

**Comment by gregw** [comment] 2023-02-28 20:08
The ability to return encoded characters is intended for characters like %2f, which will normally be rejected.

I think we should be decoding %20 as it is not ambiguous to do so.

**Comment by gregw** [comment] 2023-02-28 21:28
Looking at our core code, we are indeed decoding %20 in our canonicalPath: see https://github.com/eclipse/jetty.project/blob/jetty-12.0.0.beta0/jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpURITest.java#L81-L82

So it must be in the EE code layer.  Which EE are you using?  

We look to be doing it correctly in EE10: https://github.com/eclipse/jetty.project/blob/jetty-12.0.0.beta0/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java#L1164-L1165

In EE9, we are using the target: https://github.com/eclipse/jetty.project/blob/jetty-12.0.0.beta0/jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/ServletHandler.java#L463-L474
So that might not be decoded correctly.

hmmm we look to be doing that right as well: https://github.com/eclipse/jetty.project/blob/jetty-12.0.0.beta0/jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java#L1524-L1525   

I'll write some EE tests....  ok not working right in ee10 ???

**Comment by gregw** [comment] 2023-02-28 21:56
Ah we have messed up on %20 at least.  It is meant to be decoded in getCanonicalPath, but sometimes it is not... because we are getting confused that space is not a safe character for a URI itself.   However, it is perfectly safe to decode as it can be unambiguously re-encoded.

Will need to review (again) before beta1

**Comment by gregw** [comment] 2023-02-28 22:25
So our concept of a `HttpURI.getCanonicalPath` is a to provide a uniquely encoded path that can be passed to the JVM URI class in order to locate resources in the FileSystem.   This is fine for encoding characters like '\' and ';' which are strange to be in a URI in the first place, but it is a bit more problematic for space, which is commonly encoded in a URI.

In our core request class, we just provide a `HttpURI`, so our handlers can decide if they want the decoded path (unsafe and ambiguous) or the canonical path (safe and non-ambiguous).  We obviously use the later for our own handlers (e.g. ResourceHandler).

The issue is when we come to the servlet API, the `getPathInfo` method is meant to be fully decoded, except that servlet 6.0 provided some exceptions for ambiguous characters like `\`.  However, it also allows for a container to just reject requests with such ambiguous characters.    But space is not ambiguous, it is just not acceptable for the JVM URI class which will ultimately be used by the DefaultServlet to serve resources.

In our ee9 servlets, I believe we are further decoding the canonical URI (as we always have done) to the ambiguous form and trusting the URI violations reject bad requests.

In ee10, we are just using the `canonicalPath`.  I think we need to add a `UriUtil.nonAmbiguousDecode` method that will decode %20, but leave %2F encoded. We can use that for ee10 getPathInfo so it will only return encoded characters in the unsafe modes if the violations are set to allow those requests through.

**Comment by gregw** [comment] 2023-03-03 13:38
@Artur- the fix is merged in head now.  It would be great if you could test it before we do a beta1 release in the next few weeks.

**Comment by Artur-** [comment] 2023-03-03 13:40
Is there a public snapshot I can test?

**Comment by gregw** [comment] 2023-03-03 13:53
It is currently building after the merge, but should be available from https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-12.0.x/1083/artifacts

**Comment by joakime** [comment] 2023-03-03 13:59
We have nightly snapshot artifacts present at https://oss.sonatype.org/content/repositories/jetty-snapshots/

But that only occurs once a day, at midnight.

**Comment by joakime** [comment] 2023-03-03 16:02
Reopening, as this is now unsafe.

Lets take a look at these scenarios with the current implementation from PR #9455

url-pattern | request path | servlet-path | path-info
---- | ---- | ---- | ----
`/foo/*` | `/foo/bar%2Fzed` | `/foo` | `/bar%2Fzed`
`/foo/*` | `/foo/bar%252Fzed` | `/foo` | `/bar%2Fzed`

**Comment by joakime** [comment] 2023-03-03 16:02
I'm introducing some test cases right now (which caught this case)

**Comment by gregw** [comment] 2023-03-03 19:24
@joakime I'm confused? we already left %25 encoded.  Your PR appears to be doing something else?  I'll comment there.

**Comment by Artur-** [comment] 2023-03-04 10:44
We have one test that does basically
```
curl "http://localhost:8888/view/VAADIN/build/%252E%252E/some-resource.css"
```

and expects that path info to be
```
"/VAADIN/build/%2E%2E/some-resource.css"
```
which it is with the ee9 plugin but with ee10 it is
```
"/VAADIN/build/%252E%252E/some-resource.css"
```

**Comment by gregw** [comment] 2023-03-04 14:35
I think that test might now need to change with servlet 6.0. the spec now allows for %2f to remain encoded, but to do that, we need to leave %25 encoded so one can tell that it wasn't a %252f.

What a mess. I'll chat to the servlet specific folks and see what we should do. It may be that we need to have modal behavior, so only if we allow %2f through would we leave %25 encoded.

**Comment by gregw** [comment] 2023-03-05 04:47
I think we need to change our approach to dealing with unsafe encodings such as %2F. 

The servlet 6.0 javadoc says about `getServletPath` (and similar text for `getPathInfo`:
```java
    /*
     * @return a <code>String</code> containing the path of the servlet being called, as specified in the request URL, or an
     * empty string if the servlet used to process the request is matched using the "/*" pattern. The path will be
     * canonicalized as per section 3.5 of the specification. This method will not return any encoded characters unless the
     * container is configured specifically to allow them.
     * @throws IllegalArgumentException In standard configuration, this method will never throw. However, a container may be
     * configured to not reject some suspicious sequences identified by 3.5.2, furthermore the container may be configured
     * to allow such paths to only be accessed via safer methods like {@link #getRequestURI()} and to throw
     * IllegalArgumentException if this method is called for such suspicious paths.
     */
```

Firstly it says _"not return any encoded characters unless the container is configured specifically to allow them."_, so why are we allowing %2F by default?  The `AMBIGUOUS_PATH_SEPARATOR` violation should only be allowed if specifically configured.

Secondly the javadoc allows for ISE to be thrown when such a violation is allowed, forcing applications that wish to handle %2F to do so with safer methods.   We have not acted on this, instead trying to find a way to sometimes return %2F via `getServletPath` and `getPathInfo`

So I think we should:
 + revert our safeDecode change.
 + exclude  `AMBIGUOUS_PATH_SEPARATOR` from our default `UriCompliance`
 + throw ISE from getPathInfo and getServletPath if such a violation is allowed.  I.e we will never return encoded characters from these methods.

The last of these steps may be difficult, as we use `getPathInfo` and `getServletPath` when routing a request to a filter/servlet.

**Comment by Artur-** [comment] 2023-03-13 13:42
I re-ran our tests today with the lastest Jetty 12 snapshot and it seems all tests pass except one that hits `HTTP ERROR 400 Ambiguous URI path encoding`.

Looks like the test registers a route using the path 
```
special åäö $%20'´`
```
which then gets encoded into
```
special%20%C3%A5%C3%A4%C3%B6%20$%2520'%C2%B4%60
```

and when the URL (http://localhost:8888/context-path/special%20%C3%A5%C3%A4%C3%B6%20$%2520'%C2%B4%60) is opened, the response is
```
HTTP ERROR 400 Ambiguous URI path encoding
URI:	/badURI
STATUS:	400
MESSAGE:	Ambiguous URI path encoding
CAUSED BY:	org.eclipse.jetty.http.BadMessageException: 400: Ambiguous URI path encoding
Caused by:
org.eclipse.jetty.http.BadMessageException: 400: Ambiguous URI path encoding
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.headerComplete(HttpConnection.java:1223)
	at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1008)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1245)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1536)
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:626)
```

**Comment by joakime** [comment] 2023-03-13 13:48
What is `/badURI` and what are its `url-pattern`s ?

**Comment by joakime** [comment] 2023-03-13 13:49
note that the 12.0.0.beta0 doesn't have the latest decoding fixes on `jetty-12.0.x/HEAD`

**Comment by Artur-** [comment] 2023-03-13 13:55
It is run using
```
[INFO] jetty-12.0.0-SNAPSHOT; built: 2023-03-13T00:09:34.359Z; git: bd0186c2f78fb7c87c7bfadf9b0a970657d071f3; jvm 19.0.2
```

as
```
            <plugin>
                <groupId>org.eclipse.jetty.ee10</groupId>
                <artifactId>jetty-ee10-maven-plugin</artifactId>
                <configuration>
                    <webApp>
                        <!-- use a non-root context -->
                        <contextPath>/context-path</contextPath>
                    </webApp>
                </configuration>
            </plugin>
```
together with
```
@WebServlet(urlPatterns = { "/*" })
public class DefaultMappingServlet extends VaadinServlet {
}
```


`badURI` seems to be a Jetty thing https://github.com/eclipse/jetty.project/blob/bd0186c2f78fb7c87c7bfadf9b0a970657d071f3/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java#L1077

**Comment by Artur-** [comment] 2023-07-06 12:28
Was there any conclusion for this? It seems like 12 beta3 works like Jetty 11 except it disallows using an encoded `%20`, i.e. `%2520` in the URL path, so I deleted this case from our tests

**Comment by gregw** [comment] 2023-07-07 07:30
@Artur, By default we are not allowing %25 in a URI, as it can cause problems if that decoded string is passed to other APIs that do not know that the % is already decoded and thus try to decode it again.

However, we have a violation mode AMBIGUOUS_PATH_ENCODING, that can be allowed. So a server can be configured to allows %25.
This can be used by setting the URLCompliance mode to the string "RFC3986,AMBIGUOUS_PATH_ENCODING".    We should probably javadoc the ramifications of using this violation more (i.e. the deployer needs to check that the path is not given to any API that will decode the %.

**Comment by gregw** [comment] 2023-07-07 07:50
@Artur- See #10079 which improves the javadoc of the Violations.  We will also improve the actual external documentation soon (@sbordet tell me when the structure is there for the new doco and I'll write about URI Violations).

**Comment by Artur-** [comment] 2023-08-14 10:24
Do I understand correctly that the consequence of this is that you cannot (by default) load a file with a name that contains `%`. So for instance if I have `src/main/webapp/all done 100%.png`

then a request to `http://localhost:8080/all done 100%.png` is translated by Chrome into `http://localhost:8888/all%20done%20100%.png` and then Jetty responds with
```
org.eclipse.jetty.http.BadMessageException: 400: Bad Request
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1654)
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:626)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:460)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.NumberFormatException: !hex .
	at org.eclipse.jetty.util.TypeUtil.convertHexDigit(TypeUtil.java:416)
	at org.eclipse.jetty.http.HttpURI$Mutable.parse(HttpURI.java:1273)
	at org.eclipse.jetty.http.HttpURI$Mutable.pathQuery(HttpURI.java:935)
	at org.eclipse.jetty.http.HttpURI.build(HttpURI.java:120)
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.<init>(HttpConnection.java:1145)
	at org.eclipse.jetty.server.internal.HttpConnection.newHttpStream(HttpConnection.java:186)
	at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.startRequest(HttpConnection.java:996)
	at org.eclipse.jetty.http.HttpParser.parseLine(HttpParser.java:825)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1538)
```

If I manually URI encode it and instead request `http://localhost:8080/all%20done%20100%25.png` then I get
```
org.eclipse.jetty.http.BadMessageException: 400: Ambiguous URI path encoding
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.headerComplete(HttpConnection.java:1226)
	at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1012)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1252)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1545)
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:626)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:460)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by joakime** [comment] 2023-08-14 13:06
There are a lot of gotchas when relying on the Chrome location bar encode URLs properly.
For example:

* An open Bug that shows that the non-reserved `"<>^ {|} %+` do not encode in some situations (location bar, gurl/kurl, javascript, application launcher, and even the protocol handlers)
* An open Bug that shows the location bar sometimes encodes with ISO-8859-1 and sometimes with UTF-8 (the rules on which is used is complicated), which means the char `ë` can wind up encoded as `%EB` and some other times as `%C3%AB`

You really shouldn't rely on that Chrome behavior.

Now, the other URL you posted with `http://localhost:8080/all%20done%20100%25.png` is triggering https://tools.ietf.org/html/rfc3986#section-3.3 rules on ambiguous path encoding.  The `%25` with no hex numbers after it causes that.

This rule can be configured, btw.
See the `UriCompliance` rules on set on the `HttpConfiguration.setUriCompliance(UriCompliance)` object if using jetty embedded.
Or the `jetty.httpConfig.uriCompliance` property if using the `jetty-home` setup (see the your `${jetty.base}/start.d/server.ini` for help).

**Comment by gregw** [comment] 2023-08-23 07:41
Closing this as I believe we are now doing as best we can.  Please reopen if there are more problems.

**Closed as completed by gregw** 2023-08-23 07:41 UTC
Labels: Bug, Specification
