### ISSUE TITLE
MongoSessionIdManager bad resolution of "localhost" 

### ISSUE THREAD

**Issue by mdussere** [eclipse/jetty.project#1524] opened 2017-05-03 09:22 UTC
I'm using mongo-based clustering with jetty and I encounter a resolution problem in the resolution of the mongo host when I use 'localhost'.

Instead of resolving 'localhost' as 127.0.0.1 as it is set in /etc/hosts, MongoSessionIdManager resolves it as the local network IP (like `resolveip $(hostname)`)
... and due to a very bad configuration of the server I use it would not work.

I solved my problem by specifically using 127.0.0.1 in jetty-nosql.xml (and I ask the administrator to better configure the server :-) ) but it was tricky to figure it out and I think you should fix this unusual resolution.

This the original jetty-nosql.xml I use
```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">

    <New id="mongodb" class="com.mongodb.Mongo">
      <Arg>
        <New class="java.util.ArrayList">
          <Call name="add">
            <Arg>
              <New class="com.mongodb.ServerAddress">
                <Arg type="java.lang.String">localhost</Arg>
                <Arg type="int">27017</Arg>
              </New>
            </Arg>
          </Call>
          <!-- Add more Call statements here as desired --> </New>
      </Arg>

      <Call name="getDB">
        <Arg>HttpSessions</Arg>
        <Call id="sessionDocument" name="getCollection">
          <Arg>sessions</Arg>
        </Call>
      </Call>
      <!-- If you want to configure Jetty to be able to read through the slaves, call the following: -->
      <Call name="slaveOk"/>
    </New>

  <!-- ===================================================================== -->
  <!-- Configure a MongoSessionIdManager                                     -->
  <!-- ===================================================================== -->
  <Set name="sessionIdManager">
    <New id="mongoIdMgr" class="org.eclipse.jetty.nosql.mongodb.MongoSessionIdManager">
      <Arg>
        <Ref id="Server"/>
      </Arg>
      <Arg>
        <Ref id="sessionDocument"/>
      </Arg>
      <Set name="workerName"><Property name="jetty_nosqlSession_workerName" default="node1"/></Set>
      <Set name="scavengePeriod"><Property name="jetty.nosqlSession.scavenge" default="1800"/></Set>
    </New>
  </Set>

</Configure>
```

What the debugger gave me with the 'localhost' configuration
![image](https://cloud.githubusercontent.com/assets/12426246/25654488/7f2f56dc-2ff1-11e7-911b-ecb9555f0de2.png)

What the debugger gave me we 127.0.0.1 configuration
![image](https://cloud.githubusercontent.com/assets/12426246/25654495/881af31e-2ff1-11e7-92ff-a5ca2cf010ad.png)

The system config
```
hpcgadmin@en01:/opt/hpcg$ ping localhost
PING localhost.localdomain (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost.localdomain (127.0.0.1): icmp_seq=1 ttl=64 time=0.016 ms
64 bytes from localhost.localdomain (127.0.0.1): icmp_seq=2 ttl=64 time=0.021 ms
64 bytes from localhost.localdomain (127.0.0.1): icmp_seq=3 ttl=64 time=0.019 ms
64 bytes from localhost.localdomain (127.0.0.1): icmp_seq=4 ttl=64 time=0.018 ms
64 bytes from localhost.localdomain (127.0.0.1): icmp_seq=5 ttl=64 time=0.020 ms
64 bytes from localhost.localdomain (127.0.0.1): icmp_seq=6 ttl=64 time=0.022 ms
^C
--- localhost.localdomain ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5294ms
rtt min/avg/max/mdev = 0.016/0.019/0.022/0.004 ms


hpcgadmin@en01:/opt/hpcg$ head /etc/hosts
#
# Dynamically generated by: genconfig  (Do not edit!)
#
127.0.0.1       localhost.localdomain    localhost
192.168.10.30      en01.cluster    en01-eth0.cluster    en01-eth0    en01
192.168.189.30     en01.cluster-189    en01-eth1.cluster-189    en01-eth1
192.168.10.101     n189101.cluster    n189101-eth0.cluster    n189101-eth0    n189101
10.0.189.101       n189101-bmc.cluster    n189101-bmc
```

**Comment by mdussere** [comment] 2017-05-03 09:27
I'm using Jetty 9.3.3

I got the debugger screenshot by attaching at the process startup and putting a breakpoint on MongoSessionIdManager.java:185  in MongoSessionIdManager(Server server, DBCollection sessions)

I dived into the 'sessions' object to get the mongo client object and inspect its configuration.

**Comment by janbartel** [comment] 2017-05-03 09:29
@mdussere  the configuration for Mongo and indeed all of the session configuration has changed considerably for jetty-9.4, see https://www.eclipse.org/jetty/documentation/9.4.x/session-management.html

So we're not doing any active development on older versions, just important bug fixes. If I understand you correctly, this is not a bug, but rather an enhancement for jetty-9.3?

**Comment by mdussere** [comment] 2017-05-03 09:42
It's a bug in the sense that Jetty does not open the Mongo Session on the network interface it is supposed to use... but there is one chance on 1 million to be in the same corner case I was and have a wrong behavior. You can label it as minor and quite rare and wont fix.

In this case, my concern is more that this buggy host resolution MAY be more widely used in Jetty an MAY cause the same kind of tricky problem elsewhere.

I will take a look at the new session management and maybe migrate to a newer Jetty. I 'll try to test the localhost resolution with the new version.

PS I'm quite impressed by the rapidity of the answer

**Comment by janbartel** [comment] 2017-11-23 10:11
@mdussere jetty doesn't do any resolution of host and port for Mongo - the mongo library does that. I also think I may have upgraded the version of mongo that we use in jetty-9.4, so give that a go and see if they've improved their host resolution mechanism. I'm going to close this issue.

**Closed by janbartel** 2017-11-23 10:11 UTC
