### ISSUE TITLE
GzipHandler will return damaged request bodies if body of some requests is not read

### ISSUE THREAD

**Issue by jaroslawr** [eclipse/jetty.project#5717] opened 2020-11-24 11:13 UTC
**Jetty version**

`9.4.31.v20200723`

**Java version**

`11`

**OS type/version**

`Linux 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux`

**Description**

When a servlet running in embedded jetty with GzipHandler occasionally does not read the request body, the request bodies returned by Jetty in some of the subsequent requests are damaged - they seem to be a combination of bodies of two different real requests.

Server and client for reproduction at https://github.com/RTBHOUSE/jettyrepro.

Server with 50% probability either 
a) reads the request body, checks it for consistency and writes it back as a response, or
b) does not read the request body and returns static text

Client with 50% probability sends a POST request with either:
a) 1024 times the character "0", or
b) 1024 times the character "7"

After just a few requests, the server will see a mixture of "0" and "7" in request body and throw an exception.

The problem does not occur if GzipHandler is not used (and when client is modified to not use gzip compression).

**Comment by joakime** [comment] 2020-11-24 11:56
Please try Jetty 9.4.35.v20201120 and tell us if it's still a problem for you?

**Comment by gregw** [comment] 2020-11-24 12:55
Thanks for the report, but I believe this is a duplicate of #5605 fixed in Jetty 9.4.35.v20201120

**Closed as completed by gregw** 2020-11-24 12:55 UTC
Labels: Duplicate

**Comment by jaroslawr** [comment] 2020-11-24 13:05
@joakime @gregw Upgrading did help, thanks.
