### ISSUE TITLE
jetty-maven-plugin deploy-war silently fails (unless the pom has war packaging)

### ISSUE THREAD

**Issue by havardw** [eclipse/jetty.project#2209] opened 2018-02-21 12:58 UTC
We have a suite of integration tests that run in a separate Maven module, using jetty-maven-plugin's "deploy-war" goal. I've attached a simple test setup with separate web app and integration tests.

This works with 9.4.6, but fails with 9.4.7 and later. The web app referenced from our pom does not run, and there is no error message.

While reporting this bug I discovered #1989, which has the same symptoms and an explanation. Thus I've discovered that a possible work-around is to set war packaging for my integration test module (and also add Maven war plugin and configure it to ignore missing web.xml).

I think that it doesn't really make sense to require a Maven war module when running the deploy-war goal, as this will frequently be used to run wars outside the current module. I hope you'll reconsider the code change to require a war module, at least for the deploy-war goal.

If not there should be a simpler way to override this than changing the packaging and declaring an extra plugin. It would also be helpful if there was some kind of warning when running was skipped due to packaging type. Also, the documentation would need to be updated, the [example](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html#deploy-war-running-pre-assembled-war) for deploy-war won't work as it is shown.

Sample project: [jetty-deploy-war.zip](https://github.com/eclipse/jetty.project/files/1744043/jetty-deploy-war.zip)

**Comment by joakime** [comment] 2018-02-21 14:01
Originally, the `jetty:run-war` had that `<packaging>war</packaging>` check, as it required a project with the `maven-war-plugin` configuration to even build the war file.

The `jetty:deploy-war` was created to allow arbitrary usage, as long as you manually configure the `war` configuration parameter.

Looks like `jetty:deploy-war` is now just a variant of `jetty:run-war`.

We should either restore this behavior of `jetty:deploy-war` or change the javadoc in `jetty:deploy-war` to not mention this difference anymore.

**Comment by janbartel** [comment] 2018-02-21 22:56
Looks like the problem came in with this commit: https://github.com/eclipse/jetty.project/commit/4b513c61e8ac7400826880d18729c71eca1b6ae8#diff-28ee2c02100a8cae9e1d1754ea32af10R64

**Comment by olamy** [comment] 2018-02-21 23:17
arghh @janbartel feel free to assign it to me. Should be an ezy fix. Ideally we'd like to have one IT test per mojo.

**Comment by janbartel** [comment] 2018-02-21 23:23
@olamy it's ok, I got this one.

**Comment by janbartel** [comment] 2018-02-22 00:04
For the info of future readers, the following info from PR #2212  is reproduced here:

I've reviewed all of the goals, and implemented a check for packaging war only on these:
run
run-war
run-exploded
run-forked
run-distro
effective-web-xml

These other goals do not require packaging war:
start
stop
deploy-war

**Comment by janbartel** [comment] 2018-02-22 03:32
Fix applied to jetty-9 and beyond.

**Closed by janbartel** 2018-02-22 03:32 UTC
