### ISSUE TITLE
System ID http://www.eclipse.org/jetty/configure_9_0.dtd and others no longer working

### ISSUE THREAD

**Issue by veita** [eclipse/jetty.project#8738] opened 2022-10-19 09:46 UTC
**Description**
The Eclipse website seems to have completely switched from HTTP to HTTPS. As a consequence validated parsing of deployed Jetty configuration XML files that contain certain DTDs fails.

E.g. https://github.com/apache/solr/blob/main/solr/server/etc/jetty.xml and other files in the same directory.

Also see https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L1926

**How to reproduce?**
* `curl http://www.eclipse.org/jetty/configure_9_0.dtd`
* `curl http://www.eclipse.org/jetty/configure.dtd`
 * Parse Solr configuration XML files using a validating parser.

**Comment by joakime** [comment] 2022-10-19 13:35
Those `redirectEntity` entries keep you from hitting the public internet to parse the XML with validation turned on.

**Comment by veita** [comment] 2022-10-19 13:53
Don't know if I understand you correctly, but yesterday the affected code worked without errors.

Today it started to throw an `org.xml.sax.SAXParseException`, probably due to the HTML HTTP body sent with the 301 response.

After replacing `http://www.eclipse.org/jetty/configure_9_0.dtd`with `https://www.eclipse.org/jetty/configure_9_0.dtd` in the Jetty configuration file all went back to normal.

**Comment by joakime** [comment] 2022-10-19 14:07
Not reproducible.

This is run from a machine that has its internet turned off.

```
[xml-example-base]$ ls -la
total 20
drwxrwxr-x  5 joakim joakim 4096 Oct 19 08:58 ./
drwxr-xr-x 79 joakim joakim 4096 Oct 19 08:58 ../
drwxrwxr-x  2 joakim joakim 4096 Oct 19 08:58 resources/
drwxrwxr-x  2 joakim joakim 4096 Oct 19 08:58 start.d/
drwxrwxr-x  2 joakim joakim 4096 Oct 19 09:03 webapps/

[xml-example-base]$ cat webapps/tmp-static.xml 
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">

<Configure class="org.eclipse.jetty.server.handler.ContextHandler">
  <Call id="res" class="org.eclipse.jetty.util.resource.Resource" name="newResource">
    <Arg>/tmp/</Arg>
  </Call>
  <Set name="contextPath">temp</Set>
  <Set name="baseResource">
     <Ref refid="base"/>
  </Set>

  <Set name="handler">
    <New class="org.eclipse.jetty.server.handler.ResourceHandler" />
  </Set>
</Configure>


[xml-example-base]$ java -jar ~/code/jetty/distros/jetty-home-10.0.11/start.jar
2022-10-19 09:03:54.745:INFO :oejs.Server:main: jetty-10.0.11; built: 2022-06-21T21:12:44.640Z; git: d988aa016e0bb2de6fba84c1659049c72eae3e32; jvm 17.0.3+7
2022-10-19 09:03:54.770:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/joakim/code/jetty/distros/bases/xml-example-base/webapps/]
2022-10-19 09:03:54.795:INFO :oejsh.ContextHandler:main: Started o.e.j.s.h.ContextHandler@68e5eea7{tmp-static.xml,temp,null,AVAILABLE}
2022-10-19 09:03:54.807:INFO :oejs.AbstractConnector:main: Started ServerConnector@524d6d96{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-10-19 09:03:54.815:INFO :oejs.Server:main: Started Server@57a3af25{STARTING}[10.0.11,sto=5000] @617ms
```

This is how Jetty's `XmlParser` works, it won't attempt to access the System ID due to the `redirectEntity` setup (which uses the entity from the classpath if it encountered during XML parse).

**Comment by joakime** [comment] 2022-10-19 14:09
Even if you explicitly turn on the validation (which is true by default when run on OpenJDK) it still doesn't fail.

```
[xml-example-base]$ java -Dorg.eclipse.jetty.xml.XmlParser.Validating=true -jar ~/code/jetty/distros/jetty-home-10.0.11/start.jar
2022-10-19 09:08:30.226:INFO :oejs.Server:main: jetty-10.0.11; built: 2022-06-21T21:12:44.640Z; git: d988aa016e0bb2de6fba84c1659049c72eae3e32; jvm 17.0.3+7
2022-10-19 09:08:30.251:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/joakim/code/jetty/distros/bases/xml-example-base/webapps/]
2022-10-19 09:08:30.275:INFO :oejsh.ContextHandler:main: Started o.e.j.s.h.ContextHandler@68e5eea7{tmp-static.xml,temp,null,AVAILABLE}
2022-10-19 09:08:30.288:INFO :oejs.AbstractConnector:main: Started ServerConnector@524d6d96{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-10-19 09:08:30.294:INFO :oejs.Server:main: Started Server@57a3af25{STARTING}[10.0.11,sto=5000] @605ms

```

**Comment by veita** [comment] 2022-10-19 15:04
This can be used to reproduce the error:

https://github.com/veita/jetty-8738

Tested with Java 17, 11, and 8.

**Comment by joakime** [comment] 2022-10-19 15:30
That's an invalid test case.
It uses no Jetty classes.
It uses no Jetty dependencies.
It uses no form standard Java XML entity resolution.

* https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/org/xml/sax/EntityResolver.html
* https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/javax/xml/stream/XMLResolver.html
* https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/javax/xml/transform/URIResolver.html
* https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/org/w3c/dom/ls/LSResourceResolver.html
* https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/javax/xml/catalog/CatalogResolver.html

Once you implement any one of those (Catalog being the easiest, IMO) you will find that it works.

If you used Jetty's `XmlParser` itself you'll see it works.

**Comment by joakime** [comment] 2022-10-19 15:47
Here's the testcase for using Jetty 10.0.x `XmlParser` directly.

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlParserTest.java#L25-L40

On Jetty 10.0.x, validation is true by default.

And the one from Jetty 9.x (validation is false by default)

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlParserTest.java

And if you are using Jetty Configuration XML (also validation on by default), you would be using the `org.eclipse.jetty.xml.XmlConfiguration` class (which builds on top of Jetty's `XmlParser`).
The `XmlConfiguration` class manages the IDs, references, object maps, properties, etc for working with XML configuration lists.
Which has it's own test cases.

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java

In Jetty 4.x through Jetty 11.x we used a simple XML entity resolver.

Starting in Jetty 12.x we are using an Xml Catalog.

See: https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlParserTest.java

Take a look at the catalogs.

* (Core XML Catalog) https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-xml/src/main/resources/org/eclipse/jetty/xml/catalog-org.w3.xml
* (Jetty Configure Catalog) https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-xml/src/main/resources/org/eclipse/jetty/xml/catalog-configure.xml

And the references there are pointing to content in the same directory

* https://github.com/eclipse/jetty.project/tree/jetty-12.0.x/jetty-core/jetty-xml/src/main/resources/org/eclipse/jetty/xml

Using the CatalogResolver from those we have local resolution of XML entities (including system ids, and public ids).

Using a XML entity resolver to find content locally (and not using the internet) has been the recommended way to use XML in Java since Java 1.4 (back in early 2002).

Back in 2005, XML Catalogs were introduced by the OASIS group (the spec body that manages the XML spec).
Catalog support was introduced in nearly all Java XML libraries shortly afterwords.
However, the generic JVM level API for Catalogs were not introduced into Java till Java 9.
Once we were in a codebase no longer tied to Java 8, we were able to upgrade to using Catalog, which we are doing now in Jetty 12.

**Comment by joakime** [comment] 2022-10-19 16:02
This is not a bug in Jetty as it is using Java XML properly to avoid internet access for validating XML.
Closing.

**Closed as completed by joakime** 2022-10-19 16:02 UTC
Labels: Not a bug

**Comment by veita** [comment] 2022-10-19 16:33
I did not say that this is a bug in Jetty web server but a bug of the Eclipse Jetty website http://www.eclipse.org/jetty/.

It could cause errors in programs that have to deal with Jetty configuration XML files.

Since the Jetty project seems to have chosen http://www.eclipse.org/jetty/ as the location for some of its external entities, I assumed that it has at least some control over it and would be able to fix it.

We already have worked around the issue on our side by implementing a suitable `EntityResolver`. Of course this does not rule out that other software might be affected as well.

**Comment by joakime** [comment] 2022-10-19 16:48
This kind of change, where the host changes from http to https happens all the time.
(or the host owner changes, or the location changes, or the software is retired, etc)
This is why the recommendation has always been to not resolve over the internet, but resolve locally with xml resolvers (or catalogs).

It even happened recently to the core w3 / xml urls as well.

See https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/

This impacts pretty much all xml documents in the wild (that declare a dtd or schema). 
As those XML entity references (Public ID and System ID) are not valid anymore due to a similar change.
(example: references to `http://www.w3.org/2001/XMLSchema.dtd` and `http://www.w3.org/2001/xml.xsd`)

We have a catalog for w3.org XML entities as well ...
https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-xml/src/main/resources/org/eclipse/jetty/xml/catalog-org.w3.xml

**Comment by joakime** [comment] 2022-10-19 16:57
Read the statement from w3.org about the XML System IDs.

https://www.w3.org/blog/2022/08/https-redirection-observations/

The names must not change (eg: from `http://...` to `https://...`), the reliance on remote resources is discouraged (need an internet connection), and catalog use is recommended.

The use of `http://www.eclipse.org/jetty/configure_9_0.dtd` (not `https`) is not considered a bug by the XML standards group, or by us.
The only fix that could be required on the Jetty Project is to ensure that we have all of the System IDs (and Public IDs) that we use be resolvable by local XML entity resolvers.
