### ISSUE TITLE
Occasional connection abort/reset when chunked encoding is used in request

### ISSUE THREAD

**Issue by molsza** [eclipse/jetty.project#3027] opened 2018-10-24 08:08 UTC
We have upgraded jetty to version 9.3.25 (the same with 9.4.12) and found that server is closing (with RST flag) the persistent connection more often than before. Previously we could exchange hundredths of requests using one connection. Now it is abruptly closed after a few requests. But sometimes jetty closes the connection before the response is send back to client. It happens randomly with POST/PUT requests with small payloads (3-10 chunks). One time we have observed that connection has been aborted after a GET requests, which happened after POST. 

Our application: Requests contains the JSON and are parsed by the Jackson. It doesn't matter if we are returning the error or positive response. The request payload should be completely consumed by Jackson. Our client is using connection pool, but we also tested with connection per request and it didn't remove the error completely. SO_LINGER (-1,0 or positive) doesn't matter. Connection is returning to the pool after each requests, reused immediately. No intermediaries. We are thinking the closer the client and server are the more probable that abort will occur. When client sends the _buffered_ requests the problem is not observed. 

Here is the stack trace showing where abort occurs:

```
Breakpoint reached at org.eclipse.jetty.server.HttpConnection.abort(HttpConnection.java:533)
Breakpoint reached
	  at org.eclipse.jetty.server.HttpConnection.abort(HttpConnection.java:533)
	  at org.eclipse.jetty.server.HttpChannel.abort(HttpChannel.java:869)
	  at org.eclipse.jetty.server.HttpChannelOverHttp.abort(HttpChannelOverHttp.java:468)
	  at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:414)
	  at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:688)
	  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:473)
	  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	  at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
```

The problem has been introduced by commit https://github.com/eclipse/jetty.project/commit/79e5c31029066adcc92d0b27a62fbdf72a517df8
Removing `_httpConnection.getParser().isChunking()` makes everything works again.

I don't know if I could extract the sample application to show the issue, but I would be happy to test a patch.

**Comment by sbordet** [comment] 2018-10-24 08:38
> When client sends the buffered requests the problem is not observed.

Can you detail what are "buffered requests"?

Did you bisect to know that the problem has been introduced by 79e5c31?

Would you be able to take a network trace via Wireshark and/or a DEBUG log when the issue happen?

I ask because the change introduced by 79e5c31 should be harmless and should not cause the problems you are seeing, so we would like to know what happens at the network level.

**Comment by molsza** [comment] 2018-10-24 09:17
By "buffered" I mean that transfer encoding is not set to chunked. Whole request payload is send with Content-Length header set.
I have recompiled the 9.3.25 without the `_httpConnection.getParser().isChunking()` and the problem disappeared.
When I enable the DEBUG in Jetty the problem is not observed. 
I have a few wiresharks sessions - I will send it to you.

**Comment by molsza** [comment] 2018-10-25 09:08
I have created the sample application which shows the problem - https://github.com/molsza/jettyRST

**Comment by joakime** [comment] 2018-10-25 13:32
@molsza been playing with your example application.

Some things I've noticed.

```
jetty93Version = "9.3.10.M0" 
```

That's an unstable release, hence the "M0" (meaning Milestone 0).

When testing, you are not using Jetty 9.3.x at all, nor are you using the configured (in build.gradle) Jetty 9.4.12, instead the jersey dependencies win and use Jetty 9.4.3.
Also, Jersey 2.26-b09 is an unstable beta release.  Jersey 2.26 has a number of serious bugs as well.  You should be using 2.27 or newer.

The project doesn't like newer versions of Java 8 (update 192 breaks `:integration`).  Fails on Java 11 entirely.

**Comment by joakime** [comment] 2018-10-25 13:34
Your integration tests on Java 8u161 fail for bad URI reasons.

```
08:28:28 WARN  bad HTTP parsed: 400 No URI for HttpChannelOverHttp@3347d01{r=1,c=false,a=IDLE,uri=null}

> Task :integration FAILED
    javax.ws.rs.InternalServerErrorException: HTTP 500 Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at ArraysReverserIT.simpleSingle(ArraysReverserIT.java:72)
        at ArraysReverserIT.lambda$multiThreaded$0(ArraysReverserIT.java:31)
        at java.lang.Thread.run(Thread.java:748)

ArraysReverserIT > multiThreaded FAILED
    javax.ws.rs.InternalServerErrorException at ArraysReverserIT.java:72
```

**Comment by joakime** [comment] 2018-10-25 14:22
I forked the example project and removed the gradle-uncertainty-principle by using maven.

It now builds and tests the same way every time, not at the whims of each build of gradle.
It also works on Java 8u192 and Java 11 as well.

https://github.com/joakime/jettyRST

Changes ...

* Corrected java package names (they were invalid and did not compile in your version)
* Removed gretty entirely
* Added formal junit testing using test specific Jetty server
* Added slf4j + jul-to-slf4j + logback for logging reasons - see /src/test/resources/logback.xml for configuration)
* Using slf4j logging in testcase (so that timings can be seen in logs)
* Upgrading to Jersey 2.27
* Properly configuring `jersey-container-jetty-servlet` to exclude its own jetty dependencies (they should neither be used at testing time, nor show up in the resulting WAR file's `WEB-INF/lib` directory)
* Adding `javax.xml.bind` based dependencies to allow project to function on all JVMs

Now it runs without error.

Logging output  ...

```
09:17:50.254 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @528ms to org.eclipse.jetty.util.log.Slf4jLog
09:17:50.460 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.12.v20180830; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 1.8.0_181-b13
09:17:50.698 [main] WARN  o.e.j.annotations.AnnotationParser - Unknown asm implementation version, assuming version 393216
09:17:50.698 [main] INFO  o.e.j.a.AnnotationConfiguration - Scanning elapsed time=0ms
09:17:50.707 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /reverse-arrays, did not find org.eclipse.jetty.jsp.JettyJspServlet
09:17:50.736 [main] INFO  org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0
09:17:50.736 [main] INFO  org.eclipse.jetty.server.session - No SessionScavenger set, using defaults
09:17:50.738 [main] INFO  org.eclipse.jetty.server.session - node0 Scavenging every 660000ms
09:17:50.770 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@6f96c77{/reverse-arrays,file:///C:/code/jetty/github/jettyRST/target/classes/,AVAILABLE}
09:17:50.791 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@654f0d9c{HTTP/1.1,[http/1.1]}{0.0.0.0:49478}
09:17:50.791 [main] INFO  org.eclipse.jetty.server.Server - Started @1069ms
09:17:50.794 [main] INFO  arrays_reverser.ArraysReverserTest - Tests will finish after 2 minutes or when first error occur
09:19:50.947 [main] INFO  arrays_reverser.ArraysReverserTest - Tests finish: 2 minutes is up
09:19:50.955 [main] INFO  o.e.jetty.server.AbstractConnector - Stopped ServerConnector@654f0d9c{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
09:19:50.955 [main] INFO  org.eclipse.jetty.server.session - node0 Stopped scavenging

Process finished with exit code 0
```

**Comment by joakime** [comment] 2018-10-25 14:56
Using the forked https://github.com/joakime/jettyRST we've been able to reproduce.

This is a flaky testcase.
It can be reproduced with more frequency when using an older JVM (like Java 8u162).
It does happen on Java 9, Java 10, and Java 11, but with each release it is less easy to reproduce.

**Comment by joakime** [comment] 2018-10-25 17:21
Looks like the TRACE functionality you have enabled in jersey ... 

``` java
@ApplicationPath("/")
public class App extends ResourceConfig {
  public App() {
    property(ServerProperties.TRACING, "ALL");
    property(ServerProperties.TRACING_THRESHOLD, "VERBOSE");
  }
}
```

is triggering the following exception on the server side after a while, which results in an aborted connection.

```
12:12:39.951 [qtp1241276575-32] DEBUG org.eclipse.jetty.io.ManagedSelector [ManagedSelector.java:403] - updates 0
12:12:39.951 [qtp1241276575-32] DEBUG o.e.j.u.t.ReservedThreadExecutor [ReservedThreadExecutor.java:276] - ReservedThreadExecutor@1dd02175{s=4/8,p=0}@7600f0d7 waiting
12:12:39.951 [qtp1241276575-19] DEBUG org.eclipse.jetty.server.HttpOutput [HttpOutput.java:221] - 
org.eclipse.jetty.http.BadMessageException: 500: Response header too large
	at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:466)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:733)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:538)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:831)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:887)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:239)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:215)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.HttpWriter.close(HttpWriter.java:49)
	at org.eclipse.jetty.server.ResponseWriter.close(ResponseWriter.java:163)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1038)
	at org.eclipse.jetty.server.handler.ErrorHandler.generateAcceptableResponse(ErrorHandler.java:178)
	at org.eclipse.jetty.server.handler.ErrorHandler.doError(ErrorHandler.java:142)
	at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:78)
	at org.eclipse.jetty.server.Response.sendError(Response.java:655)
	at org.eclipse.jetty.server.Response.sendError(Response.java:590)
	at org.eclipse.jetty.server.handler.ContextHandler.checkContext(ContextHandler.java:1145)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1187)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.BufferOverflowException: null
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at org.eclipse.jetty.http.PreEncodedHttpField.putTo(PreEncodedHttpField.java:119)
	at org.eclipse.jetty.http.HttpGenerator.putTo(HttpGenerator.java:940)
	at org.eclipse.jetty.http.HttpGenerator.generateHeaders(HttpGenerator.java:702)
	at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:448)
	... 36 common frames omitted
12:12:39.951 [qtp1241276575-28] DEBUG o.e.jetty.server.HttpConnection [HttpConnection.java:552] - abort HttpConnection@6b15cb7e::SocketChannelEndPoint@683c693d{/192.168.1.31:50236<->/192.168.1.31:50223,CLOSED,fill=-,flush=-,to=18/30000}{io=0/0,kio=-1,kro=-1}->HttpConnection@6b15cb7e[p=HttpParser{s=CHUNKED_CONTENT,0 of -1},g=HttpGenerator@351a44bf{s=START}]=>HttpChannelOverHttp@139cdaaf{r=11480,c=true,a=DISPATCHED,uri=//192.168.1.31:50223/reverse-arrays/,age=16} {}
```

**Comment by joakime** [comment] 2018-10-25 18:10
Pushed a bunch of small updates to the example project to make the rest call more accurate.

Still fails on the client side with ...

```
13:00:26.529 [Thread-10] WARN  arrays_reverser.ArraysReverserTest - Unable to execute simpleSingle
javax.ws.rs.ProcessingException: java.net.SocketException: Unexpected end of file from server
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
	at arrays_reverser.ArraysReverserTest.simpleSingle(ArraysReverserTest.java:105)
	at arrays_reverser.ArraysReverserTest.lambda$multiThreaded$0(ArraysReverserTest.java:52)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:390)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
	... 12 common frames omitted
```

The server side logs are large, but appear to show the reset.

**Comment by joakime** [comment] 2018-10-25 20:35
The server logs in last message do show the reset, but after `server.stop();`, which makes sense, as the server was gracefully stopped at that point.
Fixing up the example project and testcase to gracefully wait for active clients to stop after 2 minute timeout, then allow the `server.stop();`.

**Comment by molsza** [comment] 2018-10-26 06:11
The error we are looking for:
```
  javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at ArraysReverserIT.simpleSingle(ArraysReverserIT.java:72)
        at ArraysReverserIT.lambda$multiThreaded$0(ArraysReverserIT.java:31)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:390)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
        ... 12 more

```
In this case the RST is never issue in the middle of response write, it is always before.
Let me check if I can reproduce it with your changes.

**Comment by molsza** [comment] 2018-10-26 08:00
In case of windows, test will fail regardless of the jetty version.  :/
But on ubuntu,  switching to 9.3.9.v20160517 lets the test run "forever" (invokeAll blocks till all tasks completes)

**Comment by sbordet** [comment] 2018-10-26 11:40
It's a bug in Jersey.

What happens is that Jetty receives a chunk of content that happens to be the whole JSON.
However, the terminal chunk `0\r\n\r\n` has not been received yet.

Jetty passes it to the application (Jersey) that allocates a JSON parser and successfully parses it; Jersey thinks it's done, calls the application that writes the response.

Jetty writes the response and then figures out that the request content is not fully arrived yet, since Jetty has never seen the terminal chunk. Jetty tries to consume any request content that was not read, but there is nothing to consume, as the JSON has been fully read; however, Jetty cannot know that all content arrived and that the only missing bit is the terminal chunk, so assumes that more content needs to arrive and must abort the connection, causing the exceptions you see on the client.

Jersey must pass the chunks of content to the JSON parser _and_ ensure that the request content has been fully read (by reading -1 from `ServletInputStream`), and only then call the application.
I don't know if this is configurable in Jersey, perhaps using different providers that perform JSON parsing.

I'm not sure there is something that Jetty can do here.
Change 79e5c31 is irrelevant: perhaps it makes the issue happen more frequently but it's not the cause of the problem.

**Comment by joakime** [comment] 2018-10-26 12:40
I pushed some updates to the example project to demonstrate this discovery by @sbordet, including [a workaround (hack) on the Jersey endpoint when dealing with unconsumed input](https://github.com/joakime/jettyRST/commit/e230457e70255a224568c4914c9c6c772d967e84), as a result of the combination of ...

* Request with media-type that has it's own definition of start and end (like json and xml)
* Request body content sent with chunked encoding (meaning it has no known size, like you would see with `Content-Length`)
* The jackson parser reads the json from the `HttpServletRequest.getInputStream()`, and stops when it hits the end of the JSON, leaving the InputStream not at EOF.

Ideally, Jersey should finish its object parsing (like jaxb / jackson json / xml) and then read till EOF itself. 
If there are extra (non-whitespace) bytes encountered then that's a warning that jersey can produce, possibly indicating a faulty client is in use (sending more content then was actually read/parsed by jersey)

**Comment by gregw** [comment] 2018-10-26 21:59
Note that if need be, reading to EOF can be done in a Filter.  Perhaps we should write an example that does this asynchronously?

**Comment by molsza** [comment] 2018-10-29 07:42
I have change the Jackson and register it in jersey instead of the original one. 
```
public class JaxbJsonProvider extends JacksonJaxbJsonProvider {

  @Override
  public Object readFrom(Class<Object> type, Type genericType, Annotation[] annotations, MediaType mediaType, MultivaluedMap<String, String> httpHeaders, InputStream entityStream) throws IOException {
      Object result = super.readFrom(type, genericType, annotations, mediaType, httpHeaders, entityStream);
      while (entityStream.read() != -1) {}
      return result;
  }
}
```

**Comment by sbordet** [comment] 2018-10-29 08:21
@molsza feel free to close the issue if this works for you.
Have you reported the bug to Jersey?

**Closed** 2018-10-29 09:29 UTC
