### ISSUE TITLE
jetty-alpn-server (version 9.3.5) imports non existing org.eclipse.jetty.alpn in version 9.3.5

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#246] opened 2016-02-16 23:40 UTC
migrated from Bugzilla [#481057](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481057)
status REOPENED severity *normal* in component *osgi* for *9.3.x*
Reported in version *9.3.5* on platform *PC*
Assigned to: Jan Bartel

On 2015-10-29 16:37:46 -0400, Achim Nierbeck wrote:

> The import packages for the jetty-alpn-server bundle is wrong concerning the package of org.eclipse.jetty.apln, as it imports this package in version 9.3.5. 
> The only bundle exporting this package is the alpn-api bundle in version 1.1.2.v20150522. The package version inside this bundle is 1.1.2. 
> 
> So either the api bundle or the server bundle needs a correction of either import of export package.

On 2016-01-05 23:06:51 -0500, Jan Bartel wrote:

> Achim,
> 
> I think you might not have your osgi container configured correctly.  Here's a link to the alpn doc that mentions the special setup for osgi: http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html
> 
> Essentially, you have to insure that you have the alpn-boot jar on the -Xbootclasspath of your osgi container. That jar contains the api, however it does not expose those classes to the osgi classloader. To do that, you also need to deploy - as a normal bundle - the jetty-osgi-alpn jar (at the same version as the rest of your jetty bundles) as mentioned in the link above. That jar contains a FragmentHost directive in the manifest that ensures the api is exposed correctly.
> 
> Finally, you can check the junit tests for the jetty osgi/alpn integration to get some hints: https://github.com/eclipse/jetty.project/blob/master/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2.java
> 
> These unit tests work correctly, so please check the differences between them and your setup. 
> 
> If you follow all the advice and configure your environment correctly, and you still have an issue, please reopen this issue and explain exactly how your setup differs from the junit tests and why this is a problem.
> 
> thanks
> Jan

On 2016-01-23 17:20:29 -0500, Achim Nierbeck wrote:

> Could you please take a closer look at 
> the jetty-osgi-alpn bundle, as this one only exports the package 
> org.eclipse.jetty.alpn in version 1.1.2 
> 
> This is also true for version 9.3.6 of the jetty-osgi-alpn bundle.
> So either this one needs to export the right version (9.3.6) or
> the jetty-alpn-server bundle needs to import version 1.1.2 of that package. 
> 
> Please take a look at the excerpt below: 
> 
> Bundle-Name: Jetty OSGi ALPN Fragment
> Bundle-RequiredExecutionEnvironment: JavaSE-1.8
> Bundle-SymbolicName: org.eclipse.jetty.osgi.alpn.fragment;singleton:=t
>  rue
> Bundle-Vendor: Eclipse Jetty Project
> Bundle-Version: 9.3.6.v20151106
> Export-Package: org.eclipse.jetty.alpn;version="1.1.2"
> Fragment-Host: system.bundle;extension:=framework

**Comment by janbartel** [comment] 2016-04-30 00:36
I think this is a duplicate of #263, which has been fixed, so I'll close this issue.  Thanks for the pull request and my apologies for not seeing it.

**Closed by janbartel** 2016-04-30 00:36 UTC
Labels: Bug
