### ISSUE TITLE
NPE in Response.putHeaders

### ISSUE THREAD

**Issue by phax** [eclipse/jetty.project#1538] opened 2017-05-08 08:28 UTC
Since 9.4.4 I get an NPE when delivering static resources with embedded Jetty:
```
2017-05-08 10:21:47,682 [WARN ] [dev-localhost] [qtp596470015-23] /imgs/Logo_200px.jpg - org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:517)
java.lang.NullPointerException: null
	at org.eclipse.jetty.server.Response.putHeaders(Response.java:1435) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.ResourceService.putHeaders(ResourceService.java:844) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:686) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:294) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:458) ~[jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
... caused by ...
Thread [qtp596470015-22] (Suspended (breakpoint at line 1435 in Response))	
	Response.putHeaders(HttpContent, long, boolean) line: 1435	
	ResourceService.putHeaders(HttpServletResponse, HttpContent, long) line: 844	
	ResourceService.sendData(HttpServletRequest, HttpServletResponse, boolean, HttpContent, Enumeration<String>) line: 686	
	ResourceService.doGet(HttpServletRequest, HttpServletResponse) line: 294	
	DefaultServlet.doGet(HttpServletRequest, HttpServletResponse) line: 458	
	DefaultServlet(HttpServlet).service(HttpServletRequest, HttpServletResponse) line: 687	
	DefaultServlet(HttpServlet).service(ServletRequest, ServletResponse) line: 790	
	ServletHolder.handle(Request, ServletRequest, ServletResponse) line: 833	
	ServletHandler$CachedChain.doFilter(ServletRequest, ServletResponse) line: 1650	
	CharacterEncodingFilter.doHttpFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 125	
	CharacterEncodingFilter(AbstractHttpServletFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 66	
	ServletHandler$CachedChain.doFilter(ServletRequest, ServletResponse) line: 1637	
	HttpoxyFilter.doHttpFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 57	
	HttpoxyFilter(AbstractHttpServletFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 66	
	ServletHandler$CachedChain.doFilter(ServletRequest, ServletResponse) line: 1637	
	Log4jServletFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 71	
	ServletHandler$CachedChain.doFilter(ServletRequest, ServletResponse) line: 1637	
	ServletHandler.doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 533	
	ServletHandler(ScopedHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 143	
	ConstraintSecurityHandler(SecurityHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 548	
	SessionHandler(HandlerWrapper).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 132	
	SessionHandler(ScopedHandler).nextHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 190	
	SessionHandler.doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 1595	
	WebAppContext(ScopedHandler).nextHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 188	
	WebAppContext(ContextHandler).doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 1253	
	ServletHandler(ScopedHandler).nextScope(String, Request, HttpServletRequest, HttpServletResponse) line: 168	
	ServletHandler.doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 473	
	SessionHandler.doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 1564	
	WebAppContext(ScopedHandler).nextScope(String, Request, HttpServletRequest, HttpServletResponse) line: 166	
	WebAppContext(ContextHandler).doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 1155	
	WebAppContext(ScopedHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 141	
	Server(HandlerWrapper).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 132	
	Server.handle(HttpChannel) line: 564	
	HttpChannelOverHttp(HttpChannel).handle() line: 317	
	HttpConnection.onFillable() line: 251	
	AbstractConnection$ReadCallback.succeeded() line: 279	
	AbstractEndPoint$1(FillInterest).fillable() line: 110	
	ChannelEndPoint$2.run() line: 124	
	Invocable.invokePreferred(Runnable, Invocable$InvocationType) line: 128	
	Invocable$InvocableExecutor.invoke(Runnable) line: 222	
	EatWhatYouKill.doProduce() line: 294	
	EatWhatYouKill.run() line: 199	
	QueuedThreadPool.runJob(Runnable) line: 672	
	QueuedThreadPool$2.run() line: 590	
	Thread.run() line: 748	
```

The source line is:
```java
setContentType(content.getMimeType().getBaseType().asString());
```
and the problem is, that "getMimeType()" returns `null`. Since 9.4.3 this works as expected.

Request headers:
```
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/kb;jsessionid=node01ssxbctel0pm01109hqwipdw4w0.node0
Cookie: PHOTONSESSIONID=node01ssxbctel0pm01109hqwipdw4w0.node0
Connection: keep-alive
```

**Comment by gregw** [comment] 2017-05-08 08:58
Are you setting a Locale or an explicit charset?    This branch of the code should only be hit if you have somehow got an explicit charset and the content does not.

**Comment by gregw** [comment] 2017-05-08 08:58
Not saying it is not a bug... definitely is... I just want to know how you are getting there...

**Comment by phax** [comment] 2017-05-08 09:35
I'm not setting everything. This is handled directly from your `ResourceServlet` - no special configuration in the web.xml or the like.
Wait - I do have a "CharacterEncoding" Filter that sets an encoding upon every response.... That might be the reason!?

**Comment by gregw** [comment] 2017-05-08 13:39
phax, it is the reason that you are getting the NPE.   It is kind of non-nonsensical to set a charset for an image, but then we should not NPE if you do and just send the "image/jpeg;charset=utf-8" content-type because the servlet spec takes the attitude that the developer knows what they are doing.  So I have checked in a fix for the next release. 

For the current releases (9.4.4 and 9.4.5), you can avoid the NPE by only setting the charset on text types.

**Closed by gregw** 2017-05-08 13:39 UTC

**Comment by phax** [comment] 2017-05-08 14:10
Thanks for the update. The Filter was always pleasant but I agree that it should be MIME type dependant.

**Comment by joakime** [comment] 2017-05-12 12:52
Looks like @olamy and the Apache Archiva project hit this too, but on a text (non-image) type.

@gregw do you think this is related?

```
2017-05-12 20:56:35.433:WARN:oejs.HttpChannel:qtp1084978087-112: /archiva/css/prettify.css
java.lang.NullPointerException
      at org.eclipse.jetty.server.Response.putHeaders(Response.java:1435)
      at org.eclipse.jetty.server.ResourceService.putHeaders(ResourceService.java:844)
      at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:686)
      at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:294)
      at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:458)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
      at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
      at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
      at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
      at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
      at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
      at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
```

**Comment by joakime** [comment] 2017-05-12 12:57
I suspect the `org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
` is the culprit in @olamy 's NPE

**Comment by phax** [comment] 2017-05-12 21:26
My filter is inspired by Spring's CharacterEncodingFilter so I guess it is the same :)

**Comment by olamy** [comment] 2017-05-12 23:00
`forceEncoding -> false ` with the Spring servlet fix the issue.
