### ISSUE TITLE
WebSocketServerFactory: NPE on server startup with log level DEBUG

### ISSUE THREAD

**Issue by bistvan** [eclipse/jetty.project#2666] opened 2018-06-13 12:13 UTC
In case of log level is DEBUG, the addBean() invoked by the WebSocketServerFactory constructor prints out the string value of that instance, but the creator is not initialized yet.

java.lang.NullPointerException
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.toString(WebSocketServerFactory.java:641)
	at java.lang.String.valueOf(String.java:2994)
	at org.eclipse.jetty.util.log.StdErrLog.format(StdErrLog.java:552)
	at org.eclipse.jetty.util.log.StdErrLog.format(StdErrLog.java:441)
	at org.eclipse.jetty.util.log.StdErrLog.debug(StdErrLog.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:322)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:226)
	**at org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(WebSocketServerFactory.java:149)**
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(WebSocketServerFactory.java:138)
	at org.eclipse.jetty.websocket.server.WebSocketHandler.doStart(WebSocketHandler.java:82)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
...

**Comment by joakime** [comment] 2018-06-13 19:18
The referenced lines of the Jetty 9.4.6.v20170531 `WebSocketServerFactory.toString()` causing the issue with OP.

https://github.com/eclipse/jetty.project/blob/8ba0f2d95dbacbe34898f8de15389e39b4e44279/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java#L636-L644

**Comment by joakime** [comment] 2018-06-13 19:21
Closing, as this is a Duplicate of #1603 and fixed in Jetty 9.4.7.v20170914

**Closed by joakime** 2018-06-13 19:21 UTC
