### ISSUE TITLE
DoSFilter gives java.io.NotSerializableException

### ISSUE THREAD

**Issue by thomasmey** [eclipse/jetty.project#1156] opened 2016-12-09 11:02 UTC
The inner class RateTracker is stored in the HttpSession, but the outer class is not Serializable, which leads to a stack trace like this when used in a webapp with distributable tag:

09-Dec-2016 11:23:06.034 SEVERE [http-nio-12292-exec-10] org.apache.catalina.ha.session.DeltaManager.requestCompleted Unable to serialize delta request for sessionid [9FB9B357F5ECEEC25F96516296241C7B.0]
 java.io.NotSerializableException: org.eclipse.jetty.servlets.DoSFilter
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.catalina.ha.session.DeltaRequest$AttributeInfo.writeExternal(DeltaRequest.java:401)
	at org.apache.catalina.ha.session.DeltaRequest.writeExternal(DeltaRequest.java:294)
	at org.apache.catalina.ha.session.DeltaRequest.serialize(DeltaRequest.java:308)
	at org.apache.catalina.ha.session.DeltaManager.serializeDeltaRequest(DeltaManager.java:585)
	at org.apache.catalina.ha.session.DeltaManager.requestCompleted(DeltaManager.java:966)
	at org.apache.catalina.ha.session.DeltaManager.requestCompleted(DeltaManager.java:933)
	at org.apache.catalina.ha.tcp.ReplicationValve.send(ReplicationValve.java:525)
	at org.apache.catalina.ha.tcp.ReplicationValve.sendMessage(ReplicationValve.java:513)
	at org.apache.catalina.ha.tcp.ReplicationValve.sendSessionReplicationMessage(ReplicationValve.java:495)
	at org.apache.catalina.ha.tcp.ReplicationValve.sendReplicationMessage(ReplicationValve.java:406)
	at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:329)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gregw** [comment] 2016-12-09 22:29
Interestingly you appear to be running the DoSFilter in tomcat!    I guess no reason why that would not work!

I think we have to think carefully about what DoSFilter should do when running in a cluster. Should it attempt to track request rates cluster wide?   Could be difficult with the poor session semantics available.   I would think the load balancer would be a better place to do DoS protection in a cluster.

Eitherway, we should at least remove the tracker if a session is passivated.

**Comment by thomasmey** [comment] 2016-12-12 12:58
Hi,

yeah, good points.

Another independent idea: can you enhance getRateTracker() to use "x-forwarded-for" header then try the remote IP address?

**Comment by vgarmash** [comment] 2018-02-02 21:04
I have same issue running it on Jetty:
`2018-02-02 15:57:38,012 [qtp272537970-70] WARN  org.eclipse.jetty.server.session - Problem persisting changed session data id=fll1001512l1b4cn3y8spoiszxiria2u8eed
java.io.NotSerializableException: org.eclipse.jetty.servlets.DoSFilter
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_151]
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790) ~[?:1.8.0_151]
	at java.util.HashMap.writeObject(HashMap.java:1363) ~[?:1.8.0_151]
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_151]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_151]
	at org.eclipse.jetty.server.session.JDBCSessionManager.updateSession(JDBCSessionManager.java:1084) ~[jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.JDBCSessionManager$Session.save(JDBCSessionManager.java:366) ~[jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at denver.commerce.server.sessions.MyJDBCSessionManager$MyJDBCSession.save(MyJDBCSessionManager.java:47) ~[classes/:?]
	at org.eclipse.jetty.server.session.JDBCSessionManager$Session.complete(JDBCSessionManager.java:323) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.AbstractSessionManager.complete(AbstractSessionManager.java:225) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:197) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:461) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.11.v20160721.jar:9.3.11.v20160721]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by joakime** [comment] 2018-02-02 21:19
The RateTracker inner object should probably be moved out of DoSFilter into its own top level class.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/DoSFilter.java#L1147-L1153

**Comment by vgarmash** [comment] 2018-02-02 23:00
Actually to make this filter properly serializable all it's fields should be made serializable. Looking into the source I see these non-serializable fields:

1. private final ConcurrentHashMap<String, RateTracker> _rateTrackers
2. private Queue<AsyncContext>[] _queues;
3. private AsyncListener[] _listeners;
4. private Scheduler _scheduler;

in addition to that would be also benefitial to change the parent interface from `javax.servlet.Filter` to `javax.servlet.http.HttpFilter`, which  is already Serializable.

Otherwise please let us know, how to configure Jetty to not attempt to serialize the DosFilter.

**Comment by olamy** [comment] 2019-11-21 04:29
AFICS RateTracker is now Serializable

**Comment by sbordet** [comment] 2019-11-21 08:44
The problem is that we store `RateTracker` in the `HttpSession` and so it must be serializable.
Reopening as this is still an issue.

**Comment by olamy** [comment] 2019-11-21 09:01
@sbordet more details on why I closed it. looking at the class it's definitely serializable (the only non serializable field is transient)  https://github.com/eclipse/jetty.project/blob/07680b4bb20f9acafdee9ea2fde550c23661f32b/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/DoSFilter.java#L1157    I guess it has been fixed with https://github.com/eclipse/jetty.project/commit/e39c66d42568cc63e50d935ad7036bd87dd1bd18#diff-f0d4055c341e665e66e56b4b3c8ae099
I guess this issue can closed

**Comment by sbordet** [comment] 2019-11-21 09:06
@olamy is there a test that proves this? I ask because serialization is tricky and just looking at the code may not be enough. Plus, when deserialized and without the transient `ServletContext`, will it work or just give a NPE?

**Comment by olamy** [comment] 2019-11-21 09:13
as far I can see the changes https://github.com/eclipse/jetty.project/commit/e39c66d42568cc63e50d935ad7036bd87dd1bd18#diff-f0d4055c341e665e66e56b4b3c8ae099  add a unit test which use FileSessionDataStore. There is a null check in the code.
but leave this issue open and we can review if the test really cover the case

**Comment by olamy** [comment] 2019-11-27 03:39
unit test added here #4370 cannot reproduce RateTracker is correctly serialized with JDBC session store

**Comment by sbordet** [comment] 2019-11-27 09:31
This is fixed.

**Closed by sbordet** 2019-11-27 09:31 UTC

**Comment by thomasmey** [comment] 2019-11-27 09:34
Hi,

Sorry for the late reply. I think this issue was fixed some time ago, we using version 9.4.14.v20181114 for some month now in production and we don't see the exception anymore.
