### ISSUE TITLE
Memory leak in Servlet async IO

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#299] opened 2016-02-16 23:48 UTC
migrated from Bugzilla [#487760](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487760)
status ASSIGNED severity *normal* in component *servlet-3.1* for *9.3.x*
Reported in version *9.3.7* on platform *PC*
Assigned to: Jan Bartel

On 2016-02-12 13:52:35 -0500, Xiaodong Wang wrote:

> Memory leak when using Servlet async IO, one java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask for each request, which should be cleaned once the request is completed.
> 
> You can reproduce this issue by sending several thousand requests to the sample servlet from https://github.com/eclipse/jetty.project/blob/master/examples/embedded/src/main/java/org/eclipse/jetty/embedded/AsyncEchoServlet.java

On 2016-02-15 12:23:47 -0500, Jan Bartel wrote:

> Hi,
> 
> I haven't been able to reproduce the problem. 
> 
> Can you please describe in detail how you're sending the requests, including what tool you're using to generate the requests, and an example of a generated request.  Please also attach the information you have that leads you to suspect there is one ScheduledFutureTask per request.
> 
> regards
> Jan

**Comment by xiaodongw** [comment] 2016-02-21 06:50
I wrote a sample to test the problem again.

The problem is in Scalatra framework, seems like Scalatra calls async operations like HttpServletRequest.startAsync() and AsyncContext.complete() in the ExecutionContext threads. Does Jetty require AsyncContext.complete() must be called in the thread of the callback?

Since this is not a Jetty problem, you can close this issue.

I attached the test sample, you can take a look if you are interested.
"gradle runServer" to run the test server, "gradle runClientScalatra" to send traffic to server.

[jetty-scalatra-asyncio-leak.zip](https://github.com/eclipse/jetty.project/files/139486/jetty-scalatra-asyncio-leak.zip)

**Comment by sbordet** [comment] 2016-02-21 22:00
Jetty, but more precisely the Servlet specification, does not require that `AsyncContext.complete()` be called in any particular thread: it can be any thread, included the one that called `HttpServletRequest.startAsync()`.

Closing as requested.

**Closed by sbordet** 2016-02-21 22:00 UTC
Labels: Bug
