### ISSUE TITLE
NullPointerException in AbstractConnection

### ISSUE THREAD

**Issue by markkolich** [eclipse/jetty.project#9522] opened 2023-03-21 05:25 UTC
**Jetty version(s)**
`9.4.51.v20230217`

Does _not_ reproduce with `9.4.50.v20221201`

((Yes, I know Jetty 9 is end of community support...reporting anyways))

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Raspbian-1deb10u1)
OpenJDK Server VM (build 11.0.18+10-post-Raspbian-1deb10u1, mixed mode)

**OS type/version**
Raspbian and macOS

**Description**
```
2023-03-21T05:19:49,639Z WARN [jetty-onyx-18] o.e.j.i.AbstractConnection:96 -
java.lang.NullPointerException: null
        at org.eclipse.jetty.io.AbstractConnection.lambda$failedCallback$0(AbstractConnection.java:92)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**How to reproduce?**
Not sure - just using my application which appears to function normally sans the NPE warning spew:

https://github.com/eclipse/jetty.project/blob/837a073ffe5ef2ba9f2bfaa133194c71086caaa8/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java#L90-L97

The same usage on `9.4.50.v20221201` does not result in these NPE warns.

**Comment by joakime** [comment] 2023-03-21 11:59
Duplicate of #9476

**Comment by markkolich** [comment] 2023-03-21 15:06
Tracking duplicate https://github.com/eclipse/jetty.project/issues/9476

**Closed as completed** 2023-03-21 15:06 UTC
Labels: Bug, Unsupported Release
