### ISSUE TITLE
ArrayIndexOutOfboundsException in ProxyServlet

### ISSUE THREAD

**Issue by tmrobert8** [eclipse/jetty.project#3084] opened 2018-11-09 12:22 UTC
I have a servlet that is receiving a callback from a piece of hardware (NEEO Brain) and am getting the following AIOOB.  Pretty sure the encoded slashes are what's giving it issues... 

```
2018-11-08 15:27:48.264:WARN:oejs.HttpChannel:qtp1596038409-1290: /neeo/NEEO-a5056097%2Fdevice%2Fapt-neeo_io%3Avirtual%3A6jzOoAtL%2FTemperature_GF_Living%2Fnone%2F1%2Fdirectory%2Factor/default
java.lang.ArrayIndexOutOfBoundsException: -6
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.getNotDecodedAlias(ProxyServlet.java:76)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joakime** [comment] 2018-11-09 13:30
```
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.getNotDecodedAlias(ProxyServlet.java:76)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:90)
```

This appears to be a bug in the Equinox ProxyServlet.

The Eclipse Jetty project does not maintain the Equinox ProxyServlet.

Please file this issue with the Eclipse Equinox project at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Equinox

Unfortunately, [I don't see an existing bug that fits your description](https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&f0=OP&f1=OP&f10=OP&f11=OP&f12=product&f13=component&f14=alias&f15=short_desc&f16=status_whiteboard&f17=content&f18=CP&f19=CP&f2=product&f3=component&f4=alias&f5=short_desc&f6=status_whiteboard&f7=content&f8=CP&f9=CP&j1=OR&j11=OR&list_id=18005866&o12=substring&o13=substring&o14=substring&o15=substring&o16=substring&o17=matches&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&product=Equinox&query_format=advanced&short_desc=ArrayIndexOutOfBoundsException&short_desc_type=allwordssubstr&v2=ArrayIndexOutOfBoundsException&v3=ArrayIndexOutOfBoundsException&v4=ArrayIndexOutOfBoundsException&v5=ArrayIndexOutOfBoundsException&v6=ArrayIndexOutOfBoundsException&v7=%22ArrayIndexOutOfBoundsException%22).

**Comment by joakime** [comment] 2018-11-09 13:35
The entire reason `org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.getNotDecodedAlias` even exists is because of the following bug.

https://bugs.eclipse.org/497510

You might want to look into why the equinox project did that.

**Comment by joakime** [comment] 2018-11-09 13:43
Closing as Invalid for this project and it's issue tracker.

**Closed by joakime** 2018-11-09 13:43 UTC
Labels: Invalid

**Comment by tmrobert8** [comment] 2018-11-09 13:56
Thanks - was unsure where to report this.  Reported it over at eclipse equinox now..

**Comment by joakime** [comment] 2018-11-09 15:14
Linking your new bug here (for others in the future that find this issue via search) - https://bugs.eclipse.org/540970
