### ISSUE TITLE
DNS reverse resolve is too slow

### ISSUE THREAD

**Issue by HashZhang** [eclipse/jetty.project#1694] opened 2017-07-26 12:29 UTC
In SslConnectionFactory.java:
```
 @Override
    public Connection newConnection(Connector connector, EndPoint endPoint)
    {
        SSLEngine engine = _sslContextFactory.newSSLEngine(endPoint.getRemoteAddress());
        engine.setUseClientMode(false);

        SslConnection sslConnection = newSslConnection(connector, endPoint, engine);
        sslConnection.setRenegotiationAllowed(_sslContextFactory.isRenegotiationAllowed());
        sslConnection.setRenegotiationLimit(_sslContextFactory.getRenegotiationLimit());
        configure(sslConnection, connector, endPoint);

        ConnectionFactory next = connector.getConnectionFactory(_nextProtocol);
        EndPoint decryptedEndPoint = sslConnection.getDecryptedEndPoint();
        Connection connection = next.newConnection(connector, decryptedEndPoint);
        decryptedEndPoint.setConnection(connection);

        return sslConnection;
    }

```

endPoint.getRemoteAddress() returns slowly because of DNS reverse resolving; however, in cloud environment, rely on this to get hostname is really troublemaking;
do you have some solution other than modify /etc/hosts or /etc/resolv.conf? tks~

**Comment by joakime** [comment] 2017-09-06 17:45
Duplicate of #1235 - which is available in Jetty 9.4.5+

**Closed by joakime** 2017-09-06 17:45 UTC
