### ISSUE TITLE
Jetty 9.2.11 blocks while reading content and throws java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#235] opened 2016-02-16 23:38 UTC
migrated from Bugzilla [#479299](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479299)
status NEW severity *normal* in component *proxy* for *9.3.x*
Reported in version *9.2.11* on platform *PC*
Assigned to: Simone Bordet

Original attachment names and IDs:
- _[broker.log](https://bugs.eclipse.org/bugs//attachment.cgi?id=257139)_ (ID 257139)
- _[router.log](https://bugs.eclipse.org/bugs//attachment.cgi?id=257140)_ (ID 257140)

On 2015-10-08 01:17:20 -0400, Nishant Bangarwa wrote:

> Created attachment 257139
> debug logs and stack trace for the the hanging thread
> 
> Scenario:  When we upgrade Jetty from 9.2.10 to 9.2.11 in test environment, we are seeing jetty thread hanging on below stack trace waiting for content and eventually timing out after Idle timeout, java.util.concurrent.TimeoutException: Idle timeout expired: 300005/300000 ms. 
> 
> Stack Trace where the thread Hangs - 
> "qtp1045677229-47@4865" daemon prio=5 tid=0x2f nid=NA waiting
>   java.lang.Thread.State: WAITING
>       at sun.misc.Unsafe.park(Unsafe.java:-1)
>       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
>       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
>       at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:219)
>       at org.eclipse.jetty.server.HttpInputOverHTTP.blockForContent(HttpInputOverHTTP.java:66)
>       at org.eclipse.jetty.server.HttpInput$1.waitForContent(HttpInput.java:476)
>       at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:121)
>       - locked <0x18d7> (a org.eclipse.jetty.server.HttpInputOverHTTP)
>       at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:489)
>       at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:126)
>       at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:215)
>       at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1191)
>       at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:753)
>       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
>       at io.druid.server.QueryResource.doPost(QueryResource.java:134)
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>       at java.lang.reflect.Method.invoke(Method.java:497)
>       at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
> 
> 
> More Info on setup - 
> - We use AsyncProxyServlet to proxy requests from a router to other nodes. 
> - the request content contains a JSON object.
> - Attached the debug jetty logs for the the proxy and the node which hangs with thread dumps for both.
> - when it happens there is no load on the system and only a single request is being forwarded through the proxy.
> - It starts to work if i downgrade jetty to v9.2.10
> 
> 
> Let me know if more info is required.

On 2015-10-08 01:18:30 -0400, Nishant Bangarwa wrote:

> Created attachment 257140
> debug logs for the proxy forwarding the request

On 2015-10-08 01:26:49 -0400, Nishant Bangarwa wrote:

> - Another thing to note is that it only occurs with requests whoose content is beyond a  certain size (havent figured out what that threshold is) the Json content is about 2KB in size, If we remove part of the json object to reduce the size of content it works.

**Comment by nishantmonu51** [comment] 2016-02-22 14:14
@sbordet any progress on this ?

**Comment by fjy** [comment] 2016-02-22 19:24
I've also made some comments here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=478923

**Comment by sbordet** [comment] 2016-02-23 16:13
@nishantmonu51 the request contains `Expect: 100-continue`, which is somehow controversial to interoperate well. If you can avoid it, that will be great.
Keep an eye on #277, where we seem to have a bug, but I have not explored that yet.

@fjy the bugzilla you linked is related to a whole different issue than this one: that issue was about Jetty handling better blocking cases in case of low threads.
Threads blocked while reading content is typically a client problem.
My suggestion is that you try to replicate the issue, write something that we can reproduce, or at least provide detailed logs for your particular case, and open a new issue. It may be that your issue is not this one, and neither the one you linked.

I am closing this issue as duplicate of #277, so @nishantmonu51 watch that instead.

Thanks !

**Closed by sbordet** 2016-02-23 16:13 UTC
Labels: Bug
