### ISSUE TITLE
Jetty XML Configure_10_0.dtd should handle AttrOrElementNode behavior

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4659] opened 2020-03-10 14:22 UTC
As a result of the work done in #4631 (PR #4632) the `<Configure>` element in the `Configure_10_0.dtd` doesn't not seem to have the same Attr or Element behaviors defined like `<Call>` and `<New>` have.

https://github.com/eclipse/jetty.project/blob/678385bfda0f90a0bcccf7f86aa272073c1b4f29/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd#L45-L46

https://github.com/eclipse/jetty.project/blob/678385bfda0f90a0bcccf7f86aa272073c1b4f29/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd#L168-L169

https://github.com/eclipse/jetty.project/blob/678385bfda0f90a0bcccf7f86aa272073c1b4f29/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd#L209-L210

**Comment by gregw** [comment] 2020-03-10 16:50
Closed as duplicate of #4656

**Closed as completed by gregw** 2020-03-10 16:50 UTC
Labels: Duplicate
