### ISSUE TITLE
Using start.jar --create-startd --add-to-start=<module> results in existing start.ini being deleted

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5970] opened 2021-02-11 16:34 UTC
**Jetty version**
9.4.36.v20210114

**Description**
Steps to reproduce ...

```
[myappbase]$ java -jar ~/code/jetty/distros/jetty-home-9.4.36.v20210114/start.jar --add-to-start=http,deploy
INFO  : webapp          transitively enabled, ini template available with --add-to-start=webapp
INFO  : server          transitively enabled, ini template available with --add-to-start=server
INFO  : security        transitively enabled
INFO  : servlet         transitively enabled
INFO  : http            initialized in ${jetty.base}/start.ini
INFO  : threadpool      transitively enabled, ini template available with --add-to-start=threadpool
INFO  : bytebufferpool  transitively enabled, ini template available with --add-to-start=bytebufferpool
INFO  : deploy          initialized in ${jetty.base}/start.ini
INFO  : Base directory was modified
[myappbase]$ ls -la
total 16
drwxr-xr-x  3 joakim joakim 4096 Feb 11 10:32 ./
drwxr-xr-x 30 joakim joakim 4096 Feb  2 13:56 ../
-rw-rw-r--  1 joakim joakim 2270 Feb 11 10:32 start.ini
drwxr-xr-x  3 joakim joakim 4096 Feb  9 08:28 webapps/
[myappbase]$ java -jar ~/code/jetty/distros/jetty-home-9.4.36.v20210114/start.jar --create-startd --add-to-start=rewrite
MKDIR : ${jetty.base}/start.d
INFO  : rewrite         initialized in ${jetty.base}/start.d/rewrite.ini
INFO  : Base directory was modified
[myappbase]$ ls -la
total 16
drwxr-xr-x  4 joakim joakim 4096 Feb 11 10:32 ./
drwxr-xr-x 30 joakim joakim 4096 Feb  2 13:56 ../
drwxrwxr-x  2 joakim joakim 4096 Feb 11 10:32 start.d/
drwxr-xr-x  3 joakim joakim 4096 Feb  9 08:28 webapps/
[myappbase]$ ls -la start.d/
total 16
drwxrwxr-x 2 joakim joakim 4096 Feb 11 10:32 ./
drwxr-xr-x 4 joakim joakim 4096 Feb 11 10:32 ../
-rw-rw-r-- 1 joakim joakim  527 Feb 11 10:32 rewrite.ini
```

The code seems to indicate that the start.ini is to be moved to `start.d/`, it doesn't seem to work.

I also disagree with that move of start.ini behavior, that's would be quite a shocking and unexpected change.

**Comment by joakime** [comment] 2021-02-11 16:37
This behavior remains the same even if using the older (now deprecated) command line option `--add-to-startd=<name>`

**Comment by gregw** [comment] 2021-03-22 06:00
I cannot reproduce with 9.4.38:
```
gregwilkins@gregwilkins1:/tmp
$ mkdir test

gregwilkins@gregwilkins1:/tmp
$ cd test

gregwilkins@gregwilkins1:/tmp/test
$ export JETTY_HOME=/opt/jetty-distribution-9.4.38.v20210224

gregwilkins@gregwilkins1:/tmp/test
$ java -jar $JETTY_HOME/start.jar --add-to-start=http,deploy
INFO  : webapp          transitively enabled, ini template available with --add-to-start=webapp
INFO  : server          transitively enabled, ini template available with --add-to-start=server
INFO  : security        transitively enabled
INFO  : servlet         transitively enabled
INFO  : http            initialized in ${jetty.base}/start.ini
INFO  : threadpool      transitively enabled, ini template available with --add-to-start=threadpool
INFO  : bytebufferpool  transitively enabled, ini template available with --add-to-start=bytebufferpool
INFO  : deploy          initialized in ${jetty.base}/start.ini
MKDIR : ${jetty.base}/webapps
INFO  : Base directory was modified

gregwilkins@gregwilkins1:/tmp/test
$ tree .
.
├── start.ini
└── webapps

1 directory, 1 file

gregwilkins@gregwilkins1:/tmp/test
$ java -jar $JETTY_HOME/start.jar --create-startd --add-to-start=rewrite
MKDIR : ${jetty.base}/start.d
INFO  : rewrite         initialized in ${jetty.base}/start.d/rewrite.ini
INFO  : Base directory was modified

gregwilkins@gregwilkins1:/tmp/test
$ tree .
.
├── start.d
│   ├── rewrite.ini
│   └── start.ini
└── webapps

2 directories, 2 files

```

This has been the behaviour for some time. It was added when we made it an error to have both `start.d` and a `start.ini`.

I'm closing this for now. Please reopen if you can reproduce.

**Closed as completed by gregw** 2021-03-22 06:00 UTC
