### ISSUE TITLE
EofException Reset Error

### ISSUE THREAD

**Issue by headlamp-software** [eclipse/jetty.project#6460] opened 2021-06-22 17:51 UTC
I am using Jetty 9.4.18.v20190429 and getting a reset eofexception. I am not sure if this is a Jetty bug, my bug, a bug in the Browser (Chrome in this case), or no bug at all.
What (if anything) needs to be done?
Is additional documentation needed?
Thank you
Peter Schaeffer
<img width="493" alt="Jetty" src="https://user-images.githubusercontent.com/74732954/122975021-88c31080-d358-11eb-8080-3e759151563f.PNG">

**Comment by joakime** [comment] 2021-06-22 18:56
You are using `9.4.18.v20190429`, upgrade to the latest in the 9.4.x series at least (currently at [`9.4.42.v20210604`](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.42.v20210604)), and try again.

There has been a tremendous amount of work done on HTTP/2 in the years since 9.4.18, including a whole bunch of TLS fixes, industry wide HTTP/2 protocol updates, and more.

Not to mention the various security advisories you are subject to by that old of a version of Jetty - https://www.eclipse.org/jetty/security_reports.php

You are missing a whole slew of major fixes to HTTP/2 that the entire industry performed in late 2019 due to a series of very public CVEs (Jetty made those fixes in the version 9.4.21 time period)

**Comment by headlamp-software** [comment] 2021-06-22 21:13
Thank you. How would I go about getting the jar files for Jetty 9.4.42.v20210604? Where are they located? Thank you.

**Comment by joakime** [comment] 2021-06-22 22:02
@headlamp-software the usual places.

The Eclipse Jetty project publishes it's artifacts to the global artifact repository system (that massive mirrored database of artifacts available to everyone in the world), suitable for consumption by build tools like maven, gradle, kotlin, sbt, ivy, grape, leiningen, buildr, purl etc ...   

What you need to know (depending on your build tool) is that we publish on the `org.eclipse.jetty` groupId, under the various dependencies you need, including metadata for transitive dependencies.  The exact details on accessing the artifacts are dependent on your build tool of choice.

As an example, if you use maven, here's a few search result for the jetty-proxy 9.4.42.v20210604 artifact on this respository system ...

* https://search.maven.org/artifact/org.eclipse.jetty/jetty-proxy/9.4.42.v20210604/jar 
* https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-proxy/9.4.42.v20210604

We announce here on github as well - https://github.com/eclipse/jetty.project/releases

We also update the main website at https://www.eclipse.org/jetty/download.php

**Comment by headlamp-software** [comment] 2021-06-23 04:17
OK, I upgraded to 9.4.42.v20210604. I am still getting similar errors. Are these my bugs? Jetty bugs? Browser issues? Not really a problem? Thank you. Peter Schaeffer. Note that the 'gif' file is really a Wireshark capture file. The correct file suffix is pcapng. Take a look at frame 5790. This is the rst_stream sent from the Chrome browser client to the Jetty server.

<img width="823" alt="Reset Stream Error" src="https://user-images.githubusercontent.com/74732954/123034560-5c86ae80-d3af-11eb-86cd-0b3c43978937.png">
![Reset Stream Error](https://user-images.githubusercontent.com/74732954/123034650-84761200-d3af-11eb-9f06-f5b358340b10.gif)
<img width="823" alt="Reset Stream Error" src="https://user-images.githubusercontent.com/74732954/123034653-85a73f00-d3af-11eb-8bbe-f4d8d4711abd.png">

**Comment by headlamp-software** [comment] 2021-06-24 02:32
I have worked on this a bit and found a partial explanation. I was sending a 'Connection' header back to the client even though that is forbidden by the HTTP2 specification. I took the 'Connection' header out and things improved. A get a lot fewer errors now, but the number is not zero. I still get Reset cancel_stream_error(s), but not as many of them. I am still sending something that upsets the browser . What it is, is not clear. Of course, maybe Jetty is sending it. Maybe this isn't a real problem at all. Not at all sure.

**Comment by gregw** [comment] 2021-06-30 07:05
Peter,

I'm going to close this for now, as there is nothing here to indicate a jetty problem.   However, if you do work out that the browser is resetting the connection due to something that is being sent by jetty (or even if you just capture the conversation that leads up to a reset that you suspect may be caused by jetty), then please either reopen this or raise a new issue.

In either case, having info about how other browsers/clients react would be good.... potentially trying to turn on the browsers logging/debugging might say something. Also getting full traces of all the details of the responses sent by jetty prior to the reset would be helpful.  Also, does the app in the browser actually lack any resources?  perhaps there is a reason the requests are cancelled?

**Closed as completed by gregw** 2021-06-30 07:05 UTC
Labels: Bug

**Comment by sbordet** [comment] 2021-06-30 09:47
> I was sending a 'Connection' header back to the client even though that is forbidden by the HTTP2 specification.

Even if an application is setting the `Connection` header in the response, Jetty's HTTP/2 implementation will not send it to the client, to comply with the HTTP/2 implementation.

Bear in mind that cancelled streams may be due to browser activity caused by a human, for example page refresh or closing the browser, or closing the laptop lid, etc. so they are typically expected.

If they are not expected in your case, then you have to figure out why the client was resetting the stream like @gregw suggested.
