### ISSUE TITLE
HttpClientLoadTest - javax.net.ssl.SSLException: Received fatal alert: internal_error] ==> expected: <true> but was: <false>

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3301] opened 2019-01-29 18:46 UTC
**Output:**

```
2019-01-29 12:27:18.558:INFO:oejs.Server:main: jetty-10.0.0-SNAPSHOT; built: 2019-01-29T17:50:54.682Z; git: 1d9e7b7613055e8f775b0dfe7e1d1ab2d518512f; jvm 11.0.2+7
2019-01-29 12:27:18.562:INFO:oejus.SslContextFactory:main: x509=X509@ff7d154(mykey,h=[],w=[]) for SslContextFactory@2a6736bc[provider=null,keyStore=file:///home/joakim/code/jetty/jetty.project-10.0.x/tests/test-http-client-transport/src/test/resources/keystore.jks,trustStore=file:///home/joakim/code/jetty/jetty.project-10.0.x/tests/test-http-client-transport/src/test/resources/truststore.jks]
2019-01-29 12:27:18.562:WARN:oejusS.SslContextFactoryConfig:main: No Client EndPointIdentificationAlgorithm configured for SslContextFactory@2a6736bc[provider=null,keyStore=file:///home/joakim/code/jetty/jetty.project-10.0.x/tests/test-http-client-transport/src/test/resources/keystore.jks,trustStore=file:///home/joakim/code/jetty/jetty.project-10.0.x/tests/test-http-client-transport/src/test/resources/truststore.jks]
2019-01-29 12:27:18.563:INFO:oejs.AbstractConnector:main: Started ServerConnector@765eed80{SSL,[ssl, http/1.1]}{0.0.0.0:40067}
2019-01-29 12:27:18.563:INFO:oejs.Server:main: Started @370221ms
javax.net.ssl.SSLException: Received fatal alert: internal_error
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:672)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:627)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:422)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:563)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:128)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:365)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-29 12:27:18.896:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-3: 256 requests in 328 ms, 780 req/s
2019-01-29 12:27:18.899:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-117: 256 requests in 331 ms, 773 req/s
2019-01-29 12:27:18.903:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-87: 256 requests in 335 ms, 764 req/s
2019-01-29 12:27:18.903:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-103: 256 requests in 335 ms, 764 req/s
2019-01-29 12:27:18.903:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-59: 256 requests in 335 ms, 764 req/s
2019-01-29 12:27:18.906:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-73: 256 requests in 338 ms, 757 req/s
2019-01-29 12:27:18.911:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-47: 256 requests in 343 ms, 746 req/s
2019-01-29 12:27:18.911:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-47: FAILED: Result failed Result[HttpRequest[GET /299 HTTP/1.1]@56aba01a > HttpResponse[null 0 null]@45d2df3b] javax.net.ssl.SSLException: Received fatal alert: internal_error
2019-01-29 12:27:18.911:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-75: 256 requests in 343 ms, 746 req/s
2019-01-29 12:27:18.912:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-101: 256 requests in 344 ms, 744 req/s
2019-01-29 12:27:18.913:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-19: 256 requests in 345 ms, 742 req/s
2019-01-29 12:27:18.919:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-89: 256 requests in 351 ms, 729 req/s
2019-01-29 12:27:18.921:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-115: 256 requests in 353 ms, 725 req/s
2019-01-29 12:27:18.921:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-17: 256 requests in 354 ms, 723 req/s
2019-01-29 12:27:18.928:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-31: 256 requests in 360 ms, 711 req/s
2019-01-29 12:27:18.929:INFO:oejhc.HttpClientLoadTest:ForkJoinPool.commonPool-worker-45: 256 requests in 361 ms, 709 req/s
2019-01-29 12:27:18.929:INFO:oejhc.HttpClientLoadTest:main: 256 requests in 361 ms, 709 req/s
2019-01-29 12:27:18.938:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@765eed80{SSL,[ssl, http/1.1]}{0.0.0.0:0}

org.opentest4j.AssertionFailedError: [Result failed Result[HttpRequest[GET /299 HTTP/1.1]@56aba01a > HttpResponse[null 0 null]@45d2df3b] javax.net.ssl.SSLException: Received fatal alert: internal_error] ==> expected: <true> but was: <false>
	at org.eclipse.jetty.http.client.HttpClientLoadTest.run(HttpClientLoadTest.java:181)
	at org.eclipse.jetty.http.client.HttpClientLoadTest.lambda$testConcurrent$2(HttpClientLoadTest.java:146)
	at org.eclipse.jetty.http.client.HttpClientLoadTest.lambda$testConcurrent$3(HttpClientLoadTest.java:145)
```

Fails for tests ...

* testConcurrent{Transport}[3]
* testConcurrent{Transport}[4]
* testConcurrent{Transport}[5]

**Attached surefire-report:**

 [TEST-org.eclipse.jetty.http.client.HttpClientLoadTest.xml.gz](https://github.com/eclipse/jetty.project/files/2809167/TEST-org.eclipse.jetty.http.client.HttpClientLoadTest.xml.gz)

**Environment:**

```
$ git log -1 --oneline
1d9e7b7613 (HEAD -> jetty-10.0.x, origin/jetty-10.0.x) Merge pull request #3199 from lachlan-roberts/jetty-10.0.x-3139-npe-websocket-sci

$ mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T13:41:47-05:00)
Maven home: /home/joakim/java/apache-maven-3.6.0
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /home/joakim/java/jvm/jdk-11.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-13-generic", arch: "amd64", family: "unix"
```

**Comment by sbordet** [comment] 2019-02-04 18:21
Duplicate of #3239.

**Closed by sbordet** 2019-02-04 18:21 UTC
Labels: Test
