### ISSUE TITLE
AllowSymLinkAliasChecker not working?

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#688] opened 2016-07-05 23:49 UTC
We use the following code:
```
ResourceHandler fileResourceHandler = new ResourceHandler();
fileResourceHandler.setDirectoriesListed(false);
fileResourceHandler.setWelcomeFiles(new String[]{ "index.html" });
fileResourceHandler.setResourceBase("./resources/website");
fileResourceHandler.setEtags(true);

ContextHandler fileResourceContext = new ContextHandler();
fileResourceContext.setContextPath("/");
fileResourceContext.setAllowNullPathInfo(true);
fileResourceContext.setHandler(fileResourceHandler);

// Allow to follow symlinks
fileResourceContext.addAliasCheck(new AllowSymLinkAliasChecker());
```

Now we updated jetty9 to the from 9.2.2 to the latest release (9.3.9) and at the same time we moved to openjdk-8 (7 before).
All of a sudden all symlinks do not work anymore. If I replace the symlink with the actual content, it works.
If I replace the last line of code above with
```
fileResourceContext.addAliasCheck(new ContextHandler.ApproveAliases());
```
it works too (even though `ApproveAliases` seems too permissive for following symlinks).

So it seems like the `AllowSymLinkAliasChecker` does not work anymore.
OS is Ubuntu xenial.

**Comment by janbartel** [comment] 2016-07-06 04:08
Closed as a duplicate of #687

**Closed by janbartel** 2016-07-06 04:08 UTC
Labels: Bug
