### ISSUE TITLE
The jetty-maven-plugin:stop goal doesn't stop everything completely

### ISSUE THREAD

**Issue by karlmdavis** [eclipse/jetty.project#915] opened 2016-09-09 14:41 UTC
I've got a multi-module Maven build, with two separate modules that need Jetty to run a WAR that my application under test has a dependency on. During the build for whichever module is built second, Jetty fails to bind the shutdown monitor, and so also fails to stop in the module's `post-integration-test` phase.

Here's some sample Maven output that illustrates the problem, picking up at the `stop` in the first module:

```
[INFO] --- jetty-maven-plugin:9.3.11.v20160721:stop (jetty-stop) @ bluebutton-data-pipeline-fhir-load ---
[INFO] Waiting 120 seconds for jetty to stop
[INFO] Stopped ServerConnector@3b4fcd02{SSL,[ssl, http/1.1]}{0.0.0.0:9094}
[INFO] Destroying Spring FrameworkServlet 'spring'
2016-09-07 17:54:35.514 [ShutdownMonitor] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext [AbstractApplicationContext.java:960] Closing WebApplicationContext for namespace 'spring-servlet': startup date [Wed Sep 07 17:42:54 UTC 2016]; parent: Root WebApplicationContext
[INFO] Closing Spring root WebApplicationContext
2016-09-07 17:54:35.518 [ShutdownMonitor] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext [AbstractApplicationContext.java:960] Closing Root WebApplicationContext: startup date [Wed Sep 07 17:42:39 UTC 2016]; root of context hierarchy
2016-09-07 17:54:35.520 [ShutdownMonitor] INFO  o.s.s.c.ThreadPoolTaskScheduler [ExecutorConfigurationSupport.java:203] Shutting down ExecutorService 'taskScheduler'
2016-09-07 17:54:35.565 [ShutdownMonitor] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean [AbstractEntityManagerFactoryBean.java:462] Closing JPA EntityManagerFactory for persistence unit 'HAPI_PU'
[INFO] Stopped o.e.j.m.p.JettyWebAppContext@1693d505{/,file:///var/lib/jenkins/workspace/HHSIDEAlab/bluebutton-data-pipeline/cbbd-125-jetty-stop-race/bluebutton-data-pipeline-fhir-load/target/tmp/webapp/,UNAVAILABLE}{/var/lib/jenkins/workspace/HHSIDEAlab/bluebutton-data-pipeline/cbbd-125-jetty-stop-race/bluebutton-data-pipeline-fhir-load/target/bbonfhir-server/bbonfhir-server-app-0.1.0-44.war}
[INFO] Server reports itself as stopped

...

[INFO] --- jetty-maven-plugin:9.3.11.v20160721:deploy-war (jetty-start) @ bluebutton-data-pipeline-app ---
[INFO] Configuring Jetty for project: bluebutton-data-pipeline-app
[INFO] Configuring Jetty from xml configuration file = /var/lib/jenkins/workspace/HHSIDEAlab/bluebutton-data-pipeline/cbbd-125-jetty-stop-race/bluebutton-data-pipeline-app/target/bbonfhir-server/bbonfhir-server-app-0.1.0-44-jetty-config.xml
[INFO] Context path = /
[INFO] Tmp directory = /var/lib/jenkins/workspace/HHSIDEAlab/bluebutton-data-pipeline/cbbd-125-jetty-stop-race/bluebutton-data-pipeline-app/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
Error binding ShutdownMonitor to port 9966: java.net.BindException: Address already in use
[INFO] jetty-9.3.11.v20160721

...

[INFO] --- jetty-maven-plugin:9.3.11.v20160721:stop (jetty-stop) @ bluebutton-data-pipeline-app ---
[INFO] Jetty not running!
```

The "`Error binding ShutdownMonitor to port 9966: java.net.BindException: Address already in use`" message/error indicates to me that Jetty didn't _really_ stop that first time.

**Comment by janbartel** [comment] 2016-09-15 06:56
Looks like fix for issue #402 removed code to shut the serverSocket and the accepted socket. Affects jetty-9.3 and above. Assigning to @sbordet.

**Comment by sbordet** [comment] 2016-09-15 08:20
@janbartel can you detail what code was removed ?
I only cleaned up the class and moved things around.

I just tried on a simple project that uses `jetty:run-forked` and `jetty:stop` works just fine.
@karlmdavis can you detail _all_ the steps you are doing to reproduce this issue ?

**Comment by janbartel** [comment] 2016-09-15 21:29
@sbordet the code the shutsdown and then closes the serverSocket and the socket was removed, specifically calls to stopInput(socket) and stopOutput(socket).  Eg, see line https://github.com/eclipse/jetty.project/commit/87f011d98ba6c5671981cd1b63e7e5088f2ca34f#diff-8e2e1507940b6c8c52e8e0e080d3d894L142

If the jvm does not exit (which it might not if eg you are using the jetty maven plugin as part of a maven build), then those ports are left open.

**Comment by sbordet** [comment] 2016-09-16 09:35
@janbartel 

`stopInput()` and `stopOutput()` are replaced by a try-with-resources, so no need for them.
I did remove the close of the `serverSocket` though, and that's the problem.

**Closed** 2016-09-16 09:35 UTC
Labels: Bug
