### ISSUE TITLE
Proxy authentication to HTTPS servers does not work

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#138] opened 2016-02-16 23:24 UTC
migrated from Bugzilla [#427878](https://bugs.eclipse.org/bugs/show_bug.cgi?id=427878)
status ASSIGNED severity *normal* in component *client* for *9.1.x*
Reported in version *9.1.1* on platform *PC*
Assigned to: Simone Bordet

On 2014-02-11 05:31:06 -0500, Simone Bordet wrote:

> If a proxy requires authentication, and the destination is a HTTPS server, then the CONNECT request to the proxy lacks the Proxy-Authenticate header, which leads to failure to authenticate with the proxy and ultimately to fail to send requests to the target server.

**Comment by sbordet** [comment] 2016-03-10 08:48
Duplicate of #408.

**Closed by sbordet** 2016-03-10 08:48 UTC
Labels: Bug
