### ISSUE TITLE
StreamRecvWindow and SessionRecvWindow for HTTP/2 Client

### ISSUE THREAD

**Issue by sxam** [eclipse/jetty.project#1285] opened 2017-01-25 19:24 UTC
Hi guys,
When using HTTP/2 Client I sometimes receive Timeouts (In Jetty HTTP/1.1 Client , same 9.3.15 version we don't have that issue). It was suggested by one of the guys that we could increase the SessionRecvWindow and StreamRecvWindow  using to a maximal value in order to handle it. Do you have any insights to whether it could really be connected and what are pros and cons of following this advice?

**Comment by sbordet** [comment] 2017-01-26 13:27
Typically, increasing flow control windows would not solve the timeouts, it would just hide the problem.

Flow control only stalls if the peer does not correctly consume the content it received.
This may be due to very long processing of the content, or by a mistake in using the low-level HTTP/2 APIs (in particular, not completing the content callback).

If you can reproduce the issue, I would be interested in looking at the code.
Otherwise, you have the DEBUG logs ?

**Comment by sxam** [comment] 2017-01-26 13:38
I use high level HTTP/2 API - org.eclipse.jetty.http2.client.HTTP2Client wrapped with org.eclipse.jetty.client.HttpClientmHttp2JettyClientWrapper =
    new HttpClient(new HttpClientTransportOverHTTP2(mHttp2JettyClient), sslContextFactory);
Don't have a debug logs yet.. If I will have it, will attach to issue https://github.com/eclipse/jetty.project/issues/1285

 Maxim 

    On Thursday, January 26, 2017 3:27 PM, Simone Bordet <notifications@github.com> wrote:
 

 Typically, increasing flow control windows would not solve the timeouts, it would just hide the problem.Flow control only stalls if the peer does not correctly consume the content it received.
This may be due to very long processing of the content, or by a mistake in using the low-level HTTP/2 APIs (in particular, not completing the content callback).If you can reproduce the issue, I would be interested in looking at the code.
Otherwise, you have the DEBUG logs ?—

**Comment by sbordet** [comment] 2017-02-09 15:45
@sxam any progress on this ?

**Comment by sxam** [comment] 2017-02-09 16:06
No, not currently. tried to transfer to HTTP/2 again, after increasing session and stream window but still the exceptions (timeouts, etc..) increased significantly, so reverted. Don't know what the problem is. Maxim 

    On Thursday, February 9, 2017 5:45 PM, Simone Bordet <notifications@github.com> wrote:
 

 @sxam any progress on this ?—

**Comment by sbordet** [comment] 2017-02-09 16:09
If you can reproduce and you can turn on DEBUG logging, we are interested in looking at them.

**Comment by sxam** [comment] 2017-02-09 16:13
If that happens will reply, sure. Maxim 

    On Thursday, February 9, 2017 6:09 PM, Simone Bordet <notifications@github.com> wrote:
 

 If you can reproduce and you can turn on DEBUG logging, we are interested in looking at them.—

**Comment by sbordet** [comment] 2017-04-26 08:46
Closing this, as #1504 has changed the defaults to better values.
@sxam, if you still have timeout problems, #1504 won't solve your issue, so if you have DEBUG logs, please reopen this issue.

**Closed by sbordet** 2017-04-26 08:46 UTC
