### ISSUE TITLE
Timeouts with 9.3.12

### ISSUE THREAD

**Issue by sergionalin** [eclipse/jetty.project#1084] opened 2016-11-07 21:23 UTC
I'm getting frequent timeouts from nginx (acting as a proxy in front of Jetty) after updating embedded Jetty from 9.3.6 to 9.3.12.
The timeouts affect operations as simple as GETting a static image served by a basic ResourceHandler.
Bypassing nginx and connecting directly to our Jetty application does not improve things. The connection sometimes just hangs there.

Other bits that may be of interest are that the Jetty process seems to have a large number of opened connections (all related to Jetty):

    lsof -i -a -p <jetty_process_pid> | wc -l
    941

but the server, which is started like this:

        server = new Server(new QueuedThreadPool(
                App.cfg.jettyPoolMaxThreads, // 200
                App.cfg.jettyPoolMinThreads, // 10
                App.cfg.jettyPoolIdleTimeoutSec * 1000) // 10 mins
        );

when polled like:

     server.getThreadPool().getThreads()
     ((QueuedThreadPool)server.getThreadPool()).getQueueSize()

keeps returning low numbers, like around 15 threads in the pool and an empty queue, even while there are many connections opened and waiting for data.

I realize this is not much information, but this is happening in production where unfortunately we don't have Jetty logs enabled and can't afford to keep running like this to get more details, so we're rolling back for the time being.

I can't be sure but I tend to suspect this has something to do with EWYK and, possibly, the update/fix introduced with 9.3.9.

I'll update this case providing more data if I can.

In the meantime, is there a way to programmatically disable EWYK and use a different scheduling strategy?

Thx!

**Comment by sbordet** [comment] 2016-11-07 23:10
Can you enable JMX and take a [server dump](http://www.eclipse.org/jetty/documentation/9.3.x/jetty-dump-tool.html), and attach it here ?

**Comment by sergionalin** [comment] 2016-11-08 02:29
Thanks for the quick response. Thankfully I had JMX enabled already. Dump is attached.

I can definitely see a gazillion WebSocketServerConnections in there. 
Far too many than the number of actually connected websockets (~130).

So the problem seems to be over there, which probably explains why few threads are in use and why the queue is empty... 

Question now is why all those connections just hung there without being cleaned up.

Let me know in case you need more data.

[jetty_dump.zip](https://github.com/eclipse/jetty.project/files/577166/jetty_dump.zip)

**Comment by sbordet** [comment] 2016-11-08 08:42
@joakime can you have a look ? Looks like a lot of those connections are in state `CLOSING` with `closeSource=LOCAL`, so perhaps it's the client not answering to the close exchange ?

**Comment by joakime** [comment] 2016-11-08 18:34
Looking at the jetty_dump ...

**Comment by joakime** [comment] 2016-11-08 19:18
There are 814 WebSocketServerConnections, and 814 SelectionKeys (1 for each WebSocketServerConnection).

Of the 814 connections:

 * 685 are in CLOSING state, with closeSource=LOCAL and unexpired idle timeouts (configured for 60000 ms)
 * 129 are in OPEN state

There's nothing abnormal about the state in the jetty_dump with regards to the WebSocket connections, the CLOSING state with closeSource=LOCAL means that your Server WebSocket Endpoint issued a close, but the remote hasn't responded yet.  So the WebSocket endpoint is waiting for either the CLOSE handshake from the remote, or the idle timeout, which ever comes first.

**Comment by sergionalin** [comment] 2016-11-08 19:56
Understood, but the problem is that those 685 CLOSING websockets seems to be stuck there for no reason.
I restarted (kill all processes + start) the nginx server (which acts as a proxy), therefore "killing" the remote counterpart, just in case it was the one keeping them in that state, but that did not solve the problem.

Moreover, those stuck websockets somehow caused problems in dealing with normal non-websocket http requests, much like the connection being accepted with no thread being assigned to it.

So, something seems to be amiss.

As an update: I rolled back to 9.3.6 and, with anything else being equal, the problem disappeared with the number of websocket connections remaining stable and in line with the number of active connections throughout the last 12+ hours.

I'm not sure, but could it be that some code meant to clean up CLOSING connections went bonkers and they just kept piling up?

In any case I'll keep 9.3.6 running for a few more days and see how it goes.
If needed I could get a dump out of 9.3.6.

Thanks!

**Comment by sbordet** [comment] 2016-11-08 20:04
@joakime, could it be that the client does not send the close reply, but just the FIN, so we read -1 but we don't close until the idle timeout ?

**Comment by joakime** [comment] 2016-11-08 22:14
@sergionalin we see an anomaly with regards to the "FI" (Fill Interested) behavior in your dump, we are tracking down what that could mean.  Stay tuned.

**Comment by sergionalin** [comment] 2016-11-08 23:28
Thanks for looking into this.
Besides the Jetty dump I collected a thread dump and a full heap dump of the Java process.
There's lots of sensitive data in the latter so I won't be able to share it, definitely not here, but I can extract data from it you tell me what I should be looking for.

Again, thanks.

**Comment by laeubi** [comment] 2016-11-10 10:56
Do you use AsyncContext in your application to write data from another thread?

**Comment by sergionalin** [comment] 2016-11-10 11:24
Nope.
What I have are "normal" handlers that are synchronous (used, say, for serving static stuff and handling RESTful APIs), then I have websockets.

Data can be written to websockets by other threads.
i.e.: any time a message is received on the websocket a worker thread deals with the request and then calls this code:
org.eclipse.jetty.websocket.api.Session session;  // set on onConnect
session.getRemote().sendString("blabla", null);

A cleanup/housekeeping thread than may do a session.close(), for example when an end-user logs out from its cookie-based web session and I need to close/terminate all active websockets related to that web session.

Hope this helps.

BTW: 9.3.6 still going strong with no stuck connections whatsoever.

Thanks

**Comment by laeubi** [comment] 2016-11-10 12:16
Okay, because we have seen lots of close_waits that seem to be related to https://github.com/eclipse/jetty.project/issues/1037 what is fixed in the latest jetty release can you try to test with this version?

**Comment by laeubi** [comment] 2016-11-10 12:19
Oh and I also encounter a strange problem https://github.com/eclipse/jetty.project/issues/517 where it seems a connection hangs but I don't see client errors what kind of timeouts do you see, does the client just hangs for a while or does he show connection errors?

**Comment by sergionalin** [comment] 2016-11-10 12:50
About #1037: I'll try updating to the latest version and see what happens on our QA env.

About #517: Unfortunately I don't have quality data on that. What we experienced were indirect 504 timeout errors returned by Nginx after 30 secs, and not just on websockets but on plain http connections as well. Given that nginx connection timeout is set to 10 secs and the read timeout is set to 30 secs I guess that nginx successfully connected to the Jetty process and then got nothing back.
Because the issue was severe I had to roll back to 9.3.6 before conducting more in-depth analysis. 
I have, however, both a thread dump and a heap dump, so maybe I can scavenge some useful info out of those. Just let me know what should I be looking for.

Thanks!

**Comment by laeubi** [comment] 2016-11-10 12:53
You can try to see if there are some Task stacking-up in a ScheduledExecutor with one Thread named Scheduler-(some numbers).

**Comment by joakime** [comment] 2016-11-10 14:14
Still working on this. Sorry for the delay.

**Comment by sergionalin** [comment] 2016-11-11 13:08
@laeubi 

there seems to be lots of Tasks stacking up. In the heapdump I can find:

- 2 instances of ScheduledExecutorScheduler where the name is Scheduler-(some numbers).
One instance has thread=null and threadGroup=null, the other one does have non-null thread and threadGroup.
- 2333 instances of ScheduledExecutorScheduler$ScheduledFutureTask

Attached is a snapshot showing that ScheduledExecutorScheduler$ScheduledFutureTask(s) reference a ScheduledThreadPoolExecutor with a workQueue containing 815 items

![capture](https://cloud.githubusercontent.com/assets/1381583/20215977/2da7159a-a818-11e6-9761-25b1f075c5ec.png)

Let me know if you need me to dig deeper and maybe look for something more specific.

**Comment by sergionalin** [comment] 2016-11-11 13:12
Here is the Scheduler-xxx thread dump:

```
"Scheduler-1828322162" #46 prio=5 os_prio=0 tid=0x00007fba60003800 nid=0x3109 runnable [0x00007fba6e953000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005d0c465c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None
```

**Comment by laeubi** [comment] 2016-11-11 13:26
Maybe you can find out whats the work/sceduled time for the tasks is?

**Comment by sergionalin** [comment] 2016-11-11 13:35
Not sure where to get that.

ScheduledExecutorScheduler.ScheduledFutureTask contain a scheduledFuture which is a ScheduledThreadPoolExecutor.ScheduledFutureTask 

ScheduledFutureTasks have a "time" member which, it seems, is "nanoseconds since the JVM started", so likely not of much use.

If you can point me to a variable somewhere I'll go look for it

Thx!

**Comment by laeubi** [comment] 2016-11-12 05:46
According to the javadoc time is "The time the task is enabled to execute in nanoTime units" or it has a period "Period in nanoseconds for repeating tasks". It also should have a "outerTask" meber that is the actual task to be executed.

**Comment by sergionalin** [comment] 2016-11-14 10:06
Uhm, outerTask is a reference to itself. See image1 below.
I also highlighted the differences between a Task with some retained size and a Task with no retained size (the vast majority of those 2333 instances).

Apparently the "zombie" tasks have heapIndex = -1, callable = null and state = 4
The non-zombie ones have a heapIndex, state = 0 and a callable which is an Executors.RunnableAdapter containing a task that includes an org.eclipse.jetty.io.SelectChannelEndPoint instance.
See image 2 below.

I can't find the scheduled time anywhere. Maybe I can find it in some of the Jetty structures?

Image 1

![futuretasks](https://cloud.githubusercontent.com/assets/1381583/20260241/02c41628-aa59-11e6-8778-ab1d3aa65bef.jpg)

Image 2

![capture](https://cloud.githubusercontent.com/assets/1381583/20260542/6f86f270-aa5a-11e6-9edf-5d55b98c099e.png)

**Comment by laeubi** [comment] 2016-11-15 17:57
The long property "time" shoudl be the sceduled time in nanoseconds. Is it possible that the "zombies" are just not (yet) garbage collected? The ones with org.eclipse.jetty.io.SelectChannelEndPoint should be the interesting ones since these relate to open connections afaik.

**Comment by sergionalin** [comment] 2016-11-15 18:12
The ones with the SelectChannelEndPoint seems to be ok. Their number matches the number of active websockets.
The problem seems to be the zombie ones. Apparently they pile up and don't get garbage collected and in the process cause additional connections to be delayed. At least this is my guess.

That time field is nanos *since JVM started*, which would be helpful provided I can figure out the time (say, unix epoch) when that instance of the JVM started. I'll see if I can find it somewhere.

In any case the same process with 9.3.6 is still going strong. No zombie connections and everything is running just fine.

I'll test with the latest Jetty version at the earliest opportunity and report back.

**Comment by joakime** [comment] 2017-06-19 19:03
Not reproducible in various tests.
Once a reproducible testcase exists, feel free to reopen (or ask for a reopen).

**Closed by joakime** 2017-06-19 19:03 UTC
Labels: Unable To Replicate
