### ISSUE TITLE
Get rid of test dependencies on derby

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5713] opened 2020-11-23 16:11 UTC
There are 2 modules with test dependencies on derby:

* jetty-plus
* test-loginservice

jetty-plus is not actually dependent on derby for testing, and the dependency can be deleted.
We should also try to remove the dependency for the test-loginservice and replace it with mocks where necessary.

**Comment by joakime** [comment] 2020-11-23 16:16
Duplicate of #5712

**Closed as completed** 2020-11-30 13:23 UTC
