### ISSUE TITLE
Two process of Jetty after adding log4j module

### ISSUE THREAD

**Issue by senthilrajanvs** [eclipse/jetty.project#3930] opened 2019-08-01 19:00 UTC
Hi, When I added the logging-log4j2 & console-capture, I'm seeing two process is getting started and all my -D parameters are not getting passed in both process. 

Jetty version: 9.4.18

My goal is to enable log4j2 logger and forward the console logs to separate file and not to use org.eclipse.jetty.util.RolloverFileOutputStream logger 

Please suggest.

**Comment by joakime** [comment] 2019-08-01 19:07
The 2 processes are normal.

The main process that processes the configuration.
The forked process that is the actual server.

The use of logging-log4j causes a required `--exec` option to trigger so that the configuration can be forced to use this new logger.
This `--exec` option forces a forked Jetty.

If you used `-Dkey=value` names on the java command line (before the main-class), then those will not be forwarded to the forked JVM.
But if you used the `-Dkey=value` after the main-class, or in the `${jetty.base}/start.ini`, or in a `${jetty.base}/start.d/*.ini` file then those system properties will forward to the forked JVM.

**Comment by senthilrajanvs** [comment] 2019-08-02 04:57
Thanks for the update. Is there any way to stop two process ?

**Comment by joakime** [comment] 2019-08-13 01:32
Closing as this is now a duplicate of #1822

**Closed by joakime** 2019-08-13 01:32 UTC
