### ISSUE TITLE
servlet3.0 feature, META-INF/resources could not be requested

### ISSUE THREAD

**Issue by gdyxml2000** [eclipse/jetty.project#1646] opened 2017-06-24 09:23 UTC
servlet 3.0 web-fragment.xml can be Analysis, but META-INF/resources could not be requested

**Comment by janbartel** [comment] 2017-06-24 13:27
@gdyxml2000 I don't understand, can you please explain the situation more? Please include jetty version, operating system, jvm version and any relevant customizations.

**Comment by janbartel** [comment] 2017-07-13 12:06
@gdyxml2000 please provide more details, otherwise there is not enough information here to work with.

**Comment by janbartel** [comment] 2017-11-23 09:46
Closing due to lack of information.If you can provide full details on how you are running jetty, what jetty version, what jvm you're using, debug log output and and a reproduction test case then please reopen.

**Closed by janbartel** 2017-11-23 09:46 UTC
Labels: More Info Required
