### ISSUE TITLE
Support for native OpenSSL for secure channel

### ISSUE THREAD

**Issue by vishwajeetdusane** [eclipse/jetty.project#1693] opened 2017-07-26 08:49 UTC
Hi,

It would be good addition and performant to support java binding to OpenSSL. 
[Wildfly-openssl](https://github.com/wildfly/wildfly-openssl) is good candidate.

Proposal is to provide preference in SSLSocketFactory to load openssl library using wildfly JNI interface library. If fails then fallback to JSE.

Any thoughts?

**Comment by sbordet** [comment] 2017-07-26 09:43
See also #215 and #812.

**Comment by sbordet** [comment] 2017-09-26 08:49
Closing as duplicate of #215.

**Closed by sbordet** 2017-09-26 08:49 UTC
