### ISSUE TITLE
HttpClient throwing inappropriate exception on cert hostname mismatch error

### ISSUE THREAD

**Issue by johngmyers** [eclipse/jetty.project#444] opened 2016-03-18 21:05 UTC
In a project using Jetty client embedded, we have a unit test which invokes a certificate hostname mismatch and verifies that the exception thrown out of Jetty client is either a `SSLHandshakeException` or an `EOFException`.

Upon upgrade from Jetty 9.3.7 to 9.3.8, this has started failing, instead throwing:

```
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:499)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:115)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:122)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.close(SslConnection.java:928)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:673)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:113)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:114)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:186)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

This exception thrown from cleanup code in the catch block obscures the real reason for failure and might be indicative of incorrect cleanup.

**Comment by sbordet** [comment] 2016-04-01 11:01
Closing as duplicate of #464.

**Closed by sbordet** 2016-04-01 11:01 UTC
