### ISSUE TITLE
stackoverflow in WebAppClassLoaderUrlStreamTest

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3700] opened 2019-05-28 08:27 UTC
When run from an IDE this test in jetty-10.0.x  fails to initialize with a stackoverflow error:
```
        ...
	at org.eclipse.jetty.webapp.WebAppClassLoaderUrlStreamTest$URLHandlers.getBuiltInHandler(WebAppClassLoaderUrlStreamTest.java:63)
	at org.eclipse.jetty.webapp.WebAppClassLoaderUrlStreamTest$URLHandlers.createURLStreamHandler(WebAppClassLoaderUrlStreamTest.java:92)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1415)
	at java.base/java.net.URL.<init>(URL.java:449)
	at java.base/java.net.URL.fromURI(URL.java:699)
	at java.base/java.net.URI.toURL(URI.java:1116)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:456)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:227)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:274)
	at java.base/jdk.internal.loader.BootLoader.findResource(BootLoader.java:154)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1397)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1395)
	at org.eclipse.jetty.util.TypeUtil.getLocationOfClass(TypeUtil.java:723)
	at org.eclipse.jetty.webapp.ClassMatcher.lambda$match$3(ClassMatcher.java:713)
	at org.eclipse.jetty.webapp.ClassMatcher.combine(ClassMatcher.java:751)
	at org.eclipse.jetty.webapp.ClassMatcher.match(ClassMatcher.java:713)
	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:785)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:558)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.eclipse.jetty.webapp.WebAppClassLoaderUrlStreamTest$URLHandlers.getBuiltInHandler(WebAppClassLoaderUrlStreamTest.java:63)
	at org.eclipse.jetty.webapp.WebAppClassLoaderUrlStreamTest$URLHandlers.createURLStreamHandler(WebAppClassLoaderUrlStreamTest.java:92)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1415)
	at java.base/java.net.URL.<init>(URL.java:449)
	at java.base/java.net.URL.fromURI(URL.java:699)
	at java.base/java.net.URI.toURL(URI.java:1116)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:456)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:227)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:274)
	at java.base/jdk.internal.loader.BootLoader.findResource(BootLoader.java:154)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1397)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1395)
	at org.eclipse.jetty.util.TypeUtil.getLocationOfClass(TypeUtil.java:723)
	at org.eclipse.jetty.webapp.ClassMatcher.lambda$match$3(ClassMatcher.java:713)
	at org.eclipse.jetty.webapp.ClassMatcher.combine(ClassMatcher.java:751)
	at org.eclipse.jetty.webapp.ClassMatcher.match(ClassMatcher.java:713)
	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:785)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:558)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.eclipse.jetty.webapp.WebAppClassLoaderUrlStreamTest$URLHandlers.getBuiltInHandler(WebAppClassLoaderUrlStreamTest.java:63)
	at org.eclipse.jetty.webapp.WebAppClassLoaderUrlStreamTest$URLHandlers.createURLStreamHandler(WebAppClassLoaderUrlStreamTest.java:92)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1415)
	at java.base/java.net.URL.<init>(URL.java:449)
	at java.base/java.net.URL.fromURI(URL.java:699)
	at java.base/java.net.URI.toURL(URI.java:1116)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:456)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:227)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:274)
```

**Comment by joakime** [comment] 2019-05-28 13:22
Note, this test was added because of Issue #1448

The crux of the problem in Jetty 9.4.x is that you cannot use the `WebAppClassLoader` to obtain information during the `.loadClass()` call.
In Jetty 9.4.x that used to be another Jetty `Resource` creation/call.

But now in Jetty 10.0.x, the call to `ClassMatcher.combine()` is using `TypeUtil.getLocationOfClass()` which uses the same `WebAppClassLoader`.
This needs recursion to be broken for Jetty 10.0.x to function properly on OSGi.

**Comment by joakime** [comment] 2019-06-12 19:11
Need to restore the `felix-webapp` for testing this new `jetty-10.0.x` behavior.

**Comment by joakime** [comment] 2019-06-12 19:39
Opened PR #3777 to add felix webapp testing to `/test-distribution/` in `jetty-9.4.x`
Once this is merged to `jetty-10.0.x` then the fixes introduced into `jetty-9.4.x` for issue #1448 can be re-implemented in `jetty-10.0.x`

**Comment by janbartel** [comment] 2019-06-13 06:47
Are you saying that this is an osgi issue or an ide issue? It's not a generic osgi issue because the osgi tests all work in jetty-9 and jetty-10, which deploys to the eclipse container.  Looking at your test, its not deploying a webapp into the felix container. Rather, it seems to run a webapp which starts felix internally instead.  So I think the correct characterisation of this problem is that it is a test for any code which has its own  URLStreamHandlerFactory, not really anything to do with OSGi per se?

**Comment by joakime** [comment] 2019-06-13 12:16
See issue #1448 for historical details.

The problem is fundamentally that felix manages it's bundles via java.net.URL references like `bundle://com.acme.app.Foo`
It does this by registering a URLStreamHandler for the `bundle` scheme.

This caused a problem in Jetty's 9.x's `WebAppClassLoader` and triggered a Stackoverflow.
The fix for Jetty 9.x was to not use the `WebAppClassLoader` recursively.
Meaning that while a `WebAppClassLoader.loadClass()` was being processed care was taken to not call/use `WebAppClassLoader.loadClass()` again.

Jetty 10.0.x has the same style of Stackoverflow, where `WebAppClassLoader.loadClass()` has a call to `WebAppClassLoader.loadClass()` due to the various changes it has undergone for the new Configuration behaviors.
This means that Jetty 10.0.x is now broken for Felix and any other webapp that uses URLStreamHandler.

An attempt was made to make a standard junit testcase for this, but the changes to the URLStreamHandler are permanent for the JVM, and would impact all other junit tests.
That's what WebAppClassLoaderUrlStreamTest is.

An alternate way to test this was needed.
The easiest way to create a test for this is actually to use the `/test-distribution/` and deploy a webapp that uses this concept.
The easiest one to setup, and the most common in the wild, is one that uses Apache Felix.
That's what PR #3777 attempts to bring in.
Interestingly, it shows that even our fix on Jetty 9.4.x is broken for Java 9+.
Once this new testcase is in place for Jetty 9.4.x, then the merge to Jetty 10.0.x will show what needs to be fixed in the Jetty 10.0.x Configuration implementation.

**Comment by joakime** [comment] 2019-06-18 15:18
This stackoverflow is present in Jetty 9.4.x as well.
PR #3777 shows this.

```
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.TypeUtil.getLocationOfClass(TypeUtil.java:565)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.ClasspathPattern.lambda$match$0(ClasspathPattern.java:690)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.ClasspathPattern.combine(ClasspathPattern.java:728)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:690)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:829)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:557)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/java.net.URL.getURLStreamHandler(URL.java:1415)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/java.net.URL.<init>(URL.java:449)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/java.net.URL.fromURI(URL.java:699)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/java.net.URI.toURL(URI.java:1116)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:456)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:227)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:274)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/jdk.internal.loader.BootLoader.findResource(BootLoader.java:154)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1397)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1395)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.TypeUtil.getLocationOfClass(TypeUtil.java:565)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.ClasspathPattern.lambda$match$0(ClasspathPattern.java:690)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.ClasspathPattern.combine(ClasspathPattern.java:728)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:690)
2019-06-18 10:16:22.959:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:829)
```

**Comment by joakime** [comment] 2019-06-18 15:20
The heart of the problem is ...

```
at java.base/java.net.URL.<init>(URL.java:449)
at java.base/java.net.URL.fromURI(URL.java:699)
at java.base/java.net.URI.toURL(URI.java:1116)   <-- this LINE
at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:456)
```

is the `URI.toURL()` call deep in the JDK's `BuiltinClassLoader`, which triggers the `new URL()` that causes the loop.

**Comment by joakime** [comment] 2019-06-18 15:22
We need to have a path, on `TypeUtil.getLocationOfClass()` where we never use `ClassLoader.getResource()` on JDK's newer then Java 8. (aka Java 9+)

**Comment by joakime** [comment] 2019-06-18 15:39
The specific class that causes the stackoverflow is `isServerClass(class java.lang.ThreadDeath)`

**Comment by joakime** [comment] 2019-06-18 16:04
Fixing bad assumptions in TypeUtil.getLocationOfClass() and IncludeExcludeSet in commit 5eb3e73400b25d8ba654bf53e0085532206877e2
This fixes the Stackoverflow in Java 9+.

**Closed** 2019-07-03 09:48 UTC
