### ISSUE TITLE
jetty-jspc-maven-plugin: Support reproducible builds

### ISSUE THREAD

**Issue by stokito** [eclipse/jetty.project#12295] opened 2024-09-22 12:45 UTC
**Jetty version(s)**
11.0.20

**Enhancement Description**
The [reproducible builds](https://reproducible-builds.org/) are needed to get an independently-verifiable path from source to binary code. This mainly means to remove build timestamps and compiler specific info.

The Maven does support them and provides a guide [Configuring for Reproducible Builds](https://maven.apache.org/guides/mini/guide-reproducible-builds.html).
So here is first question: does the jetty artifacts build is reproducible?
I have the jetty-jspc-maven-plugin v11.0.20 used to compile JSP pages and when I run the `mvn artifact:check-buildplan` it shows the error:

    [ERROR] plugin without solution org.eclipse.jetty:jetty-jspc-maven-plugin:11.0.20
 
I'm not sure if there are any problems, maybe the plugin is perfectly fine and makes reproducible builds. Maybe this can be reported to Maven itself.
But anyway it would be great if you can officially confirm that the plugin do support such a way of building.
So do you know if any problems may arise with the plugin?

**Comment by stokito** [comment] 2024-09-22 16:41
I also found a good instruction https://vishia.org/Java/html5/source+build/reproducibleJar.html

In basic usage it looks like it should be enough to add to the pom.xml a static build timestamp:
```xml
    <properties>
        <project.build.outputTimestamp>2023-01-01T00:00:00Z</project.build.outputTimestamp>
    </properties>
```

But also we need to exclude a few generated fields from the jar manifest:
```xml
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.4.2</version>
                    <configuration>
                        <archive>
                            <manifest>
                                <!-- Don't add Created-By and Build-Jdk-Spec fields to manifest for reproducible builds -->
                                <addDefaultEntries>false</addDefaultEntries>
                            </manifest>
                         </archive>
                    </configuration>
                </plugin>
```

**Comment by olamy** [comment] 2024-09-23 09:30
I will check jspc plugin but I guess some generated files by Jasper may contains some timestamp. 
But this has nothing to do with jar plugin and build timestamp.

**Comment by olamy** [comment] 2024-09-23 09:33
FTTR this has been added because of this finding: 

https://github.com/jvm-repo-rebuild/reproducible-central/blob/96a161d34f6511830d0b2cffc9cf576d5247db9e/content/org/apache/nifi/nifi/nifi-1.16.0.diffoscope#L167

As you can see Jasper is adding some timestamps in generated Java files and even names in web.xml are different :( 
I need to check Jasper/Tomcat sources for this.

**Comment by stokito** [comment] 2024-09-23 10:17
The JSPs are compiled not deterministically. Sometimes they use an early return but sometimes not. I guess this may happen because a compiler internally has some hashmap with random order. 
I tested on the Openfire and the issue is quite reproducible there in the xmppserver-4.10.0-SNAPSHOT.jar:/org/jivesoftware/openfire/admin/decorators/main_jsp.class

**Comment by hboutemy** [comment] 2024-09-23 16:01
@stokito don't hesitate to activate Reproducible Builds even if one plugin is not ok: RB is a journey, it's ok not to be perfect on first iteration

**Comment by hboutemy** [comment] 2024-09-24 07:34
@stokito your Openfire project is interesting: https://github.com/igniterealtime/Openfire
Do you publish your releases binaries only to GitHub releases or do you also publish to Maven Central?

Having third party rebuild independently and comparing to reference is a key workflow: IIUC current latest release 4.9.0 does not try to have Reproducible Builds, it would be nice to have next release activating the Reproducible Builds flag, so we can share concrete rebuilds and their difference to the reference released binaries

**Comment by olamy** [comment] 2024-09-25 09:01
@stokito  right after some digging. I think it's a non issue as you are using jetty 11.x (why not upgrading to 12? ;) ).

This has been fixed in Apache Tomcat code with this change https://github.com/apache/tomcat/commit/374690d5793248f26d5894a33bb5ed562e22da91#diff-57d2f0a72170743f6c3687a48997b2aa37d8d209efe200f00a0b9dc51fc7e572 


I agree with @hboutemy we need to remove the warning coming from the Apache Maven Artifact plugin. 
PR to remove the warning from artifact plugin is https://github.com/apache/maven-artifact-plugin/pull/57

**Comment by olamy** [comment] 2024-09-25 09:02
@stokito I would consider this as not an issue.

**Comment by joakime** [comment] 2024-09-25 14:21
Also note, Jetty 11 is at End of Community Support.

* #10485

**Comment by olamy** [comment] 2024-09-30 06:22
Closing this as PR to the maven plugin has been merged

**Closed as completed by olamy** 2024-09-30 06:22 UTC
Labels: Not a bug
