### ISSUE TITLE
JDK8 Test failure: org.eclipse.jetty.osgi.test.TestJettyOSGiBootContextAsService

### ISSUE THREAD

**Issue by phoe** [eclipse/jetty.project#2271] opened 2018-03-01 13:30 UTC
This is a very strange failure - there are no errors logged. Attaching surefire-reports because of this. 
[surefire-reports.zip](https://github.com/eclipse/jetty.project/files/1771285/surefire-reports.zip)

Failure happened while building `jetty-9.4.x` branch on Linux barebone.

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ uname -a
Linux phoebox 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Jetty :: OSGi :: Test 9.4.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) @ test-jetty-osgi ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-junit-dep.jar) @ test-jetty-osgi ---
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:parse-version (set-osgi-version) @ test-jetty-osgi ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.0:prepare-agent (jacoco-initialize) @ test-jetty-osgi ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] argLine set to empty
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ test-jetty-osgi ---
[INFO] 
[INFO] --- depends-maven-plugin:1.4.0:generate-depends-file (generate-depends-file) @ test-jetty-osgi ---
[INFO] Created: /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/classes/META-INF/maven/dependencies.properties
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ test-jetty-osgi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/src/main/java
[INFO] Copying 1 resource
[INFO] 
[INFO] --- jetty-version-maven-plugin:2.5:attach-version-text (attach-version) @ test-jetty-osgi ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:compile (default-compile) @ test-jetty-osgi ---
[INFO] No sources to compile
[INFO] 
[INFO] >>> maven-pmd-plugin:3.8:check (named-logging-enforcement) > :pmd @ test-jetty-osgi >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ test-jetty-osgi ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.8:check (named-logging-enforcement) < :pmd @ test-jetty-osgi <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:check (named-logging-enforcement) @ test-jetty-osgi ---
[INFO] 
[INFO] 
[INFO] >>> maven-source-plugin:3.0.1:jar (attach-sources) > generate-sources @ test-jetty-osgi >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) @ test-jetty-osgi ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-junit-dep.jar) @ test-jetty-osgi ---
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:parse-version (set-osgi-version) @ test-jetty-osgi ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.0:prepare-agent (jacoco-initialize) @ test-jetty-osgi ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] 
[INFO] <<< maven-source-plugin:3.0.1:jar (attach-sources) < generate-sources @ test-jetty-osgi <<<
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar (attach-sources) @ test-jetty-osgi ---
[INFO] Building jar: /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/test-jetty-osgi-9.4.9-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-bundle-plugin:3.3.0:manifest (default) @ test-jetty-osgi ---
[WARNING] Manifest org.eclipse.jetty.osgi:test-jetty-osgi:jar:9.4.9-SNAPSHOT : Unused Export-Package instructions: [org.eclipse.jetty.osgi.boot.test.osgi.*] 
[WARNING] Manifest org.eclipse.jetty.osgi:test-jetty-osgi:jar:9.4.9-SNAPSHOT : Unused Import-Package instructions: [javax.servlet*, javax.transaction*, org.eclipse.jetty*] 
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ test-jetty-osgi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:testCompile (default-testCompile) @ test-jetty-osgi ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/test-classes
[INFO] /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootContextAsService.java: /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootContextAsService.java uses unchecked or unsafe operations.
[INFO] /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootContextAsService.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ test-jetty-osgi ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.jetty.osgi.test.TestJettyOSGiBootContextAsService

[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Jetty :: Project ................................... SUCCESS [  5.976 s]
[INFO] Jetty :: Utilities ................................. SUCCESS [01:46 min]
[INFO] Jetty :: IO Utility ................................ SUCCESS [01:18 min]
[INFO] Jetty :: Http Utility .............................. SUCCESS [  6.189 s]
[INFO] Jetty :: XML utilities ............................. SUCCESS [  7.659 s]
[INFO] Jetty :: JMX Management ............................ SUCCESS [  4.058 s]
[INFO] Jetty :: Server Core ............................... SUCCESS [05:05 min]
[INFO] Jetty :: Security .................................. SUCCESS [ 14.781 s]
[INFO] Jetty :: Servlet Handling .......................... SUCCESS [ 37.760 s]
[INFO] Jetty :: Webapp Application Support ................ SUCCESS [ 12.232 s]
[INFO] Jetty :: JNDI Naming ............................... SUCCESS [  7.183 s]
[INFO] Jetty :: Plus ...................................... SUCCESS [  2.493 s]
[INFO] Jetty :: Servlet Annotations ....................... SUCCESS [  3.126 s]
[INFO] Jetty :: Ant Plugin ................................ SUCCESS [  2.853 s]
[INFO] Jetty :: Utilities :: Ajax(JSON) ................... SUCCESS [  2.526 s]
[INFO] Jetty :: HTTP2 ..................................... SUCCESS [  0.041 s]
[INFO] Jetty :: HTTP2 :: HPACK ............................ SUCCESS [  2.186 s]
[INFO] Jetty :: HTTP2 :: Common ........................... SUCCESS [  2.719 s]
[INFO] Jetty :: ALPN :: Parent ............................ SUCCESS [  0.029 s]
[INFO] Jetty :: ALPN :: Client ............................ SUCCESS [  0.148 s]
[INFO] Jetty :: Continuation .............................. SUCCESS [  0.193 s]
[INFO] Jetty :: Utility Servlets and Filters .............. SUCCESS [01:22 min]
[INFO] Jetty :: Asynchronous HTTP Client .................. SUCCESS [03:21 min]
[INFO] Jetty :: Proxy ..................................... SUCCESS [01:54 min]
[INFO] Jetty :: ALPN :: Server ............................ SUCCESS [  0.265 s]
[INFO] Jetty :: HTTP2 :: Server ........................... SUCCESS [ 20.700 s]
[INFO] Jetty :: HTTP2 :: Client ........................... SUCCESS [02:15 min]
[INFO] Jetty :: HTTP2 :: HTTP Client Transport ............ SUCCESS [ 17.776 s]
[INFO] Jetty :: ALPN :: OpenJDK8 Server Implementation .... SUCCESS [  0.312 s]
[INFO] Jetty :: HTTP2 :: ALPN Tests ....................... SUCCESS [  1.656 s]
[INFO] Jetty :: FastCGI :: Parent ......................... SUCCESS [  0.060 s]
[INFO] Jetty :: FastCGI :: Client ......................... SUCCESS [  2.437 s]
[INFO] Jetty :: FastCGI :: Server ......................... SUCCESS [ 18.994 s]
[INFO] Jetty :: Websocket :: Parent ....................... SUCCESS [  0.017 s]
[INFO] Jetty :: Websocket :: API .......................... SUCCESS [  1.960 s]
[INFO] Jetty :: Websocket :: Common ....................... SUCCESS [  5.409 s]
[INFO] Jetty :: Websocket :: Client ....................... SUCCESS [ 43.013 s]
[INFO] Jetty :: Websocket :: Servlet Interface ............ SUCCESS [  0.262 s]
[INFO] Jetty :: Websocket :: Server ....................... SUCCESS [ 42.443 s]
[INFO] Jetty :: Websocket :: javax.websocket :: Client Implementation SUCCESS [  5.131 s]
[INFO] Jetty :: Websocket :: javax.websocket.server :: Server Implementation SUCCESS [ 39.865 s]
[INFO] Jetty :: Apache JSP Implementation ................. SUCCESS [  1.471 s]
[INFO] Apache :: JSTL module .............................. SUCCESS [  3.011 s]
[INFO] Jetty Tests :: Parent .............................. SUCCESS [  0.021 s]
[INFO] Jetty Tests :: WebApps :: Parent ................... SUCCESS [  0.018 s]
[INFO] Jetty Tests :: WebApp :: Mock Resources ............ SUCCESS [  0.122 s]
[INFO] Jetty :: Quick Start ............................... SUCCESS [  3.532 s]
[INFO] Jetty :: JAAS ...................................... SUCCESS [  0.413 s]
[INFO] Jetty :: Jetty Maven Plugin ........................ SUCCESS [  6.514 s]
[INFO] Jetty :: Jetty JSPC Maven Plugin ................... SUCCESS [  2.608 s]
[INFO] Jetty :: Deployers ................................. SUCCESS [ 26.565 s]
[INFO] Jetty :: Start ..................................... SUCCESS [  4.629 s]
[INFO] Jetty :: CDI :: Parent ............................. SUCCESS [  0.029 s]
[INFO] Jetty :: CDI :: Core ............................... SUCCESS [  1.335 s]
[INFO] Jetty :: CDI :: Servlet ............................ SUCCESS [  4.873 s]
[INFO] Jetty :: CDI :: Dependencies ....................... SUCCESS [  0.286 s]
[INFO] Jetty :: CDI :: WebSocket .......................... SUCCESS [  7.183 s]
[INFO] Jetty :: CDI 2 ..................................... SUCCESS [  0.092 s]
[INFO] Jetty :: CDI :: Test :: WebApp ..................... SUCCESS [  0.808 s]
[INFO] Example :: Jetty Spring ............................ SUCCESS [  1.849 s]
[INFO] Jetty :: JASPI Security ............................ SUCCESS [  4.094 s]
[INFO] Jetty :: Rewrite Handler ........................... SUCCESS [  3.823 s]
[INFO] Jetty Tests :: Sessions :: Parent .................. SUCCESS [  0.077 s]
[INFO] Jetty Tests :: Sessions :: Common .................. SUCCESS [02:53 min]
[INFO] Jetty :: NoSQL Session Managers .................... SUCCESS [  0.356 s]
[INFO] Jetty :: Infinispan Session Managers ............... SUCCESS [  0.477 s]
[INFO] Jetty :: GCloud .................................... SUCCESS [  0.019 s]
[INFO] Jetty :: GCloud :: Session Manager ................. SUCCESS [  7.155 s]
[INFO] Jetty :: Memcached ................................. SUCCESS [  0.016 s]
[INFO] Jetty :: Memcached :: Sessions ..................... SUCCESS [  0.344 s]
[INFO] Jetty :: Hazelcast Session Manager ................. SUCCESS [  9.549 s]
[INFO] Jetty :: UnixSocket ................................ SUCCESS [  3.440 s]
[INFO] Test :: Jetty Test Webapp .......................... SUCCESS [  2.573 s]
[INFO] Test :: Jetty Proxy Webapp ......................... SUCCESS [  0.822 s]
[INFO] Jetty Tests :: WebApp :: RFC2616 ................... SUCCESS [  0.138 s]
[INFO] Jetty Tests :: Spec Test WebApp :: Parent .......... SUCCESS [  0.033 s]
[INFO] Jetty Tests :: WebApp :: Servlet Spec :: Fragment Jar SUCCESS [  0.169 s]
[INFO] Jetty Tests :: WebApp :: Servlet Spec :: ServletContainerInitializer Test Jar SUCCESS [  0.187 s]
[INFO] Jetty Tests :: Webapps :: Spec Webapp .............. SUCCESS [  0.603 s]
[INFO] Jetty Tests :: WebApp :: JAAS ...................... SUCCESS [  0.102 s]
[INFO] Jetty Tests :: WebApp :: JNDI ...................... SUCCESS [  0.187 s]
[INFO] Jetty :: ALPN :: OpenJDK8 Client Implementation .... SUCCESS [  0.216 s]
[INFO] Test :: Jetty HTTP2 Webapp ......................... SUCCESS [  5.724 s]
[INFO] Jetty Tests :: Sessions :: Hash .................... SUCCESS [ 24.848 s]
[INFO] Jetty Tests :: Sessions :: File .................... SUCCESS [ 45.085 s]
[INFO] Jetty Tests :: Sessions :: JDBC .................... SUCCESS [02:50 min]
[INFO] Jetty Tests :: Sessions :: Mongo ................... SUCCESS [  0.306 s]
[INFO] Jetty Tests :: Sessions :: Infinispan .............. SUCCESS [01:46 min]
[INFO] Jetty Tests :: Sessions :: GCloud .................. SUCCESS [  0.583 s]
[INFO] Jetty Tests :: Sessions :: Memcached ............... SUCCESS [  0.340 s]
[INFO] Jetty Tests :: Sessions :: Hazelcast ............... SUCCESS [06:14 min]
[INFO] Test :: Continuation ............................... SUCCESS [  5.128 s]
[INFO] Jetty Tests :: Login Service ....................... SUCCESS [  5.684 s]
[INFO] Jetty :: ALPN :: Conscrypt Server Implementation ... SUCCESS [  0.266 s]
[INFO] Jetty :: Home Assembly ............................. SUCCESS [01:28 min]
[INFO] Jetty Examples :: Parent ........................... SUCCESS [  0.076 s]
[INFO] Example Async Rest ................................. SUCCESS [  0.061 s]
[INFO] Example Async Rest :: Jar .......................... SUCCESS [  0.875 s]
[INFO] Example Async Rest :: Webapp ....................... SUCCESS [  0.949 s]
[INFO] Jetty :: Documentation ............................. SUCCESS [01:27 min]
[INFO] Jetty :: Distribution Assemblies ................... SUCCESS [  9.343 s]
[INFO] Jetty Tests :: Integrations ........................ SUCCESS [02:51 min]
[INFO] Test :: Jetty Quick Start .......................... SUCCESS [  5.397 s]
[INFO] Jetty Tests :: JMX Parent .......................... SUCCESS [  0.041 s]
[INFO] Jetty Tests :: JMX :: WebApp ....................... SUCCESS [  0.198 s]
[INFO] Jetty Tests :: JMX :: WebApp Integration Tests ..... SUCCESS [  0.303 s]
[INFO] Test :: HTTP Client Transports ..................... SUCCESS [10:22 min]
[INFO] Example :: Jetty Embedded .......................... SUCCESS [  5.512 s]
[INFO] Jetty :: Runner .................................... SUCCESS [  7.621 s]
[INFO] Jetty :: Http Service Provider Interface ........... SUCCESS [  2.216 s]
[INFO] Jetty :: OSGi ...................................... SUCCESS [  0.041 s]
[INFO] Jetty :: OSGi :: Boot .............................. SUCCESS [  1.777 s]
[INFO] Jetty :: OSGi :: Boot JSP .......................... SUCCESS [  0.803 s]
[INFO] Jetty :: OSGi :: Boot :: Warurl .................... SUCCESS [  0.398 s]
[INFO] Jetty :: OSGi :: HttpService ....................... SUCCESS [  0.455 s]
[INFO] Jetty :: OSGi :: Test WebApp ....................... SUCCESS [  0.435 s]
[INFO] Jetty :: OSGi :: Test Context ...................... SUCCESS [  0.500 s]
[INFO] Jetty :: OSGi :: WebApp Fragment ................... SUCCESS [  0.228 s]
[INFO] Jetty :: OSGi :: Server ............................ SUCCESS [  0.299 s]
[INFO] Jetty :: OSGi ALPN Fragment ........................ SUCCESS [  0.187 s]
[INFO] Jetty :: ALPN :: Conscrypt Client Implementation ... SUCCESS [  0.471 s]
[INFO] Jetty :: OSGi :: Test .............................. FAILURE [ 24.713 s]
[INFO] Jetty :: Bom ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56:28 min
[INFO] Finished at: 2018-03-01T14:19:27+01:00
[INFO] Final Memory: 179M/942M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project test-jetty-osgi: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi && /usr/lib/jvm/java-8-oracle/jre/bin/java -Dmortbay-alpn-boot=/home/emiherd/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar -jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire/surefirebooter8742564591985897377.jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire 2018-03-01T13-23-19_820-jvmRun1 surefire1745688944328002378tmp surefire_732840592332301876996tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.eclipse.jetty.osgi.test.TestJettyOSGiBootContextAsService
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi && /usr/lib/jvm/java-8-oracle/jre/bin/java -Dmortbay-alpn-boot=/home/emiherd/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar -jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire/surefirebooter8742564591985897377.jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire 2018-03-01T13-23-19_820-jvmRun1 surefire1745688944328002378tmp surefire_732840592332301876996tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.eclipse.jetty.osgi.test.TestJettyOSGiBootContextAsService
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :test-jetty-osgi

Process finished with exit code 1
```

**Comment by joakime** [comment] 2018-03-01 13:34
do you have the dump/crash file for this?

> [ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.

**Comment by phoe** [comment] 2018-03-01 13:36
The attached surefire-reports dir has some crashes.
```
$ ls *.dumpstream
2018-03-01T11-00-09_786-jvmRun1.dumpstream
2018-03-01T11-00-12_771.dumpstream
2018-03-01T13-23-19_820-jvmRun1.dumpstream
2018-03-01T13-23-20_160.dumpstream
```

**Comment by phoe** [comment] 2018-03-01 13:38
I have tried to reinstall this module only and got the following log, showing a similar crash in a different test. This one did not produce any reports in surefire-reports, nor I can see any Java dumps produced.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project test-jetty-osgi: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi && /usr/lib/jvm/java-8-oracle/jre/bin/java -Dmortbay-alpn-boot=/home/emiherd/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar -jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire/surefirebooter1034759066870524717.jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire 2018-03-01T14-32-26_859-jvmRun1 surefire5129416400759032934tmp surefire_08265445681724454367tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithAnnotations
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi && /usr/lib/jvm/java-8-oracle/jre/bin/java -Dmortbay-alpn-boot=/home/emiherd/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar -jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire/surefirebooter1034759066870524717.jar /home/emiherd/git/jetty.project/jetty-osgi/test-jetty-osgi/target/surefire 2018-03-01T14-32-26_859-jvmRun1 surefire5129416400759032934tmp surefire_08265445681724454367tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithAnnotations
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

**Comment by phoe** [comment] 2018-03-01 13:40
This issue is intermittent - the module has just successfully built for me.

**Comment by phoe** [comment] 2018-03-01 14:07
@joakime I am not sure that I have linked the proper surefire-reports directory and if the dumps are relevant to *this* bug exactly.

**Comment by joakime** [comment] 2018-03-20 18:08
We've been unable to reproduce this.

This seems to be a Maven bug.

According to your attached logs, you were using  ...

```
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

<property name="classworlds.conf" value="/opt/idea/plugins/maven/lib/maven3/bin/m2.conf"/>
<property name="java.class.path" value="/opt/idea/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar:/opt/idea/lib/idea_rt.jar"/>
<property name="sun.java.command" value="org.codehaus.classworlds.Launcher -Didea.version=2017.3 install"/>
<property name="maven.home" value="/opt/idea/plugins/maven/lib/maven3"/>
```

So the built-in Maven on IntelliJ 2017.3, with Java 1.8.0u131

And the reason for the crash is reported as ....

```
Corrupted stdin stream in forked JVM 1. Stream 'Heap'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'Heap'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:469)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:191)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:158)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:87)
	at java.lang.Thread.run(Thread.java:748)
```

Closing as unable to reproduce.

**Closed** 2018-03-20 18:11 UTC
Labels: Test
