### ISSUE TITLE
New Request Timing API and Timeout Impl

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#254] opened 2016-02-16 23:41 UTC
migrated from Bugzilla [#482016](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482016)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.2.13_ on platform _All_
Assigned to: Greg Wilkins

On 2015-11-12 09:27:49 -0500, Joakim Erdfelt wrote:

> Based on recent discussion, there seems to be a general need for a new API for low level Request Timings.
> 
> The 2 defined use cases are:
> - Accurate timing collection (performance monitoring)
> - Slow Request mitigation
> 
> As for the initial implementation using this API, the request timeout / slow request mitigation use case should be addressed first.
> 
> The existing Apache Http mod_reqtimeout shows some examples of this kind of request timeout.
> 
> https://httpd.apache.org/docs/2.4/mod/mod_reqtimeout.html
> 
> One feature above and beyond the apache mod_reqtimeout, is to have the "body" timeout be capable of being method specific (ie: POST)

On 2015-11-12 09:28:33 -0500, Joakim Erdfelt wrote:

> Assigning to Greg.
> 
> This should probably be implemented in jetty-9.2.x and merged forward to jetty-9.3.x+ (if possible)

On 2015-11-12 16:49:35 -0500, Greg Wilkins wrote:

> Currently we have 2 timeouts that apply to a request cycle: the connector idleTimeout is applied to idle periods on a connection/stream when another frame/block is expected; the HttpConfiguration blocking timeout, which is a total operation time applied to a single blocking read/write call (which can apply even if slow progress is made).
> 
> Having and extensible API that sees request event, then it can be used to apply either additional timeouts OR used to gather latency statistics.
> 
> However, we need to consider if such an API is HTTP/1 specific, or should it apply to HTTP/2 as well?
> 
> There are significant differences between the two protocols: specifically HTTP/1 is 1:1 in Connection:Channel while HTTP/2 is 1:n.   The problem this gives for this API is the event of a request starting to arrive (first bytes received) can be delivered to a specific channel in HTTP/1, but it is not so clear for HTTP/2 as the channel does not exist until the entire frame is parsed.
> 
> So start-of-header events are difficult to create generally. The events that can easily be provided for both protocols are end-of-headers and end-of-body.

**Comment by sbordet** [comment] 2017-09-14 09:34
See also #164.
Duplicate of #1807.

**Closed by sbordet** 2017-09-14 09:34 UTC
Labels: Enhancement, Help Wanted
