### ISSUE TITLE
Inflater has been closed

### ISSUE THREAD

**Issue by zcs100** [eclipse/jetty.project#4319] opened 2019-11-17 15:02 UTC
**Jetty version**
9.4.14.v20181114
**Java version**
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

we use websocket implement of jetty. The program is well in period. But the server logged out Exception , Please help us to find a workaround to be able to handle this issue correctly.

```
2019-11-13 21:21:56|||||||||qtp1731977615-831 WARN org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection 578
org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException: Inflater has been closed
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:227)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:244)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:559)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:390)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
	at java.util.zip.Inflater.inflate(Inflater.java:257)
	at java.util.zip.Inflater.inflate(Inflater.java:280)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.decompress(CompressExtension.java:175)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:79)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:219)
	... 14 common frames omitted
```

**Comment by joakime** [comment] 2019-11-17 16:33
@zcs100 do you have a reproducer?
This has been reported before, and we have been unable to reproduce.

Also, does this still happen on Jetty `9.4.22.v20191022`?

**Comment by lachlan-roberts** [comment] 2019-11-17 23:00
I don't think this will be able to be reproduced in `9.4.22` because of the use of the `InflaterPool`, another Inflater will just be taken from the pool instead of the NPE. But then if we are receiving frames after the `WebSocketSession` is stopped that is an issue.

**Comment by zcs100** [comment] 2019-11-18 03:02
The exception appears once in a while  on Jetty 9.4.14.v20181114, I can not find regular patern. 
I check log that print many repetitive message in a Session,I don't  know  it is related.
Does this downward compatibility  on Jetty 9.4.22.v20191022 ? I am trying

**Comment by lachlan-roberts** [comment] 2019-11-18 06:55
@zcs100 If you could get some jetty debug logging around when you get this error it could help work out what is going on.

Yes `9.4.22.v20191022` is backwards compatible for `9.4.14.v20181114`.

**Comment by lachlan-roberts** [comment] 2020-02-21 03:40
Closing due to lack of information and unable to reproduce.

@zcs100 let us know if you still get this error on the latest version of Jetty.

**Closed as completed by lachlan-roberts** 2020-02-21 03:40 UTC
