### ISSUE TITLE
Not able to get any response from the endpoint. Failing at InputStreamResponseListener. And even the Request class is acting wierd.

### ISSUE THREAD

**Issue by abhigithub911** [eclipse/jetty.project#3881] opened 2019-07-16 19:29 UTC
[DEBUG log for AVSClient.txt](https://github.com/eclipse/jetty.project/files/3399312/DEBUG.log.for.AVSClient.txt)

```package de.consol.labs.h2c.examples;

import org.eclipse.jetty.client.api.ContentResponse;
import org.eclipse.jetty.client.api.Response;
import org.eclipse.jetty.http.HttpMethod;
import org.eclipse.jetty.http.HttpStatus;
import org.eclipse.jetty.http2.FlowControlStrategy;
import org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2;
import org.eclipse.jetty.server.HttpConfiguration;
import org.eclipse.jetty.util.component.LifeCycle;
import org.eclipse.jetty.util.ssl.SslContextFactory;
import org.eclipse.jetty.client.util.InputStreamResponseListener;
import org.eclipse.jetty.http2.client.HTTP2Client;
import org.eclipse.jetty.util.component.LifeCycle.Listener;
import java.io.InputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.api.Request;

public class AVSClient {

    //Intialization
    private static final int REQUEST_TIMEOUT_IN_S = 5;
    private static final String EVENTS_ENDPOINT = "/v20160207/events";
    private static final String DIRECTIVES_ENDPOINT = "/v20160207/directives";
    //Hardcoding Access_token for time being as I wanted to test the connection.
    //Because it is a prototype access_token will be hardcoded generating it locally.
    private static final String Access_Token = "My access token here";

    // Host credentials.
    //The AVS endpoint to which we send a GET request.
    private static final String host = "https://alexa.na.gateway.devices.a2z.com";

    //default port number for AVS.
    private static final int port = 443;
    private static final String url = host+DIRECTIVES_ENDPOINT;
    private static HttpClient httpClient;

    public static void main(String[] args) throws Exception {
        doRequest(url);
    }

    private static void doRequest(String url)
            throws InterruptedException, TimeoutException, ExecutionException,
            UnsupportedEncodingException, IOException, Exception {

        HTTP2Client http2Client = new HTTP2Client();
        SslContextFactory sslContextFactory = new SslContextFactory();
        sslContextFactory.setTrustAll(true);
        sslContextFactory.setValidateCerts(false);
        http2Client.addBean(sslContextFactory);

        // Sets up an HttpClient that sends HTTP/1.1 requests over an HTTP/2 transport
        httpClient = new HttpClient(new HttpClientTransportOverHTTP2(http2Client), sslContextFactory);
        httpClient.start();
        String readLine = null;
        InputStream inputStream = null;
        InputStreamResponseListener responseListener = new InputStreamResponseListener();
        Request request = httpClient.newRequest(url);
        request.method(HttpMethod.GET);
        request.header("Authorization", "Bearer " + Access_Token);
        request.send(responseListener);
        Response response = responseListener.get(REQUEST_TIMEOUT_IN_S, TimeUnit.SECONDS);
        int statusCode = response.getStatus();
        if (HttpStatus.isSuccess(statusCode)) {
            if (statusCode == HttpStatus.NO_CONTENT_204) {
                System.out.println("No content");
            }
            inputStream = responseListener.getInputStream();
            BufferedReader in = new BufferedReader(new InputStreamReader(inputStream));

            System.out.println("in"+in);
            StringBuffer response11 = new StringBuffer();

            while ((readLine = in .readLine()) != null) {
                System.out.println("here3");

                response11.append(readLine);

            } in .close();

            // print result

            System.out.println("JSON String Result " + response11.toString());

        } else {
//            throw new AVSException(statusCode + ": " );
            System.out.println("In Else");
        }
    }
}
```

This is my code.

I am trying to send a GET request in HTTP/2 to an AVS endpoint with the authorization token in the header.
But I am not able to get a response from the endpoint.
I have tried send GET request to other http2 supported endpoints as well without anything in the header. But that did not work as well.

I am currently getting a TimeOutException which is as follows:    

``` 
Exception in thread "main" java.util.concurrent.TimeoutException
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:216)
	at de.consol.labs.h2c.examples.AVSClient.doRequest(AVSClient.java:87)
	at de.consol.labs.h2c.examples.AVSClient.main(AVSClient.java:56) 
```    

Which is basically failing at    
``` 
Response response = responseListener.get(REQUEST_TIMEOUT_IN_S, TimeUnit.SECONDS);
```
this line.

I seriously doubt if the request is being able to send anything to the endpoint
```       
 InputStreamResponseListener responseListener = new InputStreamResponseListener();
        Request request = httpClient.newRequest(url);
        request.method(HttpMethod.GET);
        request.header("Authorization", "Bearer " + Access_Token);
        request.send(responseListener);
```     

Can Somebody please look into this.
@sbordet  @gregw  @lachlan-roberts  @joakime

**Comment by abhigithub911** [comment] 2019-07-16 19:32
@sbordet @gregw @lachlan-roberts @joakime

**Comment by sbordet** [comment] 2019-07-16 21:15
Please enable DEBUG logging and attach the log file to this issue.

**Comment by abhigithub911** [comment] 2019-07-16 21:47
[DEBUG log for AVS Client.docx](https://github.com/eclipse/jetty.project/files/3399253/DEBUG.log.for.AVS.Client.docx)

**Comment by joakime** [comment] 2019-07-16 22:06
@abhigithub911 docx files are not easy for linux and osx users to open.
Can you use plain text please?

**Comment by joakime** [comment] 2019-07-16 22:11
For others, note that "AVS" refers to Alexa Voice Services.
Documentation can be found here - https://developer.amazon.com/docs/alexa-voice-service/manage-http2-connection.html

**Comment by abhigithub911** [comment] 2019-07-16 22:11
[DEBUG log for AVSClient.txt](https://github.com/eclipse/jetty.project/files/3399309/DEBUG.log.for.AVSClient.txt)

**Comment by abhigithub911** [comment] 2019-07-16 22:25
Also I am using Jetty Version : 9.4.11.v20180605
and Jetty ALPN api version : 1.1.3.v20160715

**Comment by abhigithub911** [comment] 2019-07-17 19:08
> @abhigithub911 docx files are not easy for linux and osx users to open.
> Can you use plain text please?

Did you find something ?

**Comment by sbordet** [comment] 2019-07-18 12:13
```
14:45:02.342:DBUG:oejac.ALPNClientConnectionFactory:HttpClient@4dcbadb4-12: org.eclipse.jetty.alpn.java.client.OpenJDK8ClientALPNProcessor@3315d4fb for 5838caef[SSLEngine[hostname=alexa.na.gateway.devices.a2z.com port=443] SSL_NULL_WITH_NULL_NULL] on DecryptedEndPoint@22123b94{alexa.na.gateway.devices.a2z.com/54.239.23.243:443<->/10.52.184.79:57181,OPEN,fill=-,flush=-,to=6/0}-><null>->SocketChannelEndPoint@3f3d9121{alexa.na.gateway.devices.a2z.com/54.239.23.243:443<->/10.52.184.79:57181,OPEN,fill=-,flush=-,to=29/0}{io=0/0,kio=0,kro=8}->SslConnection@2f44ed82{NOT_HANDSHAKING,eio=-1/-1,di=-1}=>null
```

This line from your logs show that the idle timeout for the client connection is `0`.

This is obviously a bad value, as the connection will immediately timeout as soon as it's created.

Double check that you are not setting the idle timeout to zero.

**Comment by joakime** [comment] 2019-07-21 15:54
Isn't this a duplicate of #3874

**Comment by sbordet** [comment] 2019-07-21 16:14
@joakime #3874 is about ALPN, this one seems to be an idle timeout misconfiguration.

**Comment by sbordet** [comment] 2019-09-26 19:45
@abhigithub911 looking at your latest logs, there is this:

`java.lang.NoSuchMethodError: org.eclipse.jetty.http2.parser.Parser.setMaxFrameLength(I)V`

So you are probably using newer code with older Jetty jars.

Your setup is wrong, you should use consistent Jetty versions.

**Closed by sbordet** 2019-09-26 19:45 UTC
