### ISSUE TITLE
"Jetty 9.4.12" with "Conscrypt 1.2" provokes file descriptors leak

### ISSUE THREAD

**Issue by tk-l2002** [eclipse/jetty.project#3111] opened 2018-11-14 16:15 UTC
_Originally posted by @tk-l2002 in https://github.com/eclipse/jetty.project/issues/2342#issuecomment-438718275_

**Comment by sbordet** [comment] 2018-11-14 17:35
So if `SSLEngine.isOutboundDone()` returns `true` even though it has not produced the `close_notify` bytes, `SslConnection.DecryptedEndPoint` should still try to shutdown the output on the raw `EndPoint`, and possibly close.

**Comment by radifalco** [comment] 2018-11-28 01:18
I also see this with Conscrypt 1.4.1 when using HTTP/2.

**Comment by sbordet** [comment] 2019-02-18 10:54
I tried the latest Jetty (9.4.14 and 9.4.15) and latest Conscrypt (1.4.2 and 2.0.0), and I cannot see this issue with or without HTTP/2.

If you have a reproducible case, we would love to hear the details so that we can figure this out.

**Comment by sunng87** [comment] 2019-03-22 14:53
I can reproduce this issue with Jetty 9.4.15 and Conscrypt 2.0.0, with `wrk` tool. `SslConnection`s created by `wrk` were never recycled, which causes heap/off-heap/fd leak.

**Comment by sunng87** [comment] 2019-03-22 15:23
Switched to jdk11 based `alpn-java-server`, there is no more leak. I believe this is an issue with Conscrypt.

**Comment by olamy** [comment] 2019-03-23 00:56
@sunng87  current jetty-9.4.x branch has been upgraded to use Conscrypt 2.0.0 maybe this will fix your problem? 
if not can you please provide a reproducible case.
thanks

**Comment by sunng87** [comment] 2019-04-03 16:09
@olamy sorry for late response. I tested with latest 9.4.x branch and it's still the case.  Simply start an https server using conscrypt, and test it with `wrk -t 8 -c 500 -d 10 https://localhost:8443/` several times. You will see the memory usage of Jetty process goes up and never recycled. Also by acquiring a server dump using eclipse-mat, I can use as many `SslConnection`s as I created stays in memory. 

![image](https://user-images.githubusercontent.com/221942/55494566-99024e80-566d-11e9-9df8-e33a30856a98.png)

If you like to see the server, it's a Clojure one (I changed Jetty version locally): https://github.com/sunng87/ring-jetty9-adapter/blob/master/examples/rj9a/http2.clj

**Comment by mattnelson** [comment] 2019-04-13 00:34
Was able to reproduce as well, providing some more information. I am using conscrypt-2.1.0 and jetty-9.4.15.v20190215. As shown below and [commented on conscrypt](https://github.com/google/conscrypt/issues/491#issuecomment-389561082) this appears to be competing issue between GC and the file descriptor limit. With a small heap the objects will be reclaimed/closed before reaching the FD limit. With a large heap the opposite will happen.

```
# before test
# no SslConnection objects
jcmd 1 GC.class_histogram | grep SslConnection
1250:             2            176  org.eclipse.jetty.server.SslConnectionFactory
1982:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FillState
1983:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FlushState
1984:             3             72  org.eclipse.jetty.io.ssl.SslConnection$Handshake
2850:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FillState;
2851:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FlushState;
2852:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$Handshake;
# file descriptor count
ls /proc/1/fd | wc -l
61
```

I used vegeta to simulate the load
```
echo "HEAD https://localhost:8443" | vegeta attack -duration=60s -rate=200 | vegeta report -every 10s
```


Confirming object count and file descriptor usage
```
# Must supply "-all" flag to avoid a GC
jcmd 1 GC.class_histogram -all | grep SslConnection
  46:          3274         340496  org.eclipse.jetty.io.ssl.SslConnection
  72:          3274         235728  org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint
 174:          3274          78576  org.eclipse.jetty.io.ssl.SslConnection$1
 218:          3274          52384  org.eclipse.jetty.io.ssl.SslConnection$2
 219:          3274          52384  org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback
1652:             2            176  org.eclipse.jetty.server.SslConnectionFactory
2456:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FillState
2457:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FlushState
2458:             3             72  org.eclipse.jetty.io.ssl.SslConnection$Handshake
3392:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FillState;
3393:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FlushState;
3394:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$Handshake;
ls /proc/1/fd | wc -l
641
```

Trigger a GC
```
# repeat without all flag to GC the connection
jcmd 1 GC.class_histogram | grep SslConnection
1268:             2            176  org.eclipse.jetty.server.SslConnectionFactory
1622:             1            104  org.eclipse.jetty.io.ssl.SslConnection
2012:             1             72  org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint
2013:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FillState
2014:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FlushState
2015:             3             72  org.eclipse.jetty.io.ssl.SslConnection$Handshake
2897:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FillState;
2898:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FlushState;
2899:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$Handshake;
3909:             1             24  org.eclipse.jetty.io.ssl.SslConnection$1
5333:             1             16  org.eclipse.jetty.io.ssl.SslConnection$2
5334:             1             16  org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback
ls /proc/1/fd | wc -l
63
```

**Comment by sunng87** [comment] 2019-04-13 14:08
In my case, `SslConnection`s were not recycled even with `jcmd pid GC.run`

```
$ jcmd 25726 GC.class_histogram | grep SslConnection                                          [22:06:28]
  20:          3006         312624  org.eclipse.jetty.io.ssl.SslConnection
  37:          3006         216432  org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint
  95:          3006          72144  org.eclipse.jetty.io.ssl.SslConnection$1
 110:          3006          48096  org.eclipse.jetty.io.ssl.SslConnection$2
 111:          3006          48096  org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback
 626:             1             88  org.eclipse.jetty.server.SslConnectionFactory
 676:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FillState
 677:             3             72  org.eclipse.jetty.io.ssl.SslConnection$FlushState
 678:             3             72  org.eclipse.jetty.io.ssl.SslConnection$Handshake
 859:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FillState;
 860:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$FlushState;
 861:             1             32  [Lorg.eclipse.jetty.io.ssl.SslConnection$Handshake;
```

**Comment by j-razeed** [comment] 2019-09-06 06:52
Any fix available for this issue?

**Comment by sbordet** [comment] 2019-09-16 10:49
@j-razeed the fix seemed all the times a Conscrypt issue, so be sure to be updated to the latest release of Conscrypt. We don't have evidence it is a Jetty issue so far.

**Comment by sunng87** [comment] 2019-09-17 06:16
Tried latest conscrypt 2.2.1 with no luck.

**Comment by sunng87** [comment] 2019-09-21 07:58
Not quite sure if it's related. By analysing class diagram, I saw a bunch of `ALPNCallback`s hold in memory, with it's number equals to connections I created. However, ALPN should have finished right after connection established.

![image](https://user-images.githubusercontent.com/221942/65370139-36872400-dc88-11e9-9e9a-fc0b17424ad7.png)

**Comment by kruton** [comment] 2019-09-27 08:59
@sunng87 the ALPNCallback [adds itself as a HandshakeListener](https://github.com/eclipse/jetty.project/blob/9706d70484863a014d3604e5e7cb4af40aa4cb1e/jetty-alpn/jetty-alpn-conscrypt-server/src/main/java/org/eclipse/jetty/alpn/conscrypt/server/ConscryptServerALPNProcessor.java#L82) so it won't go away until the connection is GC'd.

**Comment by kruton** [comment] 2019-09-28 01:23
It might work to separate the `ALPNSelector` and the `SSLHandshakeCallback` into two classes for now if anyone has the time to try that.

**Comment by sbordet** [comment] 2019-09-30 14:09
@kruton @sunng87 one thing we can do is to remove the `ALPNCallback` when the ALPN negotiation is finished, via `SslConnection.removeHandshakeListener()`.

If I create a branch for that, would you be able to test it?

**Comment by sunng87** [comment] 2019-10-01 03:35
@sbordet sure, I can help test.

**Comment by kruton** [comment] 2019-10-23 21:43
I posted a pull request at https://github.com/google/conscrypt/pull/735 which I think fixes the issue.

**Comment by sunng87** [comment] 2019-10-24 15:53
Tested from my build, there is no more `SslConnection` leak with google/conscrypt#735 

Class histogram after wrk test with 6000 SSL connections:

![image](https://user-images.githubusercontent.com/221942/67502926-5069bb80-f6b9-11e9-8e55-ca1fbb8f4a70.png)

**Comment by joakime** [comment] 2019-10-24 15:58
When that PR is merged, and a new release of conscrypt is released, we can upgrade Jetty to use it.

**Comment by prateekkohli2112** [comment] 2020-09-09 06:21
I am also facing this issue with Jetty - 9.4.24.v20191120 and Conscrypt - 2.1.0 .

Will it be fixed if I upgrade my Jetty to 9.4.31.v20200723 and Conscrypt to 2.5.0?

**Comment by sunng87** [comment] 2020-09-09 14:42
Unfortunately we are still experiencing memory leak with latest conscrypt. The issue is now tracked in https://github.com/google/conscrypt/issues/835

**Comment by prateekkohli2112** [comment] 2020-09-09 14:51
Is there any workaround for this?

Or do we need to go with JDK8 ALPN.

**Comment by sunng87** [comment] 2020-09-10 14:51
Yes JDK 8u252 has built-in ALPN support. Not sure about its real performance though

**Comment by debashisdeb** [comment] 2021-04-14 20:34
Any update on this issue ? We are on 2.5.1 for conscrypt along with jetty 9.3 and still seeing the issue.

**Comment by joakime** [comment] 2021-04-14 20:59
https://www.eclipse.org/jetty/download.php#what-jetty-version

Jetty 9.3 is already deprecated.
Jetty 9.4.x is in maintenance mode (till Java 8 is dead).
Jetty 10.0.x is the mainline for Jakarta EE 8 (on the old `javax.servlet` namespace)
Jetty 11.0.x is the mainline for Jakarta EE 9 (on the new `jakarta.servlet` namespace)

As far as this memory leak, that's still an open bug on conscrypt.
Not much we can do about it until they fix it.

**Comment by olamy** [comment] 2021-04-28 06:29
closing as due to external issue https://github.com/google/conscrypt/issues/835

**Closed by olamy** 2021-04-28 06:29 UTC
Labels: Bug, Performance
