### ISSUE TITLE
Load ProtectionDomain when defining classes in WebAppClassLoader

### ISSUE THREAD

**Issue by andrei-ivanov** [eclipse/jetty.project#3507] opened 2019-03-29 14:18 UTC
Hi,
Having a webapp using a ClassFileTransformer, I end up with an exception trying to use Eclipse Moxy 2.7.4 in Jetty 9.4.12:
```
java.lang.SecurityException: class "org.eclipse.persistence.jaxb.JAXBUnmarshaller"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:898) ~[?:1.8.0_181]
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_181]
        at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass(WebAppClassLoader.java:667) ~[?:?]
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:555) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at org.eclipse.persistence.jaxb.JAXBContext$JAXBContextState.createUnmarshaller(JAXBContext.java:1614) ~[org.eclipse.persistence.moxy-2.7.4.jar:?]
        at org.eclipse.persistence.jaxb.JAXBContext.createUnmarshaller(JAXBContext.java:430) ~[org.eclipse.persistence.moxy-2.7.4.jar:?]
        at org.eclipse.persistence.jaxb.JAXBContext.createUnmarshaller(JAXBContext.java:1) ~[org.eclipse.persistence.moxy-2.7.4.jar:?]
```

As far as I see, this happens because there's no `ProtectionDomain` passed in the `defineClass` call at https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L707

Is there any other way to fix it that I haven't seen?

**Comment by joakime** [comment] 2019-03-29 14:41
Seems similar to issue #1068

**Comment by andrei-ivanov** [comment] 2019-03-29 15:05
Hmm, indeed, I am running it on Java 8, didn't think that would matter.
I think I will have a task scheduled in the next couple weeks to upgrade our project to Java 11 and I will see what happens then.

**Comment by joakime** [comment] 2019-04-08 20:32
Closing this issue as a duplicate of #1068 
Feel free to continue the conversation over there.

**Closed by joakime** 2019-04-08 20:32 UTC
