### ISSUE TITLE
NPE in MultiPartInputStreamParser#getPart(String name)

### ISSUE THREAD

**Issue by cnoelle** [eclipse/jetty.project#2892] opened 2018-09-09 21:28 UTC
If I call ~~request~~`parser.getPart("name")` before a call to ~~request~~`parser.getParts()` (where `parser` is a MultiPartInputStreamParser) I get an NPE. Looking at the code in the 9.4.x and 10.0.x branches there seems to be a missing negation:
```
if(_parsed)
            parse();
```
should probably read
```
if(!_parsed)
            parse();
```

**Comment by joakime** [comment] 2018-09-09 23:48
Are you testing in Jetty 10.0.x? or 9.4.x?

**Comment by cnoelle** [comment] 2018-09-10 05:53
In 9.4.x

**Comment by cnoelle** [comment] 2018-09-10 05:59
Changed the issue description: the NPE actually occurs when using the MultiPartInputStreamParser directly, instead of the HttpServletRequest.

**Comment by joakime** [comment] 2018-09-10 07:08
In `jetty-9.4.x` the [`org.eclipse.jetty.util.MultiPartInputStreamParser`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/MultiPartInputStreamParser.java) is now deprecated.

It's been replaced by the [`org.eclipse.jetty.http.MultiPartFormInputStream`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormInputStream.java).

The internals of Jetty and it's processing of the Request InputStream for Parts is performed by either of the above based on the compliance mode set.

https://github.com/eclipse/jetty.project/blob/0c97d28cbaf98204d834336ad594abcd6b98cc27/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L2326-L2339

The `HttpConfiguration.setMultiPartFormDataCompliance()` can be used to switch between the two modes.
* `LEGACY` - the default for `jetty-9.4.x`
* `RFC7578` - the default for `jetty-10.0.x`

https://github.com/eclipse/jetty.project/blob/0c97d28cbaf98204d834336ad594abcd6b98cc27/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L2404-L2422

The behavior in `MultiParts` is to always use `getParts()`.

https://github.com/eclipse/jetty.project/blob/0c97d28cbaf98204d834336ad594abcd6b98cc27/jetty-server/src/main/java/org/eclipse/jetty/server/MultiParts.java#L58-L62

https://github.com/eclipse/jetty.project/blob/0c97d28cbaf98204d834336ad594abcd6b98cc27/jetty-server/src/main/java/org/eclipse/jetty/server/MultiParts.java#L117-L121

Closing, as I would consider this working as intended for an internal class/object that isn't meant to be a public API.

**Closed** 2018-10-10 05:20 UTC
