### ISSUE TITLE
Customize do not index HTTP2 header by Hpack 

### ISSUE THREAD

**Issue by linking12** [eclipse/jetty.project#6333] opened 2021-05-28 09:56 UTC
**Jetty version**
     9.4.41.v20210516
**Java version**
     JDK1.8
**Question**
    1:  when jetty cllient hpack index all of http2 header，found tomcat will throw some exception like this:

   ```
An exception has been raised by Name:http-nio-9315-exec-159,Id:440 java.lang.RuntimeException: java.lang.NegativeArraySizeException: -1
    at org.apache.coyote.http2.HpackDecoder.decode(HpackDecoder.java:130)
    at org.apache.coyote.http2.Http2Parser.readHeaderPayload(Http2Parser.java:486)
    at org.apache.coyote.http2.Http2Parser.readHeadersFrame(Http2Parser.java:270)
    at org.apache.coyote.http2.Http2AsyncParser$FrameCompletionHandler.completed(Http2AsyncParser.java:251)
    at org.apache.coyote.http2.Http2AsyncParser$FrameCompletionHandler.completed(Http2AsyncParser.java:164)
    at org.apache.tomcat.util.net.SocketWrapperBase$VectoredIOCompletionHandler.completed(SocketWrapperBase.java:1089)
    at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper$NioOperationState.run(NioEndpoint.java:1621)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NegativeArraySizeException: -1
    at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
    at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:112)
    at org.apache.coyote.http2.HpackDecoder.readHuffmanString(HpackDecoder.java:261)
    at org.apache.coyote.http2.HpackDecoder.readHpackString(HpackDecoder.java:251)
    at org.apache.coyote.http2.HpackDecoder.decode(HpackDecoder.java:126)
    ... 10 more

   ```
  
2:  so replace tomcat HpackDecoder code in project class to catch error like this:

```
 void decode(ByteBuffer buffer) throws HpackException {
        while (buffer.hasRemaining()) {
            int originalPos = buffer.position();
            byte b = buffer.get();
            if ((b & 0b10000000) != 0) {
                //if the first bit is set it is an indexed header field
                buffer.position(buffer.position() - 1); //unget the byte
                int index = Hpack.decodeInteger(buffer, 7); //prefix is 7
                if (index == -1) {
                    buffer.position(originalPos);
                    return;
                } else if(index == 0) {
                    throw new HpackException(
                            sm.getString("hpackdecoder.zeroNotValidHeaderTableIndex"));
                }
                handleIndex(index);
            } else if ((b & 0b01000000) != 0) {
                //Literal Header Field with Incremental Indexing
                String headerName = readHeaderName(buffer, 6);
                if (headerName == null) {
                    buffer.position(originalPos);
                    return;
                }
                String headerValue = null;
                ByteBuffer bufferReplica = buffer.duplicate();
                try {
                    headerValue = readHpackString(buffer);
                } catch (Throwable e) {
                    CharBuffer originalValue = StandardCharsets.UTF_8.decode(bufferReplica);
                    // **log decode error header** 
                    log.warn("hpack decode error, headerName: {}, value: {}", headerName, originalValue);
                    throw new RuntimeException(e);
                }
                if (headerValue == null) {
                    buffer.position(originalPos);
                    return;
                }
                emitHeader(headerName, headerValue);
                addEntryToHeaderTable(new Hpack.HeaderField(headerName, headerValue));
            } else if ((b & 0b11110000) == 0) {
                //Literal Header Field without Indexing
                String headerName = readHeaderName(buffer, 4);
                if (headerName == null) {
                    buffer.position(originalPos);
                    return;
                }
                String headerValue = null;
                ByteBuffer bufferReplica = buffer.duplicate();
                try {
                    headerValue = readHpackString(buffer);
                } catch (Throwable e) {
                    CharBuffer originalValue = StandardCharsets.UTF_8.decode(bufferReplica);
                    **log.warn("hpack decode error, headerName: {}, value: {}", headerName, originalValue);**
                    throw new RuntimeException(e);
                }
                if (headerValue == null) {
                    buffer.position(originalPos);
                    return;
                }
                emitHeader(headerName, headerValue);
            } else if ((b & 0b11110000) == 0b00010000) {
                //Literal Header Field never indexed
                String headerName = readHeaderName(buffer, 4);
                if (headerName == null) {
                    buffer.position(originalPos);
                    return;
                }
                String headerValue = null;
                ByteBuffer bufferReplica = buffer.duplicate();
                try {
                    headerValue = readHpackString(buffer);
                } catch (Throwable e) {
                    CharBuffer originalValue = StandardCharsets.UTF_8.decode(bufferReplica);
                    log.warn("hpack decode error, headerName: {}, value: {}", headerName, originalValue);
                    throw new RuntimeException(e);
                }
                if (headerValue == null) {
                    buffer.position(originalPos);
                    return;
                }
                emitHeader(headerName, headerValue);
            } else if ((b & 0b11100000) == 0b00100000) {
                //context update max table size change
                if (!handleMaxMemorySizeChange(buffer, originalPos)) {
                    return;
                }
            } else {
                throw new RuntimeException(sm.getString("hpackdecoder.notImplemented"));
            }
        }
    }

```

3: found it is a large header and change all the time cause tomcat decode error;

```
hpack decode error, headerName: device-info, value: �

```

summary:
  1: is any way to let jetty client do not hpack encode/index header?
  2: if jetty client do not encode/index header, if header transmission to server, is header can work normal?

BTW：

I want to change some code by reflection add some header in DO_NOT_INDEX

```
public class HpackEncoder
{
    static final EnumSet<HttpHeader> DO_NOT_INDEX =
        EnumSet.of(
            // HttpHeader.C_PATH,  // TODO more data needed
            // HttpHeader.DATE,    // TODO more data needed
            HttpHeader.AUTHORIZATION,
            HttpHeader.CONTENT_MD5,
            HttpHeader.CONTENT_RANGE,
            HttpHeader.ETAG,
            HttpHeader.IF_MODIFIED_SINCE,
            HttpHeader.IF_UNMODIFIED_SINCE,
            HttpHeader.IF_NONE_MATCH,
            HttpHeader.IF_RANGE,
            HttpHeader.IF_MATCH,
            HttpHeader.LOCATION,
            HttpHeader.RANGE,
            HttpHeader.RETRY_AFTER,
            // HttpHeader.EXPIRES,
            HttpHeader.LAST_MODIFIED,
            HttpHeader.SET_COOKIE,
            HttpHeader.SET_COOKIE2);
```

I submit same issue to tomcat, but tomcat dev team want to know is jetty encode bug or tomcat bug...
https://bz.apache.org/bugzilla/show_bug.cgi?id=65340
this is issue happen on prod env, It diffcult to reproduce..

**Comment by qingdaoheze** [comment] 2021-05-28 13:08
The original exception stack trace is as below in Tomcat source:

java.lang.NegativeArraySizeException: -1
	at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:112)
	at org.apache.coyote.http2.HpackDecoder.readHuffmanString(HpackDecoder.java:231)
	at org.apache.coyote.http2.HpackDecoder.readHpackString(HpackDecoder.java:221)
	at org.apache.coyote.http2.HpackDecoder.decode(HpackDecoder.java:131)
	at org.apache.coyote.http2.Http2Parser.readHeaderPayload(Http2Parser.java:486)
	at org.apache.coyote.http2.Http2Parser.readHeadersFrame(Http2Parser.java:270)
	at org.apache.coyote.http2.Http2AsyncParser$FrameCompletionHandler.completed(Http2AsyncParser.java:251)
	at org.apache.coyote.http2.Http2AsyncParser$FrameCompletionHandler.completed(Http2AsyncParser.java:164)
	at org.apache.tomcat.util.net.SocketWrapperBase$VectoredIOCompletionHandler.completed(SocketWrapperBase.java:1089)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper$NioOperationState.run(NioEndpoint.java:1621)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by gregw** [comment] 2021-05-29 22:39
Can you give us some examples of the actual headers being sent?
Why do you say "all indexed"?

**Comment by linking12** [comment] 2021-05-31 02:12
> Can you give us some examples of the actual headers being sent?
> Why do you say "all indexed"?
My understanding， for sensitive header, It can not index in hpack,but in jetty client hpack, if dynamicTableSize is enough，All of the header are indexed in hpack; 

```
  else if (name == null && fieldSize < _context.getMaxDynamicTableSize())
                {
                    // unknown name and value that will fit in dynamic table, so let's index
                    // this just in case it is the first time we have seen a custom name or a
                    // custom field.  Unless the name is once only, this is worthwhile
                    indexed = true;
                    encodeName(buffer, (byte)0x40, 6, field.getName(), null);
                    encodeValue(buffer, true, field.getValue());
                    if (_debug)
                        encoding = "LitHuffNHuffVIdx";
                }
```

In netty code, if header is sensitive, it not indexed like this:

io.netty.handler.codec.http2.HpackEncoder
```
 private void encodeHeader(ByteBuf out, CharSequence name, CharSequence value, boolean sensitive, long headerSize) {
        // If the header value is sensitive then it must never be indexed
        if (sensitive) {
            int nameIndex = getNameIndex(name);
            encodeLiteral(out, name, value, IndexType.NEVER, nameIndex);
            return;
        }
``` 

we will provider examples header after our change and verification  code for sensitive header

**Comment by gregw** [comment] 2021-05-31 05:17
Jetty has already checked against our NEVER_INDEX fields and non-zero content-lengths, which is the same concept as netty's sensitive parameter.

Even if we are not optimal in our choice of what fields to index, that should still not cause an exception in tomcat.

**Comment by linking12** [comment] 2021-05-31 07:01
> Jetty has already checked against our NEVER_INDEX fields and non-zero content-lengths, which is the same concept as netty's sensitive parameter.
> 
> Even if we are not optimal in our choice of what fields to index, that should still not cause an exception in tomcat.


you mean this?
```
 else if (fieldSize >= _context.getMaxDynamicTableSize() || header == HttpHeader.CONTENT_LENGTH && !"0".equals(field.getValue()))
                {
                    // The field is too large or a non zero content length, so do not index.
                    indexed = false;
                    encodeName(buffer, (byte)0x00, 4, header.asString(), name);
                    encodeValue(buffer, true, field.getValue());
                    if (_debug)
                        encoding = "Lit" +
                            ((name == null) ? "HuffN" : "IdxNS" + (1 + NBitInteger.octectsNeeded(4, _context.index(name)))) +
                            "HuffV!Idx";
                }
```

i think there are some wrong with custome header,  for custome header, if it is sensitive, should be indexed in hpack

```
 else if (name == null && fieldSize < _context.getMaxDynamicTableSize())
              {
               //unknown name and value that will fit in dynamic table, so let's index
               //  this just in case it is the first time we have seen a custom name or a
               //  custom field. Unless the name is once only, this is worthwhile
               indexed = true;
                encodeName(buffer, (byte)0x40, 6, field.getName(), null);
                encodeValue(buffer, true, field.getValue());
                if (_debug)
                 encoding = "LitHuffNHuffVIdx";
               }
```

**Comment by linking12** [comment] 2021-05-31 09:13
@gregw  I think we has found the problem
as i said in last reply， after we disable custome header in hpack, tomcat's exception has gone.
i think there is something wrong in dynamicTable index;

**Comment by gregw** [comment] 2021-05-31 12:22
Something strange is going on? I see email alerts for comments on this issue, but the comments are not here?

The spec does not define what "sensitive" means.  We have interpreted it to be the fields in our NEVER_INDEX set and non-zero content-lengths.   We could make it more configurable.
But ultimately, even if we do encode a "sensitvie" with indexing, that should not cause tomcat to throw an exception.  

We need actual examples of your headers that fail.

**Comment by linking12** [comment] 2021-05-31 13:06
> Something strange is going on? I see email alerts for comments on this issue, but the comments are not here?
> 
> The spec does not define what "sensitive" means. We have interpreted it to be the fields in our NEVER_INDEX set and non-zero content-lengths. We could make it more configurable.
> But ultimately, even if we do encode a "sensitvie" with indexing, that should not cause tomcat to throw an exception.
> 
> We need actual examples of your headers that fail.

@gregw 

sorry for my mistask to close this issue

device-info: eyJzY3JlZW5fcmVzb2x1dGlvbiI6IjE3OTIsMTEyMCIsImF2YWlsYWJsZV9zY3JlZW5fcmVzb2x1dGlvbiI6IjE3OTIsMTAxNyIsInN5c3RlbV92ZXJzaW9uIjoiTWFjIE9TIDEwLjE1LjciLCJicmFuZF9tb2RlbCI6InVua25vd24iLCJzeXN0ZW1fbGFuZyI6InpoLUNOIiwidGltZXpvbmUiOiJHTVQrOCIsInRpbWV6b25lT2Zmc2V0IjotNDgwLCJ1c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzkwLjAuNDQzMC4yMTIgU2FmYXJpLzUzNy4zNiIsImxpc3RfcGx1Z2luIjoiQ2hyb21lIFBERiBQbHVnaW4sQ2hyb21lIFBERiBWaWV3ZXIsTmF0aXZlIENsaWVudCIsImNhbnZhc19jb2RlIjoiNzZhNzM5NTgiLCJ3ZWJnbF92ZW5kb3IiOiJBVEkgVGVjaG5vbG9naWVzIEluYy4iLCJ3ZWJnbF9yZW5kZXJlciI6IkFNRCBSYWRlb24gUHJvIDUzMDBNIE9wZW5HTCBFbmdpbmUiLCJhdWRpbyI6IjEyNC4wNDM0NzY1NzgwODEwMyIsInBsYXRmb3JtIjoiTWFjSW50ZWwiLCJ3ZWJfdGltZXpvbmUiOiJBc2lhL1NoYW5naGFpIiwiZGV2aWNlX25hbWUiOiJDaHJvbWUgVjkwLjAuNDQzMC4yMTIgKE1hYyBPUykiLCJmaW5nZXJwcmludCI6IjRlMWQyYWNjOWU0NGNiZDM3Mzk2Y2NmNTI1YTJhZjI4IiwiZGV2aWNlX2lkIjoiIiwicmVsYXRlZF9kZXZpY2VfaWRzIjoiIn0=

I think this header cause this exception

**Comment by gregw** [comment] 2021-06-01 07:32
@linking12 Looking at https://bz.apache.org/bugzilla/show_bug.cgi?id=65340 you are suggesting that the problem is a too small buffer in Tomcat.    So we will let them analyse/confirm that.
Thanks for providing extra information.

**Comment by linking12** [comment] 2021-06-01 09:28
> @linking12 Looking at https://bz.apache.org/bugzilla/show_bug.cgi?id=65340 you are suggesting that the problem is a too small buffer in Tomcat. So we will let them analyse/confirm that.
> Thanks for providing extra information.

yes, we will double check too, we expand buffer in our code and will check the exception can reproduce again.

**Comment by linking12** [comment] 2021-06-03 06:46
> > @linking12 Looking at https://bz.apache.org/bugzilla/show_bug.cgi?id=65340 you are suggesting that the problem is a too small buffer in Tomcat. So we will let them analyse/confirm that.
> > Thanks for providing extra information.
> 
> yes, we will double check too, we expand buffer in our code and will check the exception can reproduce again.

https://bz.apache.org/bugzilla/show_bug.cgi?id=65340#c10

@gregw   I think our team has reproduce this issue, this is a bug for tomcat
1: headerReadBuffer had better to set same with maxheadersize, too many times expand is waste too much heap memory
2: fix -1 issue 
can you contact tomcat dev team to fix this issue?  they do not reply any more...

**Comment by qingdaoheze** [comment] 2021-06-03 06:51
@gregw  This issue is a bug of Tomcat. I have provided the detail in the tomcat issue as below:
https://bz.apache.org/bugzilla/show_bug.cgi?id=65340

**Comment by gregw** [comment] 2021-06-03 08:18
thanks! closing here.

**Closed as completed by gregw** 2021-06-03 08:18 UTC
Labels: Question, Third Party
