### ISSUE TITLE
Jetty12 : Passing encoded slashes (%2F) in URls is causing "400 Ambiguous URI path separator"

### ISSUE THREAD

**Issue by anvy2803** [eclipse/jetty.project#12467] opened 2024-11-01 08:32 UTC
**Jetty version(s)**
12.0.13

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.10"

**OS type/version**
macOS Sonoma 14.7

**Description**
Request URIs with encoded slash (%2F) are being rejected with 400 Bad Request after migrating to Jetty12 from Jetty11. I am also using Jakarta 6.0.0. 

**How to reproduce?**
Send any request with encoded slash. Even if there's no mapping of the URL, it should fail with 404 Not Found instead of 400 Bad Request.

**Comment by paulrutter** [comment] 2024-11-01 11:17
This is by design, see https://github.com/jetty/jetty.project/issues/12346#issuecomment-2391677068

**Comment by joakime** [comment] 2024-11-01 11:43
See the [Jakarta Servlet 6.0 spec: Section 3.5.2. URI Path Canonicalization: 10: Rejecting Suspicious Sequences.](https://github.com/jakartaee/servlet/blob/6.0.0-RELEASE/spec/src/main/asciidoc/servlet-spec-body.adoc#352-uri-path-canonicalization)

**Comment by joakime** [comment] 2024-11-01 12:01
duplicate of #12346

**Closed as not planned by joakime** 2024-11-01 12:01 UTC
Labels: Bug

**Comment by anvy2803** [comment] 2024-11-06 15:28
It's giving 400 Bad Request even after using `UriCompliance.UNSAFE`

**Comment by paulrutter** [comment] 2024-11-06 17:09
See https://github.com/jetty/jetty.project/issues/12346#issuecomment-2392475541
