### ISSUE TITLE
jetty websocket 10/11 server throws ClosedChannelException on closing connection for Firefox client

### ISSUE THREAD

**Issue by thanhvg** [eclipse/jetty.project#6769] opened 2021-09-10 19:14 UTC
**Jetty version(s)**
10.0.6 and 11.0.6

**Java version/vendor** `(use: java -version)`
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**OS type/version**
Ubuntu 18.04.1

**Description**
A websocket client running on Firefox connects to a Jetty websocket server. When the sever closes the connection, the client is able to close with status code 1000. However jetty server throws error ClosedChannelException, and closed session with different code (1006).

```
java.nio.channels.ClosedChannelException
        at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onEof(WebSocketSessionState.java:169)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:244)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:478)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:336)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
        at java.base/java.lang.Thread.run(Thread.java:829)
Socket Closed: [1006] Session Closed
```
With jetty 9x, sever won't throw error but the status code is still 1006.

I also encounter this problem when a popular node websocket client `ws` (https://github.com/websockets/ws) to connect to jetty. However with Google Chrome, it works fine with all three versions of jetty. 

**How to reproduce?**
Clone this simple webapp https://github.com/thanhvg/native-jetty-websocket-example which is based on https://github.com/jetty-project/jetty-websocket-example/tree/master.
Follow the Readme file

```
mvn clean compile
mvn exec:java -Dexec.mainClass=org.eclipse.jetty.demo.EventServer
````

then open  http://localhost:8080/ with firefox, Press the button `Connect to ws enpoint /events`. The line `websocket connection status:`  should show `on`.  Then use the text input box and `Send Message` button to send message to jetty server. Send `bye` to tell jetty server to close the connection and observe jetty throwing error on the server side. 

Thanks.

**Comment by lachlan-roberts** [comment] 2021-09-13 01:46
It looks like the firefox websocket client isn't completing the websocket close handshake and is just closing the connection straight away after receiving a close frame.

Because of this you get a close status of "NO_CLOSE" code 1006, and in Jetty-10 you are also notified of the read error that occurred in the `onWebSocketError` notification which is called directly before the `onWebSocketClose` notification. So if you don't want this exception stracktrace to be printed out you can remove the line to print it out from your `EventSocket.onWebSocketError(Throwable)` method. 

It seems we are behaving correctly in Jetty-10, the difference from jetty-9.4 is that the `onWebSocketError` was never called.

**Comment by thanhvg** [comment] 2021-09-13 02:00
Thanks for your help.

Ignoring the whole `ClosedChannelException` is a bit too much for me, is there any safety check I can add to make sure that  `ClosedChannelException` is thrown because of the client's side in this case?

**Comment by lachlan-roberts** [comment] 2021-09-13 03:29
> Ignoring the whole ClosedChannelException is a bit too much for me, is there any safety check I can add to make sure that ClosedChannelException is thrown because of the client's side in this case?

Not sure what you mean by this. Jetty is just calling `onWebSocketError` to notify you of the read error caused by the client closing the connection without completing the close handshake. Nothing you can do about this on the server side.

If you initiate the WebSocket close handshake from the client side in JavaScript you should not have the same issues. It seems firefox handles this case better and completes the close handshake.

So instead of sending "goodbye" as a text message and having the server initiate the close, you should have the JavaScript code on the browser do something like:
```javascript
wscon.close(1000, 'goodbye')
```

**Comment by thanhvg** [comment] 2021-09-13 03:46
Well I can't change how the clients behave but please correct me if I am wrong: is `ClosedChannelException` is safe to ignore across jetty websocket server? I need to log out errors for my app and if `ClosedChannelException` is benign then I can filter it out.

**Comment by lachlan-roberts** [comment] 2021-09-13 04:20
It could be that the client was going to send more messages but the connection failed, so I think how you handle it depends on your application.

**Comment by joakime** [comment] 2021-09-13 11:16
Firefox has 3 open issues regarding their websocket close wasClean=true behavior

* https://bugzilla.mozilla.org/show_bug.cgi?id=1370760
* https://bugzilla.mozilla.org/show_bug.cgi?id=1412104
* https://bugzilla.mozilla.org/show_bug.cgi?id=1426815

**Closed as completed** 2021-09-13 14:40 UTC
