### ISSUE TITLE
When WriteListener.onWritePossible() blocks, the AsyncContext never time out.

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#1035] opened 2016-10-26 14:05 UTC
This is related to this news-list post: https://dev.eclipse.org/mhonarc/lists/jetty-users/msg07332.html

When a call inside the WriteListener.onWritePossible() blocks, the AsyncContext hand forever and AsyncListener.onTimeout is never called, see example: https://github.com/laeubi/jetty_test_issues/blob/master/jetty.test.issues/src/jetty/async/test/BlockingTimeoutWriteListenerServlet.java

What happens:
 Browser is blocked forever, onTimeout is never called

What is expected:
 AsyncListener.onTimeout is called
 AsyncListener.onError might be called
 the request to the client is aborted
 maybe the Thread executing WriteListener.onWritePossible() is interrupted

Even though this example is rather malicious in a real-world example the gathering of data might block (e.g. reading from another stream, fetching from a queue) and you still want a timeout to happen.

**Comment by joakime** [comment] 2018-03-19 17:24
@gregw @sbordet any thoughts on this one?

**Comment by sbordet** [comment] 2018-03-21 10:40
@gregw `onWritePossible()` is considered a dispatch so that the idle timeout mechanism should not fire (right?), and my understanding is that `AsyncContext.timeout` only fires in `ASYNC_WAIT`, so the behavior reported is expected.
Do you recall what the specification says about this, if anything ?

**Comment by gregw** [comment] 2018-03-21 11:12
I think the spec is not precise about this, but generally there are no timeouts while a thread is dispatched... simply because there is no mechanism to interrupt the thread and we cannot call onError in parallel.

So the expected behaviour is that if the application blocks in any dispatches, then it blocks and there are no timeouts.

**Comment by laeubi** [comment] 2018-03-21 11:20
Why can't the thread be interrupted with Thread#interrupt()? This would (if the implementor responds to Thread interruption nicely) allow to break out (e.g. if there is a Thread.sleep() or Object.wait.call() and so on...)

**Comment by sbordet** [comment] 2018-03-21 15:11
@laeubi we cannot interrupt threads _hoping_ that the user code is written well enough to handle the case.
In some cases it's impossible to even implement cooperative thread interruption.

The application code has made a decision to use the Servlet 3.1 non-blocking I/O APIs, so if then blocks indefinitely inside them it's a decision that goes against the initial decision to be fully non-blocking.
If the use of blocking APIs cannot be avoided, then it's the application that needs to arrange for timeouts and possibly interrupt blocking operations.

Closing the issue as this is expected behavior.

**Closed by sbordet** 2018-03-21 15:11 UTC

**Comment by laeubi** [comment] 2018-03-21 15:54
@sbordet I just think it would be nice to signal the thread that it should have been running to long.
Beside that, it would be good to at least close the I/O connection to the client (so the client does not hand infinity).
The problem is, that the code then needs to do its own timeout handling instead of doing some stuff to stop what is done.

**Comment by sbordet** [comment] 2018-03-21 16:16
The servlet specification does not allow us to notify the application via another callback, nor to close the I/O connection to the client. As such we cannot do timeouts on behalf of the application.

**Comment by laeubi** [comment] 2018-03-21 16:31
Thanks for the clarification!
