### ISSUE TITLE
Add Junit test for HTTP3 client-server using custom trustStore

### ISSUE THREAD

**Issue by jhkst** [eclipse/jetty.project#9527] opened 2023-03-22 14:54 UTC
**Jetty version(s)**
11.0.14

**Enhancement Description**
The current [JUnit test for HTTP3 client-server communication](https://github.com/eclipse/jetty.project/blob/574ad3b4daacf0d992f40ab780f2425ecbbac7bb/jetty-http3/http3-tests/src/test/java/org/eclipse/jetty/http3/tests/AbstractClientServerTest.java#L92) uses `setVerifyPeerCertificates(false);` so verification test against custom trustStore is not tested.
I was not able to make it working in my project with trustStore generated from self-signed certificate so I was looking for working example (for HTTP3/QUIC) also in these tests, but found it just workarounded this way. Also didn't find anywhere else any example how to use trustStore for http/3 client.
So enhancement should be to add JUnit test with the trustStore used by HTTP3 client and add the example also to some documentation. E.g. [here](https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-client-http3)

I used these commands to create truststore:
```
keytool -exportcert -noprompt -rfc -alias mykey -file trust.crt -keystore keystore.p12 -storepass storepwd -storetype pkcs12 
keytool -importcert -noprompt -alias mykey -file trust.crt -keypass storepwd -keystore truststore.p12 -storepass storepwd -storetype pkcs12
```

**Comment by lorban** [comment] 2023-05-16 13:55
Duplicate of #9397

**Closed as not planned by lorban** 2023-05-16 13:55 UTC
Labels: Enhancement
