### ISSUE TITLE
Request.getPart() that results in Exception still allows other parts to be fetched.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#82] opened 2016-02-16 11:38 UTC
Seen in comment on stackoverflow http://stackoverflow.com/questions/35413971/spring-boot-jetty-catch-upload-error-file-too-big

> I'm not certain, but I think this may be a bug in Jetty. With Tomcat, a MultipartException is thrown by Spring MVC from within DispatcherServlet.checkMultipart. This method accesses all of the request's parts. Tomcat throws an exception when one of the parts is too big, triggering the MultipartException. Jetty, on the other hand, allows Spring MVC to retrieve all of the request parts, even when one of them exceeds the maximum size. It then fails later on when a second attempt is made to access the request's parts but it's too late for Spring MVC to throw a MultipartException.

This seems like it might be a behavioral bug.

**Comment by janbartel** [comment] 2016-02-16 16:00
I made some comments over on issue #81 that are relevant here.

Note that jetty is never going to throw the spring MultipartException, however we could throw the spec-compliant IOException or ServletException.

**Comment by janbartel** [comment] 2016-02-16 16:47
Assuming my understanding of the issue is correct as per comments on #81, I've pushed a fix to the jetty-9.3.x branch: 11d3448

If you'd like to test it out, that would be great.

**Closed by janbartel** 2016-02-16 16:47 UTC
