### ISSUE TITLE
URIUtil.canonicalPath incorrectly handles some paths with query parameters containing '../'

### ISSUE THREAD

**Issue by ontology-rory** [eclipse/jetty.project#1884] opened 2017-10-10 14:42 UTC
See #1079 testing the fix in 9.4.7

The fix works for URLs of the form "/install?23=..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd"
but fails for URLs of the form "/some/install?23=..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd"

The culprit seems to be in org.eclipse.jetty.server.Response at line 709

```
                location=URIUtil.canonicalEncodedPath(URIUtil.addEncodedPaths(parent,location));
                if (!location.startsWith("/")) // <= this is coming out as null following the fix
                    buf.append('/');
            }

            if(location==null)
                throw new IllegalStateException("path cannot be above root");
            buf.append(location);
```

there is a null check further on but not when the trouble starts at L709

**Comment by joakime** [comment] 2017-10-10 14:48
I think that canonicalPath doesn't touch the query portion.

The Request.getParameter* methods and RequestDispatch parameter merging on the other hand ...

**Comment by ontology-rory** [comment] 2017-10-10 14:57
Here's the stack

```
java.lang.NullPointerException
	at org.eclipse.jetty.server.Response.sendRedirect(Response.java:709)
	at org.eclipse.jetty.server.Response.sendRedirect(Response.java:729)
	at org.apache.wicket.protocol.http.servlet.ServletWebResponse.sendRedirect(ServletWebResponse.java:289)
	at org.apache.wicket.protocol.http.BufferedWebResponse$SendRedirectAction.invoke(BufferedWebResponse.java:409)
	at org.apache.wicket.protocol.http.BufferedWebResponse.writeTo(BufferedWebResponse.java:602)
	at org.apache.wicket.protocol.http.HeaderBufferingWebResponse.stopBuffering(HeaderBufferingWebResponse.java:60)
	at org.apache.wicket.protocol.http.HeaderBufferingWebResponse.flush(HeaderBufferingWebResponse.java:97)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
```

**Comment by sbordet** [comment] 2017-10-10 15:01
Duplicate of #1865.

**Closed by sbordet** 2017-10-10 15:01 UTC

**Comment by joakime** [comment] 2017-10-10 15:22
@sbordet you sure that #1865 is the duplicate?  The OP here never mentioned a NPE.

**Comment by ontology-rory** [comment] 2017-10-10 15:25
It does look the same - sorry for not checking existing bugs first

**Comment by joakime** [comment] 2017-10-10 15:26
no worries, that's why "Duplicate" exists.
