### ISSUE TITLE
Bundle org.eclipse.jetty.http.spi not available via p2 repository

### ISSUE THREAD

**Issue by Boereck** [eclipse/jetty.project#700] opened 2016-07-08 08:56 UTC
Hi,
The bundle "org.eclipse.jetty.http.spi" is available via maven central (ID "jetty-http-spi"), but not via the p2 update sites at http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/. This causes pains when using plain Eclipse projects (and target platform) with build via maven Tycho. Is there a reason for this or was it simply forgotten to be included? Or is there a different p2 repository available where to load the bundle?

Thanks,
Max

**Comment by janbartel** [comment] 2016-08-11 04:44
@Boereck we've never actually released that as a bundle in p2: we only put the minimum number of jetty bundles into p2 as necessary to run jetty as a server.

In fact, we had discussed  removing the jetty-http-spi project as we thought nobody was using it.  So I can't really see us adding in this bundle to our p2 setup, at least not as a high priority. 

The repo with our p2 setup in it is over here: https://git.eclipse.org/c/jetty/org.eclipse.jetty.releng.bundles.git/.

If you wanted to take a look at it and submit some diffs for including jetty-http-spi then I'd certainly take a look at it.

cheers

**Comment by Boereck** [comment] 2016-08-11 14:41
Well, I tried to use the bundle and found more problems with the bundle than it missing from the p2 repo. It does not implement HTTPS for example. I thought this might help me get around fact that the JAX-WS implementation shipped Oracle JVM not supporting HTTPS, so the reason for exchanging. In the end I found a way to enable HTTPS support, by using a similar configuration as described [here](https://alesaudate.wordpress.com/2010/12/08/how-to-develop-a-standalone-ssl-web-service/).

Besides this, it is **extremely** hard to teach the JVM the alternative implementation of HttpServer from within an OSGi bundle. The implementation can either be defined via a system property or via ServiceLoader. Both ways do not seem to work, since the JVM cannot access the classes loaded via OSGi. I even tried to use [SPI Fly](http://aries.apache.org/modules/spi-fly.html) to enable loading via ServiceLoader, but this failed, too.

This is a bit sad, because we use Jetty from OSGi anyway. So it would have been nice to use the JAX-WS endpoint API with Jetty under the covers. But I think in this state would not be wise to include the org.eclipse.jetty.http.spi bundle in the p2 update site anyway. And I am not sure if there is any practical way to get the project working in an OSGi based environment.

**Comment by janbartel** [comment] 2016-08-12 01:50
@Boereck  oops, looks like we forgot to put the appropriate osgi headers into the manifest that would allow the jetty-http-spi stuff to be seen with a ServiceLoader in osgi container.

I've made the change to jetty-9.3.x, jetty-9.4.x and master branches. I think our ci system should spit out some rebuilt jars soon into the snapshot repo at https://oss.sonatype.org/content/repositories/jetty-snapshots.

Can you have another go with the new jar, with the correct headers in place?

**Comment by janbartel** [comment] 2017-04-19 04:14
I am going to close this issue. The appropriate headers should now be in the manifest to allow jetty-http-spi to be discovered by a serviceloader mechanism (eg SpiFly).

As mentioned previously, I can't really see us adding this to the p2 repo, but after the issue is closed, if there is demand for it, then by all means reopen the issue and start the pleading :)

**Closed by janbartel** 2017-04-19 04:14 UTC
