### ISSUE TITLE
Automatic-Module-Name header needed for Java 9

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1873] opened 2017-10-06 15:21 UTC
See discussion about this on cross-project-issues-dev ...
https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg14888.html

**Comment by joakime** [comment] 2017-10-09 16:19
Since we create `META-INF/MANIFEST.MF` entries for OSGi, we should also be careful to add the `Automatic-Module-Name` header that Java 9 uses.

The OSGI `Bundle-SymbolicName` header and the Java 9 `Automatic-Module-Name` header have the same meaning, and when the 2 systems co-exist, this meaning should be kept in sync.

See the cross-project-issues-dev discussion on this topic from the first comment.

**Comment by sbordet** [comment] 2018-04-17 16:28
Duplicate of #2127.

**Closed by sbordet** 2018-04-17 16:28 UTC
Labels: Build
