### ISSUE TITLE
Spin in HttpInputOverHttp.blockForContent with malformed HTTP-Request

### ISSUE THREAD

**Issue by wpedot** [eclipse/jetty.project#525] opened 2016-04-26 14:05 UTC
Since upgrading to Jetty9 (embedded in equinox framework) I noticed (very rare) spikes in CPU-Usage caused by Jetty pool-threads, the only way to get rid of those threads is to terminate them with (deprecated) Thread.stop. After yet another such spike I now took the time to investigate this further, here are my findings:

The affected threads appearantly loop in HttpInputOverHttp.blockForContent, there never is any more content and isFinished does not return true .

The root-cause seems to be a malformed HTTP-Post with chunked transfer-encoding, more specifically an invalid chunk-length. This triggers a NumberFormatException which in combination with a servlet that tries to read from Request.inputStream after said exception causes the read-call to loop. I have tested this with 9.2.13 and 9.3.8. The affected servlet in my application is CXF but I was able to reproduce the issue with a skeleton-servlet as well.

Create a servlet with a doPost-method like this

<pre>
protected void doPost(HttpServletRequest request, HttpServletResponse response)  {
    try {
        request.getInputStream().read();
    } catch (Exception e) {
        try {
             // this read-call will block
            request.getInputStream().read();
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }
}
</pre>

And send a post-request like this:

<pre>
POST /testservlet HTTP/1.1
Host: localhost
Transfer-Encoding: chunked

x

</pre>

"x" is not a valid hex-digit and therefor not a valid chunk-length.
You should get an error like this in the log

<pre>
org.eclipse.jetty.http.HttpParser  - parse exception: java.lang.NumberFormatException: !hex 120 in CHUNKED_CONTENT for HttpChannelOverHttp@573efd0c{r=1,c=false,a=DISPATCHED,uri=//localhost/testservlet}
</pre>

and see a busy CPU-core and also some heap-churn.

Can you reproduce this as well?

**Comment by joakime** [comment] 2016-04-26 21:22
Why are you reading from a failed InputStream?

**Comment by joakime** [comment] 2016-04-26 21:34
Added a testcase for this, hoping to trigger the spin-loop.
Doesn't happen.

There are a few exceptions seen though ...

```
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

2016-04-26 14:29:19.113:INFO::main: Logging initialized @190ms
2016-04-26 14:29:19.162:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2016-04-26 14:29:19.185:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@762efe5d{/,null,AVAILABLE}
2016-04-26 14:29:19.187:INFO:oejs.AbstractConnector:main: Started LocalConnector@5d22bbb7{HTTP/1.1,[http/1.1]}
2016-04-26 14:29:19.187:INFO:oejs.Server:main: Started @265ms
2016-04-26 14:29:19.260:WARN:oejh.HttpParser:qtp1313953385-11: parse exception: java.lang.NumberFormatException: !hex 120 in CHUNKED_CONTENT for HttpChannelOverHttp@7ce26e3c{r=1,c=false,a=DISPATCHED,uri=//localhost/post}
2016-04-26 14:29:19.261:WARN:oejs.ServletHandler:qtp1313953385-11: 
java.lang.IllegalStateException: Request in context!
	at org.eclipse.jetty.server.Request.recycle(Request.java:1777)
	at org.eclipse.jetty.server.HttpChannel.recycle(HttpChannel.java:263)
	at org.eclipse.jetty.server.HttpChannelOverHttp.recycle(HttpChannelOverHttp.java:82)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:421)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.onBadMessage(HttpChannel.java:671)
	at org.eclipse.jetty.server.HttpChannelOverHttp.badMessage(HttpChannelOverHttp.java:257)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1429)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:353)
	at org.eclipse.jetty.server.HttpConnection.fillAndParseForContent(HttpConnection.java:288)
	at org.eclipse.jetty.server.HttpInputOverHTTP.produceContent(HttpInputOverHTTP.java:33)
	at org.eclipse.jetty.server.HttpInput.nextContent(HttpInput.java:186)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:145)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:129)
	at org.eclipse.jetty.servlet.PostServletTest$BasicReadPostServlet.doPost(PostServletTest.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:330)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ByteArrayEndPoint$1.run(ByteArrayEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
2016-04-26 14:29:19.268:WARN:oejs.HttpChannel:qtp1313953385-11: null
java.io.IOException: org.eclipse.jetty.http.BadMessageException: 500: No version
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:173)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:441)
	at org.eclipse.jetty.util.ByteArrayISO8859Writer.writeTo(ByteArrayISO8859Writer.java:109)
	at org.eclipse.jetty.server.Response.sendError(Response.java:605)
	at org.eclipse.jetty.server.Response.sendError(Response.java:511)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:650)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:330)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ByteArrayEndPoint$1.run(ByteArrayEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.eclipse.jetty.http.BadMessageException: 500: No version
	at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:348)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:690)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:521)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:690)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:744)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:441)
	at org.eclipse.jetty.util.ByteArrayISO8859Writer.writeTo(ByteArrayISO8859Writer.java:109)
	at org.eclipse.jetty.server.Response.sendError(Response.java:605)
	at org.eclipse.jetty.server.Response.sendError(Response.java:511)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:650)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:330)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ByteArrayEndPoint$1.run(ByteArrayEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

The first `read()` call triggers the `java.lang.IllegalStateException: Request in context!` error.

**Comment by wpedot** [comment] 2016-04-27 07:00
I have not yet checked why exactly the CXF-Servlet is reading after the exception, it is used to provide a SOAP webservice and wants to convert all exceptions into a SOAP-fault to send to the client.

As to reproducing:

The first read throws the IllegalStateException for me as well but I do not get the following ones you posted,
I use putty in RAW-Mode as "HTTP-Client" in my tests and there is one more detail I did not realize:

If I just paste the short invalid POST request and do nothing more I get a timeout after 30sec and all is fine, however if I send some more content (eg pressing ENTER) the threads starts looping and there is no more timeout. Even when the socket is closed there are no more exceptions.

I can also trigger this by sending a larger amount of data, my guess is that there has to be more data than some internal buffer-size (8k?) so that there is still something to read for the second call.

**Comment by wpedot** [comment] 2016-04-27 07:26
I should also add that my investigations were done with 9.2.13/15. I only verified that the same thing happens with 9.3.8 but did not check out the sources to narrow down where the looping happens. The source seems to have changed a lot in those areas...

**Comment by gregw** [comment] 2016-04-27 07:40
Well even without the looping, it is a bug in 9.3.x as the original onBadMessage callback is not well handled as it tries to generate a 400 response when already dispatched to a servlet.

So I'll fix that first in 9.3.x.... and then will see if I can repro the loop in 9.2.x

So did you see 100% CPU in 9.3.x?

**Comment by wpedot** [comment] 2016-04-27 08:33
Yes I do, but there seems to be more than one thread involved in 9.3.8.
It is possible to break the loop by interrupting the thread that made the read-call in 9.3.8 so it does spend some time in a wait-operation (HttpInput.blockForContent on _inputQ). The CPU-Usage is still high because there is another thread calling HttpInput.unblock all the time. If I suspend that thread in the debugger I get a timeout-exception after 30sec.

I have attached 2 Stacktraces, thread-72 is the one that called doPost in my servlet, thread-68 is the one calling HttpInput.unblock. I can interrupt thread-72 in this example to get rid of the CPU-Usage.

![thread1](https://cloud.githubusercontent.com/assets/18680768/14846155/8cbc5ce0-0c62-11e6-9201-bedb6bc2623e.PNG)
![thread2](https://cloud.githubusercontent.com/assets/18680768/14846162/91c452f6-0c62-11e6-926d-b168425feb81.PNG)

**Comment by gregw** [comment] 2016-04-27 09:01
I've pushed a fix to improve the way we handle the bad message during a dispatch.  However, I was not able to reproduce the 100% CPU, so I can't say if it will fix it or not.   Can you give it a test?

**Comment by wpedot** [comment] 2016-04-27 09:31
Not right away but I´ll look into that. Have you tested with 9.3.8, 9.2.15 or 9.3.snapshot?

Here is a log-snippet with debug enabled, this is running 9.3.8 on Windows 64bit Java 1.8.0_66 and posting >8k of garbage. 

[8k_log.txt](https://github.com/eclipse/jetty.project/files/238344/8k_log.txt)

This second log shows what happens when there is no problem (only posting ~1k of garbage) and there is a timeout.

[1k_log.txt](https://github.com/eclipse/jetty.project/files/238345/1k_log.txt)

**Comment by gregw** [comment] 2016-05-04 02:04
@wpedot any chance you can trace through [this method](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java#L181-L190) while reproducing the spin?   I still can't produce to spin, but can see maaaaybe that we could spin here... specifically if the blocker things we are not finished, but isFinished returns true, so produceContent is never called to read the -1?

I can't see how we can get there, but we could perhaps spin if we did... so I'll look at being more defensive here if you can confirm/deny this is the spin you are seeing.

**Comment by wpedot** [comment] 2016-05-04 08:43
Do you want me to check 9.2.15 or 9.3.8?
Here is what happens with 9.3.8:

<pre>
pollContent returns null (_inputQ is empty)
isFinished returns false (_state is STREAM)
produceContent gets called
  HttpConnection.fillAndParseForContent gets called
    _parser.inContentState returns false (HttpParser._state is CLOSE)
  fillAndParseForContent returns
produceContent returns
pollContent returns null again (_inputQ is empty)
return null
</pre>

As far as I can see none of the called methods actually does anything in this case.
I tried modifying HttpParser._state to EOF_CONTENT so that inContentState returns true and that broke the loop.

Will check out 9.2.15/16 as well

**Comment by wpedot** [comment] 2016-05-04 10:44
What happens on the second read-call in your tests? The first read-call triggers HttpParser.setState(CLOSE) in my case and the second read ultimately leads to HttpInput.blockForContent. If the request has only little content (I use a few hundred bytes) there is no call to HttpInput.unblock and the request ultimately times out. If I post a large enough request (>8k) there are constant calls to HttpInput.unblock and that causes the second read to loop because there is no more content to be read.

![first_read](https://cloud.githubusercontent.com/assets/18680768/15012050/c4507edc-11f5-11e6-82bb-d2142ab669c7.PNG)
![second_read](https://cloud.githubusercontent.com/assets/18680768/15012051/c4541e20-11f5-11e6-95f9-67f9643faff6.PNG)

**Comment by wpedot** [comment] 2016-05-04 20:42
Looking at your test-cases it does appear that you have not yet tried posting a larger amount of data. If you send all request-data at once you need to post more data than the configured inputBufferSize (default 8k).

**Comment by gregw** [comment] 2016-05-05 03:05
@wpedot Can you be a bit more specific about the test data:

- where in the data is the bad chunk header? beginning, middle or end of the >8k?   Do you need to have read >8k before the error or to have >8k of data after the error or both?
- how big are the chunks?  specifically are any chunks larger than 8k?
- How is the data written?  all at once or bit by bit?    Are chunks written in a single write or over multiple writes?

thanks

**Comment by wpedot** [comment] 2016-05-05 05:38
I send >8k of garbage letters in one line, so its basically one huge bad chunk header. My "client" is putty in raw-mode and all the data is in one line so I can assume that the data is sent in one write. I am using a TCP-connection to send the data and the server is currently a Jetty 9.3.8.v20160314 with ServerConnector (NIO). From what I have seen on the server side the important thing is that there is still data to be read after the ByteBuffer has been cleared because of the NumberFormatException in HttpParser.parseNext, this can be achieved by sending more than fits into the buffer in the first place or sending additional content after the exception has happened.

**Comment by wpedot** [comment] 2016-05-05 06:36
I have now also tested against git branch 9.3.x and I can reproduce the issue there as well.

**Comment by wpedot** [comment] 2016-05-05 15:08
Since I was building Jetty branch 9.3.x anyway I also tried to reproduce the issue with the PostServletTest-Testcase joakime created (44fa2b0). I did not notice it at first but it differs from my servlet-skeleton in one important detail: the first read-call throws an IllegalStateException which is not an IOException and therefor the second read never takes place in this testcase. Changing the first catch-clause in doPost to "catch (Exception e)" produces the issue when I run the tests in jetty-servlet.

**Comment by gregw** [comment] 2016-05-06 07:14
@wpedot awesome! thanks!!
but now might be next week before I get a chance to look at it.

**Comment by gregw** [comment] 2016-05-06 10:33
I was able to reproduce and have checked in a fix!

**Comment by wpedot** [comment] 2016-05-09 09:29
Great, thanks! 
Will there also be a backport to 9.2.x?

**Comment by gregw** [comment] 2016-05-09 13:46
reopened to consider backport to 9.2.x.

**Closed** 2017-04-28 11:09 UTC
Labels: Bug
