### ISSUE TITLE
HttpSessionListener no longer receives sessionDestroyed() event

### ISSUE THREAD

**Issue by mikemazz** [eclipse/jetty.project#1432] opened 2017-03-28 16:03 UTC
I have recently upgraded from Jetty 9.1.4 to 9.4.x. Since the upgrade, my custom HttpSessionListener no longer receives sessionDestroyed() events. I does still get sessionCreated() events.

**Comment by janbartel** [comment] 2017-03-29 00:54
@mikemazz going to need a lot more details on your webapp and session setup. All of the usual jetty httpsessionlistener unit tests pass, and anecdotal testing with the standard jetty test webapps with most recent release of jetty-9.4 also show the sessionDestroyed methods being called.

**Comment by mikemazz** [comment] 2017-03-29 13:29
@janbartel thanks for getting back to me. Some further information. 

I am embedding a Jetty instance and therefore configuring much programmatically. Attached is my class that instantiates the Jetty server. You will see that it creates a SessionListener. The SessionListener simply implements the createSession() and destroySession() methods. 

Prior to Jetty 9.4 (9.1.5) the SessionListener was working without a problem. Once I upgraded to 9.4, only the createSession() seemed to fire.

[jettyinfo.zip](https://github.com/eclipse/jetty.project/files/879145/jettyinfo.zip)

**Comment by janbartel** [comment] 2017-03-29 22:33
@mikemazz the SessionHandler you have at the outer level is superfluous - the SessionHandler that is really being used here is the one contained within the ServletContextHandler. So put your listener onto servletHandler.getSessionHandler() and it should work.

**Comment by mikemazz** [comment] 2017-03-29 22:42
Oh, I will give that a try. 

Thank you
Mike

**Comment by janbartel** [comment] 2017-04-11 00:25
@mikemazz  haven't heard how the suggestion went, so I'm going to assume it went well and close the issue. If you still have problems, please reopen and post your latest code.

**Comment by orangecoding** [comment] 2017-04-26 12:28
@janbartel This is still an issue for me. I've upgraded dropwizard (and therefor also Jetty to 9.4.4) since then, sessionDestroyed is not being called while sessionCreated is.

Code in DropwizardApp:
  `environment.servlets().setSessionHandler(new InternalSessionHandler(sessionTimeout));`

And the sessionLister:
`public class InternalSessionHandler extends org.eclipse.jetty.server.session.SessionHandler{

  private final int sessionTimeout;

  public InternalSessionHandler(int sessionTimeoutInMinutes){
    super();
    this.sessionTimeout = sessionTimeoutInMinutes;

    this.setMaxInactiveInterval(10);

    this.addEventListener(new SessionListener());
  }
}`

10 seconds for testing

**Comment by janbartel** [comment] 2017-04-26 13:17
@orangecoding  what types are environment and environment.servlets()? If you're not seeing sessionDestroy being called - and assuming you're calling session.invalidate() -  my guess is that you don't have a ServletContextHandler in your setup:  the code for handling session invalidation iterates over all handlers in the Server instance that derive from ContextHandler, and then extract the SessionHandler from each of them.  If you post more code, my guess might improve :)

**Comment by orangecoding** [comment] 2017-04-26 13:26
This is actually a typical Dropwizard setup. It worked with the old jetty (9.3). 
servlets() is an instance of https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jetty/src/main/java/io/dropwizard/jetty/setup/ServletEnvironment.java

**Comment by janbartel** [comment] 2017-04-26 13:36
@orangecoding I'm not familiar with dropwizard apps, can you give me a small reproduction test case to use to investigate please?

**Comment by orangecoding** [comment] 2017-04-26 14:38
@janbartel Here you are. (Build from the latest test example of dropwizard)
http://www.orange-coding.net/dw_test.zip

build it with `mvn clean install -DskipTests`, afterwards go to ./target start it with `java -jar Test-1.2.0-SNAPSHOT.jar server` then point your browser to localhost:8080.

In the System.out, you'll see a CREATED (Session has been created) but no DESTROY. (Should appear after 10 seconds)

**Comment by janbartel** [comment] 2017-04-26 17:56
@orangecoding  thanks for that test case. I'm still playing around with it, but I just want to point out that a comment in the code is incorrect and may be part of the problem.

The TestSessionHandler sets the maxInactiveInterval to 10 sec, and the comment above it is:
"//10 seconds until the session should be destroyed".  That's not exactly true - when the session is actually destroyed depends on how often the scavenger thread runs, and by default it is every 10mins. As I don't see anywhere where the scavenger (controlled by the jetty HouseKeeper class) is configured, then you'd need to wait for 1 cycle of the scavenger to see the session destroyed.

**Comment by orangecoding** [comment] 2017-04-26 19:39
Interesting. Well, what is this option I set then for? Did you change this behavior cause it worked before.

Anyways, I can't see the listener is called even after 10 mins... I've created the session, then closed the browser and waited for like 20 mins. sessionDestroyed is never been called.

**Comment by janbartel** [comment] 2017-04-27 08:34
@orangecoding  yes, I think there is something incorrect going on here in jetty, just investigating now.

**Comment by janbartel** [comment] 2017-04-27 09:35
@orangecoding  ok, I see the problem.  The io.dropwizard.jetty.RoutingHandler class is an org.eclipse.jetty.server.handler.AbstractHandler  whereas it should implement the org.eclipse.jetty.server.HandlerContainer interface because it actually contains other handlers.  An AbstractHandler is a leaf and a HandlerContainer is a branch. So when we interrogate the handler tree of the Server in methods like Server.getChildHandlersByClass(Class),  the handlers inside the RoutingHandler class are invisible to jetty.  Thus, when the scavenger thread runs and asks the Server for all ContextHandlers/SessionHandlers  in order to call scavenge on all of them, we do not find the SessionHandler wrapped inside the MutableServletContextHandler which is wrapped inside the InstrumentedHandler, which is an entry in the RoutingHandler class.  

So all dropwizard needs to do to make this work is to change RoutingHandler to respect the HandlerContainer interface.

**Comment by gregw** [comment] 2017-04-27 09:40
On 27 April 2017 at 11:35, Jan Bartel <notifications@github.com> wrote:

> So all dropwizard needs to do to make this work is to change
> RoutingHandler to respect the HandlerContainer interface.
>
This will give you other benefits as well, as the HandlerContainer respects
the jetty ContainerLifecycle contract - which is used for instantiating JMX
MBeans and for doing server dumps for debug etc.




-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com

**Comment by orangecoding** [comment] 2017-04-27 10:27
Well, I'll report this to dropwizard then..?

**Comment by janbartel** [comment] 2017-04-28 07:00
Closing as related dropwizard issue has closed.

**Closed by janbartel** 2017-04-28 07:00 UTC
