### ISSUE TITLE
org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 502 Bad Gateway

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#3115] opened 2018-11-14 22:37 UTC
Version 9.4.13.v20181111

I keep on getting the following intermittent exception:

```
org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 502 Bad Gateway
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:524)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:202)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:194)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:470)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:416)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:316)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:599)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1669)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1517)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:172)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:135)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

When it occurs my code sleeps 30 seconds and tries again. Once it happens (on application startup) I keep on getting it indefinitely until I kill the process and restart. I tried enabling logging using:

```
	<logger name="org.eclipse.jetty" level="trace" additivity="false">
		<appender-ref ref="STDOUT"/>
		<appender-ref ref="FILE"/>
	</logger>
```

but annoyingly enough the error almost never occurs if logging is enabled.

If the application is getting the error endlessly, and I try connecting to the exact same URI using the Chrome plugin "Browser Websocket Client" then it works just fine. This leads me to believe the problem is on Jetty's end, not the server.

I am attaching a log file for your review. It is one of the rare times I was able to reproduce the issue with logging enabled.

[http502.zip](https://github.com/eclipse/jetty.project/files/2582914/http502.zip)

**Comment by joakime** [comment] 2018-11-14 23:18
The response is ...

```
HTTP/1.1 502 Bad Gateway
Server: awselb/2.0
Date: Wed, 14 Nov 2018 22:28:46 GMT
Content-Type: text/html
Content-Length: 138
Connection: keep-alive
Set-Cookie: AWSALB=ZJDvqN2ko0dSFxwrRL+/fLrE057+PFw30HdjyEJH1GqXI3/KSuQwpX5ZHDbjjns7tUkgomTwudm4IQa1gt18jWBPRpx3P2EdXZmZe3tC9qLRpxjtQfvs0AztMHFT; Expires=Wed, 21 Nov 2018 22:28:46 GMT; Path=/
```

Enable the ELB logs on your AWS instance and report back what the logs tell you.
There's something about the request (or more likely the response) that AWS ELB doesn't like, the ELB logs will tell us.

See: https://aws.amazon.com/premiumsupport/knowledge-center/load-balancer-http-502-errors/

**Comment by cowwoc** [comment] 2018-11-14 23:31
The chrome plugin shows the following headers (obviously some values differ as this is a different request):

```
Request URL: wss://push1.kucoin.com/endpoint?bulletToken=gak5lasC7ZKYXVL3Hu--XZ2eEQenZdDYajUslb4p1PcCuMg7hjNRzA==._-Cs8kAJJtGqj-nXdJWfQg==&format=json&resource=api
Request Method: GET
Status Code: 101 Switching Protocols
Connection: upgrade
Date: Wed, 14 Nov 2018 23:23:35 GMT
sec-websocket-accept: XgIQoFmvo/2t//jsNNFXTLATO+U=
sec-websocket-extensions: permessage-deflate
Set-Cookie: AWSALB=szSMaV7fYZB++kBkO3k52MHhKk9VyOMP/FFrR7FLmKNx2vvZuMvTP9tLdqDU/EiLiRYB94iL9eSg2T6s0AFG2W6ZgVwcEx/1SXDmu4XnDlHNC26npuNABCwJy2oS; Expires=Wed, 21 Nov 2018 23:23:35 GMT; Path=/
upgrade: websocket
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: Upgrade
Cookie: __cfduid=d83ed540e144665a09949fceba18f95be1541808357; AWSALB=H507//zbtJg5A8wgrRSOc7Ie0dMyHe30DIRt5P/M1An9cnEEr5qJFJAY8N3b/cEATUl7uE1TnCGuAFSFhi8WamundUep8vfNbFRTIWRliHG+HL6LQAhPc/9AUIyl; __cfruid=ae5e5ecb9ef64ff8d19e18f23e36d35633ee0613-1542237189
Host: push1.kucoin.com
Origin: chrome-extension://mdmlhchldhfnfnkfmljgeinlffmdgkjo
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: cxHCg0D5X5dnJheIJNF1rw==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
bulletToken: gak5lasC7ZKYXVL3Hu--XZ2eEQenZdDYajUslb4p1PcCuMg7hjNRzA==._-Cs8kAJJtGqj-nXdJWfQg==
format: json
resource: api
```

**Comment by cowwoc** [comment] 2018-11-14 23:39
@joakime I just noticed that you are looking at the wrong WebSocket connection. There are 2-3 different WebSocket connections going on in that log. You want to focus on connections to `wss://push1.kucoin.com/endpoint`

Take a look at thread `HttpClient@14d14731-22` starting at line 18268.

**Comment by cowwoc** [comment] 2018-11-14 23:48
I believe the relevant headers are:

```
Accept-Encoding: gzip
User-Agent: Jetty/9.4.13.v20181111
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 0Pq+qQfmSXPTCo4s+ZrbnQ==
Sec-WebSocket-Version: 13
Pragma: no-cache
Cache-Control: no-cache
Host: push1.kucoin.com
Cookie: __cfruid=85a72df5844b8a18e52608a616da924ed6b1344d-1542234524
```

As found on line 23400. I don't know how to interpret the rest of the log though.

**Comment by joakime** [comment] 2018-11-14 23:52
Your request headers seem to be missing some Cookies.

How do you use your `WebSocketClient.connect()` ? do you pass in any headers? or a populated request object?

Also, you seem to have `permessage-deflate` extension disabled on your client side, is the server expecting that header?
What's the deal with the `bulletToken`, `format`, and `resource` headers? are they needed?
Is the server expecting a `Origin` header? (this is a concept from the WebSocket spec RFC6455)

**Comment by cowwoc** [comment] 2018-11-15 00:02
My code invokes `websocketClient.connect(websocketListener, uri);`

I don't pass any headers or a populated request object.

I don't know about `permessage-deflate` because the server specification does not mention it but frankly their documentation sucks so the lack of mention means nothing. The thing to remember is that most of the time when I start my application the requests work just fine. So unless the `permessage-deflate` header magically turns on or off across JVM runs (which I don't expect it does) then I don't think this header is required.

The query parameters `bulletToken`, `format` and `resource` are required per https://kucoinapidocs.docs.apiary.io/#introduction/websocket/overview section 2.

No idea about the `Origin` header but as mentioned above my Jetty configuration does not change across JVM runs yet the problems either occurs 100% during a particular run, or never at all.

Do you expect any of these headers to magically get set or unset across JVM runs? Or do we expect the same request headers so long as the application (and Jetty configuration) is not modified?

**Comment by joakime** [comment] 2018-11-15 00:08
Sounds like you'll need to use a different `.connect()` signature that allows you to customize the request.

Start with [`.connect(Object websocket, URI toUri, ClientUpgradeRequest request)`](https://www.eclipse.org/jetty/javadoc/9.4.13.v20181111/org/eclipse/jetty/websocket/client/WebSocketClient.html#connect-java.lang.Object-java.net.URI-org.eclipse.jetty.websocket.client.ClientUpgradeRequest-)

You'll want to define a `ClientUpgradeRequest` instance, and use the `.header("name", "value")` arguments to see the headers you are missing (and might be required)
Might need to update / declare / set the Cookies too. (the `AWSALB` one looks important)

**Comment by joakime** [comment] 2018-11-15 01:20
Seems to work just fine.

Here's a simple example code  ...

``` java
package org.eclipse.jetty.demo;


import java.net.URI;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.api.ContentResponse;
import org.eclipse.jetty.websocket.api.RemoteEndpoint;
import org.eclipse.jetty.websocket.api.Session;
import org.eclipse.jetty.websocket.api.annotations.OnWebSocketConnect;
import org.eclipse.jetty.websocket.api.annotations.OnWebSocketMessage;
import org.eclipse.jetty.websocket.api.annotations.WebSocket;
import org.eclipse.jetty.websocket.client.ClientUpgradeRequest;
import org.eclipse.jetty.websocket.client.WebSocketClient;

public class App
{
    public static void main( String[] args ) throws Exception
    {
        HttpClient http = new HttpClient();
        http.start();

        try
        {
            ContentResponse responseContent =
                    http.newRequest("https://kitchen.kucoin.com/v1/bullet/usercenter/loginUser?protocol=websocket&encrypt=true")
                            .send();

            Gson gson = new GsonBuilder().create();
            String json = responseContent.getContentAsString();
            Map map = gson.fromJson(json, Map.class);
            Map data = (Map) map.get("data");
            String token = (String) data.get("bulletToken");
            List instanceServers = (List) data.get("instanceServers");
            String endpointUri = findWebSocketEndpoint(instanceServers);

            System.out.println("json = " + json);
            System.out.println("token = " + token);

            ClientUpgradeRequest request = new ClientUpgradeRequest();

            WebSocketClient websocket = new WebSocketClient(http);
            websocket.start();
            try
            {
                MyWebSocket myWebSocket = new MyWebSocket(gson, token);
                URI wsUri = URI.create(endpointUri + "?bulletToken=" + token + "&format=json&resource=api");

                websocket.connect(myWebSocket, wsUri, request);
                myWebSocket.await();
            }
            finally
            {
                websocket.stop();
            }
        } finally
        {
            http.stop();
        }
    }

    private static String findWebSocketEndpoint(List instanceServers)
    {
        for(int i=0; i<=instanceServers.size(); i++)
        {
            Map server = (Map) instanceServers.get(i);
            String protocol = (String) server.get("protocol");
            String userType = (String) server.get("userType");
            if("websocket".equals(protocol) && "normal".equals(userType))
            {
                String endpoint = (String) server.get("endpoint");
                return endpoint;
            }
        }
        throw new RuntimeException("Unable to find websocket endpoint");
    }

    @WebSocket
    public static class MyWebSocket
    {
        private final Gson gson;
        private final String token;

        // wait for 10 messages and then exit
        private CountDownLatch latch = new CountDownLatch(10);

        private String id;
        private Session session;
        private RemoteEndpoint remote;

        public MyWebSocket(Gson gson, String token)
        {
            this.gson = gson;
            this.token = token;
        }

        @OnWebSocketConnect
        public void onOpen(Session session)
        {
            this.session = session;
            this.remote = session.getRemote();
        }

        @OnWebSocketMessage
        public void onMessage(String msg)
        {
            System.out.println("MyWebSocket.onMessage() : " + msg);
            if(id == null)
            {
                Map ack = gson.fromJson(msg, Map.class);
                id = (String) ack.get("id");
                String subscribe = String.format("{\"id\":\"%s\", \"type\":\"subscribe\", \"topic\":\"/trade/ETH-BTC_TRADE\", \"req\":1}", id);
                System.out.println("WRITE -> " + subscribe);
                remote.sendStringByFuture(subscribe);
            }
            else
            {
                latch.countDown();
            }
        }

        public void await() throws InterruptedException
        {
            latch.await(5, TimeUnit.SECONDS);
            this.session.close();
        }
    }
}
```

results in the output ...

```
2018-11-14 19:19:38.242:INFO::main: Logging initialized @267ms to org.eclipse.jetty.util.log.StdErrLog
json = {"success":true,"code":"OK","msg":"Operation succeeded","timestamp":1542244779230,"data":{"bulletToken":"qeRIL7QPvl_xdYjHFWRhGnNLxyrGeeBD80EuBJAQozACuMg7hjNRzA==.ytlvbBETQ9kpLOGLel8UCw==","instanceServers":[{"pingInterval":40000,"endpoint":"wss://push1.kucoin.com/endpoint","protocol":"websocket","encrypt":true,"pingTimeout":60000,"userType":"normal"},{"pingInterval":40000,"endpoint":"wss://push1.kucoin.com/endpoint","protocol":"websocket","encrypt":true,"pingTimeout":60000,"userType":"vip"}],"historyServers":[{"endpoint":"https://kitchen.kucoin.com/v1/bullet/history","encrypt":true,"userType":"normal"},{"endpoint":"https://kitchen.kucoin.com/v1/bullet/history","encrypt":true,"userType":"vip"}]}}
token = qeRIL7QPvl_xdYjHFWRhGnNLxyrGeeBD80EuBJAQozACuMg7hjNRzA==.ytlvbBETQ9kpLOGLel8UCw==
MyWebSocket.onMessage() : {"id":"241599763819585536","type":"ack"}
WRITE -> {"id":"241599763819585536", "type":"subscribe", "topic":"/trade/ETH-BTC_TRADE", "req":1}
MyWebSocket.onMessage() : {"id":"241599763819585536","type":"ack"}
MyWebSocket.onMessage() : {"data":{"volume":0.0031823,"price":0.031823,"count":0.1,"action":"CANCEL","time":1542244780261,"type":"SELL"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728281059}
MyWebSocket.onMessage() : {"data":{"volume":0.00010501,"price":0.031821,"count":0.0033,"action":"ADD","time":1542244780713,"type":"SELL"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728281086}
MyWebSocket.onMessage() : {"data":{"volume":0.04745072,"price":0.031729,"count":1.4955,"action":"ADD","time":1542244780937,"type":"BUY"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728281109}
MyWebSocket.onMessage() : {"data":{"volume":0.0031822,"price":0.031822,"count":0.1,"action":"ADD","time":1542244781160,"type":"SELL"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728281137}
MyWebSocket.onMessage() : {"data":{"volume":0.0031753,"price":0.031753,"count":0.1,"action":"CANCEL","time":1542244781584,"type":"BUY"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728281196}
MyWebSocket.onMessage() : {"data":{"volume":0.0031757,"price":0.031757,"count":0.1,"action":"ADD","time":1542244782058,"type":"BUY"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728281932}
MyWebSocket.onMessage() : {"data":{"volume":0.00001303,"price":0.031776,"count":0.00041,"action":"CANCEL","time":1542244782140,"type":"SELL"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728282079}
MyWebSocket.onMessage() : {"data":{"volume":0.28469916,"price":0.03163324,"count":9.0,"action":"CANCEL","time":1542244782246,"type":"BUY"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728282090}
MyWebSocket.onMessage() : {"data":{"volume":0.1982385,"price":0.03176899,"count":6.24,"action":"CANCEL","time":1542244782839,"type":"BUY"},"topic":"/trade/ETH-BTC_TRADE","type":"message","seq":32750728282187}
```

**Comment by cowwoc** [comment] 2018-11-15 04:20
@joakime As mentioned in my initial comment, the problem is intermittent. I get it less than 10% of the time. That's what makes it annoying to troubleshoot. I was really hoping you'd spot a problem in the original log file I sent...

So as far as you can tell, the client request that leads to the HTTP 502 is valid and we have no idea why one request might trigger a HTTP 502 but not another (changing per JVM run)?

**Comment by joakime** [comment] 2018-11-15 11:22
The logs show nothing all that unusual from a client point of view.
What's more interesting and useful at this point would be the server logs.

The server is making the decision on the 502 and sending it via normal http response mechanisms.
When the server fails, pay attention to the request headers and whatnot, perhaps there's a strange quirk with encoding in the Cookie that the server doesn't like??
But without logs from the server, or more clear error messages in the response body content, you'll be in the dark as to what's the root cause.

**Comment by joakime** [comment] 2019-02-17 14:50
Closing due to lack of updates.
Will happily reopen issue if more information is presented.

**Closed by joakime** 2019-02-17 14:50 UTC
Labels: More Info Required

**Comment by cowwoc** [comment] 2019-02-17 15:12
You did the right thing. I moved on to another project and forgot about this issue.
