### ISSUE TITLE
org.eclipse.jetty.websocket.api.UpgradeException: 500 Server Error

### ISSUE THREAD

**Issue by Haimonti** [eclipse/jetty.project#3934] opened 2019-08-04 14:23 UTC
Hi,
I am trying to run jetty locally, set-up a server (http://localhost:8080) and get a client to connect to it. The client connects by a WebSocket Client via a ClientUpgradeRequest. Here is the relevant code:

public HttpClient createHttpClient()
    {
	HttpClient httpClient = new HttpClient();
        return httpClient;
}

public WebSocketClient createWebSocketClient() 
    {
      return new WebSocketClient(this.httpClient);
    }

Later: 

ClientUpgradeRequest request = new ClientUpgradeRequest();
// Attempt connection
URI uri = URI.create("ws://localhost:8080/echo");
Future<Session> future = webSocketClient.connect(clientSocket,uri,request);
// Wait for Connect
Session session = future.get();
// Send a message
session.getRemote().sendString(message);
// Close session
session.close();

I keep getting the following error:
**org.eclipse.jetty.servlet.ServletHolder$1: java.lang.ClassCastException: org.eclipse.jetty.util.DecoratedObjectFactory cannot be cast to org.eclipse.jetty.util.DecoratedObjectFactory**
    at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable (ServletHolder.java:630)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet (ServletHolder.java:682)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet (ServletHolder.java:520)
    at org.eclipse.jetty.servlet.ServletHolder.prepare (ServletHolder.java:811)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:537)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:255)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:1700)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1345)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:480)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:1667)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1247)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle (Server.java:505)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:370)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:267)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run (ChannelEndPoint.java:117)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:698)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:804)
    at java.lang.Thread.run (Thread.java:748)
java.util.concurrent.ExecutionException: org.eclipse.jetty.websocket.api.UpgradeException: 500 Server Error
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at interContILP.SendServlet.sendMessageOverWebSocket(SendServlet.java:239)
	at interContILP.SendServlet.doGet(SendServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at **org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)**
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)

The request header looks like this:
Request URL: http://localhost:8080/send?message=
Request Method: GET
Status Code: 302 Found
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
Content-Length: 0
Date: Sun, 04 Aug 2019 14:12:38 GMT
Location: http://localhost:8080/
Server: Jetty(9.4.2.v20170220)

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: JSESSIONID=node04etx0tm9kadcuzuztesnwgj70.node0
DNT: 1
Host: localhost:8080
Referer: http://localhost:8080/index.jsp
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36

Any suggestions on how to resolve this would be really appreciated.

**Comment by lachlan-roberts** [comment] 2019-08-22 07:48
@Haimonti take a look at your `WEB-INF/lib` to see if you have jetty server jars there, seems likely that would be the problem

see similar issue #3827

**Comment by lachlan-roberts** [comment] 2019-09-26 03:11
Closing, seems to be duplicate of #3827.
If you are still having problems with this, comment and the issue can be reopened.

**Closed by lachlan-roberts** 2019-09-26 03:11 UTC
