### ISSUE TITLE
Any fixes for issue org.eclipse.jetty.io.EofException

### ISSUE THREAD

**Issue by xingbill** [eclipse/jetty.project#4464] opened 2020-01-08 14:36 UTC
**Jetty version**: 9.4.19.v20190610

**Java version**: OpenJDK Runtime Environment (Zulu 8.31.0.1-linux64) (build 1.8.0_181-b02)

**Question**:  Recently we are working to migrate our applications from Spring with Tomcat to springboot with Jetty.  We ran into issues with the exceptions below on development&production environments:  org.eclipse.jetty.io.EofException. We couldn't identify what causes this type of issues and even couldn't find ways to reproduce this issues. But we got quite number of exceptions on production environment. 

By the way, we don't have issues while our application runs on Tomcat.
Do you have any fixes on this issues.  Please provide any suggestions/comments on this issues.   Thx

**Comment by xingbill** [comment] 2020-01-08 15:18
Also stack trace attached:
2020-01-08 09:41:14,785 ERROR qtp747004588-66      .cloud.sleuth.instrument.web.TraceFilter - Uncaught exception thrown
org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:560)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:478)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:387)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1041)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:84)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.cloud.sleuth.instrument.web.TraceFilter.doFilter(TraceFilter.java:166)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at io.micrometer.spring.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:107)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.sas.commons.rest.filters.HeaderValidatorFilter.doFilter(HeaderValidatorFilter.java:77)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:238)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1578)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:369)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1143)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1131)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:318)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:256)
	at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:484)
	at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:577)
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:555)
	... 52 common frames omitted

**Comment by joakime** [comment] 2020-01-08 16:02
"Early EOF" means that the connection was terminated before all of the expected content was received.

Looks like it was attempting to read a POST form request body content and the entire form wasn't sent.

**Comment by xingbill** [comment] 2020-01-08 16:11
@joakime Thank you so much for quickly commenting on this.  Since we got so many this type of Exceptions, it kinda bothers us. 

We run both Tomcat and Jetty, we don't have the issues with Spring on Tomcat.  Any jetty settings, or Springboot to prevent this? Thx.

**Comment by joakime** [comment] 2020-01-08 16:20
The description of this issue points to a client bug currently (we really need more info)
What kind of client are you using with this server? (browser, open source http library, open source REST library, java HttpURLConnection, custom client, etc)
Do you have a project that can reproduce this that you can share with us?

As for the differences in Tomcat vs Jetty ...
Tomcat chooses to be quiet and just null out, drop, remove things that are incomplete.
Jetty chooses to let you know that you have incomplete / invalid content as that points to a critical data corruption issue.

The other scenarios (that are not client bugs) would be legit connection terminations.
Examples:
* Simple network connectivity issue.
* Browser navigating away before the request is completely sent.
* Mobile client having a network change (eg: switching from mobile to wifi)
* Mobile client having poor network quality / coverage.

But again, in those scenarios you have incomplete content at the server side, it would be critical to know that you have incomplete content. (hence the Early EOF).

**Comment by sbordet** [comment] 2020-01-08 20:08
@xingbill another option is that you have a wrong mapping for URIs, so that a URI hits the `HiddenHttpMethodFilter` when it should not.

**Comment by xingbill** [comment] 2020-01-16 18:49
@sbordet Thank for the comments.  What could be the wrong mapping for URIs? Any examples?

**Comment by sbordet** [comment] 2020-01-17 09:26
@xingbill you are hitting a URI that is mapped to a filter that uses `request.getParameters()`, so that the request content gets consumed, and later you land onto a Servlet that also tries to read the content, so it gets the `EofException`.

**Comment by flsusp** [comment] 2020-02-07 12:21
Getting the same behaviour with Spring Boot and Jetty. The error happens sporadically but only affect one artifact (it is an error on a health check endpoint that is called by the same client and in the same network for a lot of other artifacts). Trying to disable Spring's `HiddenHttpMethodFilter` here and see if the problem goes away. Do you have any other suggestions?

Versions:
org.springframework.boot:spring-boot-starter-jetty:2.0.2.RELEASE
org.eclipse.jetty:jetty-servlets:9.4.10.v20180503

**Comment by gregw** [comment] 2021-04-14 06:33
I'm closing this for now. If there is a concrete example of when we are loving this but should not, then please reopen.

**Closed as completed by gregw** 2021-04-14 06:33 UTC
Labels: Question
