### ISSUE TITLE
Issue encountered with Jetty 9.4.56 for type ID must be unique even though the type ID is unique in jetty9.xml

### ISSUE THREAD

**Issue by prasads6971** [eclipse/jetty.project#12355] opened 2024-10-09 04:42 UTC
**Jetty version(s)**
9.4.56

**Jetty Environment**

**Java version/vendor**
openjdk version "1.8.0_422"

**OS type/version**
Ubuntu 22.04.5 LTS

**Description**
In below Jetty9.xml

<Configure id="jettyServer" class="org.eclipse.jetty.server.Server">	

	<Call id="DefaultTimeZone" name="getDefault" class="java.util.TimeZone"/>
	<Ref id="DefaultTimeZone">
		<Get id="DefaultTimeZoneID" name="ID"/>
	</Ref>

	<New id="httpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
		<Set name="secureScheme">https</Set>
		<Set name="securePort"><Property name="jetty.ssl.port" default="8443" /></Set>
		<Set name="outputBufferSize">32768</Set>
		<Set name="requestHeaderSize">8192</Set>
		<Set name="responseHeaderSize">8192</Set>
	</New>

	<New id="LogStream" class="org.eclipse.jetty.util.RolloverFileOutputStream">
		<Arg>
			<SystemProperty name="jetty.home" default="/opt/logs/jetty"/>/jetty9_yyyy_MM_dd.log
		</Arg>
		<Arg type="boolean">true</Arg>
		<Arg type="int">90</Arg>
		<Arg><Ref id="DefaultTimeZone"/></Arg>
		
	</New>

	<New id="ServerLog" class="java.io.PrintStream">
		<Arg>
			<Ref id="LogStream"/>
		</Arg>
	</New>

	
	<Call class="java.lang.System" name="setErr">
		<Arg><Ref id="ServerLog"/></Arg>
	</Call>
	<Call class="java.lang.System" name="setOut">
		<Arg><Ref id="ServerLog"/></Arg>
	</Call>	

	
	
	<Set name="connectors">
	<Array type="org.eclipse.jetty.server.Connector">
	  <Item>
		<New class="org.eclipse.jetty.server.ServerConnector">
		  <Arg><Ref refid="jettyServer"/></Arg>
					<Arg name="factories">
						<Array type="org.eclipse.jetty.server.ConnectionFactory">
							<Item>
								<New class="org.eclipse.jetty.server.HttpConnectionFactory">
									<Arg name="config"><Ref refid="httpConfig" /></Arg>
								</New>
							</Item>
						</Array>
					</Arg>
          <Set name="port">9191</Set>
        </New>
      </Item>
			
		</Array>
	</Set>

	<New id="Context" class="org.eclipse.jetty.webapp.WebAppContext">
		<Set name="contextPath">/</Set>
		<Set name="resourceBase">/opt/binaries/sds/jetty</Set>
		
		<Set name="errorHandler">
			<New class="com.sds2.w3c.fsmlib.http.jetty.ErrorHandler9">
				
				<Set name="useParentLogic">false</Set>
			</New>
		</Set>
		
		<Call name="insertHandler">
			<Arg>
				<New id="RequestLog" class="org.eclipse.jetty.server.handler.RequestLogHandler">
					<Set name="requestLog">
						<New id="RequestLogImpl" class="org.eclipse.jetty.server.NCSARequestLog">
							<Set name="filename"><Property name="jetty.logs" default="/opt/logs/jetty"/>/jetty9req_yyyy_MM_dd.log</Set>
							<Set name="filenameDateFormat">yyyy_MM_dd</Set>
							<Set name="LogTimeZone">GMT</Set>
							<Set name="retainDays">90</Set>
							<Set name="append">true</Set>
						</New>
					</Set>
				</New>
			</Arg>
		</Call>
	</New>

	<Set name="handler">
		<New class="org.eclipse.jetty.server.handler.HandlerCollection">
			<Set name="handlers">
				<Array type="org.eclipse.jetty.server.Handler">
					<Item>
						<Ref refid="Context"/>
					</Item>
					<Item>
						<New id="DefaultHandler" class="org.eclipse.jetty.server.handler.DefaultHandler" />
					</Item>
				</Array>
			</Set>
		</New>
	</Set>
	<Set name="stopAtShutdown">true</Set>
</Configure>

We are getting below error:-
Wed Oct 9|10:07:42.708|D|main|EXCEPTION : org.xml.sax.SAXParseException : Attribute value "DefaultTimeZone" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.708|W|main|ERROR@ line:7 col:28 : org.xml.sax.SAXParseException; systemId: ; lineNumber: 7; columnNumber: 28; Attribute value "DefaultTimeZone" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.709|D|main|EXCEPTION : org.xml.sax.SAXParseException : Attribute value "DefaultTimeZone" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.709|W|main|ERROR@ line:25 col:35 : org.xml.sax.SAXParseException; systemId: ; lineNumber: 25; columnNumber: 35; Attribute value "DefaultTimeZone" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.709|D|main|EXCEPTION : org.xml.sax.SAXParseException : Attribute value "LogStream" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.709|W|main|ERROR@ line:31 col:25 : org.xml.sax.SAXParseException; systemId: ; lineNumber: 31; columnNumber: 25; Attribute value "LogStream" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.710|D|main|EXCEPTION : org.xml.sax.SAXParseException : Attribute value "ServerLog" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.710|W|main|ERROR@ line:37 col:29 : org.xml.sax.SAXParseException; systemId: ; lineNumber: 37; columnNumber: 29; Attribute value "ServerLog" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.710|D|main|EXCEPTION : org.xml.sax.SAXParseException : Attribute value "ServerLog" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||
Wed Oct 9|10:07:42.710|W|main|ERROR@ line:40 col:29 : org.xml.sax.SAXParseException; systemId: ; lineNumber: 40; columnNumber: 29; Attribute value "ServerLog" of type ID must be unique within the document.|org.eclipse.jetty.xml.XmlParser||

The same used to work fine with Jetty 9.4.50, it seems post upgrade, jetty has enforced some invalid type checks.

**Comment by joakime** [comment] 2024-10-09 14:29
Jetty 9 is at End of Community Support.

* #7958 
* #10485 

You should be using a supported version of Jetty, which is Jetty 12 at this point in time.
If you need to continue to use `javax.servlet` as opposed to `jakarta.servlet`, then use the `ee8` environment in Jetty 12.

Also, the error you are getting is not from Jetty, but from the JVM, your XML is not valid per standard XML rules.
There will be no further help with Jetty 9.

**Comment by joakime** [comment] 2024-10-09 14:33
Here's the Jetty 12 documentation on the Jetty XML syntax.

https://jetty.org/docs/jetty/12/operations-guide/xml/index.html#syntax-ref

**Comment by prasads6971** [comment] 2024-10-09 18:08
Hi @joakime, updated the XML. I can assure you the same XML is working seamlessly with Jetty 9.4.50.
I just wish to know, what change has been encorporated between 9.4.50 and 9.4.56 which seems to cause the above errors.

**Comment by joakime** [comment] 2024-10-09 19:34
@prasads6971 Jetty 9 community support is not available anymore.

See

* #7958 

Upgrade to a supported version of Jetty (Jetty 12) for community support.
Seek commercial support if you need to stay on Jetty 9.

That being said, your problem is not Jetty, or Jetty code, it's standard XML syntax issues as handled by the JVM, [it is clearly stated as such in your exception message](https://github.com/openjdk/jdk/blob/a45abf131be9ee52828c5db18a18847c45ae6994/src/java.xml/share/classes/com/sun/org/apache/xerces/internal/impl/msg/XMLMessages.properties#L243), and has to be address with standard XML syntax fixes for your entirely custom and non-standard `jetty9.xml` (a filename that isn't used on any version of Jetty).  The fact that your custom `jetty9.xml` worked on older versions of Jetty is just sheer luck and has nothing to do with Jetty or and changes in Jetty.

**Comment by joakime** [comment] 2024-10-09 19:35
Closing as out of community support.

If you replicate on a supported version of Jetty (Jetty 12 as of this message), this issue can be reopened.

**Closed as completed by joakime** 2024-10-09 19:35 UTC
Labels: Not a bug, Unsupported Release

**Comment by chetanlanje74** [comment] 2025-03-06 11:47
Hi @joakime , @prasads6971 @deridex 
Can you please help me out Regarding Error that we are getting when upgraded Jetty to **9.4.57.v20241219** 
`Caused by:
org.xml.sax.SAXParseException; lineNumber: 26; columnNumber: 24; Attribute value "pool" of type ID must be unique within the document.`
if i make Above id as Unique then more errors regarding other ID's **(context,plusconfig,Handlers)** Pops-up 

Please help me out how can i Fix it ..
i know that There is End of life & community support for all Jetty 9.x.x versions
Is there no way to make **jetty.xml** file work

**Comment by joakime** [comment] 2025-03-06 12:49
Your errors have nothing to do with Jetty.
The errors you have are with the JVM's XML implementation.
Your XML is breaking the fundamental rules of XML, rules that Jetty is not in control over.

If you upgrade to Jetty 12, then we can help.
We cannot help if you stay on on an End of Community Support release of Jetty.

**Comment by prasads6971** [comment] 2025-03-06 19:09
@chetanlanje74 I possibly have an answer. Since we resolved the unique id validation check issue with small change with one of the XML attributes - Ref.
if you see in the jetty.xml, that i had attached, we are using Ref with id as **<Ref id>**.
We replaced <Ref id> to <Ref refid> in all places in the jetty xml. So basically replacing **id** with **refid** within Ref attribute.
eg.

<Ref **refid**="DefaultTimeZone">
	<Get id="DefaultTimeZoneID" name="ID"/>
</Ref>

With this change, the unique id validation check was successful.

**Comment by chetanlanje74** [comment] 2025-03-07 09:02
Thanks Much !!!! @prasads6971  & @joakime :)
in Jetty 9.4.57.v20241219

Above Error is Resolved now when replaced `<Arg><Ref id="pool"/></Arg> with <Arg><Ref refid="pool"/></Arg>`
However i got another error as below ,Please give some suggestion on it --->

`Caused by: org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 64; cvc-elt.1: Cannot find the declaration of element 'Configure'.`

and code block in my Jetty.xml file is -->

```
?xml version="1.0" encoding="UTF-8"?
!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd"

!-- =============================================================== -->
!-- Configure the Jetty Server                                      -->
!--                                                                 -->
!-- Documentation of this file format can be found at:              -->
!-- http://docs.codehaus.org/display/JETTY/jetty.xml                -->
!--                                                                 -->
!-- =============================================================== -->


<Configure id="Server" class="org.eclipse.jetty.server.Server">

 <!-- =========================================================== -->
    <!-- Server Thread Pool                                          -->
    <!-- =========================================================== -->

    <Get name="ThreadPool" id="pool">
        <Set name="minThreads" type="int">10</Set>
        <Set name="maxThreads" type="int">%%zimbraHttpNumTh
```


i tried to replace **http://www.eclipse.org/jetty/configure_9_3.dtd** with `https://jetty.org/configure_9_3.dtd` 
But did not work...
