### ISSUE TITLE
Invalid: Inbound closed before receiving peer's close_notify

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#236] opened 2016-02-16 23:38 UTC
migrated from Bugzilla [#479505](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479505)
status NEW severity _normal_ in component _server_ for _9.3.x_
Reported in version _9.3.3_ on platform _PC_
Assigned to: Project Inbox

On 2015-10-11 04:11:04 -0400, Thomas Lussnig wrote:

> Maybe this bug is related to 370532 but here the problem is different.
> While working and debugging ssl events i found after BUG-473832 another
> handling error in the ssl engine. If the connection is closed normally jetty
> would receive an close_notify from the peer (this is also been send correctly).
> But in the SslConnection of jetty after an close the connection is hard closed
> without waiting for this event.
> 1) This cause an unnecessary SSLException
> 2) On the peer side it can cause an error since he write data that can not delivered.
> 
> java.lang.Throwable: fatal(80 , Inbound closed before receiving peer's close_notify: possible truncation attack?)
>   at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1555)
>   at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1533)
>   at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1463)
>   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.closeInbound(SslConnection.java:696)
>   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:532)
>   at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:315)
>   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:223)
>   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
>   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)

**Comment by oliverhausler** [comment] 2017-02-03 21:06
I believe I am seeing the same in embedded Jetty 9.4.1.v20170120.

I am sending a GET from Google App Engine's UrlFetchClient about once every 10 seconds. Most of the time all goes well, but randomly I see the following, approximately once or twice per hour:

```
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
        at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1561)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.closeInbound(SslConnection.java:828)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:645)
        at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:322)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:231)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbordet** [comment] 2017-02-07 11:01
That means that the server closed the connection without properly sending a TLS close message.
I don't think we can do something about it.

**Comment by oliverhausler** [comment] 2017-02-07 18:48
@sbordet What do you mean with "the server". Isn't Jetty controlling when a connection is closed? I am not so deep into low level TCP stuff, but would like to understand what exactly is going on, and what I can do. Is this a driver issue?

**Comment by sbordet** [comment] 2017-02-07 18:59
@oliverhausler it's not clear what is your setup. You mention Jetty 9.4.1, but I don't think that GAE is at that version. You mention tools that we are not terribly familiar with, so you have to detail _exactly_ what's going on. Reopening for you to provide those details.

**Comment by oliverhausler** [comment] 2017-02-07 19:13
@sbordet I didn't detail this well enough, sorry.

- The **client** is App Engine (also Jetty, but you are most probably right in that it won't be the latest version). But I think it plays no role in this scenario. On App Engine I see `java.io.IOException: Connection closed unexpectedly by server at URL: https://********:447/infos`, so it looks like the server closed the connection.

- The **server** (where I took the above stack trace) also runs on Jetty, here embedded Jetty 9.4.1 (I just updated to the newest version to see if the issue goes away, happened on older versions as well). The server is hosted, but something standard. There is no provider-side firewall or DDOS protection right now. We have 3 servers with distinct hardware, and it happens on all of them.

What I do to circumvent the issue: When I see above exception on App Engine, I just repeat the request immediately (no wait time) and all goes well. So I rather believe it's not a routing issue, but I can't say for sure. What I can say is the request never reaches my code.

Does this help? Any ideas what I could try to better pinpoint the issue?

**Comment by sbordet** [comment] 2017-02-09 15:42
@oliverhausler if this is reproducible, are you able to grab a network trace of this failure ?

The problem with your description and the stack trace is that the stack trace (taken on the server) says that the _client_ closed the connection.
However, the client on GAE says that the _server_ closed the connection.
The network trace will clarify who closed.

**Comment by sbordet** [comment] 2017-02-09 16:14
Typically I use `tcpdump -B 1024 -tttt`. Attach it here unless it contains private information.

**Comment by oliverhausler** [comment] 2017-02-09 16:17
Great, will do. Will take a few hours as it only occurs now and then.

**Comment by oliverhausler** [comment] 2017-02-09 18:31
I am seeing dropped packets, so I guess the log is trash. Will repeat with a larger buffer. Sorry for the delay.
```
tcpdump -B 1024 -tttt > /var/log/jetty-dump.log
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C82504 packets captured
97298 packets received by filter
14784 packets dropped by kernel
```

**Comment by oliverhausler** [comment] 2017-02-09 19:45
@sbordet I still have some dropped packets, logging again, but here is a first result and I think something happened at line 409. Hetzner is my provider. Is it possible their router interfered and both side are correct in that something in between has cut the conntection. Can you see that?

https://gist.github.com/oliverhausler/92f79193a9733578df4c18cc9044bcbe

**Comment by oliverhausler** [comment] 2017-02-09 19:52
Does that look like a DNS issue? The server has DHCP from the provider.

**Comment by sbordet** [comment] 2017-02-10 10:31
@oliverhausler can you please take the `tcpdump` in binary format using the `-w` option to save to a file ? That way I would be able to open it in WireShark. Thanks !

**Comment by oliverhausler** [comment] 2017-02-10 14:54
Here is the unedited file. I named it `.bin` as I don't know which extension wireshark needs.

[jetty-dump-binary.zip](https://github.com/eclipse/jetty.project/files/767001/jetty-dump-binary.zip)

The issue occurred at `hh:16:15.842` (client-side), this was 06:16 in Pacific time zone. The server is located in Germany. I stopped logging about 8 minutes after the issue occurred, so look at the last log for the hour.

**Comment by sbordet** [comment] 2017-02-10 15:22
I don't think you posted the right file. It only contains packets from `15:24:28.862` to `15:24:39.382`. In that interval, on port 447, I see a normal TLS 1.2 open and close, and another TLS open but then the capture ends.

**Comment by oliverhausler** [comment] 2017-02-10 15:50
oops, sorry, will do another one.

**Comment by oliverhausler** [comment] 2017-02-10 16:25
[jetty-dump-binary.zip](https://github.com/eclipse/jetty.project/files/767196/jetty-dump-binary.zip)

The issue occurred at `hh:08:46.163` (client-side), this was 08:08 in Pacific time zone. The server is located in Germany. I stopped logging about 10-15 minutes after the issue occurred, so look at the last log for the hour.

**Comment by sbordet** [comment] 2017-02-10 16:33
@oliverhausler pretty please double check the files, yes ?

I have times between `16:51:44` and `17:21:33` in this last dump.

You can name the files with extension `.pcap` and then zip it.

Load them in wireshark and tell me the packet number or at least the exact time, otherwise we are not getting to the end of this.

Cannot happen that in CET it's 8:46 and in PST it's 8:08.

**Comment by oliverhausler** [comment] 2017-02-10 17:50
The file is good: hh:08:46.163 == 08:08:46.163 PST == 17:08:46.163 CET.
So the problem occurred around 17:08:46 CET, or 1,022 secs after 16:51:44 CET.
When I open the .pcap in wireshark, I see absolute times, but 1,022 seconds in is around packet 13,921.

Does that make sense?

**Comment by joakime** [comment] 2017-06-19 19:04
@sbordet got an update?

**Comment by sbordet** [comment] 2017-07-14 16:11
Finally got again some time to look at this. The network dump shows the client sending the last data on that connection at `17:08:31.099` (packet 13757) and the server replying with data immediately after.

Then the connection goes idle for 15 seconds, and the server decides to close the connection. Do you confirm that the server is configured with a 15s idle timeout ?
When it receives the FIN from the server, the client attempts to write more data, but it's already too late.

This behavior is normal, as the server is always entitled at closing the connection at any time.

Could be that the client is not flushing the whole data, but then it would be a client bug to wait 15s before flushing buffered data.

Could be just a coincidence that the client is trying to send a request _exactly_ at the same time the server is closing the connection, and that would explain the fact that you get this issue rarely.

This is easily solvable by having the client idle timeout be less than the server idle timeout, so that the client will always use connections that are not going to be closed by the server. Say 10s on the client and 15s on the server, or similar.

Your workaround (resend the request) is ok, but I would try to tune the client idle timeout to see if the issue goes away.

Closing the issue as it is normal behavior. Thanks for providing the trace.

**Closed by sbordet** 2017-07-14 16:11 UTC
Labels: Bug

**Comment by oliverhausler** [comment] 2017-07-14 16:19
@sbordet Thank you for looking into this. I confirm the timeout is set to 15 sec on both sides. I will set the server idle timeout 5 secs higher than the client timeout, as you suggested.
