### ISSUE TITLE
Documentation on Release

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#10467] opened 2023-09-01 17:06 UTC
The HTML documentation on the last release for Jetty 12 was empty, aside from a couple of CSS files.

https://repo1.maven.org/maven2/org/eclipse/jetty/documentation/jetty-documentation/12.0.1/

Furthermore, Java 21 is a hard requirement for building the documentation on release, which should fail the build if 21 isn't running.

Lastly, when building with the JVM below, I got errors on the following page for the console output. @joakime had to build it for me to update the website. Still trying to figure out what is going on there, but we'll have to be very careful to ensure these things work on release.

https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-server-threadpool-virtual

`openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)`

**Comment by joakime** [comment] 2023-09-01 17:11
Duplicate of #10449

**Closed as not planned by joakime** 2023-09-01 17:11 UTC
Labels: Bug
