### ISSUE TITLE
HTTP2 without ALPN (bootstrap lib)

### ISSUE THREAD

**Issue by jknack** [eclipse/jetty.project#812] opened 2016-08-04 13:32 UTC
Hi,

 Will be nice if Jetty provides something similar to: [ALPNHackSSLEngine](https://github.com/undertow-io/undertow/blob/fa1fc5d60cd7b2770b191d132efcda63a4bfc347/core/src/main/java/io/undertow/protocols/ssl/ALPNHackSSLEngine.java)

 It is a hacky way to support ALPN in Java 8, but simplify distributions and deployment of Jetty powered servers.

 To be clear, I don't ask for removal of ALPN just one more alternative for Java 8.

 Thanks.

**Comment by gregw** [comment] 2016-08-04 22:19
@sbordet what do you think?

**Comment by sbordet** [comment] 2016-08-04 22:37
We already maintain 2 ways of providing ALPN support, the boot jar and the agent.
I'm not a fan of maintaining another one.

**Comment by gregw** [comment] 2016-08-04 23:14
@sbordet I see your point....   but our solution for java 9 already requires us to parse the hello frame, so I'm wondering if there is something similar we could do by reparsing/regenerating the hello response... or is that already encrypted/signed?

**Comment by sbordet** [comment] 2016-08-04 23:31
`ServerHello` is not encrypted in TLS 1.2, but it will in TLS 1.3.
However you see it, it's brittle hacks, that's the current situation with JDK 8.

The point with the Java 9 solution is that you can parse the `ClientHello`, but then you have means to communicate via API your decision to `SSLEngine`, which currently you cannot in JDK 8, hence the hacks.

Right now, if you have the right ALPN boot jar and JDK combo, you can run any version of Jetty.

With the hacked `SSLEngine`, you would be able to run only certain Jetty versions with certain JDKs, unless we completely replace the way we create and use `SSLEngine`, which is what we should do if we support `SSLEngine` backed by OpenSSL.

**Comment by sbordet** [comment] 2016-12-06 14:58
See also: jetty-project/jetty-alpn-agent#5.

**Comment by sbordet** [comment] 2017-09-26 08:49
Closing as duplicate of #215.

**Closed by sbordet** 2017-09-26 08:49 UTC
Labels: Enhancement
