### ISSUE TITLE
URISyntaxException when there are spaces in path to java.io.tmpdir

### ISSUE THREAD

**Issue by wilx** [eclipse/jetty.project#3427] opened 2019-03-05 14:44 UTC
We are experiencing `URISyntaxException` when there are spaces in path to `java.io.tmpdir`. This is OSGi application using Eclipse Equinox. 3.4.1.

Here is one call stack:

```
<init>:62, URISyntaxException (java.net)
fail:2848, URI$Parser (java.net)
checkChars:3021, URI$Parser (java.net)
parseHierarchical:3105, URI$Parser (java.net)
parse:3053, URI$Parser (java.net)
<init>:588, URI (java.net)
toURI:946, URL (java.net)
<init>:281, PathResource (org.eclipse.jetty.util.resource)
newResource:117, Resource (org.eclipse.jetty.util.resource)
newResource:97, Resource (org.eclipse.jetty.util.resource)
newResource:1938, ContextHandler (org.eclipse.jetty.server.handler)
getClassPath:546, ContextHandler (org.eclipse.jetty.server.handler)
initJspServlet:711, ServletHolder (org.eclipse.jetty.servlet)
initServlet:660, ServletHolder (org.eclipse.jetty.servlet)
getServlet:519, ServletHolder (org.eclipse.jetty.servlet)
prepare:803, ServletHolder (org.eclipse.jetty.servlet)
doHandle:530, ServletHandler (org.eclipse.jetty.servlet)
handle:146, ScopedHandler (org.eclipse.jetty.server.handler)
handle:524, SecurityHandler (org.eclipse.jetty.security)
handle:132, HandlerWrapper (org.eclipse.jetty.server.handler)
nextHandle:257, ScopedHandler (org.eclipse.jetty.server.handler)
doHandle:1595, SessionHandler (org.eclipse.jetty.server.session)
nextHandle:255, ScopedHandler (org.eclipse.jetty.server.handler)
doHandle:1317, ContextHandler (org.eclipse.jetty.server.handler)
nextScope:203, ScopedHandler (org.eclipse.jetty.server.handler)
doScope:473, ServletHandler (org.eclipse.jetty.servlet)
doScope:1564, SessionHandler (org.eclipse.jetty.server.session)
nextScope:201, ScopedHandler (org.eclipse.jetty.server.handler)
doScope:1219, ContextHandler (org.eclipse.jetty.server.handler)
handle:144, ScopedHandler (org.eclipse.jetty.server.handler)
handle:126, HandlerCollection (org.eclipse.jetty.server.handler)
handle:132, HandlerWrapper (org.eclipse.jetty.server.handler)
handle:531, Server (org.eclipse.jetty.server)
handle:352, HttpChannel (org.eclipse.jetty.server)
onFillable:260, HttpConnection (org.eclipse.jetty.server)
succeeded:281, AbstractConnection$ReadCallback (org.eclipse.jetty.io)
fillable:102, FillInterest (org.eclipse.jetty.io)
run:118, ChannelEndPoint$2 (org.eclipse.jetty.io)
runTask:333, EatWhatYouKill (org.eclipse.jetty.util.thread.strategy)
doProduce:310, EatWhatYouKill (org.eclipse.jetty.util.thread.strategy)
tryProduce:168, EatWhatYouKill (org.eclipse.jetty.util.thread.strategy)
run:126, EatWhatYouKill (org.eclipse.jetty.util.thread.strategy)
run:366, ReservedThreadExecutor$ReservedThread (org.eclipse.jetty.util.thread)
runJob:762, QueuedThreadPool (org.eclipse.jetty.util.thread)
run:680, QueuedThreadPool$2 (org.eclipse.jetty.util.thread)
run:745, Thread (java.lang)
```

The exception internals as observed during debugging look like this:

```
input = "file:/C:/Program Files/CA APM/Introscope99.99.0.landing/work/jetty-0.0.0.0-8081-WebContent-_-any-5681873938528372653.dir/tempTlds.jar"
reason = "Illegal character in path"
index = 16
```

I have seen #2575 but we are actually using the 9.4.11 version, so this seems like similar but different issue.

**Comment by joakime** [comment] 2019-03-05 16:53
The URLClassLoader being handed to Jetty by OSGi contains bad entries, hence the error you are seeing.

It's impossible to correctly convert that bad URL to a proper URL, just like #2575 points out.

If the URLClassLoader is correctly created by OSGi then this isn't an issue for Jetty.
Both Issue #2575 points that out, and so does the testcase in commit 0bccaf02468629d9179254680983ba31581dbc39.

Sorry, this isn't a Jetty issue, this is an Eclipse Equinox issue.

On a side note, you *really* don't want a large `java.io.tmpdir` path like that on a Windows OS machine, that will cause other problems for you related to maximum path limits present on Windows.  Try to keep your `java.io.tmpdir` fully qualified path to under 8 characters or less.

**Comment by joakime** [comment] 2019-03-21 19:24
@wilx this needs to be fixed at Eclipse Equinox to produce a URLClassloader that contains properly escaped URL entries.
There's no fix that Jetty can do that will work reliably.

Closing this issue, considering it a duplicate of #2575

**Closed by joakime** 2019-03-21 19:24 UTC
