### ISSUE TITLE
Jetty 9x doesn't follow J2EE spec when a @WebListener is explicitly referenced in the webapp descriptor

### ISSUE THREAD

**Issue by arkanovicz** [eclipse/jetty.project#2754] opened 2018-08-01 10:16 UTC
Jetty version: 9.4.10.v20180503

Let say I have a `@WebListener` class, which is also explicitly referenced in a `<listener>` section of my webapp decriptor.

The J2EE specification states that in this case, the descriptor takes precedence. But Jetty's behavior is to instantiate **twice** the web listener.

The use case is as follow:

- I cannot use `metadata-complete="true"` since I'm relying on J2EE annotations for other objects.
- I have to list the listeners in my descriptor to ensure a proper order of initialization.

**Comment by janbartel** [comment] 2018-08-02 07:25
Just to be clear, the OP's complaint is about listener **instantiation** - jetty will never start more than 1 instance of a listener for the same class.

The problem is in the annotation handling - we eagerly create an instance of the listener before checking if one already exists, and then throw away the newly created one if it does. Easy to fix.

**Comment by janbartel** [comment] 2018-08-08 21:35
Fix for eager instantiation checked in for next 9.4.x.

**Closed by janbartel** 2018-08-08 21:35 UTC
Labels: Specification
