### ISSUE TITLE
Problem with capturing response (buffering)

### ISSUE THREAD

**Issue by hareve** [eclipse/jetty.project#4586] opened 2020-02-18 11:31 UTC
**9.4.25.v20191220 (and newer)**

**openjdk version "11.0.6" 2020-01-14**

**Linux/CentOS 8**

**
PR #4409 (Jetty 9.4.x 4331 async close complete3) broke the ability to modify responses through capturing the response and writing it when done (as per https://docs.oracle.com/javaee/6/tutorial/doc/bnagb.html#bnagd). When trying to write output to the request when accessing / you will get "EOF"-exception (it does however work on requests to other resources).

Let me know if you need a code example.
**

**Comment by gregw** [comment] 2020-02-18 12:59
I think this is a duplicate of the already fixed for next release #4533 
It would be great if you could test a SNAPSHOT to confirm.

**Closed as completed** 2020-02-27 17:13 UTC
Labels: Duplicate
