### ISSUE TITLE
Jetty Close connection before Client receives full response (specific case)

### ISSUE THREAD

**Issue by krutsko** [eclipse/jetty.project#1848] opened 2017-09-26 16:19 UTC
Hello, Team

During migration from Jetty 9.2.x to 9.4.2.v20170220, I have noticed that newer version of Jetty close the connection when the Client did not receive a complete response payload. 

Criterias to reproduce:
- Jetty SO_LINGER > 0;
- Client send "Connection:close" header;
- Large response payload (~ few Mb);

It was working fine with Jetty 9.2. Was it changed on purpose? Or it's a regression ?
Please advice.

Here some code to check:
```
public static void main(String[] args) throws Exception {
        Server server = new Server();
        final ServerConnector connector = new ServerConnector(server,
                Executors.newFixedThreadPool(10),
                new ScheduledExecutorScheduler(),
                new ArrayByteBufferPool(),
                2,
                2,
                new HttpConnectionFactory());
        connector.setPort(8005);
        //connector.setSoLingerTime(1); // change it here
        connector.setName("default");
        server.addConnector(connector);
        server.setHandler(new AbstractHandler() {

            @Override
            public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
                response.setStatus(HttpServletResponse.SC_OK);
                byte[] chars = new byte[5_000_000];
                response.getOutputStream().write("stating... \n".getBytes());
                response.getOutputStream().write(chars);
                response.getOutputStream().write("\n the end".getBytes());
                baseRequest.setHandled(true);
            }
        });
        server.start();
    }
```

Result with SO_LINGER > 0:

```
curl -v -H "Connection:close" http://localhost:8005
* Rebuilt URL to: http://localhost:8005/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8005 (#0)
> GET / HTTP/1.1
> Host: localhost:8005
> User-Agent: curl/7.54.0
> Accept: */*
> Connection:close
>
< HTTP/1.1 200 OK
< Connection: close
< Date: Tue, 26 Sep 2017 16:05:27 GMT
< Server: Jetty(9.4.2.v20170220)
<
stating...
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

With disabled SO_LINGER:
```
sergey$ curl -v -H "Connection:close" http://localhost:8005
* Rebuilt URL to: http://localhost:8005/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8005 (#0)
> GET / HTTP/1.1
> Host: localhost:8005
> User-Agent: curl/7.54.0
> Accept: */*
> Connection:close
>
< HTTP/1.1 200 OK
< Connection: close
< Date: Tue, 26 Sep 2017 16:15:17 GMT
< Server: Jetty(9.4.2.v20170220)
<
stating...

* Closing connection 0
 the end
```

**Comment by sbordet** [comment] 2017-09-26 16:42
What exact Jetty version ?

**Comment by joakime** [comment] 2017-09-26 16:43
@sbordet his headers say `Jetty(9.4.2.v20170220)`

**Comment by joakime** [comment] 2017-09-26 16:45
Not reproducible in Jetty 9.4.3 ...

But only if you add `response.setContentType("application/octet-stream");` as curl attempts to process the response as text without it, which is 5MB of nulls in the testcase.

SO_LINGER = 1;

``` plain
$ curl -v -H "Connection:close" http://localhost:8005
* Rebuilt URL to: http://localhost:8005/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8005 (#0)
> GET / HTTP/1.1
> Host: localhost:8005
> User-Agent: curl/7.47.0
> Accept: */*
> Connection:close
>
< HTTP/1.1 200 OK
< Connection: close
< Date: Tue, 26 Sep 2017 16:41:26 GMT
< Content-Type: application/octet-stream
< Server: Jetty(9.4.3.v20170317)
<
stating...

* Closing connection 0
 the end
```

**Comment by joakime** [comment] 2017-09-26 16:49
Not reproducible in Jetty 9.4.7 using test code from OP with `connector.setSoLingerTime(1);` enabled.

``` plain
$ curl -v -H "Connection:close" http://localhost:8005
* Rebuilt URL to: http://localhost:8005/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8005 (#0)
> GET / HTTP/1.1
> Host: localhost:8005
> User-Agent: curl/7.47.0
> Accept: */*
> Connection:close
>
< HTTP/1.1 200 OK
< Connection: close
< Date: Tue, 26 Sep 2017 16:47:04 GMT
< Server: Jetty(9.4.7.v20170914)
<
stating...

* Closing connection 0
 the end
```

**Comment by joakime** [comment] 2017-09-26 16:57
@krutsko what are you running your server on? (OS, Kernel, Java)

**Comment by krutsko** [comment] 2017-09-26 17:07
java version "1.8.0_71"
System Version: macOS 10.12.6 (16G29)
Kernel Version: Darwin 16.7.0

I can reproduce it on my machine with Jetty (9.4.7.v20170914)

**Comment by krutsko** [comment] 2017-09-26 17:17
Originally, it was discovered on:
Operating System: Ubuntu 14.04.5 LTS
Kernel: Linux 3.13.0-117-generic
java version "1.8.0_111"
Jetty 9.4.2

**Comment by joakime** [comment] 2017-09-26 17:21
Java 1.8.0_71 is expired.

I used the following systems to test the server on.

* OSX 10.12.6 as well, but Java 1.8.0_144.
* Fedora Core 25 - Kernel 4.11.7-20 - Java 1.8.0 update 1444
* Windows 10 - 64-bit - Java 1.8.0 update 144

I used the following curl releases as well ...

* curl 7.53.1 (x86_64-apple-darwin15.6.0)
* curl 7.51.0 (x86_64-redhat-linux-gnu)
* curl 7.47.0 (x86_64-pc-linux-gnu)

**Comment by sbordet** [comment] 2017-09-26 17:27
Why do you use SO_LINGER ?

**Comment by krutsko** [comment] 2017-09-26 17:37
Java 1.8.0_71 and 1.8.0_111 are both expired JVMs

@joakime thank you, I will try with latest version and share the result.

> Why do you use SO_LINGER ?

@sbordet Historically we added this option on some services. It was set there to fight with a large number of TIME_WAIT connections on the server side.

**Comment by sbordet** [comment] 2017-09-26 17:45
SO_LINGER won't fight TIME_WAITs on the server.

SO_LINGER only affects the socket `close()` operation, and TIME_WAIT happens after the socket has been closed.
I suggest you just remove your usage of SO_LINGER.
If you still have TIME_WAIT issues, then there are other ways to contrast that.

I have yet to find a case where SO_LINGER is any useful.

**Comment by joakime** [comment] 2017-09-26 17:47
Some things to read about SO_LINGER ...

 * https://stackoverflow.com/a/3760186/775715 - answer, and good comment discussion, about SO_LINGER and how its a bad idea for combating TIME_WAIT.
 * https://www.nybek.com/blog/2015/04/29/so_linger-on-non-blocking-sockets/ - how SO_LINGER behavior is different on various OS's.

**Comment by krutsko** [comment] 2017-09-26 19:20
@joakime It still doesn't work with java 1.8.0_144 / jetty-9.4.7.v20170914 / curl 7.54.0. I'm confused, you convinced me it's working everywhere.. will take a fresh look tomorrow morning.

@sbordet @joakime thank for the info and links about SO_LINGER.

If the server initialize `close` don't the connection stay in TIME_WAIT? Could it be the case?

**Comment by sbordet** [comment] 2017-09-26 19:44
If a peer calls `close()` the TCP state will move to TIME_WAIT.
From there, it will timeout after a while, typically configured at the OS level.
If you have a lot of TIME_WAIT and you want to reduce them, that's an entirely different issue, not related to SO_LINGER.

**Comment by krutsko** [comment] 2017-09-27 16:37
@sbordet @joakime 

I have asked my colleagues help me to verify this on different machines. 
It is reproducible on:

```
Ubuntu 16.04.1 LTS
Kernel: Linux 4.4.0-96-generic
java version "1.8.0_144"  
```
and

```
Ubuntu 16.04.1 LTS
Linux 4.4.0-57-generic
java version "1.8.0_144"  
``` 

Need to notice, that a chance to reproduce this case depends on the payload size (large payload lead to more frequently fails).

All in all, if i have a chance, i will provide a more deterministic test.

**Comment by sbordet** [comment] 2017-09-27 17:10
@krutsko I'm not sure we should do something. You are using SO_LINGER for the wrong reason, and Jetty does nothing more than forward that option to the OS, and you see a weird behavior.
The solution is to just avoid using SO_LINGER.

**Comment by joakime** [comment] 2017-09-27 18:14
@krutsko here's a project with both your code (some changes to make it honor a command line option for setting arbitrary soLinger values) and a client curl script that shows the output received.

https://github.com/joakime/issue-1848

Lets coordinate via that project (or a fork you make from it).

**Comment by krutsko** [comment] 2017-09-28 09:16
Thanks @joakime 

I have performed you test and can confirm, that issue is not reproducible when client and server are running on the same machine. (Honestly, i missed the fact the curl output to console is crippled, and `--output` parameter did the trick).

But, when the peers are not in the local network, then test fails. (even when payload is 20k).
For example: `curl --verbose --header "Connection:close" --output curl-output.dat http://159.89.0.61:8005` 
I will keep this machine running for some days. 
Launched as `java -jar target/demo.jar 30 20000`

**Comment by krutsko** [comment] 2017-10-10 05:57
Anything new on that? Could you please classify this issue: is it a jetty bug or java bug or smth. else?

**Comment by gregw** [comment] 2017-10-10 06:35
If you have a reproducible test case, then yes it is could be a jetty bug.

Do you only see the truncation problem if you set solinger?

**Comment by krutsko** [comment] 2017-10-10 06:50
Yes, it's reproducible with any positive solinger; "Connection:close" header in request and the peers are not on the local machine.

With help of https://github.com/joakime/issue-1848 project:

``` 
curl --verbose --header "Connection:close" --output curl-output.dat http://159.89.0.61:8005
```
Launched as: java -jar target/demo.jar 30 20000
(so_linger = 30 seconds; payload size = 20000 bytes)

The content is truncated. I got the following result: 
```
curl --verbose --header "Connection:close" --output curl-output.dat http://159.89.0.61:8005
* Rebuilt URL to: http://159.89.0.61:8005/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 159.89.0.61...
* TCP_NODELAY set
* Connected to 159.89.0.61 (159.89.0.61) port 8005 (#0)
> GET / HTTP/1.1
> Host: 159.89.0.61:8005
> User-Agent: curl/7.54.0
> Accept: */*
> Connection:close
>
< HTTP/1.1 200 OK
< Connection: close
< Date: Tue, 10 Oct 2017 06:41:20 GMT
< Content-Type: application/octet-stream
< Server: Jetty(9.4.7.v20170914)
<
{ [20 bytes data]
* Recv failure: Connection reset by peer
100 12872    0 12872    0     0   129k      0 --:--:-- --:--:-- --:--:--  129k
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by sbordet** [comment] 2017-10-10 09:14
@gregw I doubt it's a Jetty bug: works fine without SO_LINGER and fails with. 
There is not much we can do as we only forward the option to the underlying implementation. 
@joakime already reported how brittle is the SO_LINGER behavior on different OSes and even among different Linux versions.

**Comment by mgtriffid** [comment] 2017-10-12 11:15
Hi folks, I'm @krutsko 's teammate.

Looks like we lied to you a bit about our SO_LINGER configuration. While we thought it was 300 in our environments, in fact it was 0, because framework we use on top of Jetty (Dropwizard, to be precise) sends timeout value in seconds, and Jetty then divides by 1000. Bug of Dropwizard. This means that connection is being reset forcefully once all data pushed to socket. That's exactly what we observe.

But why @krutsko and I saw this connection reset on huge payloads with test in OP? I guess because huge payload takes significant time to be passed through socket. Jetty pushes to socket, closes, waits for 1 second (see @krutsko 's test) and sends RST after expiration, not waiting for other data to be transferred.

Does this sound plausible, how do you think?

**Closed** 2018-09-10 19:26 UTC
Labels: More Info Required
