### ISSUE TITLE
precompressed resource not found

### ISSUE THREAD

**Issue by mpapirkovskyy** [eclipse/jetty.project#2300] opened 2018-03-07 19:07 UTC
After migration from Jetty 8 precompressed resources are no longer returned.
I have logo.png.gz file, which was resolved correctly in Jetty 8 since it looked for compressed resources first:
https://github.com/eclipse/jetty.project/blob/jetty-8.1.x/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DefaultServlet.java#L447

In Jetty 9 this no longer works as logic changed dramatically:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceContentFactory.java#L69

And I get 404 error now.
It seems theres no workaround to return old behavior.

**Comment by joakime** [comment] 2018-03-07 19:53
Seems like a duplicate of #1862

**Comment by joakime** [comment] 2018-03-07 19:57
Short answer, is that not all clients ask for, or support compressed content.
And of the clients that support compression, not all support gzip. (a growing number currently do not support 'deflate' and instead support 'brotli, gzip')
So having the original, uncompressed, content, **and** the technique specific (gzip and/or brotli) compressed content is recommended.

This is also more efficient (cpu and memory wise) for the server, as the server then doesn't have to use a gzip component to actually serve the content.

**Comment by joakime** [comment] 2018-03-14 12:26
Closing as duplicate of #1862

**Closed by joakime** 2018-03-14 12:26 UTC
