### ISSUE TITLE
Range request responses are not sane

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2249] opened 2018-02-26 21:13 UTC
As reported at https://stackoverflow.com/questions/48984500/partial-range-requests-from-chrome-causing-error
By https://stackoverflow.com/users/425481/vbnewbie

I have tried to implement range request video playback on a system that has webservlet and UI, that sends the range request from chrome starting with bytes :0- to the backend dataserver. Now I have been sending the full stream as I was under the impression the jetty server handles the response range. I see it work for the first and second request but then fails as the next request has a range that is less than what the previous range was.

```
  (Request 1)   Range:bytes=0-    
  (Response 1)  Accept-Ranges:bytes
                Content-Length:6748748
                Content-Range:bytes 0-10005/6748748                      
  (Request 2)   Range:bytes=6717440-                                   
  (Response 2)  Accept-Ranges:bytes
                Content-Length:6748748
                Content-Range:bytes 6717440-6718465/6748748              
  (Request 3)   Range:bytes=3932160-                                      
  (Response 3)  Accept-Ranges:bytes
                Content-Length:6748748
                Content-Range:bytes 3932160-3933185/6748748
  (Request 4)   Range:bytes=5701632- 
  (Response 4)  Fails -
```

Can anyone make sense of this? With short videos this does not occur, so is there some timeout issue but then why is the chrome request with a smaller range? This is what I specify in the headers but again do not explicitly send the bytes as requested as I thought jetty handles it.

``` java
       if(inputStream != null) {
		   if (parameters.containsKey("Range")) {
				    String range =parameters.get("Range").toString();
		            String[] ranges = range.split("=")[1].split("-");
	    	        final int from = Integer.parseInt(ranges[0]);
		            if(parameters.containsKey("Content-Length")) {
		            	int sLength = (int) parameters.get("Content-Length");
		                int to = 10005 + from;
		    	        if (to >= sLength) {
		    	            to = (int) (sLength - 1);
		    	        }
		    	        if (ranges.length == 2) {
		    	            to = Integer.parseInt(ranges[1]);
		    	        }
		    	        final String responseRange = String.format("bytes %d-%d/%d", from, to, sLength);
		    	        parameters.put("Responserange", responseRange);
		    	        } 
		           
			   }
```

EDIT:

My logs in the dataserver side show the following consistently with each request being handled:

    java.nio.channels.ClosedChannelException,

Added additional stack trace 

    java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427)
	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:489)
	at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:217)

**Comment by joakime** [comment] 2018-02-26 21:18
Some observations on report.
I am assuming the requested resources is the same, but different ranges.
I'm also assuming that the requested resources size is 6748748.
Also assuming we support [RFC7233](https://tools.ietf.org/html/rfc7233) properly.

```
  (Request 1)   Range:bytes=0-    
  (Response 1)  Accept-Ranges:bytes
                Content-Length:6748748
                Content-Range:bytes 0-10005/6748748 
```

I would have expected the response `Content-Range: 0-6748747/6748748`

```
  (Request 2)   Range:bytes=6717440-                                   
  (Response 2)  Accept-Ranges:bytes
                Content-Length:6748748
                Content-Range:bytes 6717440-6718465/6748748
```

I would have expected the response `Content-Range: 6717440-6748747/6748748`

```
  (Request 3)   Range:bytes=3932160-                                      
  (Response 3)  Accept-Ranges:bytes
                Content-Length:6748748
                Content-Range:bytes 3932160-3933185/6748748
```

I would have expected the response `Content-Range: 3932160-6748747/6748748`


```
  (Request 4)   Range:bytes=5701632- 
  (Response 4)  Fails -
```

This should definitely not failed.
I would have expected the response `Content-Range: 5701632-6748747/6748748`

**Comment by snewbie** [comment] 2018-02-27 05:46
Yes, your assumptions are correct: the resource is the same and the size in this case was gathered from file.size(). I was told using inputstream.available() is not a reliable way to get the content-length. Additional information that my be helpful is that we asynchronously deliver an audio stream as well which is also handled as a 206 request so not sure if that is causing an issue. When not using partial range requests it works fine but we cannot seek the video which is a required feature.

**Comment by joakime** [comment] 2018-02-27 14:03
@snewbie are you the author of the question on stackoverflow?

**Comment by snewbie** [comment] 2018-02-28 06:17
Yes

**Comment by gregw** [comment] 2018-02-28 06:49
I just wrote a quick test against head of 9.4.x branch and sent 4 identical range requests, to which I got the following responses:
```
HTTP/1.1 206 Partial Content
Connection: close
Date: Wed, 28 Feb 2018 06:45:46 GMT
Last-Modified: Wed, 28 Feb 2018 06:45:46 GMT
Content-Type: text/plain
Accept-Ranges: bytes
Content-Range: bytes 0-6748747/6748748
Content-Length: 6748748


HTTP/1.1 206 Partial Content
Connection: close
Date: Wed, 28 Feb 2018 06:45:46 GMT
Last-Modified: Wed, 28 Feb 2018 06:45:46 GMT
Content-Type: text/plain
Accept-Ranges: bytes
Content-Range: bytes 6717440-6748747/6748748
Content-Length: 31308


HTTP/1.1 206 Partial Content
Connection: close
Date: Wed, 28 Feb 2018 06:45:46 GMT
Last-Modified: Wed, 28 Feb 2018 06:45:46 GMT
Content-Type: text/plain
Accept-Ranges: bytes
Content-Range: bytes 3932160-6748747/6748748
Content-Length: 2816588


HTTP/1.1 206 Partial Content
Connection: close
Date: Wed, 28 Feb 2018 06:45:46 GMT
Last-Modified: Wed, 28 Feb 2018 06:45:46 GMT
Content-Type: text/plain
Accept-Ranges: bytes
Content-Range: bytes 5701632-6748747/6748748
Content-Length: 1047116
```
These all look correct to me, so hitting the DefaultServlet directly appears work fine.

Can you give us more information: which version of jetty, what filters do you have installed? Is the resource being served by the default servlet or something else?

regards

**Comment by snewbie** [comment] 2018-03-05 06:34
Sorry for the late response. Been out of the office. I eventually got this to work partially with all the requests working fine up until the last byte or so needs to be served and then it freezes with the client still waiting and eventually making a new request. I will share below what changes I have made and the actual request and responses. Thank you for your responses to this and checking on whether it was a potential bug. Turns out to be more likely programming issue:

`
Range:bytes=0-

Accept-Ranges:bytes
Content-Length:3391207
Content-Range:bytes 0-3391207/3391208
Content-Type:video/webm

Range:bytes=3383296-

Accept-Ranges:bytes
Content-Length:7911
Content-Range:bytes 3383296-3391207/3391208
Content-Type:video/webm
Date:Mon, 05 Mar 2018 06:29:07 GMT

Range:bytes=3383296-

Accept-Ranges:bytes
Content-Length:7911
Content-Range:bytes 3383296-3391207/3391208
Content-Type:video/webm
Date:Mon, 05 Mar 2018 06:31:13 GMT`


At this point the browser is still waiting for something, request is not finished yet. It then sends another request. I added the following code to explicitly send the range requested as I was having too many issues leaving it in jetty's hands but may have to go back and see how it handles.

`private static void copyStream (PullBufferStream inputStream, OutputStream outputStream, BytesStreamObject bytesWrittenObj, int from, int to) throws IOException, CodecNotAvailableException {
		//export media stream
		BufferedOutputStream bout = new BufferedOutputStream (outputStream);
		Buffer b = new Buffer();
		long skipped =0;
		int byteLength = 0;
		
		do {
			inputStream.read(b);

			int len    = b.getLength();
			byte[] data   = (byte[]) b.getData();
			int  offset = b.getOffset();
			if (len > 0) {
				if(skipped < from) {			 
				  // skip bytes until reach from position in inputstream
				  if(skipped + len <= from) {     
					  // skip all bytes just read
					  skipped += len;
				  } else {                       
					  // skip only some of bytes read 
					  offset += (from - skipped);
					  len -= (from - skipped);
					  skipped = from;
					  
				  }
				} 
				if(to >= 0) {
					if(from + byteLength + len <= to) {
						// use the full buffer
					} else {
						// trim len to needed bytes to be read to prevent exceeding the "to" input parameter
						len = (to + 1) - (from + byteLength);
					}
				} 
				
				byteLength+= len;
				bytesWrittenObj.bytesWritten = byteLength;
				bout.write(data, offset, len);
				//bout.write(data, from, end);
			} 
		} while (!b.isEOM());
		//fileProperties.setBytesLength(byteLength);
		
		//bout.close(); //TODO: Review close connection disabled for testing partial range requests on jetty. Test for memory leak.
				
	}`


This is the error I see in the logs:

>     org.eclipse.jetty.io.EofException: Closed
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:437)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)

Any ideas on this?

**Comment by gregw** [comment] 2018-03-05 21:23
Sorry but I really don't have any ideas because I'm struggling to think how the initial problems could have occurred in the first place?    If you are just using the jetty default servlet to serve a static file, then this should work.   What were the programming errors that made that not work?  Are you generating the file on the fly so it's size is changing? Are you adjusting the headers yourself? Or are you filtering the output and/or request in any way?

Any chance of giving us a sample app that reproduces the problem?

**Comment by snewbie** [comment] 2018-03-06 06:05
I am working with legacy code (large enterprise application with no documentation at all). Yes, I am using the jetty default servlet to serve a static file, which is created at runtime by downloading from a third party resource and creating the inputstream for passing back to the client. The size is specific for that playback but each request can select from 100's of video files. 

I add the headers appropriately for 206 content and initially let jetty handle everything but had some errors. To simplify this I will try and reproduce a sample app that duplicates my production environment. Thanks for your assistance. Will follow up as soon as I can.

**Comment by snewbie** [comment] 2018-03-13 07:21
Thanks for you assistance guys, but we can close this issue now. I have been able to resolve it.

**Comment by gregw** [comment] 2018-03-13 07:23
thanks

**Closed by gregw** 2018-03-13 07:23 UTC
Labels: More Info Required
