### ISSUE TITLE
Max local stream count 1000 exceeded

### ISSUE THREAD

**Issue by prakashnandihal** [eclipse/jetty.project#3036] opened 2018-10-29 10:32 UTC
We are using jetty http2 9.4.7 version and using high level http2 client for posting request, we are seeing "MessageMax local stream count 1000 exceeded" error after processing some requests. what  could be the reason for this issue.

**Comment by sbordet** [comment] 2018-10-29 10:45
If you are using `HTTP2Client`, then you have to manage the number of streams on the client yourself and be sure you don't exceed the max allowed by the server.

If you are using `HttpClient`, then it should manage the max number of streams for you and you should not worry. If you have a problem using `HttpClient`, then it may be a duplicate of #2796.

**Closed by sbordet** 2018-10-29 10:45 UTC
