### ISSUE TITLE
Invalid 'Range: bytes' header sent from the client.

### ISSUE THREAD

**Issue by ElveElve** [eclipse/jetty.project#555] opened 2016-05-09 20:20 UTC
Hey, 

I'm currently running Jetty server 9.3.6 and am occasionally receiving the following log messages:

2016-05-09 21:45:26.750:WARN:oejs.InclusiveByteRange:qtp250075633-387: Bad range format: bytes: 0-65536

The issue can be tracked down to the org.eclipse.jetty.server.InclusiveByteRange which is expecting (correctly) the header in the format of 'bytes=' as opposed to 'bytes: ' sent from the client.

Is there anything that should be done here ? I'm reluctant to disable the 'acceptRanges' init param on the DefaultServlet just to get around this issue.

Regards, 

Michael

**Comment by joakime** [comment] 2016-05-09 20:23
Nothing to do.

You have a bad client connecting to you.
The range provided wont be used, and the entire file will be presented to
the client instead.

You might want to track down the problematic client and let them know they
are doing boneheaded things.


Joakim Erdfelt / joakim@webtide.com

**Comment by sbordet** [comment] 2016-05-09 20:24
Spec reference: https://tools.ietf.org/html/rfc7233#section-2.1

**Comment by joakime** [comment] 2016-05-09 20:24
Closing as this is not a bug.

**Closed by joakime** 2016-05-09 20:24 UTC
