### ISSUE TITLE
Embedding Jetty - Chapter 21. Embedding: FileServer example is incomplete

### ISSUE THREAD

**Issue by andlenz** [eclipse/jetty.project#949] opened 2016-09-22 13:15 UTC
The FileServer example in the jetty documentation "Chapter 21. Embedding" is incomplete. 

The `server.setHandler(handlers);` method call is missing.

see [http://www.eclipse.org/jetty/documentation/current/embedding-jetty.html#_using_handlers](http://www.eclipse.org/jetty/documentation/current/embedding-jetty.html#_using_handlers)

**Comment by jmcc0nn3ll** [comment] 2016-09-29 20:04
duplicate of #943

**Closed by jmcc0nn3ll** 2016-09-29 20:04 UTC
Labels: Documentation
