### ISSUE TITLE
tcpstream getting reset in 30sec but we don’t see any method to configure tcpstream reset time , connection reset timer is 60sec

### ISSUE THREAD

**Issue by ankit58** [eclipse/jetty.project#5975] opened 2021-02-16 10:25 UTC
**Jetty version**
<jetty-version>9.4.18.v20190429</jetty-version>
**Java version**
1.8 
**OS type/version**
Kubernets
**Description**
The connection reset is 60sec and we see tcpstream reset in 30sec but we don’t see any method to configure tcpstream reset time. Is there any way by which we can configure this tcpstream reset timer for idle timeout activity ?

**Comment by sbordet** [comment] 2021-02-16 11:03
You need to be more clear about what you mean by "tcpstream reset" and "connection reset".

The default `ServerConnector` idle timeout is 30 seconds, after which the TCP connection is closed.

**Comment by joakime** [comment] 2021-02-16 13:12
> 9.4.18.v20190429

Also, upgrade your version of Jetty, you are subject to several security advisories with that version.

https://www.eclipse.org/jetty/security_reports.php

**Comment by dufourgilles** [comment] 2021-02-16 14:41
Ankit is talking about idle timeout.
His code below does set the idle timeout to an application value ... but whatever is set, the connection is closed after 30 seconds being idle.

                             httpClient = new HttpClient(http2Transport, sslContextFactory);
                             httpClient.setConnectTimeout(config.getSvcThreadConfig().getHttp2ConnectTimeoutMs());
                             if (config.getSvcThreadConfig().getHttp2IdleConnectionTimeoutSec() > 0) {
                                      httpClient.setIdleTimeout(config.getSvcThreadConfig().getHttp2IdleConnectionTimeoutSec() * 1000);
                             }
                             httpClient.setRemoveIdleDestinations(true);

**Comment by sbordet** [comment] 2021-02-16 15:49
@dufourgilles closed by whom? Could it be that it is being closed by the other peer?

It is common that Apache, Nginx, load balancers have an idle timeout of 30 seconds; do you have any of this components in your system?

**Comment by dufourgilles** [comment] 2021-02-17 09:52
Hi Simone,

I do appreciate the quick feedback here.
After further discussion with Ankit and reviewing his data, the problem is that this is the server that is closing the session as you rightly said.

Thanks and sorry for miscommunication.

Gilles.

**Comment by sbordet** [comment] 2021-02-17 11:57
No problem, thanks for the feedback. Closing the issue.

**Closed as completed by sbordet** 2021-02-17 11:57 UTC
