### ISSUE TITLE
Overriding SSL context KeyStoreType requires explicit override of TrustStoreType

### ISSUE THREAD

**Issue by oliverhausler** [eclipse/jetty.project#901] opened 2016-09-03 17:58 UTC
This is supposedly fixed, but I am still seeing this in 9.3.11.v20160721 embedded Jetty.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=473321

**Comment by mwgmnn** [comment] 2016-09-07 15:21
Hello all,

we've run into the same problem. We also use jetty embedded and only set the keystore* -fields.

On server start SslContextFactory.loadTrustStore is called with null. But _trustStoreType is set to "JKS" when the class is being instanciated and this is wrong for our configured keystore. We need to explicitly set it to null by calling setTrustStoreType( null ) in versions >= 9.3.2.

I wonder whether it is correct to init the truststore from the keystore which most of the time only contains the server key (this is Greg's intention that he commented in the other ticket). We also set trustall = true when there is no truststore configured. At least then initialization of a truststore can be skipped in my opinion which may also lead to better startup performance.

**Comment by nicktrav** [comment] 2017-10-09 18:35
Bumping this. We're seeing this in 9.4.x too in a jetty embedded server.

Is this intended behavior, or a genuine regression?

**Comment by gregw** [comment] 2017-10-10 04:15
@nicktrav I think it is an unintended behaviour:)

It would be good if you all could be a little clearer about how you wish to configure the SslContextFactory and the exact problem that you are seeing.   We are very happy to update the class to support your requirements, but we need to understand them, as obviously we've missed some nuance.

**Comment by nicktrav** [comment] 2017-10-10 04:54
Here's how we are configuring the context factory in our case:

```java
SslContextFactory sslContextFactory = new SslContextFactory();

sslContextFactory.setKeyStorePath("/path/to/some.jceks");
sslContextFactory.setKeyStoreType("JCEKS");
sslContextFactory.setKeyStorePassword("foo");

// Runtime error in the case that the following line is missing.
sslContextFactory.setTrustStoreType("JCEKS");
```

Here's what we see at runtime (this is a simple, standalone test case, but the stacktrace is the same in our application code):

```
java.io.IOException: Invalid keystore format

	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:52)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadTrustStore(SslContextFactory.java:1055)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:257)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:222)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:72)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:276)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:428)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.nickt.jetty.JettyBugTest.test(JettyBugTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Setting up the context factory works in 9.2.x without the explicit declaration that we're using a JCEKS truststore.

I have not checked 9.3.x, but I presume that given that the original issue was opened against that branch, the problem exists there too for the same test case.

Happy to share more code from the minimal test case that I have, if that will help.

**Comment by sbordet** [comment] 2017-10-10 14:57
Weirdly enough, `keytool` seems to be able to load the same file as a keyStore of type `pkcs12` and a trustStore of type `jks` :open_mouth: 

When using the keyStore type `jceks` I was able to reproduce the issue of the OP and fix it.

**Comment by sbordet** [comment] 2017-10-10 14:57
@nicktrav can you please confirm the latest code works for you ?

**Comment by nicktrav** [comment] 2017-10-10 20:24
@sbordet - thanks for the quick turnaround. I verified that this is now working, given the code I pasted above. 👍

**Comment by joakime** [comment] 2017-10-10 20:45
@nicktrav did you test with the latest changes from today? (make sure you have commit a8d08df in your tests)

**Comment by nicktrav** [comment] 2017-10-10 21:31
First test was with `2b847405e0`. I tested again now from HEAD (`a8d08df84f`), and that works fine too.

**Comment by joakime** [comment] 2017-10-10 22:37
@nicktrav good to hear. :-)

**Comment by bkrieger** [comment] 2018-01-15 20:56
@sbordet As far as I can tell, after https://github.com/eclipse/jetty.project/commit/a8d08df84fb7b6944e3bd11adb724fd05c29e357 it is impossible to configure jetty with a keystore password and a null truststore password, because the truststore will just fall back to using the keystore password. This feels wrong to me, as truststores do not require passwords.

**Comment by sbordet** [comment] 2018-06-08 14:42
@bkrieger you are right.

**Comment by sbordet** [comment] 2018-06-08 15:41
@bkrieger can you test the latest code (5165b08)?

**Comment by bkrieger** [comment] 2018-06-08 15:54
Yes, this fixes my issue.

**Comment by sbordet** [comment] 2018-06-08 15:57
@bkrieger thanks for the feedback!

**Comment by gregw** [comment] 2018-06-19 07:02
Merged.  Sorry for the slow turn around on this one.

**Closed by gregw** 2018-06-19 07:02 UTC

**Comment by nicktrav** [comment] 2018-06-19 07:58
Apologies for the late reply on this, @sbordet. Still LG.
