### ISSUE TITLE
HttpSession lastaccessedtime not getting updated in jetty 9.4.18

### ISSUE THREAD

**Issue by riyazmohd** [eclipse/jetty.project#5693] opened 2020-11-22 18:15 UTC
I see the lastaccessedtime  not getting updated when using jetty-9.4.18 . The method  'session.getLastAccessedTime()' still shows the login time , due to which the jetty server is logging out even if the end user is operating on the application . (sessionDestroy() is getting called after 15 mins)
As i see recurring  dirty=true  while storing in SessionDataStore , l assume sessiondatastore is unable to store session update values  ? Kindly suggest 

2020-11-12 11:14:46,191 | DEBUG | 1008, qtp1469424811-1008 | org.eclipse.jetty.util | session | admin | perf-mgmt:get-dp-config-00059 |  |  | Store: id=node09ub57pexl3ldw9v80qoxdsl01, **dirty=true**, lsave=1605201195938, period=0, elapsed=90253

my jetty-web.xml config :
`<Configure id="webapp"
        class="org.eclipse.jetty.webapp.WebAppContext">
        <Get name="securityHandler">    
           <Call name="setSessionRenewedOnAuthentication">
              
               <Arg type="boolean">False</Arg>
           </Call>
        </Get>
        <Get name="sessionHandler">         
           <Call `name="setHttpOnly">`
               
               <Arg type="boolean">False</Arg>
           </Call>
           <Call name="setSecureRequestOnly">
              
               <Arg type="boolean">False</Arg>
           </Call>
        </Get>
</Configure>`
pax.web timeout :  org.ops4j.pax.web.session.timeout=15

**Comment by janbartel** [comment] 2020-11-23 09:06
@riyazmohd can you please paste what your SessionDataStore and SessionCache configuration is.

Also, please post your log with DEBUG enabled - I want to see DEBUG output from the JDBCSessionDataStore.

Have you confirmed that the session cookie is present on the requests received from the client?

And finally, you're 16 versions behind the latest jetty-9.4.x release, which is 9.4.34. As always, it is always a good idea to upgrade as there have been a lot of fixes and updates in those versions.

**Comment by riyazmohd** [comment] 2020-11-23 10:33
@janbartel 
We are using the default in-memory datastore for storing of session info. Attached karaf.log
[karaf.zip](https://github.com/eclipse/jetty.project/files/5582226/karaf.zip)
 the logs 

We are using pax.web.jetty version-7.2.10 for jetty 9.4.18.
Attached the jetty.xml and jetty-web.xml 
[jetty-config.zip](https://github.com/eclipse/jetty.project/files/5582251/jetty-config.zip)

Have you confirmed that the session cookie is present on the requests received from the client ? => yes , the session is present .

Kindly suggest if the configuration of jetty-web.xml/jetty.xml  has any config issues .

**Comment by janbartel** [comment] 2020-11-23 15:43
@riyazmohd thanks for the log file and config, very enlightening.

From what I can see in the log file, it looks like the following is happening:

1. a user makes a request to the root context, which creates a session
2. the user then visits several other contexts, all of which receive the session cookie created at step 1 because the session cookie path is "/". Some of these contexts create sessions that re-use the id (but as per spec, not the contents!) created at step 1.
3. the user _never_ revisits the root context within the defined 15 min session timeout, thus (as per the spec) after 15 mins the session expires in the root context, which expires all sessions with the same id in all contexts.

So, off the top-of-my-head I can see you have a couple of options here:

* don't create a session in the root context, so the cookie path won't be "/". The default behaviour is for the session cookie path to be the context path, which means that as your contexts all have a unique path, contexts don't see each other's session cookies. Which means that each of your contexts would have their own unique session ids.
or
* still create the session in the root context, but set the session timeout to be infinite for that context only. That way, all your other contexts will still see and share the same session id (not session contents!), and whichever context is the least used will be the one to timeout the session id first.

Essentially you need to analyse your app and work out the session strategy: which contexts really need sessions; which ones need to share a session id; which ones will be the ones most/least regularly hit and thus which one will be in control of the lifecycle of the session id.

BTW the behaviour you noticed of DEBUG messages with dirty=true from the SessionDataStore are just the various different contexts interacting with their version of the session and not indicative of any problem.

Also, as an aside, I don't really recommend disabling `sessionRenewedOnAuthentication`. By not forcing a change of the session id after authentication, you risk an attacker grabbing the session id prior to authentication, and then being able to use it to gain fully authorized access post-authentication. If you leave it set to `true` jetty will take care of updating the id in all contexts for which it is present.

**Comment by riyazmohd** [comment] 2020-11-24 10:20
@janbartel 
Thank you for your inputs ,we will think on recommendations made by you .
As per our code flow The session's root context is getting created in subclass of JAASLoginInterceptor.

We are creating the HttpSession by overiding the JAASLoginInterceptor and as soon as we encounter the url '/cxf/fncsdn/main/ping', Attached the code chunk.  [codechunk.zip](https://github.com/eclipse/jetty.project/files/5589010/codechunk.zip)

 @line :237. The mentioned url called only one time per login . 

The overidden handleMessage(Message message) of subclass gets called for every /cxf request from the UI . We see request.getSession(false) has the updated lastAccesstime over here, where as at HttpSessionListenerImpl.java , it still has the old_time .

@Override
public void sessionDestroyed(HttpSessionEvent event) {
                                HttpSession session = event.getSession();   
// The session.getLastAccessedTime() is not getting updated for successive session updates .

We run a periodic call  ‘/cxf/security/keepalive’ from UI , for every 2 minutes to keep the session alive .
This session's lastaccesstime  issue we encountered after upgrading from jetty-9.2 to jetty-9.4.18. We are suspecting if pax.web.jetty wrapper is causing the issue .  

we have seen two instances of HttpSession for each session id. Only one of them has last access time updated by WEB transactions. Another HttpSession instance is not updated and gets time-out.

**Comment by janbartel** [comment] 2020-11-24 10:32
@riyazmohd 

"we have seen two instances of HttpSession for each session id. Only one of them has last access time updated by WEB transactions. Another HttpSession instance is not updated and gets time-out."  this could very well be a race condition that was fixed in jetty sessions several releases ago. Again, I urge you to update your version of jetty ;)

**Comment by riyazmohd** [comment] 2020-11-25 16:26
Thank you for your suggestions @janbartel

**Closed as completed** 2020-11-25 16:26 UTC
