### ISSUE TITLE
SslContextFactory trustAll - not trust all

### ISSUE THREAD

**Issue by readonlynetwork** [eclipse/jetty.project#3482] opened 2019-03-23 18:01 UTC
_Setting:_
Embedded jetty server, SSL + HTTP2 + AbstractHandler

I would like to get the client cert. and check that in .war or in a handler AND I don't want to trust it at SSL layer. (I tried it with no Conscrypt, not work.)

_Not Work:_ 
```
var scf = new SslContextFactory(true);
scf.setNeedClientAuth(true);
```

_I got:_
```
2019-03-23 18:59:00.725:WARN:oejusS.config:Thread-0: Trusting all certificates configured for SslContextFactory@15723c7c[provider=,keyStore=null,trustStore=null]
...
Received fatal alert: certificate_unknown
```

_Other way, I tried to set_
```
var scf = new SslContextFactory();
scf.setTrustStore(clientTrustStore); 
scf.setEndpointIdentificationAlgorithm(null);
```
_for check the cert, but skip CN or Subject Alternative Names checking, but it doesn't work._

_AbstractHandler:_
```
public void handle( String target,
                        Request baseRequest,
                        HttpServletRequest request,
                        HttpServletResponse response ) throws IOException,
                                                      ServletException
    {
        response.setContentType("text/html; charset=utf-8");
        response.setStatus(HttpServletResponse.SC_OK);
        
        PrintWriter out = response.getWriter();
        
        var clientCert = (X509Certificate[])request.getAttribute("javax.servlet.request.X509Certificate");
        if(clientCert != null) {
        	out.println("Client cert found!<br>");
        }else {
        	out.println("No client cert!<br>");
        }
        
        out.println("<h1>" + greeting + "</h1>");
        if (body != null)
        {
            out.println(body);
        }

        baseRequest.setHandled(true);
    }
```

**Comment by readonlynetwork** [comment] 2019-03-23 23:04
- Unfortunately, I let somewhere the 'scf.setEndpointIdentificationAlgorithm("HTTPS");' code and that cause the error. SO disable the EndpointIdentificationAlgorithm is work!

- But `scf.setTrustAll(true)` still not work! I tried it with `scf.setTrustStore(clientTrustStore);` or `scf.setTrustStore(null);`

**Comment by joakime** [comment] 2019-03-24 11:07
Glad you worked it out.
Closing issue.

**Comment by readonlynetwork** [comment] 2019-03-24 13:56
> **But scf.setTrustAll(true) still not work!**
It has no effect at ClientAuth

**Comment by joakime** [comment] 2019-03-24 14:16
`setTrustAll(true)` only works if you have no keystore and truststore.

Since you do have a keystore/truststore, perhaps you'll have to customize the `TrustManager` / `TrustManagerFactory` instead.

Try `scf.setTrustManagerFactoryAlgorithm("TrustAll");`

**Comment by readonlynetwork** [comment] 2019-03-25 08:16
I tried, not work.
I did not set` TrustStore`, I use var `scf = new SslContextFactory(true);` and `scf.setTrustManagerFactoryAlgorithm("TrustAll");`

**Comment by sbordet** [comment] 2019-03-25 09:31
@readonlynetwork you have to specify what exactly does not work, and exactly what error you get, especially now that you have fixed `setEndpointIdentificationAlgorithm(null)`.

**Comment by readonlynetwork** [comment] 2019-03-25 11:45
Jetty Server SslContextFactory
```
scf = new SslContextFactory(true);
scf.setTrustManagerFactoryAlgorithm("TrustAll");
scf.setNeedClientAuth(true);
scf.setKeyStorePassword(new String(keyPassword));
scf.setKeyStore(serverKeyStore);
scf.setEndpointIdentificationAlgorithm(null);
```

Exception:
`Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown`

**Comment by sbordet** [comment] 2019-03-25 15:17
Still not enough.

You show what I presume is the server-side configuration of the `SslContextFactory`.

But the exception you report is (typically) on the client. Is it? If so, then you have the client-side misconfigured.

The more you detail, the better we can understand the problem, otherwise it takes a lot of comments here asking what you are doing _exactly_ - chances are you have some wrong configuration so please double check it.

**Comment by joakime** [comment] 2019-03-25 16:19
The error just doesn't have enough detail.

Perhaps running java with `-Djavax.net.debug=all` will reveal what's going on.

**Comment by readonlynetwork** [comment] 2019-03-25 17:20
Sorry, Yes it is a client error message.
So when I put client CA cert. to `scf.setTrustStore(clientTrustStore);` then the client able to connect to the server. But If I not set client CA cert. and I set `scf.setTrustManagerFactoryAlgorithm("TrustAll");` then the client can't connect to the server because the server is not trust the client cert.

**Comment by readonlynetwork** [comment] 2019-03-25 17:27
`javax.net.ssl|ERROR|11|qtp1882872757-17|2019-03-25 18:22:34.407 CET|TransportContext.java:313|Fatal (CERTIFICATE_UNKNOWN): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by sbordet** [comment] 2019-07-26 13:36
Duplicate of #3822.

**Closed by sbordet** 2019-07-26 13:36 UTC
Labels: More Info Required, Unable To Replicate
