### ISSUE TITLE
Client AuthenticationProtocolHandler sends request failures to response failure listener

### ISSUE THREAD

**Issue by TuomasKiviaho** [eclipse/jetty.project#450] opened 2016-03-22 09:45 UTC
I was getting an NPE from missing exception at my failure listener although I knew there should've been an exception present.

The reason was that for some reason `AuthenticationProtocolHandler` treats both request and response failures to response failure listener and the request failure exception is lost because of this in the stacktrace following steps (jetty 9.3.8)

```
ResponseNotifier.notifyFailure(Response$FailureListener, Response, Throwable) line: 170	
ResponseNotifier.notifyFailure(List<ResponseListener>, Response, Throwable) line: 162	
ResponseNotifier.forwardFailure(List<ResponseListener>, Response, Throwable) line: 236	
ResponseNotifier.forwardFailureComplete(List<ResponseListener>, Request, Throwable, Response, Throwable) line: 241	
AuthenticationProtocolHandler$AuthenticationListener.forwardFailureComplete(HttpRequest, Throwable, Response, Throwable) line: 209	
AuthenticationProtocolHandler$AuthenticationListener.onComplete(Result) line: 94	
```

I think that `AuthenticationProtocolHandler` should have also a `RequestNotifier` to which request failures should be sent insetad of the `ResponseNotifier`.

**Comment by sbordet** [comment] 2016-03-22 12:39
Sorry, I don't understand. Can you please describe in detail what you expect, and what actually happens ?

**Comment by TuomasKiviaho** [comment] 2016-03-23 11:35
Everything starts from `HttpRequest` that contains `EofException` as it's request failure.

``` java
        @Override
        public void onComplete(Result result)
        {
            HttpRequest request = (HttpRequest)result.getRequest();
            ContentResponse response = new HttpContentResponse(result.getResponse(), getContent(), getMediaType(), getEncoding());
            if (result.isFailed())
            {
                Throwable failure = result.getFailure();
                if (LOG.isDebugEnabled())
                    LOG.debug("Authentication challenge failed {}", failure);
                forwardFailureComplete(request, result.getRequestFailure(), response, result.getResponseFailure());
                return;
            }
...
```
then the problem is forwarded to a response notifier ...
``` java
        private void forwardFailureComplete(HttpRequest request, Throwable requestFailure, Response response, Throwable responseFailure)
        {
            HttpConversation conversation = request.getConversation();
            conversation.updateResponseListeners(null);
            notifier.forwardFailureComplete(conversation.getResponseListeners(), request, requestFailure, response, responseFailure);
        }
```
.. that in turn it's calls `forwardFailure`
``` java
    public void forwardFailureComplete(List<Response.ResponseListener> listeners, Request request, Throwable requestFailure, Response response, Throwable responseFailure)
    {
        forwardFailure(listeners, response, responseFailure);
        notifyComplete(listeners, new Result(request, requestFailure, response, responseFailure));
    }
```
My problem was the missing response that eventually caused an NPE in my listener. It's missing because the cause was actually a request failure.

``` java
    public void notifyFailure(List<Response.ResponseListener> listeners, Response response, Throwable failure)
    {
        // Optimized to avoid allocations of iterator instances
        for (int i = 0; i < listeners.size(); ++i)
        {
            Response.ResponseListener listener = listeners.get(i);
            if (listener instanceof Response.FailureListener)
                notifyFailure((Response.FailureListener)listener, response, failure);
        }
    }
```

I was thinking that shouldn't request failures be given to `org.eclipse.jetty.client.RequestNotifier` instead?

**Comment by sbordet** [comment] 2016-04-01 10:05
This case is pretty weird.

You had a request failure, but _after_ you got a successful response that installed the authentication protocol handler.

Trying to reproduce to understand what's the best fix.
If you have a reproducible test case, will be great.

**Comment by sbordet** [comment] 2016-04-01 10:50
Managed to reproduce myself.

Fixed by forwarding response success if the response was successful, but still reporting completion failure because the request failed.

**Closed by sbordet** 2016-04-01 10:50 UTC
