### ISSUE TITLE
TimeoutException when server sends unexpected content

### ISSUE THREAD

**Issue by flymoondust** [eclipse/jetty.project#2311] opened 2018-03-10 05:13 UTC
I use jetty 9.2.24.

Recently, I encounter a strange problem about "java.util.concurrent.TimeoutException: Total timeout elapsed" as following:

First, my log print this error: 
```
2018-03-10 10:39:23,972 WARN  [HttpClient@481748570-64][ROOT][org.eclipse.jetty.http.HttpParser 1318] badMessage: 400 Unknown Version for HttpReceiverOverHTTP@7181bf8e(rsp=IDLE,failure=null)[HttpParser{s=RESPONSE_VERSION,0 of -1}]".
```
Then,the next request always occur timeout exception. （I found this suspicious pattern in my log）.
So, I suspect this is a new bug of jetty.
Following is my reason:

At the very beginning, my first guess is the server didn't response,bug then i capture the network packeges,then i found when the time i send the request which would have TimeoutException, the packeges had sent and received the answer and ack.and the server has logs that has response the request . So i begin to suspect there is some bug maybe.

Then I began to search the log ,then I found the error pattern： If "badMessage: 400 Unknown Version for HttpReceiverOverHTTP" error occur,the next request would have timeoutException.

Please pay attention to my question,help very wanted!!!!!

**Comment by flymoondust** [comment] 2018-03-10 08:10
This is some debug info of the first request that has badMessage exception:

2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.HttpExchange 210] Terminated response for HttpExchange@47dc0e6e req=TERMINATED/null@null res=TERMINATED/null@null, result: Result[HttpRequest[DELETE /restconf/data/huawei-ac-net-l3vpn-svc:l3vpn-svc-cfg/sites/site=fae5770f-7d82-4124-badc-9b1ddddb5dac/vrf-attributes/vrf-attribute=2e5138e8-7e0f-5320-0fa0-e7a19621b2c2,84a92e50-1114-437b-a319-51c68900cd62 HTTP/1.1]@59b0473d > HttpResponse[HTTP/1.1 204 null]@2526e38b] null
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.HttpReceiver 443] Response complete HttpResponse[HTTP/1.1 204 null]@2526e38b
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.HttpChannel 89] HttpExchange@47dc0e6e req=TERMINATED/null@null res=TERMINATED/null@null disassociated true from HttpChannelOverHTTP@2f052fa5(exchange=null)[send=HttpSenderOverHTTP@4fde9462(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@5eaddb4a(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.PoolingHttpDestination 167] HttpConnectionOverHTTP@699e0ec7(l:/10.145.69.45:37923 <-> r:/10.145.69.191:18008,closed=false)[HttpChannelOverHTTP@2f052fa5(exchange=null)[send=HttpSenderOverHTTP@4fde9462(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@5eaddb4a(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]] released
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.PoolingHttpDestination 109] Processing exchange null on HttpConnectionOverHTTP@699e0ec7(l:/10.145.69.45:37923 <-> r:/10.145.69.191:18008,closed=false)[HttpChannelOverHTTP@2f052fa5(exchange=null)[send=HttpSenderOverHTTP@4fde9462(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@5eaddb4a(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]] of HttpDestination[https://10.145.69.191:18008]3753ea29,queue=0,pool=ConnectionPool[c=1/100,a=1,i=0]
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.ConnectionPool 218] Connection idle HttpConnectionOverHTTP@699e0ec7(l:/10.145.69.45:37923 <-> r:/10.145.69.191:18008,closed=false)[HttpChannelOverHTTP@2f052fa5(exchange=null)[send=HttpSenderOverHTTP@4fde9462(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@5eaddb4a(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]]
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.HttpReceiver 451] Request/Response succeeded: Result[HttpRequest[DELETE /restconf/data/huawei-ac-net-l3vpn-svc:l3vpn-svc-cfg/sites/site=fae5770f-7d82-4124-badc-9b1ddddb5dac/vrf-attributes/vrf-attribute=2e5138e8-7e0f-5320-0fa0-e7a19621b2c2,84a92e50-1114-437b-a319-51c68900cd62 HTTP/1.1]@59b0473d > HttpResponse[HTTP/1.1 204 null]@2526e38b] null
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.TimeoutCompleteListener 81] Cancelled (successfully: true) timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@d34263f
2018-03-10 16:32:51,612 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 10 HttpParser{s=START,0 of -1}
2018-03-10 16:32:51,612 INFO  [http-bio-127.0.0.1-31887-exec-6][ROOT][com.huawei.ies.restconnectorservice.restful.service.svc.protocol.impl.AbstractRestClient 224] sendHttpRequest() End : url=/restconf/data/huawei-ac-net-l3vpn-svc:l3vpn-svc-cfg/sites/site=fae5770f-7d82-4124-badc-9b1ddddb5dac/vrf-attributes/vrf-attribute=2e5138e8-7e0f-5320-0fa0-e7a19621b2c2,84a92e50-1114-437b-a319-51c68900cd62, method=DELETE
2018-03-10 16:32:51,613 WARN  [http-bio-127.0.0.1-31887-exec-6][ROOT][com.huawei.ies.restconnectorservice.restful.service.svc.protocol.impl.TokenRestClient 154] restRequest has response. url : https://10.145.69.191:18008/restconf/data/huawei-ac-net-l3vpn-svc:l3vpn-svc-cfg/sites/site=fae5770f-7d82-4124-badc-9b1ddddb5dac/vrf-attributes/vrf-attribute=2e5138e8-7e0f-5320-0fa0-e7a19621b2c2,84a92e50-1114-437b-a319-51c68900cd62. requestHead is : {"Content-Type":"application/json","Accept":"application/json"}
2018-03-10 16:32:51,613 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=START DirectByteBuffer@39803506[p=1461,l=1471,c=16384,r=10]={HTTP/1.1 204\r\nX-S...6:32:49 GMT\r\n\r\n<<<No Content>>>":"0","data":[{"p...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-10 16:32:51,613 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.http.HttpParser 1561] START --> RESPONSE_VERSION
2018-03-10 16:32:51,614 WARN  [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.http.HttpParser 1318] badMessage: 400 Unknown Version for HttpReceiverOverHTTP@5eaddb4a(rsp=IDLE,failure=null)[HttpParser{s=RESPONSE_VERSION,0 of -1}]
2018-03-10 16:32:51,614 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.http.HttpParser 1320]
org.eclipse.jetty.http.HttpParser$BadMessageException: Unknown Version
        at org.eclipse.jetty.http.HttpParser.parseLine(HttpParser.java:540)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1224)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:174)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
2018-03-10 16:32:51,614 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.http.HttpParser 1561] RESPONSE_VERSION --> CLOSED
2018-03-10 16:32:51,614 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-10 16:32:51,614 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=CLOSED DirectByteBuffer@39803506[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 204\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-10 16:32:51,614 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-10 16:32:51,614 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 113] Read 0 bytes DirectByteBuffer@39803506[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 204\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} from DecryptedEndPoint@7fd7d499{/10.145.69.191:18008<->37923,Open,in,out,-,-,8/30000,HttpConnectionOverHTTP}->SelectChannelEndPoint@5abecda3{/10.145.69.191:18008<->37923,Open,in,out,-,-,4/30000,SslConnection}{io=0,kio=0,kro=1}

**Comment by flymoondust** [comment] 2018-03-10 08:11
This is some debug info of the next request  that would has timeoutException:

2018-03-10 16:32:51,804 DEBUG [http-bio-127.0.0.1-31887-exec-10][ROOT][org.eclipse.jetty.client.HttpContent 160] Advanced content past last chunk
2018-03-10 16:32:51,804 DEBUG [http-bio-127.0.0.1-31887-exec-10][ROOT][org.eclipse.jetty.client.HttpSender 255] Request committed HttpRequest[DELETE /restconf/data/huawei-ac-net-l3vpn-svc:l3vpn-svc-cfg/sites/site=fae5770f-7d82-4124-badc-9b1ddddb5dac HTTP/1.1]@3389f921
2018-03-10 16:32:51,804 DEBUG [http-bio-127.0.0.1-31887-exec-10][ROOT][org.eclipse.jetty.client.HttpSender 316] Request success HttpRequest[DELETE /restconf/data/huawei-ac-net-l3vpn-svc:l3vpn-svc-cfg/sites/site=fae5770f-7d82-4124-badc-9b1ddddb5dac HTTP/1.1]@3389f921
2018-03-10 16:32:51,804 DEBUG [http-bio-127.0.0.1-31887-exec-10][ROOT][org.eclipse.jetty.client.HttpExchange 193] Terminated request for HttpExchange@55c45a1e req=TERMINATED/null@null res=PENDING/null@null, result: null
2018-03-10 16:32:51,804 DEBUG [http-bio-127.0.0.1-31887-exec-10][ROOT][org.eclipse.jetty.client.HttpSender 363] Terminating request HttpRequest[DELETE /restconf/data/huawei-ac-net-l3vpn-svc:l3vpn-svc-cfg/sites/site=fae5770f-7d82-4124-badc-9b1ddddb5dac HTTP/1.1]@3389f921
2018-03-10 16:32:51,808 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=CLOSED DirectByteBuffer@61fc6249[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 204\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-10 16:32:51,809 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-10 16:32:51,809 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 113] Read 1428 bytes DirectByteBuffer@61fc6249[p=0,l=1428,c=16384,r=1428]={<<<HTTP/1.1 204\r\nX-S...6:32:50 GMT\r\n\r\n>>>at, 10 Mar 2018 1...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} from DecryptedEndPoint@7fd7d499{/10.145.69.191:18008<->37923,Open,in,out,-,-,195/300000,HttpConnectionOverHTTP}->SelectChannelEndPoint@5abecda3{/10.145.69.191:18008<->37923,Open,in,out,-,-,0/300000,SslConnection}{io=0,kio=0,kro=1}
2018-03-10 16:32:51,809 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=CLOSED DirectByteBuffer@61fc6249[p=0,l=1428,c=16384,r=1428]={<<<HTTP/1.1 204\r\nX-S...6:32:50 GMT\r\n\r\n>>>at, 10 Mar 2018 1...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-10 16:32:51,809 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-10 16:32:51,809 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=CLOSED DirectByteBuffer@61fc6249[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 204\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-10 16:32:51,809 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-10 16:32:51,809 DEBUG [HttpClient@1616662072-103][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 113] Read 0 bytes DirectByteBuffer@61fc6249[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 204\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} from DecryptedEndPoint@7fd7d499{/10.145.69.191:18008<->37923,Open,in,out,-,-,195/300000,HttpConnectionOverHTTP}->SelectChannelEndPoint@5abecda3{/10.145.69.191:18008<->37923,Open,in,out,-,-,0/300000,SslConnection}{io=0,kio=0,kro=1}

**Comment by sbordet** [comment] 2018-03-10 11:49
If you only consider the lines for thread 105 (`HttpClient@1616662072-105`) in your second message, you will see that the server sent down a `204` response for your `DELETE` request.

HTTP `204` means "No Content`, yet the parser notices that there are 10 more bytes, in fact the bytes "No Content".
These 10 more bytes are interpreted as the beginning of another response, and so you get the `400 Unknown Version` error.

Your server is seriously broken, so I would recommend that you fix it and I am guessing that all your other problems will go away.

**Comment by flymoondust** [comment] 2018-03-11 07:01
Sorry I don't answer in time.

**Comment by flymoondust** [comment] 2018-03-11 07:03
So, you mean that the reason of 400 exception is the server response 204 with "No Content" data,So jetty parse fails, So the next response parse failed ?

**Comment by flymoondust** [comment] 2018-03-11 07:05
Then, I'll go to the server to confirm. But I think the timeout exception is also wrong because the next req/resp is complete bug jetty parse wrong and throw a wrong excetpion which mislead the users to wrong way to locate the problem. what do you think??

**Comment by sbordet** [comment] 2018-03-11 09:53
I don't see any timeout exceptions in the logs you reported.
You say it happens, but there is no trace for it in the logs.
Again, I would fix the server first and then see if there is any other problem.

**Comment by joakime** [comment] 2018-03-11 11:35
@flymoondust to point out the specific spot that @sbordet is talking about ...

```
2018-03-10 16:32:51,613 DEBUG [HttpClient@1616662072-105][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=START
  DirectByteBuffer@39803506[p=1461,l=1471,c=16384,r=10]={HTTP/1.1 204\r\nX-S...6:32:49 GMT\r\n\r\n<<<No Content>>>":"0","data":
  [{"p...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
```

That shows a "HTTP/1.1 204" responses with body content (the "No Content" portion)

However, all 204 responses are body-less per the spec. 

See 
 * https://tools.ietf.org/html/rfc7230#section-3.3.3
 * https://tools.ietf.org/html/rfc7231#section-6.3.5

```
3.3.3.  Message Body Length

   The length of a message body is determined by one of the following
   (in order of precedence):

   1.  Any response to a HEAD request and any response with a 1xx
       (Informational), 204 (No Content), or 304 (Not Modified) status
       code is always terminated by the first empty line after the
       header fields, regardless of the header fields present in the
       message, and thus cannot contain a message body.
```

So the parser sees the "No Content" not as part of the "HTTP/1.1 204" Responses, but as the start of the next response, which is looking for "HTTP/1.1", which it doesn't find, and that results in the `org.eclipse.jetty.http.HttpParser$BadMessageException: Unknown Version`

**Comment by flymoondust** [comment] 2018-03-12 01:31
You want the timeout log,here it is:

2018-03-11 14:48:41,550 DEBUG [http-bio-127.0.0.1-31887-exec-81][ROOT][org.eclipse.jetty.client.HttpContent 160] Advanced content past last chunk
2018-03-11 14:48:41,551 DEBUG [http-bio-127.0.0.1-31887-exec-81][ROOT][org.eclipse.jetty.client.HttpSender 255] Request committed HttpRequest[DELETE /restconf/data/huawei-ac-net-vrrp:net-vrrp-cfg/instances/instance=402a9e29-672d-4236-a9c4-0bbb695fc052 HTTP/1.1]@211dbec
2018-03-11 14:48:41,551 DEBUG [http-bio-127.0.0.1-31887-exec-81][ROOT][org.eclipse.jetty.client.HttpSender 316] Request success HttpRequest[DELETE /restconf/data/huawei-ac-net-vrrp:net-vrrp-cfg/instances/instance=402a9e29-672d-4236-a9c4-0bbb695fc052 HTTP/1.1]@211dbec
2018-03-11 14:48:41,551 DEBUG [http-bio-127.0.0.1-31887-exec-81][ROOT][org.eclipse.jetty.client.HttpExchange 193] Terminated request for HttpExchange@7938c9e req=TERMINATED/null@null res=PENDING/null@null, result: null
2018-03-11 14:48:41,551 DEBUG [http-bio-127.0.0.1-31887-exec-81][ROOT][org.eclipse.jetty.client.HttpSender 363] Terminating request HttpRequest[DELETE /restconf/data/huawei-ac-net-vrrp:net-vrrp-cfg/instances/instance=402a9e29-672d-4236-a9c4-0bbb695fc052 HTTP/1.1]@211dbec
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=CLOSED DirectByteBuffer@39803506[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 200\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 113] Read 1428 bytes DirectByteBuffer@39803506[p=0,l=1428,c=16384,r=1428]={<<<HTTP/1.1 204\r\nX-S...4:48:40 GMT\r\n\r\n>>>: Sun, 11 Mar 201...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} from DecryptedEndPoint@22750655{/10.145.69.191:18008<->48013,Open,in,out,-,-,32/300000,HttpConnectionOverHTTP}->SelectChannelEndPoint@d7de896{/10.145.69.191:18008<->48013,Open,in,out,-,-,0/300000,SslConnection}{io=0,kio=0,kro=1}
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=CLOSED DirectByteBuffer@39803506[p=0,l=1428,c=16384,r=1428]={<<<HTTP/1.1 204\r\nX-S...4:48:40 GMT\r\n\r\n>>>: Sun, 11 Mar 201...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT][org.eclipse.jetty.http.HttpParser 1206] parseNext s=CLOSED DirectByteBuffer@39803506[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 204\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT][org.eclipse.jetty.client.http.HttpReceiverOverHTTP 158] Parsed false, remaining 0 HttpParser{s=CLOSED,0 of -1}
2018-03-11 14:48:41,553 DEBUG [HttpClient@1616662072-819][ROOT]**[org.eclipse.jetty.client.http.HttpReceiverOverHTTP 113] Read 0 bytes DirectByteBuffer@39803506[p=0,l=0,c=16384,r=0]={<<<>>>HTTP/1.1 204\r\nX-S...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} from** DecryptedEndPoint@22750655{/10.145.69.191:18008<->48013,Open,in,out,-,-,32/300000,HttpConnectionOverHTTP}->SelectChannelEndPoint@d7de896{/10.145.69.191:18008<->48013,Open,in,out,-,-,0/300000,SslConnection}{io=0,kio=0,kro=1}


2018-03-11 14:53:41,554 WARN  [http-bio-127.0.0.1-31887-exec-81][ROOT][com.huawei.ies.restconnectorservice.restful.service.svc.protocol.impl.TokenRestClient 179] send message timeout ,do not resend
2018-03-11 14:53:41,554 ERROR [http-bio-127.0.0.1-31887-exec-81][ROOT][com.huawei.ies.restconnectorservice.impl.RESTConnectorServiceDelegateImpl 177] RestHttpClient.sendHttpRequest() ERROR. url : https://10.145.69.191:18008/restconf/data/huawei-ac-net-vrrp:net-vrrp-cfg/instances/instance=402a9e29-672d-4236-a9c4-0bbb695fc052
2018-03-11 14:53:41,555 ERROR [http-bio-127.0.0.1-31887-exec-81][ROOT][com.huawei.bsp.roa.web.ResponseWriter 186] ServiceException
exception.id: ies.restconnector.http.client.request.expired; com.huawei.ies.restconnectorservice.common.exception.ExServiceException
        at com.huawei.ies.restconnectorservice.restful.service.svc.protocol.impl.TokenRestClient.sendHttpRequest(TokenRestClient.java:180)
        at com.huawei.ies.restconnectorservice.impl.RESTConnectorServiceDelegateImpl.getResponseResult(RESTConnectorServiceDelegateImpl.java:239)
        at com.huawei.ies.restconnectorservice.impl.RESTConnectorServiceDelegateImpl.dispatchMessage(RESTConnectorServiceDelegateImpl.java:170)
        at com.huawei.ies.restconnectorservice.service.RESTConnectorService.dispatchMessage(RESTConnectorService.java:113)
        at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.huawei.bsp.roa.common.RestRegisterItem.invoke(RestRegisterItem.java:1591)
        at com.huawei.bsp.roa.common.RestRegisterItem.invokePost(RestRegisterItem.java:1395)
        at com.huawei.bsp.roa.web.DispatcherServlet.execute(DispatcherServlet.java:456)
        at com.huawei.bsp.roa.web.DispatcherServlet.handle(DispatcherServlet.java:313)
        at com.huawei.bsp.roa.web.DispatcherServlet.doHandle(DispatcherServlet.java:270)
        at com.huawei.bsp.roa.web.DispatcherServlet.doPost(DispatcherServlet.java:151)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at com.huawei.bsp.roa.web.DispatcherServlet.service(DispatcherServlet.java:200)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.huawei.cloudsop.common.tokenhelper.filter.AbstractAuthFilter.doFilter(AbstractAuthFilter.java:177)
        at com.huawei.cloudsop.common.tokenhelper.filter.AuthFilter.customAuthToken(AuthFilter.java:141)
        at com.huawei.cloudsop.common.tokenhelper.filter.AuthFilter.doFilter(AuthFilter.java:111)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by flymoondust** [comment] 2018-03-12 01:36
I think when the parse has failed because of the 204 with 10 redundant bytes, the parse state is close but the connection didn't close. So when the next request come, jetty use the same connection, but would not parse even though jetty receive the response, util the timeout machanism take effect.

**Comment by sbordet** [comment] 2018-03-12 07:46
@flymoondust I don't see any timeout exception in the latest log you reported.

**Comment by flymoondust** [comment] 2018-03-12 11:37
My code is like this :```
try
        {

            int timeout = 60;
            if (StringUtil.isNotBlank(message.getTimeout()))
            {
                timeout = Integer.parseInt(message.getTimeout());
            }

            response = listener.get(timeout, TimeUnit.SECONDS);

        }
        catch (ExecutionException e1)
        {
            if (e1.getMessage().contains("Authentication"))
            {
                // 用户名 密码错误的时候
                RestResponseResult responseResult = new RestResponseResult();
                try
                {
                    responseResult.setResponse(new String(listener.getContent(), "UTF-8"));
                }
                catch (UnsupportedEncodingException e)
                {
                    throw new ExServiceException(AppConstant.CONNECTOR_SYSTEM_INTERNAL_ERROR,
                            HttpStatus.INTERNAL_SERVER_ERROR_500, e);
                }
                responseResult.setResponseCode(HttpStatus.UNAUTHORIZED_401);
                return responseResult;

            }
            else
            {
                LOGGER.error("sendHttpRequest() ExecutionException e=" + e1.getMessage());
                executionException(e1);
            }
        }
        catch (TimeoutException e1)
        {
            LOGGER.error("sendHttpRequest() TimeoutException e1=" + e1.getMessage());
            throw new ExServiceException(AppConstant.CONNECTOR_HTTPCLIENT_EXPIERED,
                    HttpStatus.INTERNAL_SERVER_ERROR_500);
        }
```

**Comment by sbordet** [comment] 2018-03-12 15:39
@flymoondust you continue to say that there is a timeout exception, yet you have not provided a full DEBUG log that shows it. 

I want to believe you, but the only way for me to help you is if you provide the full logs that caused the timeout exception.

Otherwise I can only say that the server did not respond in time.

**Comment by sbordet** [comment] 2018-03-12 18:48
All right, with some reverse engineering I was able to reproduce this issue.
You can work it around by fixing the server, as the wrong 204 with content causes the client to fail.
Having said that we will fix the client to cope with these bad servers.

@gregw the problem is that a 204 response comes down with a body. The parser finishes to parse the 204 and does not expect any body, so it leaves the body bytes in the buffer, and it notifies the `message complete` event which triggers the send of other possibly queued requests.
However, the thread that performed the parsing is in a parsing loop and tries to parse more, expecting a response line while instead it finds the content of the previous 204.
The parser thread is now in a race with the sender thread; if the connection is closed when the parser notifies the `bad message` event, we risk of closing the connection while we're sending the next request.

There are multiple ways to fix the issue: from stopping the parsing loop if `message complete` has been emitted, so changing the parser to look ahead if there is remaining content in the buffer and perhaps just discard it, etc. so we need to discuss what is the best approach.

**Comment by flymoondust** [comment] 2018-03-13 02:02
Thanks very much for taking me seriously. And my server has confirmed and fixed the No content problem,and then the timeout exception goes away.  I think the timeout exception is not very friendly but maybe not necessarily fixed because the scene is not very common. And maybe import some other bugs when you try to fix this that is a little complex. Please make me know your final decision. Thanks again for reply so quicklly.

**Comment by joakime** [comment] 2018-03-20 18:00
@sbordet can this be closed?

**Comment by sbordet** [comment] 2018-03-20 18:26
@gregw can you review #2324 ?

**Closed** 2018-03-21 15:25 UTC
