### ISSUE TITLE
Flaky test: SelectChannelServerSslTest.testFullURI

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2614] opened 2018-06-01 10:02 UTC
```
-------------------------------------------------------------------------------
Test set: org.eclipse.jetty.server.ssl.SelectChannelServerSslTest
-------------------------------------------------------------------------------
Tests run: 34, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 23.357 s <<< FAILURE! - in org.eclipse.jetty.server.ssl.SelectChannelServerSslTest
testFullURI(org.eclipse.jetty.server.ssl.SelectChannelServerSslTest)  Time elapsed: 0.062 s  <<< ERROR!
javax.net.ssl.SSLException: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:124)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:124)
```

**Comment by WalkerWatch** [comment] 2018-06-01 12:10
Duplicate of #2237

**Closed by WalkerWatch** 2018-06-01 12:10 UTC
Labels: Test
