### ISSUE TITLE
jetty websocket-client 9.2.18.v20160721 causing OutOfMemory

### ISSUE THREAD

**Issue by nakulsir** [eclipse/jetty.project#813] opened 2016-08-04 13:54 UTC
Dear Team

In my application I am jetty websocket-client 9.2.18.v20160721 for websocket client implementation in my web application that is deployed over jboss.
My websocket server is running on tomcat-8.0.36.
I close connection every 5 minute and create a new connection. 
Eventually within 20 minutes all memory get consumed and gives me out of memory issue.
I face this problem only with jetty and with other implementations(like tyrus, tomcat) this is not an issue.
Can you please consider that defect and please provide some fix.
I have tried other versions as well(e.g. 9.3.11.v20160721) but those are also having same issue.

Regards
Nakul Vashishth
Software Architect

**Comment by joakime** [comment] 2016-08-04 19:01
This would be quite surprising that none of the other projects that heavily use Jetty's WebSocket and WebSocketClient haven't hit this problem yet.

Can you detail how you are using the WebSocketClient?

Note: Jetty has native WebSocketClient and support for the JSR356 ClientContainer.  Tomcat has both native and jsr356 clients.  Tyrus is jsr356 only.   

Which WebSocket Client technique are you using? Native or JSR356?

**Comment by joakime** [comment] 2016-11-01 20:30
Closing, as unable to replicate.  If you can provide more information (in particular a reproduction case), feel free to reopen.

**Closed by joakime** 2016-11-01 20:30 UTC
Labels: Bug, More Info Required

**Comment by martenjacobs** [comment] 2017-08-09 15:14
Ik had a similar issue that was caused by me creating and starting a new WebSocketClient instance every time the a Session was closed due to inactivity. This was eventually solved by re-using the same WebSocketClient object and calling its 'connect' method again to create a new Session. 

WebSocketClients that have been started are not garbage-collected, even after all their Sessions have been closed. I guess this may have been done by design, but it could cause difficult-to-debug issues for some users. I have a simple reproduction case for the issue I had that [I put on Pastebin](https://pastebin.com/aDcVcF2W).

**Comment by joakime** [comment] 2017-08-09 15:39
@martenjacobs the WebSocketClient should be treated like a browser.
Calling `.start()` starts the browser and all of its resources.
If you don't close the browser (aka `.stop()`) then those resources are still used.
If you create a new WebSocketClient and `.start()` it, then that is like starting a whole new browser on your laptop (not reusing the original one).
As you can imagine, you'll run out of memory rather quickly that way.

**Comment by martenjacobs** [comment] 2017-08-10 05:26
@joakime Yes, that seems perfectly logical _now_ :)
