### ISSUE TITLE
Jetty 9.x: Support Direct Byte Buffers

### ISSUE THREAD

**Issue by tpounds** [eclipse/jetty.project#351] opened 2016-02-21 23:04 UTC
Server side direct byte buffers used to be configurable in old versions of Jetty, however, it has never been configurable in Jetty 9.x (see: 0c81b36e047717c04ace524ece667b9adef2e4df, 5b8a9bb95e0bec732fd2c2a383a1f73d116fb8d0). I've submitted several pull requests to make this configurable.

master: https://github.com/eclipse/jetty.project/pull/348
jetty-9.3.x: https://github.com/eclipse/jetty.project/pull/349
jetty-9.2.x: https://github.com/eclipse/jetty.project/pull/350

**Background:**

Typically, allocating objects on heap is preferable so the GC is aware of when it needs to free up space. However, a direct buffer is always needed when interfacing with native code (e.g. native socket reads). When using heap allocated buffers the JVM must allocate a temporary direct buffer to read and write to native sockets. It then performs an additional copy from the temporary direct buffer back into the heap allocated buffer.

Using heap allocated buffers within Jetty has the following consequences:
1. JVM allocates and caches large off heap buffers in thread local memory. The cached buffers persist for the lifetime of the thread. The off heap buffer will not be eligible for clean up until the thread exits. Additionally, there is no guarantee that the memory will be freed in a timely manner since it occurs during GC finalization. It's possible for a large number of short lived threads to exhaust the off heap memory before a GC cycle kicks in to free the memory.
   
   From [JDK-6210541](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6210541):
   
   > In jdk7, the buffer cache implementation is an array of buffers. Soft references are not used. As previously stated, the only remaining issue is short lived threads that do I/O with buffers backed by arrays in the heap. We don't have a solution for this case at this time.
2. JVM performs an additional copy for every socket read or write operation. An expensive operation to pay on every HTTP request.
3. Since Jetty maintains it's own internal  buffer pool the byte buffer memory requirements are effectively doubled, cached once for the internal Jetty buffer pool and once per Java thread. It gets worse as the number of Jetty connection threads grows.

**see:**
- http://www.evanjones.ca/java-bytebuffer-leak.html
- http://www.eclipse.org/jetty/documentation/current/preventing-memory-leaks.html
- http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6210541
- http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/sun/nio/ch/IOUtil.java#l207
- http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/sun/nio/ch/IOUtil.java#l262

**Comment by gregw** [comment] 2016-02-22 11:26
Hey Trevor ( @tpounds ),
thanks for these PRs, which I will look at in detail  shortly, but a quick response on the topic before I get into the detail.

I'm keen to get appropriate direct buffer support back into jetty, but at this stage I would imagine it only going into master (9.4), maybe 9.3.x,  but almost certainly not 9.2.x unless there is a really huge demonstrable benefit and demand from 9.2.x users.    So let's focus on getting support into master first before putting too much effort into back ports.

Now the reason that direct buffers were dropped during the 9.x refactor is that it is becoming increasing difficult to tell when it will be of benefit because of things like ssl, http2, gzip.    A write from a webapp app may be:
 * aggregated into a buffer in HttpOutput 
 * gzipped in a HttpOutput interceptor
 * fragmented into HTTP2 frames
 * encrypted via SslEngine
 * written out the network

Now only the last of these will have a benefit from direct buffer usage.... with other steps being heap to heap conversions, so direct buffers are a hindrance rather than a help.    This is even worse for the gzip step as deflators take only byte arrays rather than ByteBuffers!

There is some mitigation with Http2 fragmentation as it can use gather writes, so if it is passed a direct buffer, it will gather write a frame header with the slice of a the direct buffer.  Great... but only if the next step is not SSL!

The other unknown is how do better SslEngine implementations (eg tcnative or conscrypt) work with direct buffers?   If they can use them, then this would be a REALLY GOOD reason to reintroduce direct buffers and start using one of these better SslEngine impls.

We have a half hearted attempt to address this complexity by being able to ask an EndPoint if it is optimised for direct buffers... but I suspect this is over-simplistic. 

Anyway, having brain dumped a bit of back ground, I'll now have a look at your PR in detail.

**Comment by gregw** [comment] 2016-02-22 12:17
Ah your patch is on the read side rather than the write side!    I'm even more unconvinced that this is necessary!  Even if there is no SSL the issue is that direct buffers are quick to read/write to the network, but slow to access (ByteBuffer get needs to do a copy into temporary heap buffer).

Thus for a request buffer, that is typically read once and then accessed byte by byte as the header is parsed and then block by block as the content is read, I am very dubious that there is any benefit at all using a direct buffer.   

It would be good to see some micro benchmarks to see the difference in speed/garbage between reading/parsing direct buffers vs indirect.     Perhaps access to direct buffers is now a lot faster so the parser reading them byte by byte is not a problem (and the look ahead caches desire to look at a byte[] is not thwarted too much).

**Comment by sbordet** [comment] 2019-09-18 21:21
Closed in favor of #3952 and #3953.

**Closed by sbordet** 2019-09-18 21:21 UTC
Labels: Enhancement
