### ISSUE TITLE
IllegalStateException when Gzip compression enabled on static resource calls

### ISSUE THREAD

**Issue by ferencerdei** [eclipse/jetty.project#11305] opened 2024-01-23 17:57 UTC
**Jetty version(s)**

12.0.5
**Jetty Environment**

ee10
**Java version/vendor** `(use: java -version)`
openjdk 21 2023-09-19 LTS
OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode)
**OS type/version**
macOS 14.2.1
**Description**

**How to reproduce?**
1. enable compression, eg.:
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,application/json,image/svg+xml,application/x-font-ttf,application/font-woff,application/font-woff2,image/png,image/jpeg,image/webp
server.compression.min-response-size=1024
2. Put for example a svg file under src/main/resources/static
3. Try to open that resource from the browser: http://localhost:8080/myapp/jetty.svg

Error:
`2024-01-23T18:42:12.645+01:00  WARN 5060 --- [tp1226858597-45] o.e.jetty.ee10.servlet.ServletChannel    : /myapp/jetty.svg

java.lang.IllegalStateException: s=HANDLING rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.completed(ServletChannelState.java:1052) ~[jetty-ee10-servlet-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.lambda$handle$3(ServletChannel.java:553) ~[jetty-ee10-servlet-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.util.Callback$3.succeeded(Callback.java:162) ~[jetty-util-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.ee10.servlet.HttpOutput.complete(HttpOutput.java:424) ~[jetty-ee10-servlet-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.ee10.servlet.ServletContextResponse.completeOutput(ServletContextResponse.java:209) ~[jetty-ee10-servlet-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:553) ~[jetty-ee10-servlet-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464) ~[jetty-ee10-servlet-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571) ~[jetty-security-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703) ~[jetty-ee10-servlet-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:761) ~[jetty-server-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:594) ~[jetty-server-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.server.Server.handle(Server.java:179) ~[jetty-server-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:594) ~[jetty-server-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:424) ~[jetty-server-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322) ~[jetty-io-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99) ~[jetty-io-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971) ~[jetty-util-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201) ~[jetty-util-12.0.5.jar:12.0.5]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156) ~[jetty-util-12.0.5.jar:12.0.5]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
`

The content is rendered in the browser, but the above exception is present in the log.

Demo project:
https://github.com/ferencerdei/jetty_issue

**Comment by joakime** [comment] 2024-01-23 21:35
This is a duplicate of #11095 and is being worked on in PR #11210

**Closed as not planned by joakime** 2024-01-23 21:35 UTC
Labels: Bug
