### ISSUE TITLE
Graceful shutdown causes repeated 503s on keep-alive connections

### ISSUE THREAD

**Issue by nicolone** [eclipse/jetty.project#2749] opened 2018-07-27 12:24 UTC
### Problem
We have a microservice architecture with some services communicating with others. The services use http clients with keep-alive connections to increase performance for regular requests. We have retry mechanisms in place to handle connectivity issues gracefully.

When we do a rolling deployment of one of our services we see a lot of 503s in the logs of the calling service. When doing a graceful shutdown of Jetty, current requests are processed, new connections rejected and open connections will be served with a 503 `ServiceUnavailable`.
Since the open connections are not closed, the retry mechanism repeats the request and receives responses with http status code 503 again and again until the service/Jetty actually terminated.

### How to reproduce
The behavior can be reproduced by:
1. starting a simple Jetty server providing an arbitrary endpoint (for example `/_version`)
2. shell>`while true; do printf '"http://localhost:8080/request"\n%.0s' {1..100} | xargs -t curl -v -s -S; done`
3. Graceful shutdown by `Ctrl+C` on the Jetty server

In the output of 2. you can see 
a) the successful requests (many times):
```
...
* Connection #0 to host localhost left intact
* Found bundle for host localhost: 0x55e8f5107f20 [can pipeline]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /_version HTTP/1.1^M
> Host: localhost:8080^M
> User-Agent: curl/7.47.0^M
> Accept: */*^M
> ^M
< HTTP/1.1 200 OK^M
< Date: Fri, 27 Jul 2018 10:02:43 GMT^M
< Access-Control-Allow-Origin: *^M
< Access-Control-Allow-Headers: Origin,Accept,Authorization,Content-Type,X-Requested-With^M
< Access-Control-Max-Age: 1800^M
< Access-Control-Allow-Methods: GET^M
< Content-Type: text/plain^M
< Content-Length: 76^M
< ^M
{ [76 bytes data]
...
```
b) followed by 503s (many times):
```
...
* Connection #0 to host localhost left intact
* Found bundle for host localhost: 0x55dea5802f20 [can pipeline]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /_version HTTP/1.1^M
> Host: localhost:8080^M
> User-Agent: curl/7.47.0^M
> Accept: */*^M
> ^M
< HTTP/1.1 503 Service Unavailable^M
< Date: Fri, 27 Jul 2018 12:14:10 GMT^M
< Cache-Control: must-revalidate,no-cache,no-store^M
< Content-Type: text/html;charset=iso-8859-1^M
< Content-Length: 260^M
< ^M
{ [260 bytes data]
* Connection #0 to host localhost left intact
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 503 Service Unavailable</title>
</head>
<body><h2>HTTP ERROR 503</h2>
<p>Problem accessing /_version. Reason:
<pre>    Service Unavailable</pre></p>
</body>
</html>
...
```

c) followed by connection rejected (many times):
```
...
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 8080 failed: Connection refused
* Failed to connect to localhost port 8080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8080: Connection refused
...
```

### Patch
I propose to add a `"Connection: close"` header to the 503 responses in order to force the calling clients to close the keep-alive connection.

In org.eclipse.jetty.server.handler.StatisticsHandler.java
```
176:                baseRequest.setHandled(true);
>                     response.setHeader("Connection", "close");
177:                response.sendError(HttpStatus.SERVICE_UNAVAILABLE_503);
```

If one adds the header  `"Connection: close"` to the 503 response, b) reduces to a single:
```
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /_version HTTP/1.1^M
> Host: localhost:8080^M
> User-Agent: curl/7.47.0^M
> Accept: */*^M
> ^M
< HTTP/1.1 503 Service Unavailable^M
< Date: Fri, 27 Jul 2018 10:02:44 GMT^M
< Connection: close^M
< Cache-Control: must-revalidate,no-cache,no-store^M
< Content-Type: text/html;charset=iso-8859-1^M
< Content-Length: 260^M
< ^M
{ [260 bytes data]
* Closing connection 0
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 503 Service Unavailable</title>
</head>
<body><h2>HTTP ERROR 503</h2>
<p>Problem accessing /_version. Reason:
<pre>    Service Unavailable</pre></p>
</body>
</html>
* Hostname localhost was found in DNS cache
```
```

**Comment by joakime** [comment] 2018-07-27 13:17
Interesting proposal.

I wonder if it would be wise to close the connection on any `5xx` error response?

**Comment by gregw** [comment] 2018-07-29 14:47
Perhaps we should set `Connection:close` on any >=400 response if jetty is in `STOPPING` state?

**Comment by joakime** [comment] 2018-07-31 20:54
Would it be wise to even close the connection on any >= 500 regardless of state?

**Comment by nicolone** [comment] 2018-08-01 07:29
If jetty is not in `STOPPING` state, I would not expect the server to close the connection.
For example: the client does a request which results in a 500 due to a programming/concurrency error, he tries it again, works the second time -> with keep-alive connection there should not be reconnect.

**Comment by gregw** [comment] 2018-08-02 22:35
I'm working on this at the moment.  The problem is that we currently only put the server into Stopping state and then call `shutdown` on all components that support it, which in this case is the `StatisticsHandler`.  At the point that we commit the response, we can look to see if the server is stopping, but that is not a complete solution, because it could be that `shutdown` has only been called on the one context.

We may need to improve our graceful shutdown mechanism to make a more general solution possible, so for now it may be simpler to just add the close to the 503 response and punt a full solution to jetty-10...

**Comment by joakime** [comment] 2018-08-03 01:37
So, with the current proposal in PR #2772 it looks like there is one awkward condition that really cannot be worked around.

Scenario: An active, committed, response is ongoing.  The server enters shutdown/stopping.  Since that response is already committed, we cannot add the header to close.  The next request on that connection is processed, then that one gets a `Connection: close` response header.

**Comment by gregw** [comment] 2018-08-03 06:35
@joakime True, once committed, the Connection:close cannot be added to the response.   Currently, the next request on that connection will not be process, but will receive a 503.

However, the server is entitled to close the connection at any time, so perhaps we should just close the connection after the response is complete, as if Connection:close had been sent?

**Closed as completed** 2018-09-10 18:25 UTC
