### ISSUE TITLE
HttpServletResponse.sendRedirect() should not close the connection

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#887] opened 2016-08-30 23:24 UTC
If the client doesn't specify `Connection: close` and the the servlet (or filter, or error-handler) uses HttpServletResponse.sendRedirect() that connection should remain open.

However, in Jetty 9.3.x that connection gets closed.

**Comment by joakime** [comment] 2016-11-01 20:24
@gregw would this be allowed per the servlet spec?  having servlet use of `.sendRedirect()` be smart to the intentions of the Http Client? (honor the `Connection` header, or lack thereof)

**Comment by gregw** [comment] 2016-11-01 22:56
I don't see why 9.3 should be closing the connection unless the request was HTTP/1.0?  sendRedirect is just a normal response and should be able to be persistent.   We need to create a unit test to verify either way (if there is not one already).

**Comment by laeubi** [comment] 2016-11-04 13:27
I can confirm that

```
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.sendRedirect("/somehwereelese");
    }
```

is keeping the connection open and you can issue just another request on the same connection (jetty 9.3.8)

Jetty responds with

HTTP/1.1 302 Found
Date: Fri, 04 Nov 2016 13:26:51 GMT
Location: http://localhost/somehwereelese
Content-Length: 0

**Comment by sbordet** [comment] 2016-11-07 14:35
@joakime where did you see the case where Jetty was closing the connection on redirect ?
Please close if you think this issue is invalid.

**Comment by jazdw** [comment] 2018-08-16 19:08
For what it's worth, I saw something similar when trying to do a 302 redirect. It turned out that the headers were being written then a org.eclipse.jetty.io.EofException was being thrown (and silently gobbled in my case) which caused the TCP connection to be closed.

**Comment by joakime** [comment] 2018-08-16 19:38
@jazdw do you happen to have a stacktrace of that EofException?

**Comment by gregw** [comment] 2018-08-16 22:32
@jazdw sounds like the other end closed that connection first.

**Comment by jazdw** [comment] 2018-08-16 22:44
It's definitely not the client closing the connection, I traced it in Wireshark and the server was sending TCP FIN, ACK.

Here's a stack trace, its quite a complicated setup so make of it what you will. I suspect it could be more of a problem with either Spring (OnCommittedResponseWrapper and ShallowEtagHeaderFilter) or the setup itself.

The product I am working on is Mango Automation - https://github.com/infiniteautomation/ma-core-public which is why there are additional filters etc.

Jetty version 9.4.11.v20180605
Spring version 5.0.8-FINAL

```
Thread [qtp1175662879-25] (Suspended (exception EofException))	
	HttpOutput.write(byte[], int, int) line: 482	
	OnCommittedResponseWrapper$SaveContextServletOutputStream.write(byte[], int, int) line: 639	
	OnCommittedResponseWrapper$SaveContextServletOutputStream.write(byte[], int, int) line: 639	
	FastByteArrayOutputStream.writeTo(OutputStream) line: 251	
	ShallowEtagHeaderFilter$HttpStreamingAwareContentCachingResponseWrapper(ContentCachingResponseWrapper).copyBodyToResponse(boolean) line: 228	
	ShallowEtagHeaderFilter$HttpStreamingAwareContentCachingResponseWrapper(ContentCachingResponseWrapper).copyBodyToResponse() line: 212	
	MangoShallowEtagHeaderFilter(ShallowEtagHeaderFilter).updateResponse(HttpServletRequest, HttpServletResponse) line: 123	
	MangoShallowEtagHeaderFilter(ShallowEtagHeaderFilter).doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 111	
	MangoShallowEtagHeaderFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 90	
	MangoShallowEtagHeaderFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
	ServletHandler$CachedChain.doFilter(ServletRequest, ServletResponse) line: 1634	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 320	
	MangoSwitchUserFilter(SwitchUserFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 197	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	FilterSecurityInterceptor.invoke(FilterInvocation) line: 127	
	FilterSecurityInterceptor.doFilter(ServletRequest, ServletResponse, FilterChain) line: 91	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	RateLimitingFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 56	
	RateLimitingFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	PermissionExceptionFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 34	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	ExceptionTranslationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	SessionManagementFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 137	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	AnonymousAuthenticationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 111	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	SecurityContextHolderAwareRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 170	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	ConcurrentSessionFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 155	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	UsernamePasswordAuthenticationFilter(AbstractAuthenticationProcessingFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 200	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	JsonUsernamePasswordAuthenticationFilter(AbstractAuthenticationProcessingFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 200	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	LogoutFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 116	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	CsrfFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 100	
	CsrfFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	CorsFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 96	
	CorsFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	HeaderWriterFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 66	
	HeaderWriterFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	SecurityContextPersistenceFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 105	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	WebAsyncManagerIntegrationFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 56	
	WebAsyncManagerIntegrationFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 107	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
	FilterChainProxy.doFilterInternal(ServletRequest, ServletResponse, FilterChain) line: 215	
	FilterChainProxy.doFilter(ServletRequest, ServletResponse, FilterChain) line: 178	
	DelegatingFilterProxy.invokeDelegate(Filter, ServletRequest, ServletResponse, FilterChain) line: 357	
	DelegatingFilterProxy.doFilter(ServletRequest, ServletResponse, FilterChain) line: 270	
	ServletHandler$CachedChain.doFilter(ServletRequest, ServletResponse) line: 1642	
	ServletHandler.doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 533	
	ServletHandler(ScopedHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 146	
	ConstraintSecurityHandler(SecurityHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 548	
	SessionHandler(HandlerWrapper).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 132	
	SessionHandler(ScopedHandler).nextHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 257	
	SessionHandler.doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 1595	
	OverridingWebAppContext(ScopedHandler).nextHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 255	
	OverridingWebAppContext(ContextHandler).doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 1317	
	ServletHandler(ScopedHandler).nextScope(String, Request, HttpServletRequest, HttpServletResponse) line: 203	
	ServletHandler.doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 473	
	SessionHandler.doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 1564	
	OverridingWebAppContext(ScopedHandler).nextScope(String, Request, HttpServletRequest, HttpServletResponse) line: 201	
	OverridingWebAppContext(ContextHandler).doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 1219	
	OverridingWebAppContext(ScopedHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 144	
	ContextHandlerCollection.handle(String, Request, HttpServletRequest, HttpServletResponse) line: 219	
	GzipHandler.handle(String, Request, HttpServletRequest, HttpServletResponse) line: 724	
	Server(HandlerWrapper).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 132	
	Server.handle(HttpChannel) line: 531	
	HttpChannelOverHttp(HttpChannel).handle() line: 352	
	HttpConnection.onFillable() line: 260	
	AbstractConnection$ReadCallback.succeeded() line: 281	
	AbstractEndPoint$1(FillInterest).fillable() line: 102	
	ChannelEndPoint$2.run() line: 118	
	EatWhatYouKill.runTask(Runnable) line: 333	
	EatWhatYouKill.doProduce(boolean) line: 310	
	EatWhatYouKill.tryProduce(boolean) line: 168	
	EatWhatYouKill.run() line: 126	
	ReservedThreadExecutor$ReservedThread.run() line: 366	
	QueuedThreadPool.runJob(Runnable) line: 762	
	QueuedThreadPool$2.run() line: 680	
	Thread.run() line: 748	
```

**Comment by joakime** [comment] 2018-08-16 22:56
I see a `WebAsyncManagerIntegrationFilter` in there.
Are you using Async I/O (Servlet 3.1) perhaps?
If so, you want to make sure you are not extending/wrapping the HttpServletRequest input streams or HttpServletResponse output streams.

**Comment by jazdw** [comment] 2018-08-16 23:05
Looks like we are using `JettyJspServlet` with `ServletHolder.setAsyncSupported(true)` yes. Also the spring security filter chain filter has `setAsyncSupported(true)` too. I'm positive there is lots of Request/Response wrapping going on in the Spring filters. As long as they are designed for async support there is no issue right?

Here's a wireshark trace of the server closing the connection. Server IP blacked out:
![image](https://user-images.githubusercontent.com/3579645/44239218-86d2af00-a175-11e8-80c3-3775793a692a.png)

**Closed** 2018-08-18 04:48 UTC
Labels: Bug, Enhancement
