### ISSUE TITLE
WebSocketServerFactory throw NullPointException when start jetty9.4.6 and set log level to  debug

### ISSUE THREAD

**Issue by duke88** [eclipse/jetty.project#1728] opened 2017-08-10 14:47 UTC
Hi
I use embedded  Jetty9.4.6 , when start Jetty and set log level to debug, then print all servlet config , the WebSocketServerFactory throw a NullPointException at the toString method, the creator field reference is null, it seems that the  constructor method call addBean and log the added bean, but the creator reference is not init, so it happens .

 java.lang.RuntimeException: java.lang.NullPointerException
        at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:68) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:329) ~[jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501) ~[jetty-webapp-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463) ~[jetty-webapp-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785) ~[jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261) ~[jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) [jetty-webapp-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.Server.start(Server.java:452) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.Server.doStart(Server.java:419) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at com.jeff.web.WebServer.startServer0(WebServer.java:496) [JeffServer.jar:1.0.2-build201708091148]
        at com.jeff.web.WebServer.initServer(WebServer.java:346) [JeffServer.jar:1.0.2-build201708091148]
        at com.jeff.container.server.AbstractServer.init(AbstractServer.java:59) [JeffServer.jar:1.0.2-build201708091148]
        at com.jeff.container.server.ServerManager.init(ServerManager.java:50) [JeffServer.jar:1.0.2-build201708091148]
        at com.jeff.container.Container.initServers(Container.java:421) [JeffServer.jar:1.0.2-build201708091148]
        at com.jeff.container.Container.init(Container.java:158) [JeffServer.jar:1.0.2-build201708091148]
        at com.jeff.boot.ContainerBooter.boot(ContainerBooter.java:38) [JeffServer.jar:1.0.2-build201708091148]
        at com.jeff.boot.Bootstarp.main(Bootstarp.java:20) [JeffServer.jar:1.0.2-build201708091148]
Caused by: java.lang.NullPointerException
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.toString(WebSocketServerFactory.java:641) ~[websocket-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_121]
        at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_121]
        at com.jeff.web.WebServerLogger.debug(WebServerLogger.java:26) [JeffServer.jar:1.0.2-build201708091148]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:322) ~[jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:226) ~[jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(WebSocketServerFactory.java:149) ~[websocket-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(WebSocketServerFactory.java:126) ~[websocket-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(WebSocketServerFactory.java:105) ~[websocket-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.websocket.server.NativeWebSocketConfiguration.<init>(NativeWebSocketConfiguration.java:51) ~[websocket-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer.getDefaultFrom(NativeWebSocketServletContainerInitializer.java:36) ~[websocket-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer.onStartup(NativeWebSocketServletContainerInitializer.java:46) ~[websocket-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:136) ~[jetty-plus-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
        ... 31 more

**Comment by joakime** [comment] 2017-08-10 16:02
Duplicate of #1603

**Closed** 2017-08-10 16:02 UTC
