### ISSUE TITLE
Jetty Client randomly ignores response from back-end services

### ISSUE THREAD

**Issue by idikshit** [eclipse/jetty.project#7041] opened 2021-10-25 13:50 UTC
**Jetty version(s)**
9.4.42.v20210604

**Java version**
16

**Description**
Hi, we are currently using 9.4.42.v20210604 version of Jetty Client with Java 16 support. We observe a random intermittent behavior where Jetty Client randomly ignores the response received and sends RESET_STREAM towards back-end services. The issue is observed while running traffic of around 500-1000 TPS.

Please find debug logs and network trace attached below in the zip file. Thanks

[jetty_client_issue.zip](https://github.com/eclipse/jetty.project/files/7410488/jetty_client_issue.zip)

**Comment by joakime** [comment] 2021-10-25 14:58
Please try 9.4.44, it has some improvements around terminated parsers and connections.

**Comment by sbordet** [comment] 2021-10-25 17:22
@idikshit your log file does not show any problem.

Please be more specific, point out exactly where the request that should receive a response does not receive it.

Also, I would recommend you triple check your application code, because very likely the problem is not in Jetty.

FTR, 500-1000 requests/s is almost nothing for Jetty's client.

**Comment by janbartel** [comment] 2022-01-19 01:11
@idikshit I'm closing this issue as you haven't supplied any further info on it. If you do have further info, please reopen and attach.

**Closed as completed by janbartel** 2022-01-19 01:11 UTC
Labels: Bug
